/-
# Dregg2.Circuit.ListCommitPortedCone — the MACHINE-PORTED S3 cone of `ListDigestBindsList`.

GENERATED by `Dregg2.Tools.ConePort` (driver: `Tools/ConePortListCommitRun`, regenerate with
`CONE_PORT_WRITE=1 lake env lean Dregg2/Tools/ConePortListCommitRun.lean`), then AUDITED and
committed as source. Do not hand-edit ports in place; regenerate or supersede explicitly.

Each theorem below is a direct threader of `ListCommit.ListDigestBindsList` with the refuted
`compressNInjective` floor binder (and, where it was binder-carried, `listLeafInjective`) replaced
by per-instance `¬ Coll` side conditions instantiated at the EXACT arguments the original proof
passes — the elaborated term decided, never a regex. Conclusions are UNCHANGED (the S3 discipline:
the shape change is confined to the endpoint file, `Circuit/ListCommitRegrounded`).

HONEST-BUT-CONDITIONAL, stated rather than smuggled: each port is conditional on the deployed hash
not colliding at the NAMED per-instance points — a refutable, decidable-per-instance claim (at
1-felt widths ~2^15.5-breakable, `docs/WOUND-felt-width-boundaries-2026-07-19.md`), NOT a security
proof and NOT the refuted universal injectivity. The unconditional content lives in the endpoint's
S2 (`listDigest_binds_or_collides`) and the ROM headline (`listDigestRom_binds`); the teeth
(`canary_drop_moves_digest_or_collides`, `listDigest_binds_unconditional_false`,
`noColl_satisfiable`/`listColl_refutable`) live there too and gate this whole family.

Every port re-verifies at build; the pins below re-prove: axiom-clean, and the refuted floor +
the old endpoint are UNREACHABLE from every port.
-/
import Dregg2.Circuit.ListCommitRegrounded
import Dregg2.Circuit.RotatedKernelRefinementNotes
import Dregg2.Circuit.RotatedKernelRefinementMisc
import Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc
import Dregg2.Circuit.RotatedKernelRefinementProgram
import Dregg2.Circuit.RotatedKernelRefinementCellSeal
import Dregg2.Circuit.RotatedKernelRefinementBirth
import Dregg2.Circuit.RotatedKernelRefinementLifecycle
import Dregg2.Circuit.RotatedKernelRefinementPermsVK
import Dregg2.Exec.FieldsMap
import Dregg2.Tactics

namespace Dregg2.Circuit.ListCommitPortedCone

set_option autoImplicit false

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementNotes.noteListRoot_binds` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementNotes.noteListRoot_binds_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementNotes.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementNotes.FieldElem)
  (xs ys : List ℕ),
  Dregg2.Circuit.RotatedKernelRefinementNotes.noteListRoot compressN xs =
      Dregg2.Circuit.RotatedKernelRefinementNotes.noteListRoot compressN ys →
    ¬Dregg2.Circuit.ListCommitRegrounded.CNColl Dregg2.Circuit.RotatedKernelRefinementNotes.noteLeaf
          compressN xs ys →
      xs = ys :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementNotes.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementNotes.FieldElem)
    (xs ys : List ℕ)
    (h :
      Dregg2.Circuit.RotatedKernelRefinementNotes.noteListRoot compressN xs =
        Dregg2.Circuit.RotatedKernelRefinementNotes.noteListRoot compressN ys)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementNotes.noteLeaf compressN xs ys) =>
  Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
    Dregg2.Circuit.RotatedKernelRefinementNotes.noteLeaf compressN
    Dregg2.Circuit.RotatedKernelRefinementNotes.noteLeaf_injective xs ys hno h
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementNotes.noteListRoot_binds_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementNotes.noteListRoot_binds_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementMisc.fixRootBinds` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementMisc.fixRootBinds_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementMisc.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementMisc.FieldElem)
  (w target : ℤ) (postRoot : Dregg2.Circuit.RotatedKernelRefinementMisc.FieldElem),
  postRoot =
      Dregg2.Circuit.ListCommit.listDigest Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf
        compressN [w] →
    Dregg2.Circuit.RotatedKernelRefinementMisc.gFixOne compressN target postRoot →
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
            Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN [w] [target] →
        w = target :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementMisc.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementMisc.FieldElem)
    (w target : ℤ) (postRoot : Dregg2.Circuit.RotatedKernelRefinementMisc.FieldElem)
    (hw :
      postRoot =
        Dregg2.Circuit.ListCommit.listDigest
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN [w])
    (hgate : Dregg2.Circuit.RotatedKernelRefinementMisc.gFixOne compressN target postRoot)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN [w] [target]) =>
  have hroots :=
    Eq.mpr
      (id
        (congrArg
          (fun (_a : Dregg2.Circuit.RotatedKernelRefinementMisc.FieldElem) =>
            _a =
              Dregg2.Circuit.ListCommit.listDigest
                Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN [target])
          (Eq.symm hw)))
      hgate;
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf_injective [w] [target] hno hroots;
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementMisc.fixRootBinds_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementMisc.fixRootBinds_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.discRoot_binds` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementLifecycleDisc.discRoot_binds_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.FieldElem)
  (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId),
  Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.discRoot compressN k cell =
      Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.discRoot compressN k' cell →
    ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN [k.lifecycle cell]
          [k'.lifecycle cell] →
      k.lifecycle cell = k'.lifecycle cell :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.FieldElem)
    (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId)
    (h :
      Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.discRoot compressN k cell =
        Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.discRoot compressN k' cell)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN [k.lifecycle cell]
          [k'.lifecycle cell]) =>
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf_injective [k.lifecycle cell]
      [k'.lifecycle cell] hno h;
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycleDisc.discRoot_binds_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycleDisc.discRoot_binds_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementProgram.setProgram_forced` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementProgram.setProgram_forced_of_noColl :
    ∀ (compressN hash : List ℤ → ℤ) {minit : ℤ → ℤ} {mfin : ℤ → ℤ × ℕ} {maddrs : List ℤ}
  {t : Dregg2.Circuit.DescriptorIR2.VmTrace} {permOut : List ℤ → List ℤ},
  Dregg2.Circuit.RotatedKernelRefinement.RotTableSide permOut hash t →
    Dregg2.Circuit.DescriptorIR2.Satisfied2 hash
        Dregg2.Circuit.Emit.EffectVmEmitRotationV3.setProgramV3 minit mfin maddrs t →
      ∀ (pre post : Dregg2.Exec.RecChainedState) (actor cell : Dregg2.Exec.CellId) (prog : ℤ)
        (rd :
          Dregg2.Circuit.RotatedKernelRefinementProgram.SetProgramTraceReadout compressN hash t pre
            post actor cell prog),
        ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
              Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
              [Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.programField
                  (post.kernel.cell cell)]
              [prog] →
          Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.programField
              (post.kernel.cell cell) =
            prog :=
  fun (compressN hash : List ℤ → ℤ) {minit : ℤ → ℤ} {mfin : ℤ → ℤ × ℕ} {maddrs : List ℤ}
    {t : Dregg2.Circuit.DescriptorIR2.VmTrace} {permOut : List ℤ → List ℤ}
    (hside : Dregg2.Circuit.RotatedKernelRefinement.RotTableSide permOut hash t)
    (hsat :
      Dregg2.Circuit.DescriptorIR2.Satisfied2 hash
        Dregg2.Circuit.Emit.EffectVmEmitRotationV3.setProgramV3 minit mfin maddrs t)
    (pre post : Dregg2.Exec.RecChainedState) (actor cell : Dregg2.Exec.CellId) (prog : ℤ)
    (rd :
      Dregg2.Circuit.RotatedKernelRefinementProgram.SetProgramTraceReadout compressN hash t pre post
        actor cell prog)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
          [Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.programField
              (post.kernel.cell cell)]
          [prog]) =>
  have hv1 :=
    Dregg2.Circuit.Emit.EffectVmEmitV2.graduateV1_sound hash
      (Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3WithRecordPin
        Dregg2.Circuit.Emit.EffectVmEmitRotationV3.B_RECORD_DIGEST
        Dregg2.Circuit.RotatedKernelRefinementProgram.setVKface)
      minit mfin maddrs t (Dregg2.Circuit.RotatedKernelRefinement.RotTableSide.chip hside)
      hside.range Dregg2.Circuit.RotatedKernelRefinementProgram.setProgram_rcp_graduable hsat
      rd.lastRow rd.hlastRow;
  have hlastt :=
    Eq.mpr (id Dregg2.Circuit.RotatedKernelRefinementProgram.setProgram_forced._simp_1_1)
      rd.hlastRowIsLast;
  have hpinCong :=
    Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3WithRecordPin_pins
      Dregg2.Circuit.Emit.EffectVmEmitRotationV3.B_RECORD_DIGEST hash
      Dregg2.Circuit.RotatedKernelRefinementProgram.setVKface
      (Dregg2.Circuit.DescriptorIR2.envAt t rd.lastRow) (rd.lastRow == 0)
      (Eq.mp
        (congrArg
          (fun (_a : Bool) =>
            Dregg2.Circuit.Emit.EffectVmEmit.satisfiedVm hash
              (Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3WithRecordPin
                Dregg2.Circuit.Emit.EffectVmEmitRotationV3.B_RECORD_DIGEST
                Dregg2.Circuit.RotatedKernelRefinementProgram.setVKface)
              (Dregg2.Circuit.DescriptorIR2.envAt t rd.lastRow) (rd.lastRow == 0) _a)
          hlastt)
        hv1);
  have hpin :=
    Dregg2.Circuit.Emit.EffectVmEmitRotation.canon_eq_of_modEq rd.recordLimbCanon rd.piCanon
      hpinCong;
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf_injective
      [Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.programField
          (post.kernel.cell cell)]
      [prog] hno
      (Eq.mp
        (congrArg
          (fun (_a : ℤ) =>
            Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN post.kernel cell
                Dregg2.Exec.TurnExecutorFull.programField =
              _a)
          rd.piAnchored)
        (Eq.mp
          (congrArg
            (fun (_a : ℤ) =>
              _a =
                (Dregg2.Circuit.DescriptorIR2.envAt t rd.lastRow).pub
                  (Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3
                      Dregg2.Circuit.RotatedKernelRefinementProgram.setVKface).piCount)
            rd.recordLimbDecodes)
          hpin));
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementProgram.setProgram_forced_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementProgram.setProgram_forced_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleRoot_binds` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementCellSeal.lifecycleRoot_binds_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementCellSeal.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.FieldElem)
  (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId),
  Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleRoot compressN k cell =
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleRoot compressN k' cell →
    ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN [k.lifecycle cell]
          [k'.lifecycle cell] →
      k.lifecycle cell = k'.lifecycle cell :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementCellSeal.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementCellSeal.FieldElem)
    (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId)
    (h :
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleRoot compressN k cell =
        Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleRoot compressN k' cell)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN [k.lifecycle cell]
          [k'.lifecycle cell]) =>
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf_injective [k.lifecycle cell]
      [k'.lifecycle cell] hno h;
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementCellSeal.lifecycleRoot_binds_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementCellSeal.lifecycleRoot_binds_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot_binds` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementBirth.accountsRoot_binds_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem)
  (k k' : Dregg2.Exec.RecordKernelState),
  Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot compressN k =
      Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot compressN k' →
    ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf compressN
          (Dregg2.Circuit.AccountsCommit.accountsSorted k)
          (Dregg2.Circuit.AccountsCommit.accountsSorted k') →
      k.accounts = k'.accounts :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem)
    (k k' : Dregg2.Exec.RecordKernelState)
    (h :
      Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot compressN k =
        Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot compressN k')
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf compressN
          (Dregg2.Circuit.AccountsCommit.accountsSorted k)
          (Dregg2.Circuit.AccountsCommit.accountsSorted k')) =>
  have hsorted :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf_injective
      (Dregg2.Circuit.AccountsCommit.accountsSorted k)
      (Dregg2.Circuit.AccountsCommit.accountsSorted k') hno h;
  Dregg2.Circuit.AccountsCommit.accounts_eq_of_sorted_eq k.accounts k'.accounts hsorted
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementBirth.accountsRoot_binds_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementBirth.accountsRoot_binds_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementBirth.accountsGrowForced` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementBirth.accountsGrowForced_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem)
  (preK postK : Dregg2.Exec.RecordKernelState) (newCell : Dregg2.Exec.CellId)
  (preRoot postRoot : Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem),
  Dregg2.Circuit.RotatedKernelRefinementBirth.AccountsRootRow compressN preK postK preRoot
      postRoot →
    Dregg2.Circuit.RotatedKernelRefinementBirth.gAccountsGrow compressN preK newCell postRoot →
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
            Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf compressN
            (Dregg2.Circuit.AccountsCommit.accountsSorted postK)
            ((Insert.insert newCell preK.accounts).sort fun (x1 x2 : Dregg2.Exec.CellId) =>
              x1 ≤ x2) →
        postK.accounts = Insert.insert newCell preK.accounts :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem)
    (preK postK : Dregg2.Exec.RecordKernelState) (newCell : Dregg2.Exec.CellId)
    (preRoot postRoot : Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem)
    (henc :
      Dregg2.Circuit.RotatedKernelRefinementBirth.AccountsRootRow compressN preK postK preRoot
        postRoot)
    (hgate :
      Dregg2.Circuit.RotatedKernelRefinementBirth.gAccountsGrow compressN preK newCell postRoot)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf compressN
          (Dregg2.Circuit.AccountsCommit.accountsSorted postK)
          ((Insert.insert newCell preK.accounts).sort fun (x1 x2 : Dregg2.Exec.CellId) =>
            x1 ≤ x2)) =>
  And.casesOn henc
    fun (left : preRoot = Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot compressN preK)
      (hpost :
        postRoot = Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot compressN postK) =>
    have hroots :=
      Eq.mpr
        (id
          (congrArg
            (fun (_a : Dregg2.Circuit.RotatedKernelRefinementBirth.FieldElem) =>
              _a =
                Dregg2.Circuit.ListCommit.listDigest
                  Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf compressN
                  ((Insert.insert newCell preK.accounts).sort fun (x1 x2 : Dregg2.Exec.CellId) =>
                    x1 ≤ x2))
            (Eq.symm hpost)))
        hgate;
    have hsorted :=
      Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
        Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf compressN
        Dregg2.Circuit.RotatedKernelRefinementBirth.accountsLeaf_injective
        (Dregg2.Circuit.AccountsCommit.accountsSorted postK)
        ((Insert.insert newCell preK.accounts).sort fun (x1 x2 : Dregg2.Exec.CellId) => x1 ≤ x2) hno
        hroots;
    Dregg2.Circuit.AccountsCommit.accounts_eq_of_sorted_eq postK.accounts
      (Insert.insert newCell preK.accounts) hsorted
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementBirth.accountsGrowForced_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementBirth.accountsGrowForced_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementLifecycle.deathCertRoot_binds` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementLifecycle.deathCertRoot_binds_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
  (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId),
  Dregg2.Circuit.RotatedKernelRefinementLifecycle.deathCertRoot compressN k cell =
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.deathCertRoot compressN k' cell →
    ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN [k.deathCert cell]
          [k'.deathCert cell] →
      k.deathCert cell = k'.deathCert cell :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
    (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId)
    (h :
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.deathCertRoot compressN k cell =
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.deathCertRoot compressN k' cell)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN [k.deathCert cell]
          [k'.deathCert cell]) =>
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleLeaf_injective [k.deathCert cell]
      [k'.deathCert cell] hno h;
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.deathCertRoot_binds_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.deathCertRoot_binds_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot_binds` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementLifecycle.auditSlotRoot_binds_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
  (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId) (f : Dregg2.Exec.FieldName),
  Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN k cell f =
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN k' cell f →
    ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
          [Dregg2.Exec.EffectsState.fieldOf f (k.cell cell)]
          [Dregg2.Exec.EffectsState.fieldOf f (k'.cell cell)] →
      Dregg2.Exec.EffectsState.fieldOf f (k.cell cell) =
        Dregg2.Exec.EffectsState.fieldOf f (k'.cell cell) :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
    (k k' : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId) (f : Dregg2.Exec.FieldName)
    (h :
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN k cell f =
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN k' cell f)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
          [Dregg2.Exec.EffectsState.fieldOf f (k.cell cell)]
          [Dregg2.Exec.EffectsState.fieldOf f (k'.cell cell)]) =>
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf_injective
      [Dregg2.Exec.EffectsState.fieldOf f (k.cell cell)]
      [Dregg2.Exec.EffectsState.fieldOf f (k'.cell cell)] hno h;
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.auditSlotRoot_binds_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.auditSlotRoot_binds_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotForced` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementLifecycle.auditSlotForced_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
  (postK : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId) (f : Dregg2.Exec.FieldName)
  (postRoot : Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem),
  postRoot = Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN postK cell f →
    Dregg2.Circuit.RotatedKernelRefinementLifecycle.gAuditSlotOne compressN cell f postRoot →
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
            Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
            [Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell)] [1] →
        Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell) = 1 :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
    (postK : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId) (f : Dregg2.Exec.FieldName)
    (postRoot : Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
    (hpost :
      postRoot =
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN postK cell f)
    (hgate :
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.gAuditSlotOne compressN cell f postRoot)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
          [Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell)] [1]) =>
  have hroots :=
    Eq.mpr
      (id
        (congrArg
          (fun (_a : Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem) =>
            _a =
              Dregg2.Circuit.ListCommit.listDigest
                Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN [1])
          (Eq.symm hpost)))
      hgate;
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf_injective
      [Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell)] [1] hno hroots;
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.auditSlotForced_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.auditSlotForced_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementLifecycle.refusal_forced` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementLifecycle.refusal_forced_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
  (hash : List ℤ → ℤ) {minit : ℤ → ℤ} {mfin : ℤ → ℤ × ℕ} {maddrs : List ℤ}
  {t : Dregg2.Circuit.DescriptorIR2.VmTrace} {permOut : List ℤ → List ℤ},
  Dregg2.Circuit.RotatedKernelRefinement.RotTableSide permOut hash t →
    Dregg2.Circuit.DescriptorIR2.Satisfied2 hash
        Dregg2.Circuit.Emit.EffectVmEmitRotationV3.refusalV3 minit mfin maddrs t →
      ∀ (pre post : Dregg2.Exec.RecChainedState) (actor cell : Dregg2.Exec.CellId)
        (rd :
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.RefusalTraceReadout compressN hash t pre
            post actor cell),
        ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
              Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
              [Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.refusalField
                  (post.kernel.cell cell)]
              [1] →
          Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.refusalField
              (post.kernel.cell cell) =
            1 :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.FieldElem)
    (hash : List ℤ → ℤ) {minit : ℤ → ℤ} {mfin : ℤ → ℤ × ℕ} {maddrs : List ℤ}
    {t : Dregg2.Circuit.DescriptorIR2.VmTrace} {permOut : List ℤ → List ℤ}
    (hside : Dregg2.Circuit.RotatedKernelRefinement.RotTableSide permOut hash t)
    (hsat :
      Dregg2.Circuit.DescriptorIR2.Satisfied2 hash
        Dregg2.Circuit.Emit.EffectVmEmitRotationV3.refusalV3 minit mfin maddrs t)
    (pre post : Dregg2.Exec.RecChainedState) (actor cell : Dregg2.Exec.CellId)
    (rd :
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.RefusalTraceReadout compressN hash t pre post
        actor cell)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
          [Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.refusalField
              (post.kernel.cell cell)]
          [1]) =>
  have hv1 :=
    Dregg2.Circuit.Emit.EffectVmEmitV2.graduateV1_sound hash
      (Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3WithRecordPin
        Dregg2.Circuit.Emit.EffectVmEmitRotationV3.B_RECORD_DIGEST
        Dregg2.Circuit.Emit.EffectVmEmitRefusal.refusalVmDescriptor)
      minit mfin maddrs t (Dregg2.Circuit.RotatedKernelRefinement.RotTableSide.chip hside)
      hside.range Dregg2.Circuit.RotatedKernelRefinementLifecycle.refusal_rcp_graduable hsat
      rd.lastRow rd.hlastRow;
  have hlastt :=
    Eq.mpr (id Dregg2.Circuit.RotatedKernelRefinementLifecycle.refusal_forced._simp_1_1)
      rd.hlastRowIsLast;
  have hpinCong :=
    Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3WithRecordPin_pins
      Dregg2.Circuit.Emit.EffectVmEmitRotationV3.B_RECORD_DIGEST hash
      Dregg2.Circuit.Emit.EffectVmEmitRefusal.refusalVmDescriptor
      (Dregg2.Circuit.DescriptorIR2.envAt t rd.lastRow) (rd.lastRow == 0)
      (Eq.mp
        (congrArg
          (fun (_a : Bool) =>
            Dregg2.Circuit.Emit.EffectVmEmit.satisfiedVm hash
              (Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3WithRecordPin
                Dregg2.Circuit.Emit.EffectVmEmitRotationV3.B_RECORD_DIGEST
                Dregg2.Circuit.Emit.EffectVmEmitRefusal.refusalVmDescriptor)
              (Dregg2.Circuit.DescriptorIR2.envAt t rd.lastRow) (rd.lastRow == 0) _a)
          hlastt)
        hv1);
  have hpin :=
    Dregg2.Circuit.Emit.EffectVmEmitRotation.canon_eq_of_modEq rd.recordLimbCanon rd.piCanon
      hpinCong;
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf_injective
      [Dregg2.Exec.EffectsState.fieldOf Dregg2.Exec.TurnExecutorFull.refusalField
          (post.kernel.cell cell)]
      [1] hno
      (Eq.mp
        (congrArg
          (fun (_a : ℤ) =>
            Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN post.kernel cell
                Dregg2.Exec.TurnExecutorFull.refusalField =
              _a)
          rd.piAnchored)
        (Eq.mp
          (congrArg
            (fun (_a : ℤ) =>
              _a =
                (Dregg2.Circuit.DescriptorIR2.envAt t rd.lastRow).pub
                  (Dregg2.Circuit.Emit.EffectVmEmitRotationV3.rotateV3
                      Dregg2.Circuit.Emit.EffectVmEmitRefusal.refusalVmDescriptor).piCount)
            rd.recordLimbDecodes)
          hpin));
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.refusal_forced_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementLifecycle.refusal_forced_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Circuit.RotatedKernelRefinementPermsVK.slotSetForced` — S3: floor binder(s) `hN` replaced by 1 instantiated per-instance side condition(s) [noCNColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem RotatedKernelRefinementPermsVK.slotSetForced_of_noColl :
    ∀
  (compressN :
    List Dregg2.Circuit.RotatedKernelRefinementPermsVK.FieldElem →
      Dregg2.Circuit.RotatedKernelRefinementPermsVK.FieldElem)
  (postK : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId) (f : Dregg2.Exec.FieldName)
  (target : ℤ) (postRoot : Dregg2.Circuit.RotatedKernelRefinementPermsVK.FieldElem),
  postRoot = Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN postK cell f →
    Dregg2.Circuit.RotatedKernelRefinementPermsVK.gSlotSet compressN cell f target postRoot →
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
            Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
            [Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell)] [target] →
        Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell) = target :=
  fun
    (compressN :
      List Dregg2.Circuit.RotatedKernelRefinementPermsVK.FieldElem →
        Dregg2.Circuit.RotatedKernelRefinementPermsVK.FieldElem)
    (postK : Dregg2.Exec.RecordKernelState) (cell : Dregg2.Exec.CellId) (f : Dregg2.Exec.FieldName)
    (target : ℤ) (postRoot : Dregg2.Circuit.RotatedKernelRefinementPermsVK.FieldElem)
    (hpost :
      postRoot =
        Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot compressN postK cell f)
    (hgate :
      Dregg2.Circuit.RotatedKernelRefinementPermsVK.gSlotSet compressN cell f target postRoot)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.CNColl
          Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
          [Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell)] [target]) =>
  have hroots :=
    Eq.mpr
      (id
        (congrArg
          (fun (_a : Dregg2.Circuit.RotatedKernelRefinementPermsVK.FieldElem) =>
            _a =
              Dregg2.Circuit.ListCommit.listDigest
                Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN [target])
          (Eq.symm hpost)))
      hgate;
  have hlist :=
    Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noCNColl
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf compressN
      Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditLeaf_injective
      [Dregg2.Exec.EffectsState.fieldOf f (postK.cell cell)] [target] hno hroots;
  List.head_eq_of_cons_eq hlist
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementPermsVK.slotSetForced_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.RotatedKernelRefinementPermsVK.slotSetForced_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

/-- ⚙ MACHINE-PORTED (`Tools/ConePort`) from `Dregg2.Exec.FieldsMap.fieldsRoot_binds_tail` — S3: floor binder(s) `hN`, `hLE` replaced by 1 instantiated per-instance side condition(s) [noColl]; conclusion UNCHANGED, proof surgered at 1 site(s), kernel-checked and round-tripped. HONEST-BUT-CONDITIONAL: the port is conditional on the deployed hash not colliding at the NAMED per-instance points — refutable, decidable per instance, never universal. -/
theorem FieldsMap.fieldsRoot_binds_tail_of_noColl :
    ∀ (compress2 : ℤ → ℤ → ℤ) (compressN : List ℤ → ℤ) (v w : Dregg2.Exec.Value),
  Dregg2.Exec.FieldsMap.fieldsRoot compress2 compressN v =
      Dregg2.Exec.FieldsMap.fieldsRoot compress2 compressN w →
    ¬Dregg2.Circuit.ListCommitRegrounded.ListColl (Dregg2.Exec.FieldsMap.tailLeaf compress2)
          compressN (Dregg2.Exec.FieldsMap.userTail v) (Dregg2.Exec.FieldsMap.userTail w) →
      Dregg2.Exec.FieldsMap.userTail v = Dregg2.Exec.FieldsMap.userTail w :=
  fun (compress2 : ℤ → ℤ → ℤ) (compressN : List ℤ → ℤ) (v w : Dregg2.Exec.Value)
    (h :
      Dregg2.Exec.FieldsMap.fieldsRoot compress2 compressN v =
        Dregg2.Exec.FieldsMap.fieldsRoot compress2 compressN w)
    (hno :
      ¬Dregg2.Circuit.ListCommitRegrounded.ListColl (Dregg2.Exec.FieldsMap.tailLeaf compress2)
          compressN (Dregg2.Exec.FieldsMap.userTail v) (Dregg2.Exec.FieldsMap.userTail w)) =>
  Dregg2.Circuit.ListCommitRegrounded.listDigest_binds_of_noColl
    (Dregg2.Exec.FieldsMap.tailLeaf compress2) compressN (Dregg2.Exec.FieldsMap.userTail v)
    (Dregg2.Exec.FieldsMap.userTail w) hno h
#assert_axioms Dregg2.Circuit.ListCommitPortedCone.FieldsMap.fieldsRoot_binds_tail_of_noColl
#assert_not_depends_on Dregg2.Circuit.ListCommitPortedCone.FieldsMap.fieldsRoot_binds_tail_of_noColl [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]

end Dregg2.Circuit.ListCommitPortedCone
