#import "../section-helpers.typ": theorem, boundary

= Higher-order logic and the categorical boundary

There is no single object called "the higher-order arithmetization."  Four
different constructions are exact, and they answer four different questions.

- Finite extensional HOL has a complete polynomial semantics, but arrow values are
  dense tables.
- Family-indexed finite-field hom codes exist exactly for locally finite categories;
  one-hot composition is quadratic.
- A typed STLC compiler targets shared nets without tabulating functions, and the
  source and target are genuine cartesian closed categories connected by a
  strong-CCC functor.
- Every small CCC embeds fully faithfully in a presheaf CCC by Yoneda, preserving
  the chosen exponentials up to explicit isomorphism.  This is the general semantic
  answer, not a finite-field encoding.

The separation matters.  The first two results are arithmetizations.  The third is
an intensional compiler with checkable local evidence.  The fourth is a categorical
embedding.  Conflating them would turn a collection of precise theorems into one
false performance claim.

#theorem([FOUR EXACT CONSTRUCTIONS], [
  `FiniteHOLFormulaArithmetization` proves the dense finite model;
  `FinitePolynomialCategoryClassification` proves the locally finite
  classification; `IntensionalCCCCategory` proves the shared-net CCC and its
  strong-CCC compiler; and `SmallCCCYonedaPresheaf` proves the arbitrary-small-CCC
  semantic embedding.  None is advertised as a succinct arithmetization of every
  cartesian closed category.
])

== Finite extensional HOL: complete, exact, and dense

Fix a finite field $F$ of cardinality $q$.  For a finite coordinate type $sigma$,
write $F^sigma$ for $sigma -> F$.  Every function from one finite field power to
another is represented coordinatewise by a polynomial function.  For one scalar
output, the explicit interpolation formula is

$
  delta_a(x) = product_(i in sigma) (1 - (x_i-a_i)^(q-1)),
  quad
  p_f(X) = sum_(a in F^sigma) f(a) delta_a(X).
$

Fermat's finite-field law gives $delta_a(a)=1$ and $delta_a(x)=0$ for $x != a$,
so $p_f(x)=f(x)$ at every field point.  `eval_interpolate` and
`eval_interpolateVector` prove the scalar and vector forms; the corresponding
surjectivity theorems state that every extensional map has such a representative.
These are polynomial *functions*.  Formal polynomials are identified by their
evaluation on $F$: $X^q-X$ is generally nonzero as syntax and zero as a function.

The finite HOL construction uses types generated by unit, scalar, product, and
arrow.  A type $A$ has a finite coordinate type $C_A$ and value space
$bracket.l A bracket.r = F^(C_A)$.  An arrow has coordinates

$
  C_(A arrow B) = (F^(C_A)) times C_B,
$

so an arrow value is its complete input-output table.  Lambda fills the table;
application reads it.  The intrinsically typed term language validates product
beta, function beta, and extensional eta.  Its formula language adds extensional
equality, all Boolean connectives, and universal and existential quantification at
every generated type.  In particular, quantification at arrow type really ranges
over every table, rather than over a sample of functions.

A typed environment is flattened losslessly by `environmentEquiv`.  Every term
coordinate has a polynomial `termPolynomial`, with lambda and application boundaries
proved exact.  Every formula $phi$ has a `formulaPolynomial` that is Boolean on the
entire ambient field power and satisfies

$
  "eval"(p_phi, x) = 0 quad "iff" quad x models phi.
$

The headline theorems are `eval_formulaPolynomial_point_isBit` and
`eval_formulaPolynomial_point_eq_zero_iff`; the forall, exists, and arrow-forall
specializations are proved separately.  This is a complete formal arithmetization of
the defined finite extensional equality-HOL.  It is noncomputable truth-table
interpolation, not an extracted optimizing compiler.

=== Exact exponential cost and the fixed-model obstruction

If $|sigma|=n$ and $|tau|=m$, then

$
  |(F^sigma -> F^tau)| = (q^m)^(q^n) = q^(m q^n).
$

The exponential object therefore has exactly $m q^n$ field coordinates and
$q^(m q^n)$ points.  `card_expCoord`, `card_tableObject`, and
`card_arrowQuantifierDomain` prove those counts.  The blowup is the size of the
represented function space, not slack in the analysis.

This also supplies the no-go theorem for one fixed finite extensional carrier.  Any
faithfully encoded hom-set must have at most $q^(m q^n)$ elements
(`finite_hom_bound`), and an infinite hom-set cannot inject into it
(`no_injective_infinite_hom`).  The concrete witness is the CCC `Type`: already
`Nat -> Bool` is infinite, so `no_injective_nat_predicates` rules out a faithful
encoding into any fixed finite table space.  An effective faithful encoding would
also reflect decidable equality from the finite target.

#boundary([
  Finite extensional HOL is solved positively and exactly, but its higher-order
  values are complete tables.  It cannot be promoted to an arithmetization of
  arbitrary CCCs by changing the prose around the theorem.
])

== Locally finite categories: the exact indexed classification

There is a broader finite-field theorem, but its indexing is load-bearing.  An
`IndexedHomPresentation` chooses a finite coordinate type and an injective field
vector code separately for every ordered pair of objects $(A,B)$.  The theorem

$
  "indexed finite-field hom presentation exists"
  quad "iff" quad
  "every Hom(A,B) is finite"
$

is `indexedPresentation_nonempty_iff_locallyFinite`.

For the reverse direction, `oneHotPresentation` takes the hom-type itself as the
coordinate set.  On valid one-hot inputs, composition has output coordinate

$
  "Comp"_h(x,y) =
    sum_(f : A arrow B) sum_(g : B arrow D)
      [g compose f = h] x_f y_g.
$

This is a sum of bilinear monomials, so its total degree is at most two;
`eval_compositionPolynomial` proves exactness.  Identity is a constant one-hot
vector, and code equality reflects equality of source morphisms.

This result does *not* place the whole category inside one finite semantic object.
The coordinate type varies with $(A,B)$; an infinite locally finite category may
need infinitely many such presentations; and product or exponential preservation is
additional data.  Nor is the one-hot representation succinct.  It classifies a
family-indexed arithmetization of hom-sets and composition, exactly and no more.

== The intensional route: a shared-net CCC

Dense tables are not the only semantics for higher-order programs.  The intensional
development instead starts from intrinsically typed STLC with unit, natural numbers,
products, arrows, and explicit source `let1`.  Its target `Net` language adds a
sharing binder.  Beta compilation performs the local transformation

$
  (lambda x. b) a quad arrow.r.long quad "share" a "as" x "in" b,
$

so the argument is represented once and referenced wherever the variable occurs.
`compile_denote`, `localStep_denote`, and `trace_denote` prove source compilation and
every typed local trace denotationally exact.  Product beta and extensional eta have
their own local certificates.

The quantitative specimen binds an eight-operation computation once and uses it
twice.  Its shared target contains 8 work nodes and 13 total nodes; literal copying
contains 16 work nodes and 19 total nodes.  Beta costs one local rewrite.  The shared
cost is independent of $q$, while the matching one-input, two-output extensional
table has $2q$ coordinates; `shared_smaller_than_table_coordinates` proves the shared
graph smaller from $q >= 7$.  This is a checked structural comparison, not a prover
latency benchmark.

=== A genuine category, not just beta examples

`IntensionalCCCCategory` closes the earlier gap.  A shared-net arrow $A -> B$ is a
semantic function equipped with a closed typed-net representative.  Equality is
equality of the represented functions.  `ofNet_eq_iff` proves that two concrete nets
map to the same arrow exactly when their denotations agree, and `ofNet_surjective`
proves that every arrow in the category has a net representative.

Identity, composition, terminal arrows, pairing, evaluation, curry, and uncurry all
have explicit closed-net representatives.  The category laws and the terminal,
product, beta, eta, and exponential universal equations are collected by
`Shared.laws`.  Exponentials are the typed intensional function objects; no finite
table is materialized.

The source STLC quotient/image is constructed as a second genuine CCC.  The
structural compiler induces `compilerFunctor` from the source category to the
shared-net category.  `Compiler.strongCCC` proves preservation of:

- identities and composition;
- the terminal object and terminal arrows;
- product objects, projections, and pairing; and
- exponential objects, evaluation, currying, and uncurrying.

Thus the higher-order compiler now has the categorical theorem one actually wants
for its formalized fragment.  This is stronger than saying that some beta redexes
evaluate correctly.  It is still not the universal property of the free CCC, an
embedding of every CCC, or a polynomial proof system.

== From typed reductions to checked interaction receipts

The intensional proof objects connect to DREGG's existing executable interaction-net
checker.  `IntensionalCCCInteractionBridge` translates each typed local step into a
receipt containing a distinct root-rule tag and the complete outer-to-inner address
of the interaction.  Beta, eta, first projection, and second projection have
distinct root tags; congruence paths distinguish, among other cases, the value and
body sides of a sharing binder.

`stepReceipt_checks` proves that every honest translation is accepted by the
fail-closed Boolean checker.  `translatedStep_checked_and_source_sound` deliberately
returns two separate facts:

$
  "receipt checker accepts" quad and quad
  "the original typed denotation is preserved".
$

This separation prevents a Boolean marker graph from being misrepresented as the
higher-order value itself.  Traces translate to checked batches, and hostile tests
reject a wrong location and the wrong side of a sharing binder.

The bridge also fixes a proposed row budget: a step at address depth $d$ occupies
exactly $d+1$ rows and $4(d+1)$ cells.  `constraint_rows_exact` and
`constraint_cells_exact` prove those counts.  The budget is an ABI for a later
DescriptorIR2 emitter; this module does not claim that the rows have already been
committed by a cryptographic IOP.

== Arbitrary small CCCs: Yoneda is the semantic generalization

For a genuinely small cartesian closed category $C$, the Yoneda functor

$
  y : C arrow (C^op arrow "Type")
$

is fully faithful.  It preserves terminal objects and binary products because it
preserves limits.  More importantly, the formalization constructs the pointwise
equivalence and presheaf isomorphism

$
  y(B^A) "isomorphic to" (y B)^(y A).
$

The forward map uncurries an arrow into $B^A$ and composes it with product pairing;
the inverse evaluates a natural family at the two projections and curries.  The
proofs are `representableExponentialEquiv`, `representableExponentialIso`, and
`smallCCCYonedaExponentialIso`.

This is the clean answer to the arbitrary-CCC challenge at the level of semantics:
every small CCC embeds fully faithfully in a presheaf topos while retaining the
chosen cartesian closed structure up to the exhibited isomorphisms.  There is no
finiteness hypothesis.  Accordingly, there is also no finite-field coordinate
bound, polynomial compiler, succinctness theorem, or cryptographic verifier hidden
in the result.  Arithmetic must be introduced later for selected finite observations
or receipts, with its own range, binding, and cost proofs.

== The presentation category correction

Certified changes of representation form a useful global category, but the global
category is *not* cartesian closed.  Each object in `CertifiedPresentationChange`
carries its own source predicate, and every arrow proves equivalence of source
meaning.  A terminal object would therefore have to be meaning-equivalent to both
truth and falsity.  `no_weakTerminal` refutes even that existence condition, and
`no_global_cartesian_structure` records the consequence.

The obvious attempt to use logical conjunction as a categorical product also fails.
A first projection from $P and Q$ to $P$ would, under meaning-equivalent arrows,
force $P -> Q$; `truth_and_falsity_has_no_firstProjection` gives the concrete
counterexample.  Logical conjunction and categorical product cannot simply be
identified in the global presentation category.

The correct positive structure lives over a fixed meaning.  In a fixed-meaning,
zero-resource fibre, objects are evidence families and arrows are pointwise evidence
transformers.  Terminal evidence is `Unit`, product evidence is a pair, and
exponential evidence is a pointwise function from one evidence type to another.
`EvidenceFamily.laws` proves terminality, product beta and eta, and exponential beta
and eta.  `Hom.toChange` embeds each fibre arrow as an exact global presentation
change with the same meaning and zero bookkeeping cost.  Products here combine two
evidence representations of *the same predicate*; they are not conjunction of
unrelated predicates.  `Intensional.representedArrow` shows how closed shared nets
can inhabit these evidence families without becoming dense function tables.

=== What has, and has not, been arithmetized

#table(
  columns: (1.05fr, 1.3fr, 1.7fr),
  inset: 4.2pt,
  table.header([*Construction*], [*Exact result*], [*Boundary*]),
  [Finite extensional HOL],
    [Every defined formula has an exact Boolean polynomial.],
    [Complete arrow tables; finite carrier; dense quantification.],
  [Locally finite hom presentation],
    [Faithful one-hot hom codes with quadratic composition.],
    [Family-indexed; no automatic product or exponential preservation.],
  [STLC to shared nets],
    [Genuine source and target CCCs; strong-CCC compiler; checked local receipts.],
    [One generated intensional fragment; not a field encoding or arbitrary-CCC embedding.],
  [Yoneda],
    [Fully faithful embedding of every small CCC; terminal, products, and exponentials preserved.],
    [Presheaf semantics, generally infinite; no succinct arithmetic backend.],
  [Fixed-meaning evidence fibre],
    [Pointwise CCC of evidence transformers.],
    [The global category is not cartesian; zero-resource fibre laws are not cost laws.],
)

An arithmetization of an arbitrary CCC would still require a computable assignment
of objects and arrows to an arithmetic backend, a stated and proved equality notion,
faithfulness, preservation of terminal objects, products, and exponentials, and
honest resource bounds for composition, evaluation, curry, and equality checking.
The present development supplies exact pieces of that map and rules out the naive
fixed finite-table version.  It does not pretend the remaining engineering and
cryptographic obligations are already discharged.
