#!/usr/bin/env python3
"""gen_cutover_check.py — generate the cutover's SEMANTIC teeth from the ConePort-generated cone.

Reads Dregg2/Circuit/ListCommitPortedCone.lean (the machine-ported, kernel-checked, committed S3
cone) BEFORE the cutover deletes it, and emits Dregg2/Circuit/ListCommitCutoverCheck.lean: for
each ported theorem, an

    example : <the cone's exact printed S3 type> := @<the original's full name>

which elaborates (post-cutover) iff the IN-PLACE cut-over original has EXACTLY the type ConePort
verified for that site (kernel defeq — binder order, instantiated side condition, unchanged
conclusion). Plus the moved pins: #assert_axioms and #assert_not_depends_on
[compressNInjective, ListDigestBindsList] on each cut-over original.

Chain of custody: ConePort kernel-checked cone-type ≡ (original's conclusion + side condition);
this module kernel-checks in-place-type ≡ cone-type; therefore the in-place cutover preserved the
conclusion exactly and added only the pinned side condition. Fail-closed: if the cone file is
missing or any of the 13 expected theorems cannot be parsed, the generator refuses (exit 2) and
emits NOTHING — a check module generated from a partial parse would be a tooth with missing teeth.
"""
import re
import sys

CONE = 'Dregg2/Circuit/ListCommitPortedCone.lean'
OUT = 'Dregg2/Circuit/ListCommitCutoverCheck.lean'

# local cone name -> original full name (the 13, explicit — auditable, no guessing).
ORIGINALS = {
    'RotatedKernelRefinementNotes.noteListRoot_binds_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementNotes.noteListRoot_binds',
    'RotatedKernelRefinementMisc.fixRootBinds_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementMisc.fixRootBinds',
    'RotatedKernelRefinementLifecycleDisc.discRoot_binds_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc.discRoot_binds',
    'RotatedKernelRefinementProgram.setProgram_forced_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementProgram.setProgram_forced',
    'RotatedKernelRefinementCellSeal.lifecycleRoot_binds_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementCellSeal.lifecycleRoot_binds',
    'RotatedKernelRefinementBirth.accountsRoot_binds_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementBirth.accountsRoot_binds',
    'RotatedKernelRefinementBirth.accountsGrowForced_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementBirth.accountsGrowForced',
    'RotatedKernelRefinementLifecycle.deathCertRoot_binds_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementLifecycle.deathCertRoot_binds',
    'RotatedKernelRefinementLifecycle.auditSlotRoot_binds_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotRoot_binds',
    'RotatedKernelRefinementLifecycle.auditSlotForced_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementLifecycle.auditSlotForced',
    'RotatedKernelRefinementLifecycle.refusal_forced_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementLifecycle.refusal_forced',
    'RotatedKernelRefinementPermsVK.slotSetForced_of_noColl':
        'Dregg2.Circuit.RotatedKernelRefinementPermsVK.slotSetForced',
    'FieldsMap.fieldsRoot_binds_tail_of_noColl':
        'Dregg2.Exec.FieldsMap.fieldsRoot_binds_tail',
}

HEADER = '''/-
# Dregg2.Circuit.ListCommitCutoverCheck — the SEMANTIC teeth of the ListDigestBindsList cutover.

GENERATED by `scripts/gen_cutover_check.py` from the ConePort-generated, kernel-checked S3 cone
(`Circuit/ListCommitPortedCone.lean`) at the moment of cutover — the cone module itself was then
RETIRED (`Tools/ConeCutoverListCommit`), and these pins are what remains of it: for each of the 13
cut-over theorems, the `example : ⟨cone type⟩ := @original` below re-proves ON EVERY BUILD, by
KERNEL defeq, that the in-place original has EXACTLY the S3 type ConePort verified for that site —
same conclusion, floor binder gone, the per-instance side condition and nothing else. A silent
weakening, a binder reorder, or a floor-binder resurrection turns the build red HERE.

Chain of custody: ConePort kernel-checked ⟨cone type⟩ ≡ ⟨original conclusion + side condition⟩
(surgery on the elaborated term, `Meta.check` + `isDefEq` + kernel `addDecl` + delaboration
round-trip); this module kernel-checks ⟨in-place type⟩ ≡ ⟨cone type⟩. The `#assert_not_depends_on`
pins are the MOVED pins of the retired cone: the refuted floor and the old endpoint are
UNREACHABLE from every cut-over theorem.
-/
import Dregg2.Circuit.ListCommitRegrounded
import Dregg2.Circuit.RotatedKernelRefinementNotes
import Dregg2.Circuit.RotatedKernelRefinementMisc
import Dregg2.Circuit.RotatedKernelRefinementLifecycleDisc
import Dregg2.Circuit.RotatedKernelRefinementProgram
import Dregg2.Circuit.RotatedKernelRefinementCellSeal
import Dregg2.Circuit.RotatedKernelRefinementBirth
import Dregg2.Circuit.RotatedKernelRefinementLifecycle
import Dregg2.Circuit.RotatedKernelRefinementPermsVK
import Dregg2.Exec.FieldsMap
import Dregg2.Tactics

namespace Dregg2.Circuit.ListCommitCutoverCheck

set_option autoImplicit false
'''

FOOTER = '\nend Dregg2.Circuit.ListCommitCutoverCheck\n'

THM = re.compile(r'^theorem (\S+) :\n(.*?) :=\n', re.MULTILINE | re.DOTALL)


def main():
    try:
        text = open(CONE, encoding='utf-8').read()
    except FileNotFoundError:
        print(f'FATAL: {CONE} not found — the check module must be generated BEFORE the cutover '
              f'retires the cone (it IS the record of the cone\'s verified types).',
              file=sys.stderr)
        return 2
    found = {}
    for m in THM.finditer(text):
        name, ty = m.group(1), m.group(2)
        if name in ORIGINALS:
            found[name] = ty
    missing = [n for n in ORIGINALS if n not in found]
    if missing:
        print(f'FATAL: could not parse {len(missing)} expected cone theorem(s): {missing} — '
              f'refusing to emit a check module with missing teeth.', file=sys.stderr)
        return 2
    out = [HEADER]
    for local, orig in ORIGINALS.items():
        ty = found[local]
        out.append(f'''
/-- ⚙ CUTOVER CHECK — `{orig}` has EXACTLY the ConePort-kernel-checked S3 type
(the retired cone's `{local}`); kernel defeq, re-proved every build. -/
example :
    {ty} :=
  @{orig}
#assert_axioms {orig}
#assert_not_depends_on {orig} [Dregg2.Circuit.StateCommit.compressNInjective, Dregg2.Circuit.ListCommit.ListDigestBindsList]
''')
    out.append(FOOTER)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(''.join(out))
    print(f'WROTE {OUT}: {len(found)} type pins + axiom pins + floor-unreachability pins.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
