/-
# Dregg2.Verify.FloorRatchetBaselineInline — the INLINE-SPELLED grandfathered carriers.

GENERATED, and kept SEPARATE from `FloorRatchetBaseline.lean` on purpose. Two reasons:

* **Provenance.** Every name here became visible on one day, from one cause: `#floor_ratchet`
  learned to read a floor spelled `Function.Injective f` instead of by name
  (`Dregg2/Verify/InjSpelling.lean`). None of them is a new theorem. Each was ALREADY vacuous and
  ALREADY uncounted — the gate's own log printed the size of the hole on every run ("N
  `Function.Injective`-spelled sites ungated (known residual)") and nobody could act on a number.
  Keeping the raise in its own file keeps that cause readable instead of dissolving it into a
  2000-line list.
* **Co-tenancy.** The main baseline is edited by other lanes in the same working tree. A
  several-hundred-line append to the same generated file is exactly the clobber `CLAUDE.md`
  forbids.

⚑ WHAT EACH LINE MEANS. The declaration takes `Function.Injective f` as a HYPOTHESIS at a
signature this tree REFUTES — either because the inline spelling is definitionally a named refuted
floor (`Poseidon2SpongeCR` at `List ℤ → ℤ`), or because an in-tree theorem proves NO function of
that type is injective at all. The second kind is the majority and is the worse one: a
whole-function digest `(CellId → AssetId → ℤ) → ℤ` maps an UNCOUNTABLE domain into a countable
one, so the hypothesis is a CARDINALITY IMPOSSIBILITY — false at every parameter set, for every
hash, in every field (`Dregg2/Verify/InjSpelledFloors.lean`). These are not optimistic assumptions
about Poseidon2; they are assumptions with no models.

The PORT is structural, not cryptographic: digest the FINITE support actually touched (the
`accounts : Finset CellId` rows), never the whole function. A finite-support digest has a
countable domain and is back at the ordinary deployed-parameter CR bar, where the campaign's
per-instance `…Coll` side conditions apply. `Circuit/EffectCommit2.funcComponent` is the single
constructor almost every line below flows through, so the port has ONE head.

Only ever gets SHORTER. The next `#floor_ratchet_emit` folds surviving entries into
`FloorRatchetBaseline.lean`'s chunks; when that happens this array goes empty and stays.
-/
set_option autoImplicit false

namespace Dregg2.Verify.FloorRatchetBaselineInline

private def i0 : Array String := #[
  "Dregg2.Cell.InterfaceIdWidth.seedOf_ne_stepOf",
  "Dregg2.Cell.InterfaceIdWidth.seed_arity_injective",
  "Dregg2.Cell.InterfaceIdWidth.stepOf_inj",
  "Dregg2.Cell.InterfaceIdWidth.wideId_injective",
  "Dregg2.Cell.InterfaceIdWidth.wide_separates",
  "Dregg2.Circuit.Argus.Effects.BalanceA.balanceACircuit",
  "Dregg2.Circuit.Argus.Effects.CellDestroy.cellDestroyCircuit",
  "Dregg2.Circuit.Argus.Effects.CellDestroy.cellDestroyE_components_are_full_functions",
  "Dregg2.Circuit.Argus.Effects.CellSeal.cellSealCircuit",
  "Dregg2.Circuit.Argus.Effects.CellUnseal.cellUnsealCircuit",
  "Dregg2.Circuit.Argus.Effects.DelegateAtten.delegateAttenCircuit",
  "Dregg2.Circuit.Argus.Effects.RefreshDelegation.refreshDelegationCircuit",
  "Dregg2.Circuit.BornEmptyCommit.bornEmptyAuthorityComponent",
  "Dregg2.Circuit.BornEmptyCommit.bornEmptySideComponent",
  "Dregg2.Circuit.BornEmptyCommit.spawnCreateLegComponent",
  "Dregg2.Circuit.EffectEmittedRefinement.attenuateAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.attenuateA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.balanceAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.balanceA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.burnEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.burn_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.cellDestroyAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.cellDestroyA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.cellSealAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.cellSealA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.cellUnsealAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.cellUnsealA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.delegateAttenAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.delegateAttenA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.delegateEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.delegate_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.heapWriteAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.heapWriteA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.introduceAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.introduceA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.mintEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.mint_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.receiptArchiveLifecycleAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.receiptArchiveLifecycleA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.refreshDelegationAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.refreshDelegationA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.revokeDelegationAEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.revokeDelegationA_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.revokeDelegationEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.revokeEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.revoke_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectEmittedRefinement.transferEmittedStep",
  "Dregg2.Circuit.EffectEmittedRefinement.transfer_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectInstances2.apex_iff_mintASpec",
  "Dregg2.Circuit.EffectInstances2.balComponent",
  "Dregg2.Circuit.EffectInstances2.mintE",
  "Dregg2.Circuit.EffectInstances2.mintEWire_circuit_eq",
  "Dregg2.Circuit.EffectInstances2.mintGuardDecodes",
  "Dregg2.Circuit.EffectInstances2.mintGuardEncodes",
  "Dregg2.Circuit.EffectInstances2.mintRestFrameDecodes",
  "Dregg2.Circuit.EffectRefinement.balanceACircuitStep",
  "Dregg2.Circuit.EffectRefinement.balanceACircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinement.balanceARestFrameEncodes",
  "Dregg2.Circuit.EffectRefinement.balanceA_spec_refines_circuit",
  "Dregg2.Circuit.EffectRefinement.burnCircuitStep",
  "Dregg2.Circuit.EffectRefinement.burnCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinement.burnRestFrameEncodes",
  "Dregg2.Circuit.EffectRefinement.burn_spec_refines_circuit",
  "Dregg2.Circuit.EffectRefinement.delegateCircuitStep",
  "Dregg2.Circuit.EffectRefinement.delegateCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinement.delegateRestFrameEncodes",
  "Dregg2.Circuit.EffectRefinement.delegate_spec_refines_circuit",
  "Dregg2.Circuit.EffectRefinement.mintCircuitStep",
  "Dregg2.Circuit.EffectRefinement.mintCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinement.mintEmittedStep",
  "Dregg2.Circuit.EffectRefinement.mintRestFrameEncodes",
  "Dregg2.Circuit.EffectRefinement.mint_emitted_equiv_circuit",
  "Dregg2.Circuit.EffectRefinement.mint_spec_refines_circuit",
  "Dregg2.Circuit.EffectRefinement.revokeCircuitStep",
  "Dregg2.Circuit.EffectRefinement.revokeCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinement.revokeDelegationCircuitStep",
  "Dregg2.Circuit.EffectRefinement.revokeDelegationCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinement.revokeRestFrameEncodes",
  "Dregg2.Circuit.EffectRefinement.revoke_spec_refines_circuit",
  "Dregg2.Circuit.EffectRefinement.transferCircuitStep",
  "Dregg2.Circuit.EffectRefinement.transferRestFrameEncodes",
  "Dregg2.Circuit.EffectRefinement.transfer_spec_refines_circuit",
  "Dregg2.Circuit.EffectRefinementBatch2.attenuateCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.attenuateCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinementBatch2.cellDestroyCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.cellDestroyCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinementBatch2.cellSealCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.cellSealCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinementBatch2.cellUnsealCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.cellUnsealCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinementBatch2.delegateAttenCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.delegateAttenCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinementBatch2.heapWriteCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.heapWriteCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinementBatch2.receiptArchiveLifecycleCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.receiptArchiveLifecycleCircuitStep.congr_simp",
  "Dregg2.Circuit.EffectRefinementBatch2.refreshDelegationCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.refreshDelegationFullCircuitStep",
  "Dregg2.Circuit.EffectRefinementBatch2.refreshDelegationFullCircuitStep.congr_simp",
  "Dregg2.Circuit.Emit.MembershipDepthGeneralRung2.foldNode4_inj",
  "Dregg2.Circuit.Emit.MembershipDepthGeneralRung2.foldNode4_len_lt",
  "Dregg2.Circuit.Inst.AttenuateA.apex_iff_attenuateSpec",
  "Dregg2.Circuit.Inst.AttenuateA.attenuateE",
  "Dregg2.Circuit.Inst.AttenuateA.attenuateGuardDecodes",
  "Dregg2.Circuit.Inst.AttenuateA.attenuateGuardEncodes",
  "Dregg2.Circuit.Inst.AttenuateA.attenuateRestFrameDecodes",
  "Dregg2.Circuit.Inst.AttenuateA.capsComponent",
  "Dregg2.Circuit.Inst.BalanceA.apex_iff_balanceASpec",
  "Dregg2.Circuit.Inst.BalanceA.balComponent",
  "Dregg2.Circuit.Inst.BalanceA.balanceAE",
  "Dregg2.Circuit.Inst.BalanceA.balanceGuardDecodes",
  "Dregg2.Circuit.Inst.BalanceA.balanceGuardEncodes",
  "Dregg2.Circuit.Inst.BalanceA.balanceRestFrameDecodes",
  "Dregg2.Circuit.Inst.BridgeMintA.apex_iff_inboundMintSpec",
  "Dregg2.Circuit.Inst.BridgeMintA.bridgeMintE",
  "Dregg2.Circuit.Inst.BridgeMintA.bridgeMintGuardDecodes",
  "Dregg2.Circuit.Inst.BridgeMintA.bridgeMintGuardEncodes",
  "Dregg2.Circuit.Inst.BridgeMintA.bridgeMintRestFrameDecodes",
  "Dregg2.Circuit.Inst.BurnA.apex_iff_burnSpec",
  "Dregg2.Circuit.Inst.BurnA.balComponent",
  "Dregg2.Circuit.Inst.BurnA.burnE",
  "Dregg2.Circuit.Inst.BurnA.burnEWire_circuit_eq",
  "Dregg2.Circuit.Inst.BurnA.burnGuardDecodes",
  "Dregg2.Circuit.Inst.BurnA.burnGuardEncodes",
  "Dregg2.Circuit.Inst.BurnA.burnRestFrameDecodes",
  "Dregg2.Circuit.Inst.CellDestroyA.apex_iff_cellDestroySpec",
  "Dregg2.Circuit.Inst.CellDestroyA.cellDestroyE",
  "Dregg2.Circuit.Inst.CellDestroyA.cellDestroyGuardDecodes",
  "Dregg2.Circuit.Inst.CellDestroyA.cellDestroyGuardEncodes",
  "Dregg2.Circuit.Inst.CellDestroyA.cellDestroyRestFrameDecodes",
  "Dregg2.Circuit.Inst.CellDestroyA.deathCertComponent",
  "Dregg2.Circuit.Inst.CellDestroyA.lifecycleComponent",
  "Dregg2.Circuit.Inst.CellSealA.apex_iff_cellSealSpec",
  "Dregg2.Circuit.Inst.CellSealA.cellSealE",
  "Dregg2.Circuit.Inst.CellSealA.cellSealGuardDecodes",
  "Dregg2.Circuit.Inst.CellSealA.cellSealGuardEncodes",
  "Dregg2.Circuit.Inst.CellSealA.cellSealRestFrameDecodes",
  "Dregg2.Circuit.Inst.CellSealA.lifecycleComponent",
  "Dregg2.Circuit.Inst.CellUnsealA.apex_iff_cellUnsealSpec",
  "Dregg2.Circuit.Inst.CellUnsealA.cellUnsealE",
  "Dregg2.Circuit.Inst.CellUnsealA.cellUnsealGuardDecodes",
  "Dregg2.Circuit.Inst.CellUnsealA.cellUnsealGuardEncodes",
  "Dregg2.Circuit.Inst.CellUnsealA.cellUnsealRestFrameDecodes",
  "Dregg2.Circuit.Inst.CellUnsealA.lifecycleComponent",
  "Dregg2.Circuit.Inst.CreateCellA.balComp",
  "Dregg2.Circuit.Inst.CreateCellA.bornEmptyComp",
  "Dregg2.Circuit.Inst.CreateCellFromFactoryA.balComp",
  "Dregg2.Circuit.Inst.CreateCellFromFactoryA.bornEmptyAuthorityComp",
  "Dregg2.Circuit.Inst.CreateCellFromFactoryA.cellComp",
  "Dregg2.Circuit.Inst.CreateCellFromFactoryA.slotCaveatsComp"]

private def i1 : Array String := #[
  "Dregg2.Circuit.Inst.Delegate.apex_iff_delegateSpec",
  "Dregg2.Circuit.Inst.Delegate.capsComponent",
  "Dregg2.Circuit.Inst.Delegate.delegateE",
  "Dregg2.Circuit.Inst.Delegate.delegateGuardDecodes",
  "Dregg2.Circuit.Inst.Delegate.delegateGuardEncodes",
  "Dregg2.Circuit.Inst.Delegate.delegateRestFrameDecodes",
  "Dregg2.Circuit.Inst.DelegateAttenA.apex_iff_delegateAttenSpec",
  "Dregg2.Circuit.Inst.DelegateAttenA.capsComponent",
  "Dregg2.Circuit.Inst.DelegateAttenA.delAttenGuardDecodes",
  "Dregg2.Circuit.Inst.DelegateAttenA.delAttenGuardEncodes",
  "Dregg2.Circuit.Inst.DelegateAttenA.delAttenRestFrameDecodes",
  "Dregg2.Circuit.Inst.DelegateAttenA.delegateAttenE",
  "Dregg2.Circuit.Inst.HeapWriteA.apex_iff_heapWriteSpec",
  "Dregg2.Circuit.Inst.HeapWriteA.cellComponent",
  "Dregg2.Circuit.Inst.HeapWriteA.heapWriteE",
  "Dregg2.Circuit.Inst.HeapWriteA.heapWriteGuardDecodes",
  "Dregg2.Circuit.Inst.HeapWriteA.heapWriteGuardEncodes",
  "Dregg2.Circuit.Inst.HeapWriteA.heapWriteRestFrameDecodes",
  "Dregg2.Circuit.Inst.HeapWriteA.heapsComponent",
  "Dregg2.Circuit.Inst.IntroduceA.apex_iff_delegateSpec",
  "Dregg2.Circuit.Inst.IntroduceA.capsComponent",
  "Dregg2.Circuit.Inst.IntroduceA.introduceE",
  "Dregg2.Circuit.Inst.IntroduceA.introduceGuardDecodes",
  "Dregg2.Circuit.Inst.IntroduceA.introduceGuardEncodes",
  "Dregg2.Circuit.Inst.IntroduceA.introduceRestFrameDecodes",
  "Dregg2.Circuit.Inst.MintA.apex_iff_mintASpec",
  "Dregg2.Circuit.Inst.MintA.balComponent",
  "Dregg2.Circuit.Inst.MintA.mintE",
  "Dregg2.Circuit.Inst.MintA.mintEWire_circuit_eq",
  "Dregg2.Circuit.Inst.MintA.mintGuardDecodes",
  "Dregg2.Circuit.Inst.MintA.mintGuardEncodes",
  "Dregg2.Circuit.Inst.MintA.mintRestFrameDecodes",
  "Dregg2.Circuit.Inst.ReceiptArchiveLifecycleA.apex_iff_ReceiptArchiveLifecycleSpec",
  "Dregg2.Circuit.Inst.ReceiptArchiveLifecycleA.archiveGuardDecodes",
  "Dregg2.Circuit.Inst.ReceiptArchiveLifecycleA.archiveGuardEncodes",
  "Dregg2.Circuit.Inst.ReceiptArchiveLifecycleA.archiveRestFrameDecodes",
  "Dregg2.Circuit.Inst.ReceiptArchiveLifecycleA.lifecycleComponent",
  "Dregg2.Circuit.Inst.ReceiptArchiveLifecycleA.receiptArchiveLifecycleE",
  "Dregg2.Circuit.Inst.RefreshDelegationA.apex_iff_refreshDelegationSpec",
  "Dregg2.Circuit.Inst.RefreshDelegationA.delegationsComponent",
  "Dregg2.Circuit.Inst.RefreshDelegationA.refreshDelegationE",
  "Dregg2.Circuit.Inst.RefreshDelegationA.refreshDelegationGuardDecodes",
  "Dregg2.Circuit.Inst.RefreshDelegationA.refreshDelegationGuardEncodes",
  "Dregg2.Circuit.Inst.RefreshDelegationA.refreshDelegationRestFrameDecodes",
  "Dregg2.Circuit.Inst.Revoke.apex_iff_revokeSpec",
  "Dregg2.Circuit.Inst.Revoke.capsComponent",
  "Dregg2.Circuit.Inst.Revoke.revokeE",
  "Dregg2.Circuit.Inst.Revoke.revokeGuardDecodes",
  "Dregg2.Circuit.Inst.Revoke.revokeGuardEncodes",
  "Dregg2.Circuit.Inst.Revoke.revokeRestFrameDecodes",
  "Dregg2.Circuit.Inst.RevokeDelegationA.apex_iff_revokeSpec",
  "Dregg2.Circuit.Inst.RevokeDelegationA.capsComponent",
  "Dregg2.Circuit.Inst.RevokeDelegationA.revokeDelegationE",
  "Dregg2.Circuit.Inst.RevokeDelegationA.revokeGuardDecodes",
  "Dregg2.Circuit.Inst.RevokeDelegationA.revokeGuardEncodes",
  "Dregg2.Circuit.Inst.RevokeDelegationA.revokeRestFrameDecodes",
  "Dregg2.Circuit.Inst.RevokeDelegationFullA.apex_iff_revokeDelegationFullSpec",
  "Dregg2.Circuit.Inst.RevokeDelegationFullA.capsComponent",
  "Dregg2.Circuit.Inst.RevokeDelegationFullA.delegationStepComponent",
  "Dregg2.Circuit.Inst.RevokeDelegationFullA.revokeDelegationFullE",
  "Dregg2.Circuit.Inst.RevokeDelegationFullA.revokeGuardDecodes",
  "Dregg2.Circuit.Inst.RevokeDelegationFullA.revokeGuardEncodes",
  "Dregg2.Circuit.Inst.RevokeDelegationFullA.revokeRestFrameDecodes",
  "Dregg2.Circuit.Inst.SpawnA.capsComp",
  "Dregg2.Circuit.Inst.SpawnA.delegateComp",
  "Dregg2.Circuit.Inst.SpawnA.delegationsComp",
  "Dregg2.Circuit.Inst.SpawnA.spawnCreateLegComp",
  "Dregg2.Circuit.Inst.Transfer.apex_iff_balanceMovementSpec",
  "Dregg2.Circuit.Inst.Transfer.balComponent",
  "Dregg2.Circuit.Inst.Transfer.balanceE",
  "Dregg2.Circuit.Inst.Transfer.balanceGuardDecodes",
  "Dregg2.Circuit.Inst.Transfer.balanceGuardEncodes",
  "Dregg2.Circuit.Inst.Transfer.balanceRestFrameDecodes",
  "Dregg2.Circuit.LogHashPortedCone.AttenuateA.attenuateA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.BalanceA.balanceA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.BridgeMintA.bridgeMintA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.BurnA.burnA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.CellDestroyA.cellDestroyA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.CellSealA.cellSealA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.CellUnsealA.cellUnsealA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.Delegate.delegate_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.DelegateAttenA.delegateAttenA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.EffectInstances2.mintE_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.HeapWriteA.heapWriteA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.IntroduceA.introduceA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.MintA.mintA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.ReceiptArchiveLifecycleA.receiptArchiveLifecycleA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.RefreshDelegationA.refreshDelegationA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.Revoke.revoke_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.RevokeDelegationA.revokeDelegationA_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.RevokeDelegationFullA.revokeDelegationFull_full_sound_of_noColl",
  "Dregg2.Circuit.LogHashPortedCone.Transfer.transfer_full_sound_of_noColl",
  "Dregg2.Circuit.MapInsertImtRepoint.padImtRoot_ne_mapRoot_of_good",
  "Dregg2.Circuit.MapInsertImtRepoint.reconcileGates_aafi_forces_key_present",
  "Dregg2.Circuit.MapInsertImtRepoint.reconcileGates_aafi_unsat_at_fresh_key",
  "Dregg2.Circuit.MapKindImtGates.map_imtLeafHash_injective",
  "Dregg2.Circuit.MapKindImtGates.reconcileGates_insert_forces_key_present",
  "Dregg2.Circuit.MapKindImtGates.reconcileGates_insert_unsat_at_fresh_key",
  "Dregg2.Circuit.MapPaddedDenotation.narrow_opensToMerkle_functional",
  "Dregg2.Circuit.MapPaddedDenotation.narrow_opensToMerkle_some_excludes_none",
  "Dregg2.Circuit.MapPaddedDenotation.narrow_writesToMerkle_functional",
  "Dregg2.Circuit.Poseidon2KeyedBridge.family_H_injective_of_injective_sponge",
  "Dregg2.Circuit.TurnEmit.mintA_extract_rejects_wrong_supply",
  "Dregg2.Circuit.Witness.CellSealWitness.seal_execute_produces_satisfying_witness",
  "Dregg2.Circuit.Witness.DelegateAttenWitness.execute_produces_satisfying_witness",
  "Dregg2.Circuit.Witness.DelegateWitness.execute_produces_satisfying_witness",
  "Dregg2.Circuit.Witness.IntroduceWitness.execute_produces_satisfying_witness",
  "Dregg2.Circuit.Witness.RefreshDelegationWitness.execute_produces_satisfying_witness",
  "Dregg2.Circuit.Witness.RevokeDelegationWitness.execute_produces_satisfying_witness",
  "Dregg2.Circuit.WitnessExtractPerEffect.attenuateA_extract_rejects_wrong_caps",
  "Dregg2.Circuit.WitnessExtractPerEffect.balanceA_extract_rejects_wrong_ledger",
  "Dregg2.Circuit.WitnessExtractPerEffect.bridgeMintA_extract_rejects_wrong_supply",
  "Dregg2.Circuit.WitnessExtractPerEffect.burnA_extract_rejects_wrong_supply",
  "Dregg2.Circuit.WitnessExtractPerEffect.cellSealA_extract_rejects_wrong_lifecycle",
  "Dregg2.Circuit.WitnessExtractPerEffect.cellUnsealA_extract_rejects_wrong_lifecycle",
  "Dregg2.Circuit.WitnessExtractPerEffect.delegateAttenA_extract_rejects_wrong_caps",
  "Dregg2.Circuit.WitnessExtractPerEffect.delegate_extract_rejects_wrong_caps",
  "Dregg2.Circuit.WitnessExtractPerEffect.introduceA_extract_rejects_wrong_caps",
  "Dregg2.Circuit.WitnessExtractPerEffect.receiptArchiveLifecycleA_extract_rejects_wrong_lifecycle",
  "Dregg2.Circuit.WitnessExtractPerEffect.refreshDelegationA_extract_rejects_wrong_delegations",
  "Dregg2.Circuit.WitnessExtractPerEffect.revokeDelegationA_extract_rejects_wrong_caps",
  "Dregg2.Circuit.WitnessExtractPerEffect.revoke_extract_rejects_wrong_caps",
  "Dregg2.Circuit.WitnessExtractPerEffect.transfer_extract_rejects_wrong_ledger",
  "Dregg2.Crypto.HierarchicalGraphFrame.treeAbsorbInjective_of_digest8_injective",
  "Dregg2.Distributed.PrivateLeg.exists_forged_leg",
  "Dregg2.Substrate.Heap.hget_hset_frame",
  "Dregg2.Substrate.Heap.map_leaf_injective",
  "Dregg2.Substrate.Heap.rootColl_refutable_of_injective",
  "Dregg2.Substrate.Heap.root_binds_get",
  "Dregg2.Substrate.Heap.root_injective"]

/-- The inline-spelled grandfathered carriers (280). Only ever gets SHORTER. -/
def inlineSpelled : Array String :=
  i0 ++ i1

end Dregg2.Verify.FloorRatchetBaselineInline
