//! **The proof-producing render** — the usable form of the templater: render a handlebars
//! template with data and emit a re-verifiable certificate that the output was
//! template-generated.
//!
//! This is the Rust SDK realization of the GENERATE direction of
//! `metatheory/Dregg2/Crypto/Handlebars.lean`. The Lean `render T d = T.segments.flatMap
//! (renderSeg d)` (fixed literal text interleaved with per-hole data) is mirrored here
//! byte-for-byte ([`render`]), and the Lean generation-side guard `safe T d` (every hole
//! receives `NoDoubleBrace` data — no `{{` breakout) is the render-time guard
//! ([`RenderError::InjectingHoleData`], via the SAME [`crate::injection::injection_free`]
//! matcher the zkOracle injection leg uses).
//!
//! ## The certificate IS the deployed `CompactCert` — no new leg type
//!
//! The rendered output is a JSON document. Its well-formed-leg witness is exactly the
//! deployed [`crate::cfg::CompactCert`] — the leftmost derivation's rule sequence
//! ([`crate::cfg::prove_cfg_compact`]), the O(tokens) pushdown-replay certificate
//! (`CfgCompact.lean::Replay`). [`render_with_proof`] renders and emits that certificate;
//! [`verify_render_attestation`] replays it with the SAME [`crate::cfg::verify_cfg_compact`]
//! the zkOracle well-formed leg uses. There is no bespoke render checker.
//!
//! ## The attestation — a thin ProofEnvelope, legs re-derived on verify
//!
//! [`RenderAttestation`] mirrors the shape of `dregg_oracle::ProofEnvelope` and
//! [`crate::attestation::ZkOracleAttestation`]: a thin evidence bundle whose properties are
//! RE-DERIVED on verify, not trusted from the wire. It carries the shared
//! [`crate::attestation::content_commitment`] over the rendered output (the SAME Poseidon2
//! sponge the zkOracle cross-leg weld threads) and the `CompactCert`. Verification
//! recomputes the commitment over the presented output and refuses a mismatch
//! ([`RenderVerifyError::CrossLegMismatch`], the exact analogue of
//! [`crate::attestation::ZkOracleError::CrossLegMismatch`]), binding the certificate to the
//! EXACT output bytes — a byte-tampered output is refused before the cert even replays.
//!
//! ## What this proves — and the honest residual
//!
//! An accepted [`RenderAttestation`] over `output` re-derives: (1) `output` is well-formed
//! JSON, witnessed by a genuine leftmost derivation (the `CompactCert`); (2) the cert and
//! commitment are about THOSE EXACT bytes; (3) the prover committed to the template it used
//! ([`RenderAttestation::template_commit`]). A party holding the template + data can go
//! further and REPRODUCE the render ([`verify_render_reproducible`]) — a genuine
//! "generated by THIS template with THIS data" check by byte-equality.
//!
//! The full zero-knowledge "generated by template `T` with SOME in-slot data" claim — a
//! parse of `output` back against `handlebarsToGrammar T` recovering per-hole data — is the
//! round-trip / uniqueness direction named as a residual in `Handlebars.lean` §9 (it needs
//! the delimiter-guarded unambiguity side-condition mathlib has no API for). This SDK ships
//! the tractable, load-bearing GENERATE direction; it does not claim the converse.

use crate::attestation::content_commitment;
use crate::cfg::{CfgError, CompactCert, prove_cfg_compact, verify_cfg_compact};
use crate::injection::injection_free;
use dregg_circuit::field::BabyBear;
use dregg_circuit::poseidon2::hash_bytes;
use std::collections::BTreeMap;

/// The attestation scheme tag (pinned; [`verify_render_attestation`] refuses any other).
pub const SCHEME: &str = "dregg-render/1";

/// The tool + version that produced an attestation.
pub const TOOL: &str = concat!("dregg-zkoracle-prove render ", env!("CARGO_PKG_VERSION"));

/// A template **segment** — the Rust twin of `Handlebars.lean::Segment`: fixed literal
/// bytes, or a named hole filled from the render data.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Segment {
    /// Fixed literal text (emitted verbatim).
    Lit(Vec<u8>),
    /// A named hole (filled by the data's value for `name`).
    Hole(String),
}

/// A **handlebars template** — a list of segments, fixed text interleaved with holes (the
/// Rust twin of `Handlebars.lean::HandlebarsTemplate`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Template {
    /// The segments, in output order.
    pub segments: Vec<Segment>,
}

impl Template {
    /// Build a template from its segments.
    pub fn new(segments: Vec<Segment>) -> Self {
        Template { segments }
    }
}

/// A per-hole data assignment (`Handlebars.lean`'s `d : HoleId → List Tok`, here a finite
/// map so it serializes and iterates deterministically).
pub type RenderData = BTreeMap<String, Vec<u8>>;

/// Why the prover could not PRODUCE a render / its certificate.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RenderError {
    /// A hole named by the template has no value in the render data.
    MissingHole(String),
    /// A hole's data carries the `{{` handlebars delimiter — an in-slot breakout. The
    /// render-time realization of `Handlebars.lean`'s `safe T d` (`NoDoubleBrace` per hole):
    /// the templater REFUSES to render an injecting assignment (mirroring
    /// [`crate::attestation::ProveError::Injection`]).
    InjectingHoleData(String),
    /// The rendered output is not well-formed JSON, so no `CompactCert` exists for it — the
    /// literals + hole data did not compose into a JSON document.
    NotWellFormed(CfgError),
}

impl core::fmt::Display for RenderError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            RenderError::MissingHole(h) => write!(f, "template hole {h:?} has no render data"),
            RenderError::InjectingHoleData(h) => write!(
                f,
                "refusing to render: hole {h:?} data carries the {{{{ delimiter (in-slot breakout)"
            ),
            RenderError::NotWellFormed(e) => {
                write!(f, "rendered output is not well-formed JSON: {e:?}")
            }
        }
    }
}

impl std::error::Error for RenderError {}

/// **RENDER a template with data** — the GENERATE direction, the Rust twin of
/// `Handlebars.lean::render` (`T.segments.flatMap (renderSeg d)`): literal segments emit
/// their bytes, hole segments emit their data value. Each hole's data is checked
/// injection-free ([`crate::injection::injection_free`]) — the render-time realization of
/// the Lean `safe T d` precondition — so an injecting assignment is REFUSED, never rendered.
pub fn render(template: &Template, data: &RenderData) -> Result<Vec<u8>, RenderError> {
    let mut out = Vec::new();
    for seg in &template.segments {
        match seg {
            Segment::Lit(bytes) => out.extend_from_slice(bytes),
            Segment::Hole(name) => {
                let val = data
                    .get(name)
                    .ok_or_else(|| RenderError::MissingHole(name.clone()))?;
                // The generation-side guard: safe hole data has no `{{` breakout.
                if !injection_free(val) {
                    return Err(RenderError::InjectingHoleData(name.clone()));
                }
                out.extend_from_slice(val);
            }
        }
    }
    Ok(out)
}

/// **RENDER + PROVE** — render `template` with `data` and emit the output together with its
/// well-formed-leg certificate: the deployed [`CompactCert`] over the rendered output
/// ([`prove_cfg_compact`], the leftmost rule sequence). A malformed render (literals + data
/// that do not compose into JSON) yields [`RenderError::NotWellFormed`] — the certificate
/// only exists for a genuine JSON output.
pub fn render_with_proof(
    template: &Template,
    data: &RenderData,
) -> Result<(Vec<u8>, CompactCert), RenderError> {
    let output = render(template, data)?;
    let cert = prove_cfg_compact(&output).map_err(RenderError::NotWellFormed)?;
    Ok((output, cert))
}

/// **A template's structural commitment** — a Poseidon2 sponge over a canonical byte
/// encoding of the segments (tagged, length-prefixed), the SAME [`hash_bytes`] primitive the
/// content commitment uses. Binds an attestation to the TEMPLATE it was generated from; a
/// party holding the template recomputes it ([`verify_render_reproducible`]).
pub fn template_commitment(template: &Template) -> BabyBear {
    let mut enc = Vec::new();
    for seg in &template.segments {
        match seg {
            Segment::Lit(bytes) => {
                enc.push(0u8);
                enc.extend_from_slice(&(bytes.len() as u64).to_le_bytes());
                enc.extend_from_slice(bytes);
            }
            Segment::Hole(name) => {
                enc.push(1u8);
                let nb = name.as_bytes();
                enc.extend_from_slice(&(nb.len() as u64).to_le_bytes());
                enc.extend_from_slice(nb);
            }
        }
    }
    hash_bytes(&enc)
}

/// **The render attestation** — a thin ProofEnvelope-shaped evidence bundle (mirroring
/// [`crate::attestation::ZkOracleAttestation`] and `dregg_oracle::ProofEnvelope`) that the
/// output was template-generated. Every field is RE-DERIVED on verify, not trusted.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct RenderAttestation {
    /// Format tag (pinned to [`SCHEME`]).
    pub scheme: String,
    /// The tool + version that produced this attestation.
    pub tool: String,
    /// **The output↔cert weld** — the shared [`content_commitment`] over the rendered
    /// output. [`verify_render_attestation`] recomputes it over the presented output and
    /// refuses a mismatch, binding the certificate to the EXACT output bytes.
    pub output_commit: BabyBear,
    /// **The template binding** — [`template_commitment`] over the template that generated
    /// the output. A party holding the template re-derives it ([`verify_render_reproducible`]).
    pub template_commit: BabyBear,
    /// **The well-formed leg** — the deployed [`CompactCert`] over the rendered output (the
    /// leftmost rule sequence, replayed by [`verify_cfg_compact`]). NOT a new leg type.
    pub cfg_cert: CompactCert,
}

/// **PRODUCE a render attestation** — render `template` with `data`, then bundle the
/// output commitment, template commitment, and well-formed-leg certificate. Returns the
/// rendered output alongside so the caller can present both. Refuses an injecting or
/// malformed render exactly as [`render_with_proof`] does.
pub fn attest_render(
    template: &Template,
    data: &RenderData,
) -> Result<(Vec<u8>, RenderAttestation), RenderError> {
    let (output, cfg_cert) = render_with_proof(template, data)?;
    let att = RenderAttestation {
        scheme: SCHEME.to_string(),
        tool: TOOL.to_string(),
        output_commit: content_commitment(&output),
        template_commit: template_commitment(template),
        cfg_cert,
    };
    Ok((output, att))
}

/// Why a render attestation was REFUSED.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RenderVerifyError {
    /// The attestation's scheme tag is not [`SCHEME`].
    UnknownScheme(String),
    /// **The output↔cert weld refused** — the recomputed [`content_commitment`] over the
    /// presented output disagrees with [`RenderAttestation::output_commit`]. A byte-tampered
    /// output (or an attestation about a DIFFERENT output) fails HERE, before the cert
    /// replays. The exact analogue of [`crate::attestation::ZkOracleError::CrossLegMismatch`].
    CrossLegMismatch,
    /// **The well-formed leg refused** — the [`CompactCert`] does not replay against the
    /// presented output (`verify_cfg_compact` failed: the output is not the JSON word the
    /// cert derives).
    NotWellFormed(CfgError),
    /// **The template binding refused** ([`verify_render_reproducible`] only) — the recomputed
    /// [`template_commitment`] disagrees with [`RenderAttestation::template_commit`].
    TemplateMismatch,
    /// **The reproduced render disagrees** ([`verify_render_reproducible`] only) — rendering
    /// the given template + data did not reproduce the presented output byte-for-byte, or the
    /// render itself was refused.
    Reproduce(RenderError),
}

impl core::fmt::Display for RenderVerifyError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            RenderVerifyError::UnknownScheme(s) => {
                write!(f, "unknown attestation scheme {s:?} (expected {SCHEME})")
            }
            RenderVerifyError::CrossLegMismatch => write!(
                f,
                "output↔cert weld refused: the certificate is not about the presented output bytes"
            ),
            RenderVerifyError::NotWellFormed(e) => {
                write!(f, "well-formed leg refused: {e:?}")
            }
            RenderVerifyError::TemplateMismatch => {
                write!(
                    f,
                    "template binding refused: the given template is not the one attested"
                )
            }
            RenderVerifyError::Reproduce(e) => {
                write!(
                    f,
                    "reproduced render disagrees with the attested output: {e}"
                )
            }
        }
    }
}

impl std::error::Error for RenderVerifyError {}

/// **VERIFY a render attestation over a presented output** — re-derive the legs.
///
/// ACCEPTS iff: the scheme is pinned; the recomputed [`content_commitment`] over `output`
/// equals [`RenderAttestation::output_commit`] (the weld — binds the cert to THESE exact
/// bytes); and the [`CompactCert`] replays against `output` ([`verify_cfg_compact`], the
/// well-formed leg). A byte-tampered output fails the weld ([`RenderVerifyError::CrossLegMismatch`]);
/// a cert about a structurally different output fails the replay ([`RenderVerifyError::NotWellFormed`]).
pub fn verify_render_attestation(
    att: &RenderAttestation,
    output: &[u8],
) -> Result<(), RenderVerifyError> {
    if att.scheme != SCHEME {
        return Err(RenderVerifyError::UnknownScheme(att.scheme.clone()));
    }
    // ── THE OUTPUT↔CERT WELD ── recompute the commitment over the presented bytes.
    if content_commitment(output) != att.output_commit {
        return Err(RenderVerifyError::CrossLegMismatch);
    }
    // ── THE WELL-FORMED LEG ── replay the CompactCert against the presented output.
    verify_cfg_compact(&att.cfg_cert, output).map_err(RenderVerifyError::NotWellFormed)?;
    Ok(())
}

/// **VERIFY by REPRODUCING the render** — the strongest "generated by THIS template with
/// THIS data" check, for a party holding both. Re-derives the template binding, re-renders
/// the output, and checks it byte-for-byte against the attested output (via the weld +
/// well-formed leg). Returns the reproduced output on success.
pub fn verify_render_reproducible(
    att: &RenderAttestation,
    template: &Template,
    data: &RenderData,
) -> Result<Vec<u8>, RenderVerifyError> {
    if template_commitment(template) != att.template_commit {
        return Err(RenderVerifyError::TemplateMismatch);
    }
    let output = render(template, data).map_err(RenderVerifyError::Reproduce)?;
    verify_render_attestation(att, &output)?;
    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A two-hole JSON template: `{"greeting":"` · ⟨name⟩ · `","kind":"` · ⟨kind⟩ · `"}`.
    fn greet_template() -> Template {
        Template::new(vec![
            Segment::Lit(br#"{"greeting":""#.to_vec()),
            Segment::Hole("name".to_string()),
            Segment::Lit(br#"","kind":""#.to_vec()),
            Segment::Hole("kind".to_string()),
            Segment::Lit(br#""}"#.to_vec()),
        ])
    }

    fn greet_data() -> RenderData {
        BTreeMap::from([
            ("name".to_string(), b"world".to_vec()),
            ("kind".to_string(), b"wave".to_vec()),
        ])
    }

    #[test]
    fn render_matches_manual_concatenation() {
        // The Rust render is exactly the Lean flatMap: literals + hole data in order.
        let out = render(&greet_template(), &greet_data()).unwrap();
        assert_eq!(out, br#"{"greeting":"world","kind":"wave"}"#);
    }

    #[test]
    fn render_with_proof_certificate_verifies() {
        // THE PRIMARY POLE: verify_cfg_compact ACCEPTS the render_with_proof certificate
        // over the rendered output.
        let (out, cert) = render_with_proof(&greet_template(), &greet_data()).unwrap();
        verify_cfg_compact(&cert, &out).expect("the render certificate replays over the output");
    }

    #[test]
    fn attestation_round_trips_and_verifies() {
        let (out, att) = attest_render(&greet_template(), &greet_data()).unwrap();
        verify_render_attestation(&att, &out).expect("a genuine attestation accepts");
        // ProofEnvelope-shaped: serializes and re-verifies off the wire.
        let json = serde_json::to_string(&att).unwrap();
        let back: RenderAttestation = serde_json::from_str(&json).unwrap();
        verify_render_attestation(&back, &out).expect("the deserialized attestation accepts");
        assert_eq!(att.scheme, SCHEME);
    }

    #[test]
    fn tampered_output_fails_the_weld() {
        // DIFFERENTIAL POLE A: a byte-flipped output → content_commitment mismatch → REFUSE
        // (CrossLegMismatch). Flip a byte inside a string literal so the tampered output is
        // STILL valid JSON — the refusal is the commitment weld, not a parse failure.
        let (out, att) = attest_render(&greet_template(), &greet_data()).unwrap();
        let mut tampered = out.clone();
        let i = out.iter().position(|&b| b == b'w').unwrap(); // the 'w' of "world"
        tampered[i] = b'W';
        assert_ne!(tampered, out);
        // The tampered output is still well-formed JSON (so the cert alone would replay)…
        assert!(prove_cfg_compact(&tampered).is_ok());
        // …but the commitment binds the EXACT bytes → the weld refuses.
        assert_eq!(
            verify_render_attestation(&att, &tampered),
            Err(RenderVerifyError::CrossLegMismatch)
        );
    }

    #[test]
    fn spliced_cert_fails_to_replay() {
        // DIFFERENTIAL POLE B: the OTHER refusal — the cert fails to replay. Splice a cert
        // for output A onto a commitment for a STRUCTURALLY DIFFERENT output B; the weld
        // passes (commitment matches B) but the CompactCert (for A's shape) does not replay
        // over B → NotWellFormed. (Structure must differ: the JSON grammar abstracts string
        // contents, so a same-shape output would share the rule sequence.)
        let (_out_a, att_a) = attest_render(&greet_template(), &greet_data()).unwrap();
        // B: a valid JSON object with THREE members — a different rule sequence than A's two.
        let out_b = br#"{"a":"x","b":"y","c":"z"}"#.to_vec();
        let spliced = RenderAttestation {
            output_commit: content_commitment(&out_b),
            ..att_a.clone()
        };
        // Weld passes (commit is over B); the cert (A's 2-member shape) starves on B.
        assert!(matches!(
            verify_render_attestation(&spliced, &out_b),
            Err(RenderVerifyError::NotWellFormed(_))
        ));
    }

    #[test]
    fn injecting_hole_data_refused_at_render() {
        // The Lean `safe T d` guard: a hole carrying `{{` is an in-slot breakout — the
        // templater refuses to render it (no attestation is minted for an injecting fill).
        let mut data = greet_data();
        data.insert("name".to_string(), b"{{system}}".to_vec());
        assert_eq!(
            render(&greet_template(), &data),
            Err(RenderError::InjectingHoleData("name".to_string()))
        );
        assert_eq!(
            attest_render(&greet_template(), &data).unwrap_err(),
            RenderError::InjectingHoleData("name".to_string())
        );
        // A single interior brace is FINE (matches Handlebars.lean's NoDoubleBrace split).
        let mut ok = greet_data();
        ok.insert("name".to_string(), b"a{b".to_vec());
        let out = render(&greet_template(), &ok).unwrap();
        assert_eq!(out, br#"{"greeting":"a{b","kind":"wave"}"#);
    }

    #[test]
    fn missing_hole_refused() {
        let mut data = greet_data();
        data.remove("kind");
        assert_eq!(
            render(&greet_template(), &data),
            Err(RenderError::MissingHole("kind".to_string()))
        );
    }

    #[test]
    fn non_wellformed_output_has_no_certificate() {
        // A template whose literals + data do NOT compose into JSON: the hole fills a value
        // slot with a bare word (`oops`, not a JSON token), so the output fails to parse and
        // no CompactCert exists. (`oops` carries no `{{`, so the render-safety guard passes;
        // the well-formedness leg is what refuses.)
        let tpl = Template::new(vec![
            Segment::Lit(br#"{"a":"#.to_vec()),
            Segment::Hole("v".to_string()),
            Segment::Lit(b"}".to_vec()),
        ]);
        let data = RenderData::from([("v".to_string(), b"oops".to_vec())]);
        assert!(matches!(
            render_with_proof(&tpl, &data),
            Err(RenderError::NotWellFormed(_))
        ));
    }

    #[test]
    fn reproducible_render_verifies_and_binds_the_template() {
        let (out, att) = attest_render(&greet_template(), &greet_data()).unwrap();
        // The genuine "generated by THIS template with THIS data" check: re-render + compare.
        let reproduced =
            verify_render_reproducible(&att, &greet_template(), &greet_data()).unwrap();
        assert_eq!(reproduced, out);
        // A DIFFERENT template is refused by the template binding, before re-rendering.
        let other = Template::new(vec![Segment::Lit(br#"{"x":1}"#.to_vec())]);
        assert_eq!(
            verify_render_reproducible(&att, &other, &greet_data()),
            Err(RenderVerifyError::TemplateMismatch)
        );
        // The right template but DIFFERENT data reproduces a different output → weld refuses.
        let mut other_data = greet_data();
        other_data.insert("name".to_string(), b"mars".to_vec());
        assert_eq!(
            verify_render_reproducible(&att, &greet_template(), &other_data),
            Err(RenderVerifyError::CrossLegMismatch)
        );
    }

    #[test]
    fn unknown_scheme_refused() {
        let (out, mut att) = attest_render(&greet_template(), &greet_data()).unwrap();
        att.scheme = "bogus/9".to_string();
        assert_eq!(
            verify_render_attestation(&att, &out),
            Err(RenderVerifyError::UnknownScheme("bogus/9".to_string()))
        );
    }
}
