/-
# A cartesian closed category of finite polynomial functions

The objects in this category are the finite field-power types generated by
`FiniteHOL.Ty`.  A morphism is an extensional function between the corresponding
finite powers.  Finite-field interpolation proves that every such morphism is
represented coordinatewise by a polynomial, so this is equivalently the
category of *polynomial functions* (polynomials identified by their evaluations),
not the category of intensional polynomial syntax.

The exponential is the complete finite function table.  Consequently this
construction is exactly cartesian closed, but its exponential object has one
coordinate per input value and output coordinate; the construction does not
claim a succinct representation of arbitrary higher-order functions.
-/
import Dregg2.Metatheory.FinitePolynomialFunctions

namespace Dregg2.Metatheory.FinitePolynomialCCC

open Dregg2.Metatheory.FinitePolynomialFunctions
open Dregg2.Metatheory.FinitePolynomialFunctions.FiniteHOL

noncomputable section

variable {F : Type} [Field F] [Fintype F]
variable {A B C D X : Ty}

/-! ## The small category -/

/-- Extensional arrows between finite field powers. -/
abbrev Hom (F : Type) [Field F] [Fintype F] (A B : Ty) := Val F A → Val F B

/-- Identity arrow. -/
def id (A : Ty) : Hom F A A := fun x => x

/-- Diagrammatic composition: `comp g f` means first `f`, then `g`. -/
def comp (g : Hom F B C) (f : Hom F A B) : Hom F A C := fun x => g (f x)

@[simp] theorem id_apply (x : Val F A) : id A x = x := rfl

@[simp] theorem comp_apply (g : Hom F B C) (f : Hom F A B) (x : Val F A) :
    comp g f x = g (f x) := rfl

@[simp] theorem id_comp (f : Hom F A B) : comp (id B) f = f := by
  rfl

@[simp] theorem comp_id (f : Hom F A B) : comp f (id A) = f := by
  rfl

theorem comp_assoc (h : Hom F C D) (g : Hom F B C) (f : Hom F A B) :
    comp h (comp g f) = comp (comp h g) f := by
  rfl

/-! ## Terminal object and binary products -/

/-- The zero-coordinate field power is terminal. -/
abbrev terminal : Ty := .unit

/-- The unique map into the zero-coordinate power. -/
def terminate (A : Ty) : Hom F A terminal := fun _ i => nomatch i

theorem terminal_unique (f : Hom F A terminal) : f = terminate A := by
  funext x i
  exact Empty.elim i

/-- Binary products concatenate coordinate sets. -/
abbrev product (A B : Ty) : Ty := .prod A B

/-- Pair two values by placing them in the two coordinate summands. -/
def pairValue (x : Val F A) (y : Val F B) : Val F (product A B) :=
  Sum.elim x y

/-- First projection. -/
def fst : Hom F (product A B) A := fun z i => z (Sum.inl i)

/-- Second projection. -/
def snd : Hom F (product A B) B := fun z j => z (Sum.inr j)

/-- Pair arrows with a common domain. -/
def pair (f : Hom F X A) (g : Hom F X B) : Hom F X (product A B) :=
  fun x => pairValue (f x) (g x)

@[simp] theorem fst_pair (f : Hom F X A) (g : Hom F X B) :
    comp fst (pair f g) = f := by
  rfl

@[simp] theorem snd_pair (f : Hom F X A) (g : Hom F X B) :
    comp snd (pair f g) = g := by
  rfl

/-- Product eta for values. -/
@[simp] theorem pairValue_fst_snd (z : Val F (product A B)) :
    pairValue (fst z) (snd z) = z := by
  funext ij
  cases ij <;> rfl

/-- Product eta for arrows. -/
@[simp] theorem pair_fst_snd (h : Hom F X (product A B)) :
    pair (comp fst h) (comp snd h) = h := by
  funext x
  exact pairValue_fst_snd (h x)

/-- The product mediator is unique. -/
theorem pair_unique (h : Hom F X (product A B)) (f : Hom F X A) (g : Hom F X B)
    (hfst : comp fst h = f) (hsnd : comp snd h = g) : h = pair f g := by
  rw [← hfst, ← hsnd, pair_fst_snd]

/-! ## Table exponentials -/

/-- The exponential object: a coordinate for each input value/output coordinate pair. -/
abbrev exponential (A B : Ty) : Ty := .arr A B

/-- Evaluation of a complete finite function table. -/
def evaluation : Hom F (product (exponential A B) A) B := fun z =>
  tableEval (fst z) (snd z)

/-- Curry a morphism by filling its complete finite function table. -/
def curry (f : Hom F (product X A) B) : Hom F X (exponential A B) :=
  fun x xj => f (pairValue x xj.1) xj.2

/-- Uncurry a table-valued morphism by evaluating its table component. -/
def uncurry (g : Hom F X (exponential A B)) : Hom F (product X A) B :=
  fun xa => tableEval (g (fst xa)) (snd xa)

/-- Exponential beta: evaluating a curried arrow recovers the original arrow. -/
@[simp] theorem uncurry_curry (f : Hom F (product X A) B) :
    uncurry (curry f) = f := by
  funext xa j
  change f (pairValue (fst xa) (snd xa)) j = f xa j
  rw [pairValue_fst_snd]

/-- Exponential eta: currying evaluation of a table-valued arrow recovers it. -/
@[simp] theorem curry_uncurry (g : Hom F X (exponential A B)) :
    curry (uncurry g) = g := by
  funext x xj
  rfl

/-- Uncurrying is the usual evaluation diagram. -/
theorem uncurry_eq_evaluation (g : Hom F X (exponential A B)) :
    uncurry g = comp evaluation (pair (comp g fst) snd) := by
  rfl

/-- The beta equation in categorical evaluation form. -/
theorem evaluation_beta (f : Hom F (product X A) B) :
    comp evaluation (pair (comp (curry f) fst) snd) = f := by
  rw [← uncurry_eq_evaluation, uncurry_curry]

/-- The exponential mediator is unique. -/
theorem curry_unique (f : Hom F (product X A) B) (g : Hom F X (exponential A B))
    (heval : comp evaluation (pair (comp g fst) snd) = f) : g = curry f := by
  rw [← uncurry_eq_evaluation] at heval
  rw [← heval, curry_uncurry]

/-! ## A compact bundle of the universal laws

This record is deliberately smaller than Mathlib's bundled category hierarchy:
it states precisely the category, terminal, product, and exponential equations
used by the construction, without introducing coercions or universe-level
bookkeeping unrelated to the arithmetization theorem.
-/

/-- The law package witnessing that finite field-power polynomial functions form a CCC. -/
structure Laws : Prop where
  leftIdentity : ∀ {A B} (f : Hom F A B), comp (id B) f = f
  rightIdentity : ∀ {A B} (f : Hom F A B), comp f (id A) = f
  associativity : ∀ {A B C D} (h : Hom F C D) (g : Hom F B C) (f : Hom F A B),
    comp h (comp g f) = comp (comp h g) f
  terminality : ∀ {A} (f : Hom F A terminal), f = terminate A
  productBetaFst : ∀ {X A B} (f : Hom F X A) (g : Hom F X B),
    comp fst (pair f g) = f
  productBetaSnd : ∀ {X A B} (f : Hom F X A) (g : Hom F X B),
    comp snd (pair f g) = g
  productEta : ∀ {X A B} (h : Hom F X (product A B)),
    pair (comp fst h) (comp snd h) = h
  exponentialBeta : ∀ {X A B} (f : Hom F (product X A) B), uncurry (curry f) = f
  exponentialEta : ∀ {X A B} (g : Hom F X (exponential A B)), curry (uncurry g) = g

/-- The explicit operations above satisfy the bundled CCC laws. -/
theorem finitePolynomialCCCLaws : Laws (F := F) where
  leftIdentity := id_comp
  rightIdentity := comp_id
  associativity := comp_assoc
  terminality := terminal_unique
  productBetaFst := fst_pair
  productBetaSnd := snd_pair
  productEta := pair_fst_snd
  exponentialBeta := uncurry_curry
  exponentialEta := curry_uncurry

/-! ## Polynomial representation -/

/-- Coordinatewise interpolation of any arrow in the CCC. -/
def represent (f : Hom F A B) : Coord F B → MvPolynomial (Coord F A) F :=
  interpolateVector f

/-- Every CCC arrow is represented extensionally by its interpolated polynomials. -/
@[simp] theorem eval_represent (f : Hom F A B) (x : Val F A) (j : Coord F B) :
    MvPolynomial.eval x (represent f j) = f x j := by
  exact eval_interpolateVector f x j

/-- The specialized polynomial for the evaluation arrow. -/
def evaluationPolynomial (j : Coord F B) :
    MvPolynomial (Coord F (product (exponential A B) A)) F :=
  tableEvalPolynomial j

/-- The exponential evaluation morphism is represented exactly by table interpolation. -/
@[simp] theorem eval_evaluationPolynomial
    (z : Val F (product (exponential A B) A)) (j : Coord F B) :
    MvPolynomial.eval z (evaluationPolynomial j) = evaluation z j := by
  have hz : pack (fst z) (snd z) = z := by
    funext ij
    cases ij <;> rfl
  rw [← hz]
  exact eval_tableEvalPolynomial j (fst z) (snd z)

#assert_all_clean [id_comp, comp_id, comp_assoc, terminal_unique, fst_pair, snd_pair,
  pairValue_fst_snd, pair_fst_snd, pair_unique, uncurry_curry, curry_uncurry,
  uncurry_eq_evaluation, evaluation_beta, curry_unique, finitePolynomialCCCLaws,
  eval_represent, eval_evaluationPolynomial]

end

end Dregg2.Metatheory.FinitePolynomialCCC
