//! # The Lean-sourced program loader.
//!
//! The multiway-tug play teeth are **authored in Lean**
//! (`metatheory/Dregg2/Games/MultiwayTugProgram.lean :: multiwayTugProgram`) and emitted to the
//! checked-in artifact [`PROGRAM_JSON`] by the verified emit
//! (`metatheory/EmitMultiwayTugProgram.lean`). This module does the ONLY Rust-side work: it
//! deserializes that symbolic artifact and resolves the symbolic slot/method NAMES into the
//! runtime [`CellProgram`] by looking them up in the translation-validated `dregg-schema`
//! allocator ([`Deployment`]). There is NO hand-rolled `CellProgram::Cases` in Rust anymore —
//! the deployed program IS the Lean object by construction (edit a threshold in the Lean source,
//! re-emit via `program/regen.sh`, and the deployed game changes).
//!
//! **What is Lean-sourced vs Rust-resolved.** The teeth STRUCTURE — which methods, which
//! constraints, the conservation sum, the `WriteOnce`/`Monotonic`/`StrictMonotonic` atoms, and
//! the NINE scoring clauses with their thresholds, cross-register tie-breaks and pinned `winner`
//! values (`charm >= 11`, `guilds >= 4`, `b_charm < a_charm`, `round_actions >= 12`) — is entirely
//! the artifact's content. Rust only maps a symbolic NAME to its allocator-assigned index
//! (`reg`/`key`) and a method NAME to its `symbol()` hash. The allocator is itself
//! translation-validated (the RotatedLayout Legal discipline), so the name→index binding is not
//! a hand-authored semantic object; the semantic teeth are the Lean value's.

use dregg_app_framework::{
    CellProgram, StateConstraint, TransitionCase, TransitionGuard, field_from_u64, symbol,
};
use dregg_cell::program::{HeapAtom, SimpleStateConstraint};
use serde::Deserialize;
use spween_dregg::GENESIS_DONE_EXT_KEY;

use crate::state::Deployment;

/// The checked-in Lean-emitted artifact (a CACHE of the verified Lean emission; Lean is the
/// source of truth, regenerated by `program/regen.sh`).
pub const PROGRAM_JSON: &str = include_str!("../program/multiway_tug_program.json");

/// The symbolic top-level program (mirrors the Lean `CellProgram.cases`).
#[derive(Debug, Deserialize)]
struct SymProgram {
    scene: String,
    /// ⚑ The nine scoring-clause METHOD NAMES, in `roundWinner` precedence order, emitted by Lean
    /// (`MultiwayTugProgram.scoreBranchMethod` over `scoreBranches`). A scoring turn commits under
    /// `score_branches[branch]` where `branch` is the clause the Lean oracle named — so Rust never
    /// holds a branch→method table of its own and cannot drift from the emitted cases.
    score_branches: Vec<String>,
    cases: Vec<SymCase>,
}

#[derive(Debug, Deserialize)]
struct SymCase {
    method: String,
    constraints: Vec<SymConstraint>,
}

/// The symbolic `StateConstraint` subset tug uses (mirrors Lean `Constraint`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymConstraint {
    SumEquals {
        regs: Vec<String>,
        value: u64,
    },
    WriteOnce {
        reg: String,
    },
    StrictMonotonic {
        reg: String,
    },
    FieldGte {
        reg: String,
        value: u64,
    },
    HeapField {
        key: SymKey,
        atom: SymAtom,
    },
    AnyOf {
        variants: Vec<SymSimple>,
    },
    /// `new[reg] <= new[other] + delta` (signed) — the deployed cross-register comparison
    /// (`StateConstraint::FieldLteOther`). The scoring clauses need it: `roundWinner` adjudicates
    /// on `b_charm < a_charm`, which no literal threshold can express.
    FieldLteOther {
        reg: String,
        other: String,
        delta: i64,
    },
}

/// The symbolic heap-key reference (mirrors Lean `HeapKeyRef`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymKey {
    Named { name: String },
    Sentinel,
}

/// The symbolic heap-atom subset (mirrors Lean `HeapAtom`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymAtom {
    WriteOnce,
    Monotonic,
    Immutable,
    Equals { value: u64 },
    DeltaEquals { d: i64 },
}

/// The symbolic simple-constraint subset (mirrors Lean `SimpleConstraint`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymSimple {
    FieldEquals { reg: String, value: u64 },
    FieldGte { reg: String, value: u64 },
    Not { inner: Box<SymSimple> },
}

impl SymKey {
    fn resolve(&self, dep: &Deployment) -> u64 {
        match self {
            SymKey::Named { name } => dep.key(name),
            SymKey::Sentinel => GENESIS_DONE_EXT_KEY,
        }
    }
}

impl SymAtom {
    fn resolve(&self) -> HeapAtom {
        match self {
            SymAtom::WriteOnce => HeapAtom::WriteOnce,
            SymAtom::Monotonic => HeapAtom::Monotonic,
            SymAtom::Immutable => HeapAtom::Immutable,
            SymAtom::Equals { value } => HeapAtom::Equals {
                value: field_from_u64(*value),
            },
            SymAtom::DeltaEquals { d } => HeapAtom::DeltaEquals { d: *d },
        }
    }
}

impl SymSimple {
    fn resolve(&self, dep: &Deployment) -> SimpleStateConstraint {
        match self {
            SymSimple::FieldEquals { reg, value } => SimpleStateConstraint::FieldEquals {
                index: dep.reg(reg),
                value: field_from_u64(*value),
            },
            SymSimple::FieldGte { reg, value } => SimpleStateConstraint::FieldGte {
                index: dep.reg(reg),
                value: field_from_u64(*value),
            },
            SymSimple::Not { inner } => SimpleStateConstraint::Not(Box::new(inner.resolve(dep))),
        }
    }
}

impl SymConstraint {
    fn resolve(&self, dep: &Deployment) -> StateConstraint {
        match self {
            SymConstraint::SumEquals { regs, value } => StateConstraint::SumEquals {
                indices: regs.iter().map(|n| dep.reg(n)).collect(),
                value: field_from_u64(*value),
            },
            SymConstraint::WriteOnce { reg } => StateConstraint::WriteOnce {
                index: dep.reg(reg),
            },
            SymConstraint::StrictMonotonic { reg } => StateConstraint::StrictMonotonic {
                index: dep.reg(reg),
            },
            SymConstraint::FieldGte { reg, value } => StateConstraint::FieldGte {
                index: dep.reg(reg),
                value: field_from_u64(*value),
            },
            SymConstraint::HeapField { key, atom } => StateConstraint::HeapField {
                key: key.resolve(dep),
                atom: atom.resolve(),
            },
            SymConstraint::AnyOf { variants } => StateConstraint::AnyOf {
                variants: variants.iter().map(|v| v.resolve(dep)).collect(),
            },
            SymConstraint::FieldLteOther { reg, other, delta } => StateConstraint::FieldLteOther {
                index: dep.reg(reg),
                other: dep.reg(other),
                delta: *delta,
            },
        }
    }
}

/// The scene id the artifact must declare (fixes the deterministic world-cell identity).
pub const EXPECTED_SCENE: &str = "dregg-multiway-tug/phase0";

/// **Load the Lean-authored tug program**, resolving the symbolic slot/method names against the
/// allocator. Panics if the artifact fails to parse or names the wrong scene — a corrupt/stale
/// artifact must fail loud at deploy, never silently ship a different program.
pub fn load_program(dep: &Deployment) -> CellProgram {
    let sym = parse();
    assert_eq!(
        sym.scene, EXPECTED_SCENE,
        "Lean-emitted program scene mismatch (stale/foreign artifact)"
    );
    let cases = sym
        .cases
        .into_iter()
        .map(|c| TransitionCase {
            guard: TransitionGuard::MethodIs {
                method: symbol(&c.method),
            },
            constraints: c.constraints.iter().map(|k| k.resolve(dep)).collect(),
        })
        .collect();
    CellProgram::Cases(cases)
}

/// Parse the checked-in artifact (panicking on a corrupt one — a stale artifact must fail loud at
/// deploy, never silently ship a different program).
fn parse() -> SymProgram {
    serde_json::from_str(PROGRAM_JSON).expect("multiway_tug_program.json (Lean-emitted) parses")
}

/// The number of scoring clauses the terminal rule has (`roundWinner`'s precedence length).
pub const SCORE_BRANCHES: usize = 9;

/// **The deployed method a scoring turn commits under for clause `branch`** — read straight out of
/// the Lean-emitted artifact, never from a Rust table. `branch` is what the Lean oracle answered
/// (`MultiwayTugFFI`'s `branch` verb over `roundWinnerBranch`); this only looks it up.
///
/// Panics on an out-of-range clause or an artifact whose `score_branches` is the wrong length —
/// both mean the emitted program and the oracle have come apart, which must fail loud.
pub fn score_branch_method(branch: u8) -> String {
    let sym = parse();
    assert_eq!(
        sym.score_branches.len(),
        SCORE_BRANCHES,
        "Lean-emitted score_branches has {} entries, expected {SCORE_BRANCHES} \
         (the artifact and the terminal rule have come apart)",
        sym.score_branches.len()
    );
    sym.score_branches
        .get(branch as usize)
        .unwrap_or_else(|| panic!("scoring clause {branch} is out of range 0..{SCORE_BRANCHES}"))
        .clone()
}

/// Every scoring-clause method name, in precedence order (the artifact's own list).
pub fn score_branch_methods() -> Vec<String> {
    parse().score_branches
}
