import { Field } from 'o1js';

// ---------------------------------------------------------------------------
// The dregg-side Rust hasher's committed Mina-Poseidon vectors.
//
// Every constant below is a VERBATIM copy of a value asserted by
// `circuit-prove/sketches/mina-pasta-hash-probe/src/main.rs` (the `GOLD`
// table at `:118-155`, `GOLD_PMINUS1*` at `:158-160`, and the depth-2 Merkle
// root at `:215`). That probe hashes with `mina-poseidon`
// (o1-labs/proof-systems rev 36a8b510) —
// `ArithmeticSponge<Fp, PlonkSpongeConstantsKimchi, 55>` over
// `pasta::fp_kimchi::static_params()`.
//
// The two sides are INDEPENDENT IMPLEMENTATIONS of the same sponge: Rust/arkworks
// here, OCaml-compiled-to-WASM inside o1js there. Asserting that both reproduce
// the same 9 digests + the same depth-2 root is a real cross-implementation
// agreement on Mina-Poseidon over Pasta Fp.
//
// ⚑ Provenance, stated honestly: these vectors were originally GENERATED by
// o1js (`scripts/poseidon-kat.ts`) and pasted into the Rust probe, so the Rust
// side is the one that was pinned against the other. Agreement is therefore a
// two-way check on the two implementations, not evidence that dregg "emitted"
// anything about its own state. See docs/AUDIT-IMPORTER-AND-DOCS.md §3.3-3.4.
//
// If the Rust probe's constants and these ever diverge, the gate must go red;
// `npm run kat` regenerates this side, and the Rust `#[test]`s check that side.
// ---------------------------------------------------------------------------

/** Pasta Fp modulus, as the Rust probe's `P_HEX` states it (`main.rs:116`). */
export const PASTA_FP_MODULUS_HEX =
  '0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001';

export type GoldCase = {
  name: string;
  /** Sponge inputs. `'p-1'` denotes the field element `p - 1`. */
  inputs: (bigint | 'p-1')[];
  /** The digest the Rust probe asserts, as a 0x-prefixed 64-hex-digit string. */
  digest: string;
};

/** `main.rs:118-160` — the full `GOLD` table plus the two `p-1` edge cases. */
export const RUST_GOLD_HASHES: GoldCase[] = [
  {
    name: 'empty',
    inputs: [],
    digest: '0x2fadbe2852044d028597455bc2abbd1bc873af205dfabb8a304600f3e09eeba8',
  },
  {
    name: 'zero',
    inputs: [0n],
    digest: '0x2fadbe2852044d028597455bc2abbd1bc873af205dfabb8a304600f3e09eeba8',
  },
  {
    name: 'one',
    inputs: [1n],
    digest: '0x10b41a5d3139ef0802e5faf6a7776aab079e44e99ec5b306ddddd88e15fe9e6d',
  },
  {
    name: 'two',
    inputs: [2n],
    digest: '0x2ff0e1a38b683e46ad044aae772f0d3029c51e6f5610041c717a2c24c03e3cfe',
  },
  {
    name: 'seq012',
    inputs: [0n, 1n, 2n],
    digest: '0x33c9a84ee660a76f7cf69fc1928848bf67a1bcd1801625926008eddebe371bb1',
  },
  {
    name: 'block_boundary',
    inputs: [1n, 2n, 3n, 4n, 5n],
    digest: '0x27cc8fc2d8052df2f44fee2d74ea01aa33195d263b99128f78f24ae0b420d7ec',
  },
  {
    name: 'compress_LR',
    inputs: [123456789n, 987654321n],
    digest: '0x0ef95ec0c90a0dc01fb3010b91b8ddfdbbb7f166f0bf5b8f7ef26b90ae5230d8',
  },
  {
    name: 'pminus1',
    inputs: ['p-1'],
    digest: '0x363529b92c382593b6e8b455ac5e148fb262237aeeb15617799aaab76a879b4b',
  },
  {
    name: 'pminus1_pair',
    inputs: ['p-1', 'p-1'],
    digest: '0x2e0215c1db41c4c1622e2f573bd876c43d8f465aa0fecb40b7ee030577d5f4d3',
  },
];

/**
 * `main.rs:215` — the depth-2 root over leaves `[1,2,3,4]`, built by the Rust
 * probe's `compress(compress(1,2), compress(3,4))`. This is the value the
 * in-circuit Merkle walk is pinned against.
 *
 * ⚑ It is a FIXED-LEAF TEST VECTOR, not a commitment to dregg state.
 */
export const RUST_MERKLE_ROOT_1234 =
  0x0f82b06f11a6dea422082c77668f6ac9fd97a5f21b81525cb61a46c335bbb777n;

/** The leaves that root commits to. */
export const RUST_MERKLE_LEAVES_1234 = [1n, 2n, 3n, 4n];

/** Resolve a `GoldCase` input list to concrete o1js `Field`s. */
export function goldInputs(c: GoldCase): Field[] {
  return c.inputs.map((x) => (x === 'p-1' ? Field(Field.ORDER - 1n) : Field(x)));
}

/** Render a `Field` the way the Rust probe's `fp_hex` does. */
export function fpHex(x: Field): string {
  return '0x' + x.toBigInt().toString(16).padStart(64, '0');
}
