/-
# Dregg2.Bridge.MinaChainSelectionDifferential — the Lean `select` against a REAL implementation.

`MinaChainSelection` is a transcription. A transcription is a claim, and the way this repo makes a
claim into a fact is to run it against the thing it claims to be. This module does that: it checks
`MinaChainSelection`'s `def`s, row by row, against numbers produced by **openmina's own
`mina_core::consensus`** functions running over **real Mina protocol states**.

## Provenance of the vectors, end to end

  1. `metatheory/fixtures/samasika-forks/*.json` — five real fork pairs (tip + candidate protocol
     states, named by their Base58Check state hashes), copied INTO THIS REPO from
     `mina-rust/tests/files/forks/`. They are the fixtures openmina's OWN `short_range_fork` /
     `long_range_fork` tests assert decisions against.
  2. `metatheory/fixtures/pickles-extractors/src/bin/samasika_vectors.rs` — the extractor, **in
     this repo** (the Kimchi lesson: an extractor living in a third-party checkout is one
     `git clean` from gone). It deserializes those states, calls openmina's
     `is_short_range_fork`, `relative_min_window_density`, `short_range_fork_take`,
     `long_range_fork_take` and `consensus_take`, and — in the SAME run over the SAME state — the
     OCaml daemon's `is_short_range` / `update_min_window_density` / `select` semantics.
     Before emitting anything it `assert!`s that openmina reproduces the five fixtures' own
     asserted verdicts.
  3. `Dregg2/Bridge/MinaSelectionVectors.lean` — generated by that extractor, copied in verbatim.

## What the differential covers

  * **5 real fork pairs**, two long-range and three short-range, with openmina's own ground-truth
    verdicts (a length tie-break, two VRF tie-breaks, two density comparisons).
  * **52 derived pairs** obtained by moving ONE field — `curr_global_slot` — of a real state. The
    raw fixtures all sit below both grace-period ends, so the projected-window machinery never
    runs on them; the derived family lifts them above 2237 and sweeps the gap across sub-window
    boundaries (0, 1, 6, 7, 8, 13, 14, 15, 21, 28, 42, 70, 76, 77, 78, 84, 100, 200 slots), in
    both orientations, plus six pairs straddling 1440 and 2237.
  * For every row, SEVEN quantities are checked against the extractor: `is_short_range` (both
    renderings), the relative density in both directions (both renderings), and the final verdict
    (both renderings).

## What it found

`minaSelectDifferentialOk` passes: the Lean `select` reproduces the OCaml daemon's verdict on all
57, and `selectOpenmina` reproduces openmina's on all 57. They are **not the same verdict**:
`decisionDivergentCount` is **8** — eight real-state pairs on which openmina's `consensus_take`
adopts a different chain than the daemon's `select` would. That is a consensus-critical
disagreement between the two implementations, and it is a `#guard` here rather than a sentence.
-/
import Dregg2.Bridge.MinaSelectionVectors

set_option autoImplicit false
set_option maxRecDepth 100000

namespace Dregg2.Bridge.MinaChainSelectionDifferential

open Dregg2.Bridge.MinaChainSelection
open Dregg2.Bridge.MinaSelectionVectors

/-- The constants a vector is judged under. Only `slots_per_epoch` varies (the fork fixtures come
from a test network with `slots_per_epoch = 30`); it is carried ON the state
(`curr_global_slot_since_hard_fork.slots_per_epoch`) and both implementations read it from there,
so the constants are rebuilt from the state exactly as the extractor did. -/
def constantsFor (v : Vec) : Constants := { mainnet with slotsPerEpoch := v.e.slotsPerEpoch }

/-- openmina's hardcoded grace-period end (`mina-rust/crates/core/src/consensus.rs:15`). -/
def openminaGracePeriodEnd : Nat := 1440

/-- The OCaml half of the differential: `is_short_range`, both relative densities, and the verdict. -/
def ocamlRowOk (v : Vec) : Bool :=
  let C := constantsFor v
  let m := maxSlot v.e v.c
  (isShortRange C v.e v.c == v.ocShort)
    && (virtualMinWindowDensity C v.e m == v.ocVmwdE)
    && (virtualMinWindowDensity C v.c m == v.ocVmwdC)
    && ((select C v.e v.c v.eh v.ch == SelectStatus.take) == v.ocTake)

/-- The openmina half of the differential. -/
def openminaRowOk (v : Vec) : Bool :=
  let C := constantsFor v
  (isShortRangeOpenmina C v.e v.c == v.omShort)
    && (relMinWindowDensityOpenmina C openminaGracePeriodEnd v.e v.c == v.omRelE)
    && (relMinWindowDensityOpenmina C openminaGracePeriodEnd v.c v.e == v.omRelC)
    && ((selectOpenmina C openminaGracePeriodEnd v.e v.c v.eh v.ch == SelectStatus.take)
          == v.omTake)

/-- **THE DIFFERENTIAL.** Both renderings, every row. -/
def minaSelectDifferentialOk : Bool := vectors.all (fun v => ocamlRowOk v && openminaRowOk v)

/-- How many rows the two implementations DISAGREE on, as verdicts. -/
def decisionDivergentCount : Nat :=
  (vectors.filter (fun v => v.ocTake != v.omTake)).length

/-- How many rows the two implementations disagree on in the relative density alone. -/
def densityDivergentCount : Nat :=
  (vectors.filter (fun v => v.ocVmwdE != v.omRelE || v.ocVmwdC != v.omRelC)).length

/-- The names of the rows on which the VERDICTS differ. -/
def decisionDivergentNames : List String :=
  (vectors.filter (fun v => v.ocTake != v.omTake)).map (fun v => v.name)

-- ⚑ THE GATE. A `#guard` is a build-time error when false, so this cannot rot into a comment.
#guard vectors.length == 57
#guard minaSelectDifferentialOk
#guard densityDivergentCount == 30
#guard decisionDivergentCount == 8
#guard decisionDivergentNames ==
  ["derived-swapped-10006-10000", "derived-swapped-10007-10000", "derived-swapped-10008-10000",
   "derived-swapped-10013-10000", "derived-swapped-10014-10000", "derived-swapped-10015-10000",
   "derived-swapped-10021-10000", "derived-swapped-10028-10000"]

-- The five REAL fork fixtures, individually, with openmina's own asserted verdicts. These are the
-- rows where the ground truth is not our transcription of anything — it is an assertion openmina
-- makes about a block it shipped.
#guard (vectors.filter (fun v => v.name == "short-take-length-60-61")).all
  (fun v => v.ocShort && v.ocTake && ocamlRowOk v)
#guard (vectors.filter (fun v => v.name == "short-take-vrf-99-99")).all
  (fun v => v.ocShort && v.ocTake && ocamlRowOk v)
#guard (vectors.filter (fun v => v.name == "short-keep-vrf-117-117")).all
  (fun v => v.ocShort && !v.ocTake && ocamlRowOk v)
#guard (vectors.filter (fun v => v.name == "long-take-density-92-97")).all
  (fun v => !v.ocShort && v.ocTake && ocamlRowOk v)
#guard (vectors.filter (fun v => v.name == "long-keep-density-161-166")).all
  (fun v => !v.ocShort && !v.ocTake && ocamlRowOk v)

/-! ## The differential's own NON-VACUITY.

A differential that would pass against a broken `def` proves nothing. These two `#guard`s show the
vectors DISCRIMINATE: openmina's density rendering fails the OCaml column on 30 rows and its
verdict fails on 8, so `ocamlRowOk` is not satisfied by whatever happens to be there. -/

/-- Feeding the OCaml column openmina's density would FAIL — the vectors separate the two. -/
def wouldFailIfWeUsedOpenminaDensity : Bool :=
  vectors.any (fun v =>
    let C := constantsFor v
    relMinWindowDensityOpenmina C openminaGracePeriodEnd v.e v.c != v.ocVmwdE)

/-- Feeding the OCaml column openmina's VERDICT would FAIL too. -/
def wouldFailIfWeUsedOpenminaVerdict : Bool := vectors.any (fun v => v.omTake != v.ocTake)

#guard wouldFailIfWeUsedOpenminaDensity
#guard wouldFailIfWeUsedOpenminaVerdict

end Dregg2.Bridge.MinaChainSelectionDifferential
