import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { Field, Poseidon } from 'o1js';
import { RealRootAir, realRootColumns, rootAirAccumulator } from '../src/RootAirDag.js';
import {
  RealRootFri,
  airColumnIndex,
  friLaneTable,
  planOpenedValues,
  rootFriShape,
  rootPreambleMeta,
  segmentWalk,
} from '../src/RootFriWalk.js';
import {
  UniformSpec,
  VK_TREE_DEPTH,
  assertHomogeneous,
  assertOpensTerminalSeal,
  leafOf,
  planUniform,
  specName,
  terminalSealPreimage,
  totalSteps,
  uniformFriDigestOf,
  uniformLaneTable,
  uniformLayout,
  vkTreeRoot,
} from '../src/RootFriUniform.js';
import {
  AIR_CHUNK_LANES,
  airLaneValues,
  chunkDigestsBigInt,
  friLaneValues,
  walkTwin,
} from '../src/RootFriSlice.js';
import { dagDigestOfChunkDigests } from '../src/RootAirChain.js';
import { claimChunks, claimIndex, NUM_CHAIN_CLAIMS, SEG_ANCHOR_WIDTH, octetBigInt } from '../src/RootClaim.js';
import {
  accOutDigestOf,
  assertRealPins,
  terminalSealOf,
  type DreggChainPins,
} from '../src/DreggHeadAnchor.js';

// ---------------------------------------------------------------------------
// THE PIN EMITTER — `dregg-chain-pins.json`, from the chain rather than by hand.
//
// `DreggHeadGate` bakes four constants into its verification key and refuses to
// exist without them. This is the ONE thing allowed to produce them.
//
// ⚑ IT REPRODUCES THE PLAN, IT DOES NOT RESTATE IT. Every call below is the one
// `root-claim-carry.ts`'s `context()` makes, in the same order, and the counts
// are cross-checked against that leg's own ratchet (905 instances, 131 programs)
// — so a plan that has drifted fails HERE rather than emitting a pin file for a
// chain nobody built.
//
// ⚑ AND THE KEYS IT READS MUST BE THE CLAIM-CARRYING ONES. `.fullchain/uniform`
// currently holds 46 keys from the §3.29-shape chain: `publicOutput: Field`, no
// claim, no preamble. §3.30 changed the public output type, so EVERY key in the
// chain changed; a pin file built from those 46 would name a chain whose terminal
// proof states nothing. This refuses a directory whose key count is not the
// program count and says which shape it found.
//
// ⚑ AND IT EMITS THE SEAL PREIMAGE, WHICH IS A SEPARATE ARTIFACT ON PURPOSE.
// `advanceHead(terminal, vk, friCommit, accOutDigest)` takes two fields that are
// NOT RECOVERABLE FROM THE PROOF — the boundary the proof publishes is a hash of
// them — so without them an advance cannot be presented at all, whatever the
// verification keys say. `dregg-chain-seal.json` is those two fields.
//
// It is a SECOND FILE because the two have different prerequisites, and merging
// them would make the one that is emittable today wait on the one that is not:
//
//   dregg-chain-seal.json   needs the proof artifacts ONLY. Emittable now.
//   dregg-chain-pins.json   needs all 131 compiled verification keys.
//
// Both are regenerated by THIS script from `.fullchain/`; neither is hand-typed,
// and a rotation of the VK spine changes the pin file without touching the seal.
//
//   node dist/scripts/head-anchor-pins.js            # report only
//   node dist/scripts/head-anchor-pins.js --emit     # write both files
// ---------------------------------------------------------------------------

const WORK = process.env.HEAD_WORKDIR ?? resolve(process.cwd(), '.fullchain');
const KEYS = process.env.HEAD_KEYS ?? resolve(WORK, 'uniform-claim');
const OUT = process.env.HEAD_PINS ?? resolve(process.cwd(), 'dregg-chain-pins.json');
const SEAL_OUT = process.env.HEAD_SEAL ?? resolve(process.cwd(), 'dregg-chain-seal.json');
const CHUNK = Number(process.env.CLAIM_CHUNK ?? 256);
const BUDGET = Number(process.env.CLAIM_BUDGET ?? 50_000);
const EMIT = process.argv.includes('--emit');

/** `root-claim-carry`'s ratchet, restated as a REFUSAL rather than a comment. */
const EXPECT = { instances: 905, programs: 131 };

const fail = (m: string): never => {
  console.error(`\n✗ ${m}`);
  process.exit(1);
};

function readReal(): { air: RealRootAir; fri: RealRootFri } {
  const a = resolve(WORK, 'real-root-air.json');
  const f = resolve(WORK, 'real-root-fri.json');
  if (!existsSync(a)) fail(`${a} is missing — run \`npm run root-air-fullchain\``);
  if (!existsSync(f)) fail(`${f} is missing — run the \`root_fri_instance\` dumper`);
  return { air: JSON.parse(readFileSync(a, 'utf8')), fri: JSON.parse(readFileSync(f, 'utf8')) };
}

function main() {
  const { air: realAir, fri: realFri } = readReal();
  const shape = rootFriShape(realFri);
  const airIx = airColumnIndex();
  const meta = rootPreambleMeta(realAir, airIx);
  const op = planOpenedValues(shape, airIx);
  //  ⚑ WITH the preamble — 905 / 131 is the §3.29 shape and 820 / 46 is the one
  //  without it. Getting this wrong changes `totalSteps`, which is a PIN.
  const w = segmentWalk(shape, { preamble: meta });
  const ftD = friLaneTable(shape, op);
  const L = uniformLayout(w, shape, ftD, CHUNK);
  const ft = uniformLaneTable(shape, ftD, L);
  assertHomogeneous(w, op, ft, L);
  const plan = planUniform(w, op, ft, L, { usableRows: BUDGET });

  const programs: UniformSpec[] = [
    ...plan.head.map((_, pos) => ({ kind: 'head' as const, pos })),
    ...plan.block.map((_, pos) => ({ kind: 'block' as const, pos })),
  ];
  const terminal: UniformSpec = { kind: 'block', pos: plan.block.length - 1 };
  const T = totalSteps(plan);

  console.log('=== HEAD-ANCHOR PINS ===\n');
  console.log(`    instances     ${plan.totalSlices} uniform + 7 AIR = ${T} steps  (totalSteps PIN)`);
  console.log(`    programs      ${programs.length}  (${plan.head.length} head + ${plan.block.length} block)`);
  console.log(`    terminal      ${specName(terminal)} at key-tree leaf ${leafOf(plan, terminal)}`);

  if (plan.totalSlices !== EXPECT.instances || programs.length !== EXPECT.programs)
    fail(
      `the plan is ${plan.totalSlices} instances / ${programs.length} programs and ` +
        `root-claim-carry's ratchet pins ${EXPECT.instances} / ${EXPECT.programs}. The plan moved; ` +
        'a pin file emitted from it would name a chain that leg never measured.',
    );
  console.log(`    ✓ matches root-claim-carry's ratchet (${EXPECT.instances} / ${EXPECT.programs})`);

  //  The claim's own geometry, so a pin file cannot be emitted for a chain whose
  //  claim does not resolve.
  const ix = claimIndex(airIx);
  const chunks = claimChunks(ix, CHUNK);
  console.log(`    claim         ${NUM_CHAIN_CLAIMS} lanes, AIR chunks [${chunks}]`);

  //  The genesis anchor, off the proof's own `expose_claim` public values.
  const ec = realAir.instances.find((i: any) => (i as any).table === 'expose_claim') as any;
  if (!ec) fail('the root proof exposes no claim — there is no genesis anchor to pin');
  const lanes: bigint[] = ec.publicValues.map((x: any) => BigInt(x));
  const genesisRoot = octetBigInt(lanes.slice(0, SEG_ANCHOR_WIDTH));
  console.log(`    genesisRoot   0x${genesisRoot.toString(16)}`);

  //  ---- the SEAL PREIMAGE ------------------------------------------------
  //  ⚑ NEEDS NO VERIFICATION KEY, so it is emittable today and is emitted
  //  today. The gate compares `airTerminalSeal(friCommit,
  //  Poseidon(accOutDigest, chainVkRoot), totalSteps)` against the proof's
  //  boundary, and a caller who does not hold these two fields has no advance to
  //  present — this is not an optimisation, it is the difference between an
  //  advance existing and not existing.
  console.log('\n    ── the seal preimage ──');
  const cols = realRootColumns(realAir);
  const airLanes = airLaneValues(cols.base, cols.ext);
  const friLanes = friLaneValues(realFri, shape, ft, op);
  const twin = walkTwin(w, shape, ft, op, friLanes, airLanes, realFri);
  const acc = rootAirAccumulator(realAir);

  const nAirChunks = airLanes.length / AIR_CHUNK_LANES;
  const dagDigest = dagDigestOfChunkDigests(chunkDigestsBigInt(airLanes, nAirChunks, AIR_CHUNK_LANES));
  const friDigest = uniformFriDigestOf(L, friLanes);
  const friCommit = Poseidon.hash([dagDigest, friDigest]);

  const ctx = { w, shape, ft, op, plan, real: realFri };
  const pre = terminalSealPreimage(ctx, twin, friCommit, acc);

  //  ⚑ THE ROUND TRIP, AT TWO INDEPENDENT KEY-LIST ROOTS. The chain's own
  //  `uniformBoundaryOut` at the terminal position is the oracle, and `vkRoot`
  //  enters both sides through the SAME single Poseidon input — so agreement at
  //  two unrelated roots is agreement on `accOutDigest` itself, and it is
  //  checkable BEFORE the 131 keys exist. When they do exist the check is redone
  //  at the real root below.
  //
  //  ⚑ AND THROUGH THE GATE'S OWN FUNCTIONS TOO, which is a DIFFERENT CODE
  //  PATH: `DreggHeadGate` calls `terminalSealOf`, the chain emits with
  //  `uniformBoundaryOut`. A preimage that opens one and not the other is
  //  exactly the drift this repo has already paid for twice, and it would
  //  surface as an advance nobody can explain.
  for (const probe of [Field(1), Field(0x5eed_beefn)]) {
    const chainSide = assertOpensTerminalSeal(ctx, twin, pre, acc, probe);
    const gateSide = terminalSealOf(pre.friCommit, pre.accOutDigest, probe, pre.totalSteps);
    if (gateSide.toBigInt() !== chainSide.toBigInt())
      fail(
        '`DreggHeadAnchor.terminalSealOf` and the chain\'s `uniformBoundaryOut` disagree on the ' +
          'terminal seal at the same preimage — the gate and the chain are computing two different ' +
          'messages and no advance would ever be accepted.',
      );
  }
  //  The gate's own `accOutDigestOf` must be the function that built it, not a
  //  numerically-equal accident: same lanes in, same field out.
  if (
    accOutDigestOf(acc.map((x) => Field(x)), []).toBigInt() === pre.accOutDigest.toBigInt() &&
    pre.nLiveOut > 0
  )
    fail(
      'the emitted `accOutDigest` equals the digest of the ACCUMULATOR ALONE while the terminal ' +
        `position carries ${pre.nLiveOut} live-out lanes — the live set is not in the preimage`,
    );
  console.log(`    friCommit     ${pre.friCommit.toBigInt()}`);
  console.log(`    accOutDigest  ${pre.accOutDigest.toBigInt()}`);
  console.log(
    `    from          ${pre.terminalProgram} at q=${pre.terminalQuery}, ${pre.nLiveOut} live-out lanes + ` +
      `${acc.length} accumulator limbs`,
  );
  console.log('    ✓ opens the chain\'s own terminal boundary, through BOTH the chain\'s and the gate\'s functions');

  if (pre.terminalProgram !== specName(terminal))
    fail(
      `the seal preimage was taken at '${pre.terminalProgram}' and the pin file names ` +
        `'${specName(terminal)}' as terminal — two answers to which position closes the chain`,
    );

  /**
   * ⚑ ONE WRITER, CALLED TWICE, so the artifact is the same shape whether or not
   * the key ring exists. `chainVkRoot` is the only thing the seal file cannot
   * know on its own, and when it IS known the DERIVED seal is recorded beside
   * the preimage — for a reader, never as a second source of truth: `verify`
   * below re-derives it and the gate recomputes it in circuit.
   */
  const writeSeal = (chainVkRoot: bigint | null) => {
    writeFileSync(
      SEAL_OUT,
      JSON.stringify(
        {
          label:
            `dregg root-fri uniform chain, claim-carrying, ${programs.length} programs / ${T} steps ` +
            '— the seal PREIMAGE, which no proof publishes',
          friCommit: pre.friCommit.toBigInt().toString(),
          accOutDigest: pre.accOutDigest.toBigInt().toString(),
          totalSteps: pre.totalSteps,
          terminalProgram: pre.terminalProgram,
          terminalQuery: pre.terminalQuery,
          nLiveOut: pre.nLiveOut,
          //  Recorded so a reader can re-derive `friCommit` without re-running
          //  the walk, and so a swapped artifact is visible.
          dagDigest: dagDigest.toBigInt().toString(),
          friDigest: friDigest.toBigInt().toString(),
          accLimbs: acc.map((x) => x.toString()),
          genesisRoot: genesisRoot.toString(),
          //  Present only once the key ring exists. `null` is the honest value
          //  and is never a zero: `assertRealPins` refuses a zero for exactly
          //  this reason and a seal file must not be the place that reintroduces
          //  one.
          chainVkRoot: chainVkRoot === null ? null : chainVkRoot.toString(),
          terminalSeal:
            chainVkRoot === null
              ? null
              : terminalSealOf(pre.friCommit, pre.accOutDigest, Field(chainVkRoot), pre.totalSteps)
                  .toBigInt()
                  .toString(),
          //  ⚑ REGENERABLE, NOT HAND-COPIED. This is the whole command.
          regenerate: 'npm run head-anchor-pins -- --emit',
          verify:
            'terminalSeal == Poseidon([friCommit, Poseidon([accOutDigest, chainVkRoot]), ' +
            'totalSteps, 1]) — `DreggHeadAnchor.terminalSealOf`, which is `RootAirChain' +
            '.airTerminalSeal` over `terminalDigest`',
          //  ⚑ RELATIVE. An artifact carrying `/Users/ember/...` is one a
          //  rehearsal on hbox finds broken, and this arc already found a tool
          //  that did exactly that.
          source: {
            air: relative(process.cwd(), resolve(WORK, 'real-root-air.json')),
            fri: relative(process.cwd(), resolve(WORK, 'real-root-fri.json')),
          },
          emittedAt: new Date().toISOString(),
        },
        null,
        2,
      ) + '\n',
    );
    console.log(
      `    wrote ${SEAL_OUT}` + (chainVkRoot === null ? ' (chainVkRoot absent — preimage only)' : ''),
    );
  };
  if (EMIT) writeSeal(null);

  //  ---- the keys ---------------------------------------------------------
  const keyFile = (sp: UniformSpec) => resolve(KEYS, `key-${specName(sp)}.json`);
  const missing = programs.filter((sp) => !existsSync(keyFile(sp)));
  if (missing.length) {
    console.log(`\n    ◌ NOT EMITTABLE — ${missing.length} of ${programs.length} keys are absent in ${KEYS}`);
    console.log(`      first missing: ${missing.slice(0, 4).map(specName).join(', ')}`);
    console.log(
      '      ⚑ AND `.fullchain/uniform` IS NOT THE ANSWER. Those 46 keys are the §3.29 chain:\n' +
        '        `publicOutput: Field`, no claim, no preamble. §3.30 changed the public output\n' +
        '        type, so every key in the chain changed. The claim-carrying chain must be\n' +
        '        compiled — 131 programs, one process each — into HEAD_KEYS.',
    );
    if (EMIT)
      fail(
        '--emit was given and the key list is incomplete. There is no partial pin file.\n' +
          `      ⚑ THE SEAL PREIMAGE WAS WRITTEN (${SEAL_OUT}) — it needs no key and is complete.\n` +
          '      What is missing is the KEY RING, and `chainVkRoot`/`terminalVkHash` with it.',
      );
    return;
  }

  //  ⚑ A COMPLETE DIRECTORY IS NOT A MATCHING ONE. The count check above catches
  //  `.fullchain/uniform`'s 46; it does not catch 131 keys compiled against a
  //  DIFFERENT plan, claim geometry or key-tree depth, which is the same wound
  //  one turn later — a pin file naming a chain nobody built. `uniform-claim-keys`
  //  records the shape it compiled in every key file; this refuses a ring whose
  //  recorded shape is not the chain THIS run just planned.
  const files = programs.map((sp) => JSON.parse(readFileSync(keyFile(sp), 'utf8')));
  const wantPlan = {
    instances: plan.totalSlices,
    programs: plan.distinctPrograms,
    steps: T,
    head: plan.head.length,
    block: plan.block.length,
    chunk: CHUNK,
    budget: BUDGET,
  };
  const unshaped = programs.filter((_, i) => !files[i].shape);
  if (unshaped.length)
    fail(
      `${unshaped.length} of ${programs.length} keys record no shape (first: ${specName(unshaped[0])}). ` +
        'They were written by something other than `npm run uniform-claim-keys`, so nothing says ' +
        'which chain they are the key ring of. Re-compile them.',
    );
  programs.forEach((sp, i) => {
    const s = files[i].shape;
    if (JSON.stringify(s.plan) !== JSON.stringify(wantPlan))
      fail(
        `key-${specName(sp)}.json was compiled against ${JSON.stringify(s.plan)} and this run planned ` +
          `${JSON.stringify(wantPlan)} — the ring belongs to a different chain`,
      );
    if (s.vkTreeDepth !== VK_TREE_DEPTH)
      fail(
        `key-${specName(sp)}.json was compiled at key-tree depth ${s.vkTreeDepth} and this run is at ` +
          `${VK_TREE_DEPTH} — every Merkle path in the chain is a different length`,
      );
    if (s.leaf !== leafOf(plan, sp))
      fail(
        `key-${specName(sp)}.json records key-tree leaf ${s.leaf} and this plan puts ${specName(sp)} at ` +
          `${leafOf(plan, sp)} — the ring is ordered differently than the chain that will use it`,
      );
  });
  console.log(
    `\n    ✓ all ${programs.length} keys record THIS plan (${wantPlan.instances}/${wantPlan.programs}/` +
      `${wantPlan.steps}, depth ${VK_TREE_DEPTH}) and their own leaf`,
  );

  const hashes = files.map((f) => Field(f.hash));
  const root = vkTreeRoot(hashes);
  const terminalHash = hashes[leafOf(plan, terminal)];

  const pins: DreggChainPins = assertRealPins({
    label: `dregg root-fri uniform chain, claim-carrying, ${programs.length} programs / ${T} steps`,
    terminalVkHash: terminalHash.toBigInt(),
    chainVkRoot: root.toBigInt(),
    totalSteps: T,
    genesisRoot,
  });
  console.log(`\n    terminalVkHash ${pins.terminalVkHash}`);
  console.log(`    chainVkRoot    ${pins.chainVkRoot}`);

  //  ⚑ THE ROUND TRIP AT THE REAL KEY-LIST ROOT, now that there is one. The
  //  probes above establish the identity; this establishes it at the value the
  //  deployed gate bakes into its verification key.
  const realSeal = assertOpensTerminalSeal(ctx, twin, pre, acc, Field(pins.chainVkRoot));
  console.log(`    terminalSeal   ${realSeal.toBigInt()}   (the field the gate compares)`);

  if (!EMIT) {
    console.log('\n    (report only — pass `--emit` to write the pin file)\n');
    return;
  }
  writeSeal(pins.chainVkRoot);
  writeFileSync(
    OUT,
    JSON.stringify(
      {
        ...pins,
        terminalVkHash: pins.terminalVkHash.toString(),
        chainVkRoot: pins.chainVkRoot.toString(),
        genesisRoot: pins.genesisRoot.toString(),
        terminalProgram: specName(terminal),
        terminalLeaf: leafOf(plan, terminal),
        emittedAt: new Date().toISOString(),
        keys: KEYS,
      },
      null,
      2,
    ) + '\n',
  );
  console.log(`\n    wrote ${OUT}\n`);
}

main();
