#!/usr/bin/env bash
# proof-mutation-gate.sh — THE PERMANENT JOINT (FRI + AIR) MUTATION-DIFFERENTIAL CONTROL.
#
# A proof-systems review ranked in-circuit verifier fidelity the #1 live risk: no systematic
# differential that the o1js verifier accepts iff dregg's native verifier accepts. `fri-mutation-
# gate.sh` measures the FRI half. THIS gate measures the AIR half AND the JOINT proof:
#
#   the Rust oracle (`circuit-prove/src/bin/root_proof_mutation`) mutates dregg's REAL committed root
#   proof one field element at a time and runs BOTH deployed native verifiers on the SAME mutated
#   proof — `TwoAdicFriPcs::verify` (FRI/PCS) and the per-instance AIR closing equality
#   `accumulator·Z_H(zeta)^{-1} == quotient(zeta)` — streaming a faithful FRI decode AND AIR decode;
#   the twin (`dist/scripts/proof-mutation-differential.js`) walks each with the SAME node-walk the
#   armed `RootAirProcessChain`/FRI slice circuits execute, and asserts verdict agreement three-valued
#   per region, per verifier (FRI / AIR / JOINT).
#
# GOES RED on: a forgery-shaped disagreement (a twin accepts what a native verifier rejects) in ANY
# of FRI/AIR/JOINT, agreement below the floor, or a JOINT free lane (both-accept) in a region not
# known to be unconstrained.
#
# ⚑⚑ SUBSTRATE / FORK REV — READ THIS BEFORE TRUSTING A GREEN. The AIR half runs `ConstAir::eval`,
# which under the CURRENTLY-PINNED fork rev `fc3c6df` reads `prep[2..D]` the committed fixture does
# not carry and ABORTS (`index out of bounds: len 2, index 2`). The committed fixture
# (`whole_history_proof.bin`, vk 434f57d2…) was proven under `0a4a554` and the committed root AIR DAG
# (`src/generated/root-air-dag.json`) is `0a4a554`-shaped (Const preprocessed width 2). This gate is
# therefore MEASURED at rev `0a4a554` — the rev the committed fixture and DAG both realize. Build the
# oracle from a worktree pinned to `0a4a554` and pass it as PROOFMUT_BIN. When the const-value
# binding lane re-genesises the fixture under `fc3c6df` (D preprocessed value columns + D equalities)
# and re-emits the DAG, both the fixture and this gate must be re-run — a named FLAG DAY.
#
# ⚑ RECORDED CONSTANTS — reproducible. Changing these is a deliberate act, not a drift:
#     SEED=20260731  TRIALS=3000  FLOOR=1.0  EXPECTED_FREE=commit_pow_witness  (fork 0a4a554)
#   Observed 2026-07-31 (seed 20260731, 3000 trials): agreement FRI/AIR/JOINT all 100.000%,
#   0 forgery-shaped, 0 completeness gaps; JOINT free lanes ONLY in commit_pow_witness. The AIR half
#   shows opened_trace/opened_preprocessed free lanes — the next-row (traceNext/prepNext) openings for
#   columns the AIR does not read at the next row (a correct AIR non-binding; FRI binds them, which
#   the JOINT confirms).
#
# ⚑ FALSIFIABILITY — the instrument CAN go red. `PROOFMUT_DISABLE_TEETH=airClosing` drops the closing
#   equality (the tooth the DEPLOYED o1js path LACKS — it seals acc but never checks it against the
#   opened quotient), turning every AIR-bound opened region forgery-shaped in the AIR verifier while
#   the JOINT stays green (FRI covers). FRI teeth: inputRoot,commitRoot,final,preSeal.
#
# USAGE:
#   PROOFMUT_BIN=/abs/path/root_proof_mutation scripts/proof-mutation-gate.sh    # prebuilt (0a4a554)
#   PROOFMUT_TRIALS=300 PROOFMUT_BIN=... scripts/proof-mutation-gate.sh          # quicker smoke
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MZ="$(cd "$HERE/.." && pwd)"                      # bridge/mina-zkapp
REPO="$(cd "$MZ/../.." && pwd)"                   # repo root

SEED="${PROOFMUT_SEED:-20260731}"
TRIALS="${PROOFMUT_TRIALS:-3000}"
FLOOR="${PROOFMUT_FLOOR:-1.0}"
export PROOFMUT_EXPECTED_FREE="${PROOFMUT_EXPECTED_FREE:-commit_pow_witness}"

# --- resolve the Rust oracle binary ----------------------------------------
# ⚑ At HEAD the workspace pins fork rev fc3c6df, whose ConstAir::eval aborts on the committed
# fixture; a build there cannot run this gate. Prefer a prebuilt PROOFMUT_BIN from a 0a4a554 worktree.
BIN="${PROOFMUT_BIN:-}"
if [[ -z "$BIN" ]]; then
  echo "building the Rust oracle (root_proof_mutation) from $REPO ..." >&2
  echo "  ⚠ if this build's fork rev is fc3c6df, the AIR half will abort on ConstAir::eval — set" >&2
  echo "    PROOFMUT_BIN to a binary built from a worktree pinned to plonky3-recursion rev 0a4a554." >&2
  ( cd "$REPO" && cargo build -p dregg-circuit-prove --release --bin root_proof_mutation ) || {
    echo "✗ could not build root_proof_mutation. Set PROOFMUT_BIN to a prebuilt (0a4a554) binary." >&2
    exit 5
  }
  BIN="$REPO/target/release/root_proof_mutation"
fi
[[ -x "$BIN" ]] || { echo "✗ oracle binary not found/executable: $BIN" >&2; exit 5; }

# --- the AIR fixture must be present (regenerated by root_air_instance under 0a4a554) ---
[[ -f "$MZ/.fullchain/real-root-air.json" ]] || { echo "✗ missing .fullchain/real-root-air.json (regenerate with root_air_instance under 0a4a554)" >&2; exit 5; }
[[ -f "$MZ/.fullchain/real-root-fri.json" ]] || { echo "✗ missing .fullchain/real-root-fri.json (regenerate with root_fri_instance under 0a4a554)" >&2; exit 5; }

# --- build the twin side ----------------------------------------------------
( cd "$MZ" && npm run build >/dev/null 2>&1 ) || { echo "✗ tsc build failed" >&2; exit 5; }

echo "=== JOINT (FRI+AIR) mutation differential — seed $SEED, $TRIALS trials, floor $FLOOR (fork 0a4a554) ===" >&2
cd "$MZ"
"$BIN" "$SEED" "$TRIALS" | node --max-old-space-size=16384 dist/scripts/proof-mutation-differential.js "$FLOOR"
rc=$?
exit $rc
