//! # THE GATE THAT FLIPS — the owner key's ninth lane, and the column it does not yet have.
//!
//! ## What this file is
//!
//! The 2026-08-01 key flag day landed in two pieces and only one of them is in the bytes.
//!
//! * **The ENCODER moved and is closed.** All four twins run the base-`2^29` nonet
//!   (`dregg_commit::typed::canonical_32_to_lanes_9`), image exactly `2^256`, and the membership
//!   leaf (`compress_member`) and both four-felt id folds absorb all nine lanes today.
//! * **The GEOMETRY did not.** `B_PUBKEY_OCTET` is eight columns wide, so the rotated pre-limb
//!   write commits lanes 0..=7 and the ninth lane never enters the `wireCommitR` absorption chain.
//!   `state_commit` — and therefore the signed consensus anchor — binds 232 of the key's 256 bits,
//!   and the 24 it misses include the Ed25519 sign bit.
//!
//! **A documented wound is not a detected one.** This file is the detector. It is keyed on
//! `NUM_PRE_LIMBS`, which is GENERATED from `metatheory/EmitLayoutManifest.lean`, so it cannot rot
//! the way the hand-carried `B_CHAIN_BASE = 180` rotted across the `178 → 184` flag day
//! (`28695cefc`: one un-exported constant made ~143 rotated members UNSAT).
//!
//! ## ⚑ HOW THIS FILE BEHAVES, AND WHY IT IS NOT A PERMANENT RED
//!
//! It is GREEN today and it asserts the SHORTFALL — "the geometry has not been emitted, and here
//! is exactly what that costs". The day `layout_generated.rs` is regenerated at 187,
//! [`the_geometry_is_still_at_184_and_here_is_what_that_costs`] goes RED and names the three edits
//! that must follow. A test that goes red on the *fix* is the shape that cannot be ignored,
//! whereas a test that is red every day is one everybody learns to skip.
//!
//! ## What is blocking the emit, verified at source rather than relayed
//!
//! `python3 scripts/emit_descriptors.py` refuses at its first emitter:
//!
//! ```text
//! EmitRotationV3.lean:21:0: error: object file '.../Dregg2/Circuit/Emit/EffectVmEmitRotationWide.olean'
//!   of module Dregg2.Circuit.Emit.EffectVmEmitRotationWide does not exist
//! ```
//!
//! and building that module directly gives three axiom-hygiene failures:
//!
//! ```text
//! EffectVmEmitRotationWide.lean:1392:0: axiom-hygiene FAIL: ...wideAppend_pins depends on [sorryAx]
//! EffectVmEmitRotationWide.lean:1394:0: axiom-hygiene FAIL: ...wideAppend_binds_published depends on [sorryAx]
//! EffectVmEmitRotationWide.lean:1637:0: axiom-hygiene FAIL: ...v3RegistryWide_binds depends on [sorryAx]
//! ```
//!
//! That file is under another lane's edit. `metatheory/EmitLayoutManifest.lean` — the emitter that
//! OWNS `layout_generated.rs` — imports `RotWideCompactS2`, which imports it, so the Rust layout
//! cannot be regenerated by anyone until it is green. **Do not hand-carry the 187 constants to get
//! past this.** That is precisely the move that cost `28695cefc`.

use dregg_circuit::effect_vm::layout_generated::{
    B_IROOT, B_PUBKEY_OCTET, B_STATE_COMMIT, NUM_PRE_LIMBS, ROTATED_PADS,
};

/// The pre-limb count the nine-lane key layout requires. **This is not a target typed from
/// memory** — it is forced, and the two facts that force it are asserted below rather than quoted:
/// the region is full, and `n ≡ 1 (mod 3)`.
const NINE_LANE_NUM_PRE_LIMBS: usize = 187;

#[test]
fn the_geometry_is_still_at_184_and_here_is_what_that_costs() {
    // ⚑ WHEN THIS GOES RED, THE EMIT LANDED. Do not relax it — do these three things:
    //
    //   1. `cell/src/commitment.rs::compute_rotated_pre_limbs` and
    //      `turn/src/rotation_witness.rs::produce` must write lane 8 to in-block limb 186
    //      (`Faithful8::from_key_nonet_low8` is a projection and must be replaced by a nine-lane
    //      write). Both sites carry a `⚑ LANE 8 IS DROPPED HERE` comment naming this test.
    //   2. `Faithful8::from_key_nonet_low8` and `KEY_NONET_NINTH_LANE_UNBOUND` are then dead —
    //      delete them, and delete their three rows from the burn-down list in
    //      `docs/FAITHFUL-COMMITMENT-LAW.md`. The burn-down gate in
    //      `faithful8_key_octet_below_floor.rs` fails on a listed entry with no call site, so it
    //      will not let you delete one and forget the other.
    //   3. The residual assertions in `faithful8_key_octet_below_floor.rs` and
    //      `commit/tests/key_octet_f2_twins_and_the_hole.rs` that pin the anchor at 232 bits —
    //      each carries a message telling you to delete rather than relax it.
    assert_eq!(
        NUM_PRE_LIMBS, 184,
        "layout_generated.rs moved off 184 — if it is now {NINE_LANE_NUM_PRE_LIMBS}, the key \
         nonet's ninth lane has a column and this test has done its job. Read the three follow-ups \
         in the source above; do NOT relax this assertion."
    );

    // The cost, in the same breath, so the shortfall is a number and not an adjective.
    assert_eq!(
        B_PUBKEY_OCTET + 8,
        105 + 8,
        "the owner key occupies eight columns and the ninth lane has none"
    );
    assert_eq!(
        B_IROOT, NUM_PRE_LIMBS,
        "iroot sits right after the pre-limbs"
    );
    assert_eq!(B_STATE_COMMIT, B_IROOT + 1);
}

#[test]
fn the_pre_limb_region_is_full_so_the_ninth_lane_cannot_be_squeezed_in() {
    // The first of the two facts that force a GROW rather than a re-use. `ROTATED_PADS` is the
    // spare-column list and it is empty: the two former pads were eaten by the FIELDS nonet on
    // 2026-07-31. So there is no free absorbed pre-limb to point the key's ninth lane at, and
    // "just use a pad" is not available.
    assert!(
        ROTATED_PADS.is_empty(),
        "there are spare pre-limbs {ROTATED_PADS:?} — re-check whether the region must grow at all"
    );
}

#[test]
fn the_ninth_lane_needs_187_not_185_and_the_reason_is_a_floor_division() {
    // ⚑ THE SECOND FACT, and the one that makes 185 a TRAP rather than merely wrong.
    //
    // The rotated block's span is `B_SPAN := n + 3 + (n - 4) / 3` — Nat FLOOR division — while the
    // real carrier chain is `chunk31`, whose count is a CEILING. The two agree only when
    // `n ≡ 1 (mod 3)`, and nobody had written that invariant down.
    //
    // Recomputed here from both sides rather than transcribed, so this is two independent
    // derivations meeting and not a pin against its own definition.
    let b_span_formula = |n: usize| n + 3 + (n - 4) / 3;
    // The carrier chain over a body of `n - 4` limbs, grouped three at a time, ceiling.
    let chunk_count = |n: usize| (n - 4).div_ceil(3) + 1;

    assert_eq!(b_span_formula(184), 247);
    assert_eq!(
        chunk_count(184),
        61,
        "184 is consistent: formula and chain agree"
    );

    // 185 — the number an eyeball reaches for, needing "one more limb". The formula silently
    // under-allocates the block by one carrier column, which is the shape that made every rotated
    // member UNSAT the last time a geometry constant went quietly wrong.
    assert_ne!(
        b_span_formula(185) - 185,
        chunk_count(185) + 2,
        "185 must be INCONSISTENT — if this ever passes, the trap is gone and 185 would work"
    );

    // 186 is not body-aligned either.
    assert_ne!(
        (186 - 4) % 3,
        0,
        "186 leaves an arity-2 leftover in the body"
    );

    // 187 is the next value that is both body-aligned and consistent. This is why the flag day is
    // 184 -> 187 and buys THREE ninth lanes (child_vk, contract_hash, public_key) rather than one.
    assert_eq!((NINE_LANE_NUM_PRE_LIMBS - 4) % 3, 0, "187 is body-aligned");
    assert_eq!(
        NINE_LANE_NUM_PRE_LIMBS % 3,
        1,
        "the unwritten invariant: n = 1 mod 3"
    );
    assert_eq!(b_span_formula(NINE_LANE_NUM_PRE_LIMBS), 251);
    assert_eq!(chunk_count(NINE_LANE_NUM_PRE_LIMBS), 62);

    // And the three limbs 187 buys are exactly the three eight-lane carrier octets in the block.
    assert_eq!(
        NINE_LANE_NUM_PRE_LIMBS - 184,
        3,
        "the grow buys one ninth lane each for child_vk, contract_hash and public_key"
    );
}

#[test]
fn the_deployed_range_widths_admit_the_nonets_two_legs() {
    // The canonicity envelope is TWO legs at TWO widths — eight lookups at 29 and one at 24 — and
    // both must be admissible custom range widths or the envelope cannot be emitted at all.
    use dregg_circuit::descriptor_ir2::CUSTOM_RANGE_WIDTHS;
    assert!(
        CUSTOM_RANGE_WIDTHS.contains(&29),
        "the 29-bit lane lookup has no table: {CUSTOM_RANGE_WIDTHS:?}"
    );
    assert!(
        CUSTOM_RANGE_WIDTHS.contains(&24),
        "the 24-bit top-lane lookup has no table: {CUSTOM_RANGE_WIDTHS:?}"
    );

    // ⚠ AND THEY MUST STAY TWO. A uniform nine-lane check at 29 admits `[0, …, 0, 2^24]`, whose
    // value is exactly 2^256 and which decodes to the all-zero key. Dropping 24 "for uniformity"
    // re-opens the encoding — the exhibit is in `faithful8_key_octet_below_floor.rs`.
    assert_ne!(
        24, 29,
        "the two legs are different widths and that is the point"
    );
}
