//! # ⚑ THE DEFERRED IPA ACCUMULATOR CHECK, PROVED AND REFUSED IN A CIRCUIT.
//!
//! ## Substrate, said out loud (HOUSE LAW #1)
//!
//! **The AIR is Lean-authored.** `dregg-mina-accumulator-seg::v1` and
//! `dregg-mina-accumulator-final::v1` are `EffectLower.lowerAir` of
//! `Dregg2.Circuit.Emit.MinaAccumulatorAir.{accSegAir, accFinalAir}` — the threaded sound VESTA RCB
//! row with its two endpoints published, and (in `-final`) the 64 `.last`-row window gates that
//! force the terminal accumulator to be the point at infinity. Nothing in this file authors a
//! constraint, a `Builder` gadget or an `air_accepts` predicate. It parses the Lean artifacts,
//! reads Lean-generated trace fixtures, and runs the deployed prover. **When the prover refuses a
//! trace, the WITNESS is wrong.**
//!
//! ## What is being checked, and against what it was NOT checked before
//!
//! `mina-rust`'s verifier `&&`s `Ipa::Step::accumulator_check` into `batch_step_dlog_check`
//! (`verify.ml:135-146`). dregg discharges it **natively** in
//! `bridge/src/mina_accumulator_discharge.rs` — whose own header says *"Nothing here is an AIR"* —
//! and a Mina head's acceptance depends on that native oracle
//! (`turn/src/executor/mina_accumulator_oracle.rs`). This file is the first time the relation is
//! inside a constraint system.
//!
//! Read as a running sum, the batched discharge `Σᵢrⁱ·Cᵢ − ⟨Σᵢrⁱ·s(u⃗ᵢ), G⟩ == O` is a chain of
//! complete additions that starts at the claim commitment and must end at the identity:
//!
//! ```text
//!     acc_0 = C  ;  acc_{r+1} = acc_r + A_r  ;  acc_n = O
//! ```
//!
//! so the entry accumulator IS the claim (published at `PI[0..95]`, elementwise at full width, no
//! digest) and `acc_n = O` IS the check.
//!
//! ## ⚑ THE THREE FIXTURES AND WHICH GATE SEPARATES WHICH PAIR
//!
//! All three are Lean-generated by `metatheory/EmitMinaAccumulator.lean` from the same
//! `PastaCurveSound.rcbSoundRow` chained by `PastaCurveComplete.rcbAddM`, on **Vesta**.
//!
//! | fixture       | threads hold | terminal `X`/`Z` | `-seg` | `-final` |
//! |---------------|--------------|------------------|--------|----------|
//! | `discharging` | yes          | all zero         | proves | proves   |
//! | `open`        | yes          | all 64 NONZERO   | proves | REFUSED  |
//! | `unchained`   | **no** (6→7) | all zero         | REFUSED| REFUSED  |
//!
//! * `discharging` vs `open` isolates the **discharge gate**: both are eight independently honest
//!   rows with every thread held; the only difference is whether the accumulator vanished.
//! * `discharging` vs `unchained` isolates the **thread**: eight independently honest rows whose
//!   accumulator does not chain, which is exactly what a ladder looks like when the accumulator is
//!   re-pinned instead of threaded.
//!
//! ## ⚑ THE FALSIFIERS ARE CHECKED TO MOVE, AND TO MOVE SOMETHING NONZERO
//!
//! This campaign shipped two falsifiers that passed for the wrong reason — one moved a zero into a
//! zero, one was refused by a range lookup rather than by the gate under test. So before any
//! polarity runs:
//!
//! * `the_falsifiers_move_and_what_they_move_is_nonzero` asserts the cell counts AND that the
//!   `open` fixture's terminal `X`/`Z` limbs are nonzero in all 64 positions — the discharge gate
//!   is refusing a genuinely non-vanishing accumulator, not an absent one;
//! * `every_fixture_cell_is_inside_the_declared_limb_width` asserts every input-block cell is
//!   `< 2^8` and every cell is `< 2^16`, so no range lookup can be the refusal; and
//! * every refusal tooth calls [`assert_violated_constraint_not_bus`], which holds in EVERY profile
//!   — so a LogUp imbalance cannot stand in for the gate under test.
//!
//! ⚠ **RUN IN RELEASE.** These descriptors carry lookups, so an algebraic refusal is a p3
//! `#[cfg(debug_assertions)]` PANIC in debug and a clean `Err` in release:
//!
//! ```text
//! cargo test -p dregg-circuit --release --test mina_accumulator_air_proves -- --nocapture
//! ```
//!
//! ## ⚠ WHAT THIS DOES NOT ESTABLISH
//!
//! **Not that the addends are the SRS.** `MinaAccumulatorAir.accumulator_discharge_forced` forces
//! the chain of the trace's own addends to vanish and says nothing about what those addends are;
//! forcing `A_r` to be the `r`-th scaled generator is the ROUTING half, it lives in
//! `PastaMsmBucketed`'s exact-public lookups, and `the_routing_tuple_does_not_fit_one_table` prices
//! the one deployed constant in its way. So this is the **SUMMATION** half of the accumulator
//! check, in a circuit, soundly, at full 256-bit width — not the whole check.

use dregg_circuit::BabyBear;
use dregg_circuit::descriptor_ir2::{
    EffectVmDescriptor2, MemBoundaryWitness, VmConstraint2, parse_vm_descriptor2,
    prove_vm_descriptor2, verify_vm_descriptor2,
};
use dregg_circuit::refusal::{
    Refusal, assert_violated_constraint_not_bus, must_refuse_or_unsat_panic,
};

// ────────────────────────────────────────────────────────────────────────────────────────────────
// The Lean-emitted artifacts and the Lean-generated fixtures.
// ────────────────────────────────────────────────────────────────────────────────────────────────

const SEG_JSON: &str = include_str!("../descriptors/by-name/mina-accumulator-seg.json");
const FINAL_JSON: &str = include_str!("../descriptors/by-name/mina-accumulator-final.json");

const DISCHARGING: &str = include_str!("fixtures/mina-accumulator-discharging-trace.txt");
const OPEN: &str = include_str!("fixtures/mina-accumulator-open-trace.txt");
const UNCHAINED: &str = include_str!("fixtures/mina-accumulator-unchained-trace.txt");

/// `PastaCurveSound.RCB_WIDTH`.
const WIDTH: usize = 3048;
/// Eight rows: seven generator adds and the closing one. A power of two, which the deployed prover
/// requires of a base trace.
const ROWS: usize = 8;
/// Limbs per Pasta field element in the sound encoding (`PastaFieldSound.SK`).
const SK: usize = 32;

/// The accumulator's three INPUT blocks, contiguous at `0, 32, 64` (`MinaAccumulatorAir.ACC_*`).
const ACC: [usize; 3] = [0, SK, 2 * SK];
/// The accumulator's three OUTPUT blocks — the gadget's SSA `v 26 / v 29 / v 32`, which are NOT
/// contiguous. That is exactly why the published PI side is.
const OUT: [usize; 3] = [1024, 1120, 1216];

/// `4 476` sound row-local + `96` threads + `192` endpoint pins.
const SEG_CONSTRAINTS: usize = 4476 + 96 + 192;
/// …and the `64` discharge gates on top.
const FINAL_CONSTRAINTS: usize = SEG_CONSTRAINTS + 64;
/// `6 · SK` — two projective Vesta points.
const PI_COUNT: usize = 6 * SK;

fn descriptor(json: &str) -> EffectVmDescriptor2 {
    parse_vm_descriptor2(json).expect("the STRICT deployed checker parses the accumulator AIR")
}

fn trace(text: &str) -> Vec<Vec<BabyBear>> {
    let rows = cells(text);
    assert_eq!(rows.len(), ROWS);
    assert!(rows.iter().all(|r| r.len() == WIDTH));
    rows.into_iter()
        .map(|r| {
            r.into_iter()
                .map(|c| BabyBear::new(u32::try_from(c).expect("a cell fits a u32")))
                .collect()
        })
        .collect()
}

/// The raw decimal cells, for assertions about the FIXTURE rather than about the field.
fn cells(text: &str) -> Vec<Vec<u64>> {
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            l.split_whitespace()
                .map(|t| t.parse::<u64>().expect("cell is a u64 decimal"))
                .collect()
        })
        .collect()
}

/// ⚑ **THE PUBLISHED CLAIM AND RESULT, READ OFF THE TRACE'S OWN PINNED COLUMNS.**
///
/// `PI[0..95]` are the FIRST row's `ACC_X‖ACC_Y‖ACC_Z` limbs — the accumulator the chain starts
/// from, which in the accumulator check is the claim commitment `C`. `PI[96..191]` are the LAST
/// row's `OUT_X‖OUT_Y‖OUT_Z` limbs. Derived from the columns the Lean pins name, never authored.
fn public_inputs(t: &[Vec<BabyBear>]) -> Vec<BabyBear> {
    let mut pis = Vec::with_capacity(PI_COUNT);
    for base in ACC {
        for i in 0..SK {
            pis.push(t[0][base + i]);
        }
    }
    for base in OUT {
        for i in 0..SK {
            pis.push(t[ROWS - 1][base + i]);
        }
    }
    assert_eq!(pis.len(), PI_COUNT);
    pis
}

/// p3 numbers AIR constraints skipping `Lookup`s, so a descriptor constraint-LIST index is not a p3
/// index. ⚑ DERIVED from the parsed artifact, never a literal: a widening that inserts a gate moves
/// both sides only if the mapping is real.
fn air_index(desc: &EffectVmDescriptor2, list_index: usize) -> usize {
    assert!(
        list_index < desc.constraints.len(),
        "constraint {list_index} is past the end of {}'s {} constraints",
        desc.name,
        desc.constraints.len()
    );
    assert!(
        !matches!(desc.constraints[list_index], VmConstraint2::Lookup(_)),
        "constraint {list_index} is a LOOKUP; it has no AIR-constraint index"
    );
    desc.constraints[..list_index]
        .iter()
        .filter(|c| !matches!(c, VmConstraint2::Lookup(_)))
        .count()
}

/// ⚑ **THE REFUSAL NAMED THE GATE THIS TOOTH NAMES** — not merely "something objected".
///
/// [`assert_violated_constraint_not_bus`] holds in EVERY profile and is the load-bearing negative
/// clause: a tooth aimed at the discharge gate must not be kept green by a range lookup's LogUp
/// failing instead. The ROW and the failed-constraint SET are only available when p3's debug check
/// is the mechanism; under `--release` the verdict is `OodEvaluationMismatch`, which carries
/// neither — said out loud rather than left as a silent weakening.
#[track_caller]
fn refused_by_gates(
    what: &str,
    refusal: &Refusal<String>,
    desc: &EffectVmDescriptor2,
    gates: &[usize],
    row: usize,
) -> String {
    let reason = refusal.reason();
    assert_violated_constraint_not_bus(what, &reason);

    let Some(rest) = reason.split("constraints not satisfied on row ").nth(1) else {
        return reason;
    };
    let (got_row, rest) = rest
        .split_once(':')
        .expect("p3 renders `on row N: failed constraints = [...]`");
    assert_eq!(
        got_row.trim().parse::<usize>().expect("a row index"),
        row,
        "{what}: refused on the wrong ROW — the gate this tooth names fires on row {row}: {reason}"
    );
    let list = rest
        .split_once('[')
        .and_then(|(_, r)| r.split_once(']'))
        .expect("p3 renders the failed set in brackets")
        .0;
    let got: Vec<usize> = list
        .split(',')
        .map(|t| {
            t.trim()
                .trim_start_matches('#')
                .parse::<usize>()
                .expect("a constraint index")
        })
        .collect();
    assert!(!got.is_empty(), "{what}: p3 named no failed constraint");
    let want: Vec<usize> = gates.iter().map(|&i| air_index(desc, i)).collect();
    for g in &got {
        assert!(
            want.contains(g),
            "{what}: constraint #{g} objected and it is NOT one of the gates this tooth names \
             ({want:?}). Something other than the named gate is what catches this forgery: {reason}"
        );
    }
    reason
}

// ────────────────────────────────────────────────────────────────────────────────────────────────
// (a) the artifacts declare the layout this file reads
// ────────────────────────────────────────────────────────────────────────────────────────────────

/// ⚑ **THE SHAPE, MEASURED OFF THE PARSED DESCRIPTORS.** The final artifact is the segment plus
/// exactly 64 constraints, at the same width and the same PI count — the discharge APPENDS.
#[test]
fn the_lean_artifacts_declare_the_layout_this_file_reads() {
    let seg = descriptor(SEG_JSON);
    let fin = descriptor(FINAL_JSON);

    assert_eq!(seg.name, "dregg-mina-accumulator-seg::v1");
    assert_eq!(fin.name, "dregg-mina-accumulator-final::v1");
    assert_ne!(seg.name, fin.name, "a name is a KEY, not a label");

    for d in [&seg, &fin] {
        assert_eq!(d.trace_width, WIDTH, "3 048 at EVERY chain depth");
        assert_eq!(
            d.public_input_count, PI_COUNT,
            "two projective Vesta points: the claim and the result"
        );
        assert_eq!(
            d.tables.len(),
            4,
            "main + range_w8 + range_w16 + range_w1 — the sound row's union, nothing new"
        );
    }
    assert_eq!(seg.constraints.len(), SEG_CONSTRAINTS);
    assert_eq!(fin.constraints.len(), FINAL_CONSTRAINTS);

    // ⚑ TWO INDEPENDENT ARTIFACTS ON DISK, and the segment's constraints are a genuine PREFIX of
    // the final's. This is what makes the discharge-gate indices below derived rather than guessed:
    // everything the segment forces, the final artifact forces identically.
    assert_eq!(
        seg.constraints,
        fin.constraints[..SEG_CONSTRAINTS],
        "the final descriptor must EXTEND the segment, not re-author it"
    );
}

/// ⚑ **THE SELECTOR CENSUS, AND IT IS WHERE A RE-SCOPE BECOMES VISIBLE.**
///
/// 96 `.transition` threads in both artifacts; 64 `when_last_row` discharge boundaries in the final
/// one and NONE in the segment. Both families are byte-identical algebra under a different
/// selector, so neither move shows up in a constraint COUNT:
///
/// * `.transition → .all` on a thread accepts strictly more (on the last row p3's `next` is the
///   WRAP row);
/// * `.last → .all` on the discharge would demand that EVERY intermediate accumulator vanish — a
///   descriptor that accepts nothing, which reads as "very strict" and is worthless.
///
/// The discharge bodies are also checked to be exactly the `OUT_X` and `OUT_Z` limb columns, so a
/// gate pointed at the wrong block (say `OUT_Y`, which for the point at infinity is NONZERO) is not
/// something this census would pass.
#[test]
fn the_discharge_is_sixty_four_last_row_gates_and_the_threads_are_transition() {
    use dregg_circuit::lean_descriptor_air::{LeanExpr, VmConstraint, VmRow};

    let seg = descriptor(SEG_JSON);
    let fin = descriptor(FINAL_JSON);

    for (who, d, want_last) in [("seg", &seg, 0usize), ("final", &fin, 64usize)] {
        let mut transition = 0usize;
        let mut every_row = 0usize;
        let mut last_boundaries: Vec<usize> = Vec::new();
        for c in &d.constraints {
            match c {
                VmConstraint2::WindowGate(g) if g.on_transition => transition += 1,
                VmConstraint2::WindowGate(_) => every_row += 1,
                VmConstraint2::Base(VmConstraint::Boundary {
                    row: VmRow::Last,
                    body,
                }) => match body {
                    LeanExpr::Var(v) => last_boundaries.push(*v),
                    other => panic!("{who}: a last-row boundary with an unexpected body {other:?}"),
                },
                _ => {}
            }
        }
        assert_eq!(
            transition, 96,
            "{who}: three coordinates x 32 limbs of thread"
        );
        assert_eq!(
            every_row, 0,
            "{who}: an `.all`-scoped window accepts strictly more than a transition one"
        );
        assert_eq!(
            last_boundaries.len(),
            want_last,
            "{who}: the discharge gates"
        );

        if want_last > 0 {
            last_boundaries.sort_unstable();
            let mut want: Vec<usize> = (0..SK).flat_map(|i| [OUT[0] + i, OUT[2] + i]).collect();
            want.sort_unstable();
            assert_eq!(
                last_boundaries, want,
                "{who}: the discharge must vanish the terminal X and Z blocks — and NOT Y, which \
                 is nonzero at the point at infinity"
            );
        }
    }

    // …and the 192 endpoint pins, which are what a fold node reads.
    let pins = fin
        .constraints
        .iter()
        .filter(|c| matches!(c, VmConstraint2::Base(VmConstraint::PiBinding { .. })))
        .count();
    assert_eq!(
        pins, 192,
        "96 incoming limbs pinned first-row, 96 outgoing last"
    );
}

// ────────────────────────────────────────────────────────────────────────────────────────────────
// (b) the fixtures, before the prover sees them
// ────────────────────────────────────────────────────────────────────────────────────────────────

/// Does the accumulator thread hold across every seam of this fixture? Returns the broken ones.
fn broken_seams(t: &[Vec<u64>]) -> Vec<usize> {
    (0..t.len() - 1)
        .filter(|&r| (0..3).any(|b| (0..SK).any(|i| t[r + 1][ACC[b] + i] != t[r][OUT[b] + i])))
        .collect()
}

/// ⚑ **THE HONEST TRACE THREADS, WALKS, AND VANISHES BY ARITHMETIC.**
///
/// The accumulator genuinely walks `2G, 3G, … 8G` and then meets `−8G`, so the terminal `X` and `Z`
/// blocks are the canonical all-zero limbs — `pasta_msm::is_identity` — while `Y` is NOT zero,
/// which is what makes it the projective point at infinity `(0 : y : 0)` rather than an all-zero
/// scribble. A fixed-point fixture would make every thread gate vacuous; eight distinct
/// accumulators is what rules that out.
#[test]
fn the_discharging_fixture_threads_walks_and_vanishes() {
    let t = cells(DISCHARGING);
    assert_eq!(t.len(), ROWS);
    assert_eq!(
        broken_seams(&t),
        Vec::<usize>::new(),
        "every seam must chain"
    );

    for i in 0..SK {
        assert_eq!(
            t[ROWS - 1][OUT[0] + i],
            0,
            "terminal X limb {i} must vanish"
        );
        assert_eq!(
            t[ROWS - 1][OUT[2] + i],
            0,
            "terminal Z limb {i} must vanish"
        );
    }
    assert!(
        (0..SK).any(|i| t[ROWS - 1][OUT[1] + i] != 0),
        "the identity is (0 : y : 0) with y NONZERO — an all-zero triple is not a projective point \
         and would make this exhibit a scribble rather than a discharge"
    );

    let accs: std::collections::HashSet<Vec<u64>> = (0..ROWS)
        .map(|r| t[r][ACC[0]..ACC[0] + SK].to_vec())
        .collect();
    assert_eq!(
        accs.len(),
        ROWS,
        "eight DISTINCT accumulators; a fixed point would make the threads vacuous"
    );
}

/// ⚑ **THE FALSIFIERS MOVE, AND WHAT THEY MOVE IS NONZERO.** The check this campaign paid for
/// twice: one tamper moved a zero into a zero, another was refused by a range lookup.
#[test]
fn the_falsifiers_move_and_what_they_move_is_nonzero() {
    let d = cells(DISCHARGING);
    let o = cells(OPEN);
    let u = cells(UNCHAINED);

    for (name, f) in [("open", &o), ("unchained", &u)] {
        assert_eq!(f.len(), ROWS);
        let moved: usize = (0..ROWS)
            .map(|r| (0..WIDTH).filter(|&c| d[r][c] != f[r][c]).count())
            .sum();
        assert!(
            moved > 2000,
            "{name}: the forgery must MOVE cells, not relabel them; moved = {moved}"
        );
        let differing: Vec<usize> = (0..ROWS).filter(|&r| d[r] != f[r]).collect();
        assert_eq!(
            differing,
            vec![ROWS - 1],
            "{name}: only the last row differs, so a refusal cannot be blamed on collateral damage"
        );
    }

    // ⚑ THE `open` FIXTURE'S TERMINAL ACCUMULATOR IS NONZERO IN ALL 64 DISCHARGED POSITIONS.
    // A tamper that left the terminal limbs at zero would be refused by nothing, and a tamper that
    // moved one limb would leave 63 gates satisfied — this asserts the gate is refusing a genuinely
    // non-vanishing accumulator.
    let nonzero = (0..SK).filter(|&i| o[ROWS - 1][OUT[0] + i] != 0).count()
        + (0..SK).filter(|&i| o[ROWS - 1][OUT[2] + i] != 0).count();
    assert_eq!(
        nonzero, 64,
        "the open chain's terminal X and Z limbs must ALL be nonzero: the discharge gate is being \
         shown a real point, not an absent one"
    );

    // …and every thread still holds in `open`, so the discharge gate is the ONLY thing left.
    assert_eq!(broken_seams(&o), Vec::<usize>::new());
    // …while `unchained` breaks exactly the 6 -> 7 seam and nothing else.
    assert_eq!(broken_seams(&u), vec![ROWS - 2]);
}

/// ⚑ **EVERY FIXTURE CELL IS INSIDE THE DECLARED LIMB WIDTH** — so a range lookup CANNOT be what
/// refuses any of them. This is the second wrong-reason failure this campaign hit.
#[test]
fn every_fixture_cell_is_inside_the_declared_limb_width() {
    for (name, text) in [
        ("discharging", DISCHARGING),
        ("open", OPEN),
        ("unchained", UNCHAINED),
    ] {
        let t = cells(text);
        for (r, row) in t.iter().enumerate() {
            for c in 0..6 * SK {
                assert!(
                    row[c] < 256,
                    "{name} row {r} input limb {c} = {} leaves the declared 8-bit width; a range \
                     lookup would refuse this trace and the gate under test would never be reached",
                    row[c]
                );
            }
            for (c, v) in row.iter().enumerate() {
                assert!(
                    *v < 65536,
                    "{name} row {r} cell {c} = {v} is outside the widest declared range table"
                );
            }
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────────────────────────
// (c) BOTH POLARITIES
// ────────────────────────────────────────────────────────────────────────────────────────────────

/// ⚑ **POLARITY 1 — THE ACCUMULATOR CHECK PROVES.**
///
/// A real threaded chain of eight sound Vesta complete additions that ends at the point at
/// infinity, proved and verified by the deployed `prove_vm_descriptor2` / `verify_vm_descriptor2`
/// against the descriptor whose `.last` gates DEMAND that it vanish. The public inputs are the
/// chain's own published endpoints: the claim at `PI[0..95]` and the result at `PI[96..191]`.
#[test]
fn the_discharging_chain_proves_under_both_descriptors() {
    let t = trace(DISCHARGING);
    let pis = public_inputs(&t);
    for (who, json) in [("seg", SEG_JSON), ("final", FINAL_JSON)] {
        let d = descriptor(json);
        let proof = prove_vm_descriptor2(&d, &t, &pis, &MemBoundaryWitness::default(), &[])
            .unwrap_or_else(|e| panic!("{who}: the discharging chain must prove: {e:?}"));
        verify_vm_descriptor2(&d, &proof, &pis)
            .unwrap_or_else(|e| panic!("{who}: the discharging proof must verify: {e:?}"));
    }
}

/// ⚑⚑ **POLARITY 2 — AN OPEN ACCUMULATOR IS REFUSED, AND THE DISCHARGE GATE IS WHAT REFUSES IT.**
///
/// This is the OLD-ADMITS / NEW-REJECTS pair, and it cannot rot into agreement: the same eight
/// honest rows, every thread held, every cell a legal limb, PROVE under `dregg-mina-accumulator-
/// seg::v1` and are REFUSED under `dregg-mina-accumulator-final::v1`. The refusing constraints are
/// the 64 `.last` window gates at descriptor constraint indices `SEG_CONSTRAINTS .. FINAL_CONSTRAINTS`
/// — derived from the parsed prefix relation, not pinned as a literal — firing on the LAST row.
///
/// Deleting the discharge turns the second half green while the first half stays green, which is
/// what makes the first half the negative control rather than decoration.
#[test]
fn an_open_accumulator_is_refused_by_the_discharge_gate() {
    let t = trace(OPEN);
    let pis = public_inputs(&t);

    // OLD ADMITS: the segment descriptor has nothing to say about vanishing, and says nothing.
    let seg = descriptor(SEG_JSON);
    let proof = prove_vm_descriptor2(&seg, &t, &pis, &MemBoundaryWitness::default(), &[]).expect(
        "the OPEN chain is eight honest threaded rows — the SEGMENT descriptor must accept it, or \
         the refusal below would be about something other than the discharge",
    );
    verify_vm_descriptor2(&seg, &proof, &pis).expect("and the segment proof verifies");

    // NEW REJECTS.
    let fin = descriptor(FINAL_JSON);
    let gates: Vec<usize> = (SEG_CONSTRAINTS..FINAL_CONSTRAINTS).collect();
    let refusal = must_refuse_or_unsat_panic("an open accumulator under -final", || {
        prove_vm_descriptor2(&fin, &t, &pis, &MemBoundaryWitness::default(), &[])
    });
    let reason = refused_by_gates(
        "an open accumulator under -final",
        &refusal,
        &fin,
        &gates,
        ROWS - 1,
    );
    println!("discharge gate refused the open chain: {reason}");
}

/// ⚑ **POLARITY 3 — AND THE THREAD IS WHAT REFUSES THE UNCHAINED ONE.**
///
/// Eight independently honest rows whose accumulator does not chain — the shape a ladder takes when
/// the accumulator is re-pinned instead of threaded. It is refused by the SEGMENT descriptor, so
/// the refusal is the thread's and not the discharge's: the unchained fixture's terminal
/// accumulator vanishes exactly like the honest one's.
#[test]
fn the_unchained_chain_is_refused_by_the_thread() {
    let t = trace(UNCHAINED);
    let pis = public_inputs(&t);
    let seg = descriptor(SEG_JSON);
    let refusal = must_refuse_or_unsat_panic("an unchained accumulator under -seg", || {
        prove_vm_descriptor2(&seg, &t, &pis, &MemBoundaryWitness::default(), &[])
    });
    assert_violated_constraint_not_bus("an unchained accumulator under -seg", &refusal.reason());
    println!("thread refused the unchained chain: {}", refusal.reason());
}

/// ⚑ **AND THE PUBLISHED ENDPOINTS ARE PINNED, NOT DECORATIVE.**
///
/// A prover that publishes a claim the trace did not start from — one limb of `PI[0..95]` displaced
/// by one — is refused. Without this the 192 pins would be a decoration and a fold node connecting
/// them would be connecting free prover scalars, which is precisely the "re-pins the same public
/// inputs" failure the phase-2 chain already paid for.
#[test]
fn a_displaced_claim_is_refused_by_the_endpoint_pins() {
    let t = trace(DISCHARGING);
    let honest = public_inputs(&t);
    let seg = descriptor(SEG_JSON);

    for slot in [0usize, 40, 95, 96, 150, 191] {
        let mut pis = honest.clone();
        pis[slot] = honest[slot] + BabyBear::new(1);
        assert_ne!(pis[slot], honest[slot], "the tamper must MOVE the value");
        let refusal = must_refuse_or_unsat_panic("a displaced endpoint publication", || {
            prove_vm_descriptor2(&seg, &t, &pis, &MemBoundaryWitness::default(), &[])
        });
        assert_violated_constraint_not_bus(
            &format!("a displaced endpoint publication at PI[{slot}]"),
            &refusal.reason(),
        );
    }
}
