//! The EffectVM's developer-field lane count must agree across the Lean that AUTHORS the
//! descriptor, the registries that are EMITTED from it, and the Rust that produces traces
//! against it — and the gap to `STATE_SLOTS` must stay NAMED rather than quietly closed.
//!
//! ═══ THE WOUND THIS CLOSES ═══════════════════════════════════════════════════════
//! Measured 2026-07-30, from GitHub #61 (`prover panics on whisper payload slots`) and
//! #62 (`long-running disk-mode node stops persisting turns`). They are ONE defect.
//!
//! `circuit/src/effect_vm/trace.rs` carried `assert!(*field_idx < 8)` — a bare literal,
//! with `dregg_cell::state::STATE_SLOTS = 16` sitting next to it. Read alone, that looks
//! exactly like a stale number left behind by a half-landed 8→16 widening, and the obvious
//! "fix" is to raise it. It is NOT stale, and raising it is a WRONG PROOF, not a wider one:
//!
//!   * the Lean that authors the circuit types the slot as `Fin 8`
//!     (`setFieldVmDescriptor (slot : Fin 8)`), and every soundness capstone in that module
//!     — `setFieldDescriptor_full_sound`, `_binds_state_advantage_bound`, `_classA` — is
//!     quantified over that `Fin`;
//!   * the rotated registry is GENERATED by `(List.finRange 8).map`, so the deployed
//!     descriptor set literally contains eight per-slot members and no ninth;
//!   * `state::FIELD_BASE = 3` and `state::CAP_ROOT = 11` — there are eight columns between
//!     them and the cap-root limb immediately follows, so there is no ninth lane to write.
//!
//! What IS true is that a cell holds sixteen indexed slots. `fields[8..16]` fold into the
//! authority residue (`cell/src/commitment.rs`'s `st.fields[8..STATE_SLOTS]` loop → the
//! `record_digest` limb), never into a state-block column. So slots 8..15 are legal,
//! committed, and unprovable — and the trace generator met them with a `panic!`.
//!
//! ═══ WHY A PANIC WAS THE ACTUAL DEFECT ═══════════════════════════════════════════
//! That panic is reachable from a turn the executor has ALREADY accepted, committed and
//! receipted. On the async HTTP path `spawn_blocking` catches it and the receipt sits
//! "committed-but-unattested" forever (#61). On the finalized path the proving leg runs
//! INLINE and the durable commit-log write is downstream of it in the same function, so the
//! unwind SKIPS THE DURABLE BARRIER and the turn never reaches redb (#62). A refusal has to
//! be a value the caller can carry past that barrier.
//!
//! ═══ WHY THIS IS A FILE READ AND NOT A LITERAL ═══════════════════════════════════
//! Same argument as `cell/tests/fields_root_reserved_band_pin.rs`, which this is the sibling
//! of: asserting `NUM_FIELDS == 8` pins ONE side, and the drift that actually happens is two
//! sides moving independently. So this reads the Lean `def` out of the source AND counts the
//! per-slot members in the emitted registry TSV, and compares both against the deployed Rust
//! column layout. A comment cannot go red.

use dregg_cell::state::STATE_SLOTS;
use dregg_circuit::effect_vm::state;

/// The Lean module that AUTHORS the per-slot setField descriptor.
const LEAN_EMIT_SETFIELD: &str = "../metatheory/Dregg2/Circuit/Emit/EffectVmEmitSetField.lean";
/// The Lean-generated column-layout manifest checked into the circuit crate.
const GENERATED_LAYOUT: &str = "src/effect_vm/layout_generated.rs";
/// The three EMITTED registries whose per-slot setField members are the deployed set.
const REGISTRIES: [&str; 3] = [
    "descriptors/rotation-v3-staged-registry.tsv",
    "descriptors/rotation-wide-registry-staged.tsv",
    "descriptors/rotation-wide-umem-welded-registry-staged.tsv",
];

fn read(path: &str) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!(
            "cannot read {path}: {e}. This pin compares the DEPLOYED Rust field-lane count \
             against the Lean source and the emitted registries that define the same number; \
             if a file moved, re-point it rather than deleting the check — an unread pin is the \
             drift it exists to catch."
        )
    })
}

/// Parse `N` out of `def setFieldVmDescriptor (slot : Fin N) : EffectVmDescriptor :=`.
///
/// Deliberately NOT a loose grep for `Fin 8`: that string occurs in a dozen doc comments and
/// theorem statements in that module, and matching prose is how a reader reports a number
/// nobody wrote. We anchor on the `def` line of the descriptor itself.
fn lean_setfield_slot_arity() -> usize {
    parse_setfield_slot_arity(&read(LEAN_EMIT_SETFIELD))
}

/// The parser, over an arbitrary source string — so the reader itself can be RED-PROOFED
/// against a fabricated module without mutating anything in the shared tree.
fn parse_setfield_slot_arity(src: &str) -> usize {
    {
        let line = src
            .lines()
            .find(|l| l.trim_start().starts_with("def setFieldVmDescriptor "))
            .expect(
                "no `def setFieldVmDescriptor` in the Lean emit module — the descriptor was \
                 renamed or moved; re-point this pin at wherever the AIR's slot type now lives",
            );
        let after = line
            .split("Fin ")
            .nth(1)
            .unwrap_or_else(|| panic!("the descriptor's slot is not a `Fin`: {line:?}"));
        after
            .chars()
            .take_while(char::is_ascii_digit)
            .collect::<String>()
            .parse::<usize>()
            .unwrap_or_else(|_| panic!("could not parse a `Fin` arity out of: {line:?}"))
    }
}

/// Parse `pub const CUSTOM_APP_FIELD_OCTET_LEN: usize = N;` out of the @generated manifest —
/// the field-octet width Lean's `EmitLayoutManifest` publishes to Rust.
fn generated_field_octet_len() -> usize {
    let src = read(GENERATED_LAYOUT);
    let line = src
        .lines()
        .find(|l| {
            l.trim_start()
                .starts_with("pub const CUSTOM_APP_FIELD_OCTET_LEN")
        })
        .expect("no CUSTOM_APP_FIELD_OCTET_LEN in the generated layout manifest");
    line.rsplit('=')
        .next()
        .and_then(|v| v.trim().trim_end_matches(';').parse::<usize>().ok())
        .unwrap_or_else(|| panic!("could not parse a usize out of: {line:?}"))
}

/// The per-slot `setFieldVmDescriptor2-{i}R24` members actually present in a registry, as the
/// set of slot indices `i`. This is the EMITTED descriptor set, read off the TSV — not a Rust
/// constant asserting what the emitted set ought to be.
fn registry_static_setfield_slots(path: &str) -> Vec<usize> {
    let src = read(path);
    let mut slots: Vec<usize> = src
        .lines()
        .filter_map(|l| l.split('\t').next())
        .filter_map(|name| {
            name.strip_prefix("setFieldVmDescriptor2-")?
                .strip_suffix("R24")?
                .parse::<usize>()
                .ok()
        })
        .collect();
    slots.sort_unstable();
    slots
}

/// **THE PIN.** Lean's authored slot type, the generated layout manifest, and the deployed
/// Rust column layout must all name the same field-lane count.
#[test]
fn lean_generated_layout_and_rust_agree_on_the_field_lane_count() {
    let lean = lean_setfield_slot_arity();
    let generated = generated_field_octet_len();
    let rust = state::NUM_FIELDS;

    assert_eq!(
        lean, rust,
        "\nTHE AIR'S FIELD-LANE COUNT DISAGREES BETWEEN LEAN AND THE DEPLOYED LAYOUT.\n\
         \n  Lean  Dregg2/Circuit/Emit/EffectVmEmitSetField.lean::setFieldVmDescriptor  = Fin {lean}\n  \
           Rust  circuit/src/effect_vm/columns.rs::state::NUM_FIELDS (CAP_ROOT-FIELD_BASE) = {rust}\n\n\
         The Lean `Fin` is the type the write gate, the seven bystander-freeze gates and every \
         soundness capstone in that module are quantified over; the Rust number is how many \
         columns the trace generator will write between FIELD_BASE and CAP_ROOT. If Rust is the \
         larger, the producer writes past the field octet into the cap-root limb and the proof \
         attests a state nobody holds. If Lean is the larger, honest writes are UNSAT.\n\n\
         This is not a literal to raise on either side. Widening the AIR moves state::SIZE, \
         EFFECT_VM_WIDTH, the GROUP-4 commitment absorb set, every rotated block offset, all \
         three registries and all three fingerprints — a VK rotation and a full descriptor \
         re-emit. Do that deliberately, then move this line.\n"
    );

    assert_eq!(
        generated, rust,
        "\nTHE LEAN-GENERATED LAYOUT MANIFEST AND THE DEPLOYED COLUMN LAYOUT DISAGREE.\n\
         \n  Generated  circuit/src/effect_vm/layout_generated.rs::CUSTOM_APP_FIELD_OCTET_LEN = {generated}\n  \
           Rust       circuit/src/effect_vm/columns.rs::state::NUM_FIELDS                    = {rust}\n\n\
         The manifest is @generated by metatheory/EmitLayoutManifest.lean and is what the \
         rotated app-root weld indexes the AFTER-block field octet by. A disagreement here means \
         the weld and the producer are reading different octets — the exact class of drift that \
         module's header was written about.\n"
    );
}

/// **THE EMITTED-SET MEASUREMENT.** The prompt for this work asked for the AIR's width read
/// from the emitted descriptor, not from a Rust constant. This is that reading: each deployed
/// registry must carry exactly one per-slot member for each lane the layout has, indices
/// `0..NUM_FIELDS` contiguous, and NO member for `NUM_FIELDS`.
#[test]
fn every_emitted_registry_carries_exactly_one_member_per_field_lane() {
    let expected: Vec<usize> = (0..state::NUM_FIELDS).collect();
    for registry in REGISTRIES {
        let slots = registry_static_setfield_slots(registry);
        assert_eq!(
            slots,
            expected,
            "\n{registry} does not carry one setFieldVmDescriptor2-{{i}}R24 per field lane.\n\
             \n  emitted slot members : {slots:?}\n  \
               state::NUM_FIELDS     : {}\n\n\
             The registry is generated from Lean's `(List.finRange N).map fun slot => \
             (s!\"setFieldVmDescriptor2-{{slot.val}}R24\", …)`. If the emitted set and the column \
             layout disagree, a producer will resolve a descriptor name for a slot that has no \
             deployed VK (or leave a deployed member with no producer).\n",
            state::NUM_FIELDS
        );
        assert!(
            !slots.contains(&state::NUM_FIELDS),
            "{registry} emits a per-slot member for slot {} — one past the last field lane",
            state::NUM_FIELDS
        );
    }
}

/// **THE NAMED GAP.** The cell holds more slots than the AIR has lanes, and that difference is
/// the whole subject of #61/#62. Pinning it keeps the gap VISIBLE: if someone widens the AIR
/// to 16 this goes red and forces the flag-day to be stated; if someone narrows `STATE_SLOTS`
/// to 8 it also goes red, because that would silently delete a band ~15 shipped cells write to
/// (grain's `ATTESTATION_SLOT = 8`, the node's `HEALTHY_SLOT`/`SOLO_SLOT`, the DKG blueprint's
/// slots 8..11, nameservice, vat, dungeon meta, gear respec, trustlines).
#[test]
fn the_cell_holds_more_slots_than_the_air_can_attest_and_the_gap_is_stated() {
    assert!(
        state::NUM_FIELDS < STATE_SLOTS,
        "\nTHE UNPROVABLE BAND CLOSED WITHOUT A FLAG DAY.\n\
         \n  circuit  state::NUM_FIELDS          = {}\n  \
           cell     state::STATE_SLOTS          = {STATE_SLOTS}\n\n\
         If these became equal by WIDENING the AIR, say so: that re-emits all three registries \
         and rotates all three fingerprints, and this assertion should be replaced by one that \
         says the bands now coincide. If they became equal by NARROWING STATE_SLOTS, a live band \
         of committed cell state was deleted.\n",
        state::NUM_FIELDS
    );

    // The band is exactly what the executor routes to the fixed register file and the authority
    // residue: `apply_set_field` writes `fields[index]` for `index < STATE_SLOTS`, and
    // `compute_authority_digest` folds `fields[NUM_FIELDS..STATE_SLOTS]`. Naming the size keeps
    // a partial widening (say, lanes 8→12) from passing silently.
    assert_eq!(
        STATE_SLOTS - state::NUM_FIELDS,
        8,
        "the unprovable fixed-slot band changed size; `cell/src/commitment.rs`'s \
         `st.fields[8..STATE_SLOTS]` residue fold and this pin must move together"
    );
}

/// ANTI-VACUITY for the readers above. Each parse could "succeed" against prose, a renamed
/// definition, or an empty file and leave the pins comparing something nobody wrote.
#[test]
fn the_readers_landed_on_real_definitions_and_not_prose() {
    let lean_src = read(LEAN_EMIT_SETFIELD);

    // (a) There is EXACTLY ONE `def setFieldVmDescriptor ` line. More than one would mean the
    //     reader is picking an arbitrary variant.
    let defs = lean_src
        .lines()
        .filter(|l| l.trim_start().starts_with("def setFieldVmDescriptor "))
        .count();
    assert_eq!(
        defs, 1,
        "expected exactly one `def setFieldVmDescriptor` in {LEAN_EMIT_SETFIELD}, found {defs}"
    );

    // (b) `Fin` appears many more times than once in that module (the capstones, the row
    //     encoder, `slotName`). If the matcher is ever loosened to a bare `Fin` grep it would
    //     start reading one of those instead — this records that the hazard is real.
    assert!(
        lean_src.matches("Fin ").count() >= 10,
        "the module should mention `Fin` throughout (capstones, RowEncodesSF, slotName); a low \
         count means the module changed shape and the narrow `def`-anchored parse should be \
         re-checked rather than trusted"
    );

    // (c) The parsed arity is a real positive number, not a degenerate zero that would make
    //     every field write refuse and every one of these pins trivially agree.
    let lean = lean_setfield_slot_arity();
    assert!(
        lean > 0,
        "a zero-lane AIR would make every field write unprovable"
    );
    assert_eq!(
        lean,
        generated_field_octet_len(),
        "the two independently-parsed Lean-side numbers must agree with each other"
    );

    // (d) ⚑ RED-PROOF OF THE READER, without mutating a shared file. Fed a FABRICATED module
    //     whose descriptor is `Fin 16`, the parser must report 16 — i.e. it tracks the source
    //     rather than returning a constant, and the `assert_eq!` in the pin above would FAIL
    //     against it. A pin whose reader cannot report a different number is not a pin.
    let fabricated = "\
/-- a fabricated module: the descriptor widened to Fin 16 -/\n\
def setFieldVmDescriptor (slot : Fin 16) : EffectVmDescriptor :=\n  { name := \"x\" }\n";
    let widened = parse_setfield_slot_arity(fabricated);
    assert_eq!(
        widened, 16,
        "the reader must report the FABRICATED arity, not a constant"
    );
    assert_ne!(
        widened,
        state::NUM_FIELDS,
        "the fabricated arity must differ from the deployed one, or this red-proof proves nothing"
    );

    // (e) The registry reader really found members — an empty parse would make
    //     `every_emitted_registry_carries_exactly_one_member_per_field_lane` compare `[]` to
    //     `[]` only if NUM_FIELDS were 0, but a typo'd path or prefix would surface here first.
    for registry in REGISTRIES {
        assert!(
            !registry_static_setfield_slots(registry).is_empty(),
            "{registry} yielded no setFieldVmDescriptor2-{{i}}R24 members — the prefix or the \
             path is wrong, and the emitted-set measurement above would be vacuous"
        );
    }
}
