/-
# `Dregg2.Crypto.Keccak.Fips202Spec` — a FAITHFUL, bit-indexed FIPS 202 specification of Keccak-p[1600,24].

This file is the SPEC HALF of the Keccak floor. It is written to be read directly against
**NIST FIPS 202** ("SHA-3 Standard: Permutation-Based Hash and Extendable-Output Functions",
Aug 2015, https://doi.org/10.6028/NIST.FIPS.202), sections 3.2 (the five step mappings θ ρ π χ ι),
3.3 (the round `Rnd`), 3.4 (Keccak-p) and Algorithms 5/6 (the round constants). It is deliberately
SEPARATE from the executable `Dregg2.Crypto.Keccak` (a `UInt64`/`Array` sponge): the spec models the
state as a bit function and the executable stores lanes as machine words. The refinement between them
lives in `Dregg2.Crypto.Keccak.Fips202Refine`.

## The state (FIPS 202 §3.1)

For b = 1600, w = 64, ℓ = 6, the Keccak state is a 5×5×64 array of bits, A[x, y, z] with
x, y ∈ ℤ/5 and z ∈ ℤ/64. We model it as `KState := Fin 5 → Fin 5 → Fin 64 → Bool`. All index
arithmetic is modular exactly as in FIPS 202 (`m5` for the x/y coordinates mod 5, `subZ` for the
z coordinate mod 64). No `sorry`, no `axiom`; only `Bool`/`Fin`/`Nat`.

## Scope

This specifies the PERMUTATION Keccak-p[1600,24] = Keccak-f[1600] (§3.4). It does NOT specify the
sponge construction (pad10*1, absorb, squeeze) — that layer is stated as an open obligation in the
refinement file. Every definition here is a transcription of the cited FIPS 202 clause.
-/

namespace Dregg2.Crypto.Keccak.Fips202

/-- The Keccak-1600 state as a bit function: `A x y z` is FIPS 202's `A[x, y, z]`, `x,y ∈ ℤ/5`,
`z ∈ ℤ/64` (w = 64). -/
abbrev KState := Fin 5 → Fin 5 → Fin 64 → Bool

/-- Reduce a `Nat` coordinate mod 5 (the FIPS 202 `x mod 5` / `y mod 5`). -/
@[inline] def m5 (a : Nat) : Fin 5 := ⟨a % 5, Nat.mod_lt _ (by decide)⟩

/-- The z-coordinate shifted DOWN by `r` mod 64: `(z − r) mod 64`. Written additively as
`(z + (64 − r mod 64)) mod 64` so it is manifestly a `Fin 64`. This is the read index used by both
the θ `D` term (`r = 1`) and the ρ rotations. -/
@[inline] def subZ (z : Fin 64) (r : Nat) : Fin 64 :=
  ⟨(z.val + (64 - r % 64)) % 64, Nat.mod_lt _ (by decide)⟩

/-! ## θ — FIPS 202 §3.2.1

`C[x, z] = ⊕_{y=0}^{4} A[x, y, z]`,
`D[x, z] = C[(x−1) mod 5, z] ⊕ C[(x+1) mod 5, (z−1) mod 64]`,
`A′[x, y, z] = A[x, y, z] ⊕ D[x, z]`. -/

/-- FIPS 202 §3.2.1 step 1: the column parity `C[x, z]`. -/
def C (A : KState) (x : Fin 5) (z : Fin 64) : Bool :=
  xor (xor (xor (xor (A x 0 z) (A x 1 z)) (A x 2 z)) (A x 3 z)) (A x 4 z)

/-- FIPS 202 §3.2.1 step 2: `D[x, z] = C[x−1, z] ⊕ C[x+1, z−1]`. -/
def D (A : KState) (x : Fin 5) (z : Fin 64) : Bool :=
  xor (C A (m5 (x.val + 4)) z) (C A (m5 (x.val + 1)) (subZ z 1))

/-- FIPS 202 §3.2.1 step 3: `θ(A)[x, y, z] = A[x, y, z] ⊕ D[x, z]`. -/
def theta (A : KState) : KState := fun x y z => xor (A x y z) (D A x z)

/-! ## ρ — FIPS 202 §3.2.2

`ρ(A)[x, y, z] = A[x, y, (z − offset[x, y]) mod 64]`, with the rotation offsets of FIPS 202 Table 2
(equivalently, generated by the §3.2.2 recurrence `(x, y) ↦ (y, (2x+3y) mod 5)` with the triangular
number offsets `(t+1)(t+2)/2 mod 64`). -/

/-- FIPS 202 Table 2 rotation offsets, laid out `[y][x]`. Byte-identical to the executable
`Dregg2.Crypto.Keccak.rho` (which indexes the same table by `x + 5·y`). -/
def rhoOffset (x y : Fin 5) : Nat :=
  (#[ #[0,  1, 62, 28, 27],
      #[36, 44,  6, 55, 20],
      #[3, 10, 43, 25, 39],
      #[41, 45, 15, 21,  8],
      #[18,  2, 61, 56, 14] ][y.val]!)[x.val]!

/-- FIPS 202 §3.2.2: `ρ(A)[x, y, z] = A[x, y, (z − offset[x,y]) mod 64]`. -/
def rho (A : KState) : KState := fun x y z => A x y (subZ z (rhoOffset x y))

/-! ## π — FIPS 202 §3.2.3 : `π(A)[x, y, z] = A[(x + 3y) mod 5, x, z]`. -/

/-- FIPS 202 §3.2.3. -/
def pi (A : KState) : KState := fun x y z => A (m5 (x.val + 3 * y.val)) x z

/-! ## χ — FIPS 202 §3.2.4 :
`χ(A)[x, y, z] = A[x, y, z] ⊕ ((A[(x+1) mod 5, y, z] ⊕ 1) · A[(x+2) mod 5, y, z])`. -/

/-- The per-bit χ transform of FIPS 202 §3.2.4: `t0 ⊕ ((¬t1) ∧ t2)`. Factored out so the refinement
lemma `chi_bit` can name it as the target of the executable's `b0 ^^^ (~~~b1 &&& b2)`. -/
@[inline] def chiBit (t0 t1 t2 : Bool) : Bool := xor t0 ((! t1) && t2)

/-- FIPS 202 §3.2.4. -/
def chi (A : KState) : KState := fun x y z =>
  chiBit (A x y z) (A (m5 (x.val + 1)) y z) (A (m5 (x.val + 2)) y z)

/-! ## ι — FIPS 202 §3.2.5 + Algorithms 5 & 6

`ι` XORs a round-constant lane into position (0, 0). The round-constant bits are `rc(t)` (Algorithm
5, an 8-bit LFSR) placed at `z = 2^j − 1` for `j = 0..ℓ` by Algorithm 6. -/

/-- FIPS 202 Algorithm 5 — `rc(t)`: the round-constant bit. An 8-bit LFSR clocked `t mod 255` times.
`R` holds `R[0..7]` with `R[0]` the output bit. Prepending a 0 and folding `R[8]` into positions
0,4,5,6 (then truncating to 8) is the Algorithm 5 step written out. -/
def rcBit (t : Nat) : Bool := Id.run do
  if t % 255 == 0 then
    return true
  let mut R : Array Bool := #[true, false, false, false, false, false, false, false]
  for _ in [0 : t % 255] do
    let r8 := R[7]!                    -- after "R = 0 || R", position 8 is the old R[7]
    let mut N : Array Bool := Array.replicate 8 false
    N := N.set! 0 (xor false r8)       -- R[0] ⊕ R[8]
    N := N.set! 1 (R[0]!)
    N := N.set! 2 (R[1]!)
    N := N.set! 3 (R[2]!)
    N := N.set! 4 (xor (R[3]!) r8)     -- R[4] ⊕ R[8]
    N := N.set! 5 (xor (R[4]!) r8)     -- R[5] ⊕ R[8]
    N := N.set! 6 (xor (R[5]!) r8)     -- R[6] ⊕ R[8]
    N := N.set! 7 (R[6]!)
    R := N
  return R[0]!

/-- FIPS 202 Algorithm 6 — the round-constant lane `RC` for round `ir`: bit `z` is `rc(j + 7·ir)`
when `z = 2^j − 1` (`j = 0..6`), else 0. -/
def rcLaneOf (ir : Nat) (z : Fin 64) : Bool := Id.run do
  for j in [0:7] do
    if z.val == 2 ^ j - 1 then
      return rcBit (j + 7 * ir)
  return false

/-- FIPS 202 §3.2.5: `ι(A)[0,0,z] = A[0,0,z] ⊕ RC[z]`; all other lanes unchanged. -/
def iota (rcLane : Fin 64 → Bool) (A : KState) : KState := fun x y z =>
  if x.val = 0 ∧ y.val = 0 then xor (A x y z) (rcLane z) else A x y z

/-! ## The round and the permutation — FIPS 202 §3.3, §3.4 -/

/-- FIPS 202 §3.3: `Rnd(A, ir) = ι(χ(π(ρ(θ(A)))), ir)`. -/
def rnd (rcLane : Fin 64 → Bool) (A : KState) : KState :=
  iota rcLane (chi (pi (rho (theta A))))

/-- FIPS 202 §3.4: Keccak-p[1600, 24] — for b = 1600 (ℓ = 6), the 24 rounds `ir = 0..23`
(`ir = 12 + 2ℓ − nr .. 12 + 2ℓ − 1` with `nr = 24`). This is Keccak-f[1600]. -/
def keccakP (A : KState) : KState := Id.run do
  let mut S := A
  for ir in [0:24] do
    S := rnd (rcLaneOf ir) S
  return S

/-- Keccak-f[1600] = Keccak-p[1600, 24] (FIPS 202 §3.4). -/
def keccakF : KState → KState := keccakP

end Dregg2.Crypto.Keccak.Fips202
