#!/usr/bin/env bash
# Assemble the certified export-function serve (serve.S) and its re-entrant host
# driver (cake_serve_ffi.c) into libcakeserve.a. The dataplane build links this
# archive WHEN PRESENT and gates the alternative serve path behind it; run this
# once to enable the DRORB_CAKE_SERVE path, and again after re-emitting serve.S.
#
# PER-SHARD IMAGES. The emitted object holds its heap/stack region slots
# (cml_heap/cml_stack/cml_stackend) and its saved runtime state (ret_base/
# ret_stack/ret_stackend/can_enter) as fixed-address words that the machine code
# reaches rip-relative. Two shard threads that shared one image would race on
# those words and stomp each other's heap. There is no way to make those words
# thread-local without re-emitting the code with %fs-relative access, so instead
# this script mints N symbol-disjoint COPIES of the object: for image i, every
# GLOBAL symbol (serve, cml_main, the region slots, the buffer bounds) is renamed
# with an `cakeI_` prefix, while the file-local words (ret_base, can_enter, ...)
# are already private per object and the undefined runtime hooks (cml_clear,
# cml_err) stay shared. Each image is a fully independent runtime; shard i drives
# image i, so N shards serve in parallel over private heaps with zero shared
# mutable state.
set -euo pipefail
cd "$(dirname "$0")"
CC=${CC:-cc}

# How many parallel per-shard images to mint. Covers one image per reactor
# serve-owner / blocking serve thread; threads past this fall through to the
# leanc serve. Generous default (a core-count ceiling); override with CAKE_IMAGES.
N=${CAKE_IMAGES:-32}

# The GLOBAL symbols the emitted object exports; each must be renamed per image
# so N copies link without duplicate-definition clashes. (The file-local runtime
# words — ret_base/ret_stack/ret_stackend/can_enter/cake_main/... — are already
# private to each object copy and need no rename; the undefined hooks cml_clear/
# cml_err are intentionally left shared across all images.)
GLOBALS="cml_heap cml_stack cml_stackend cml_main serve \
cake_text_begin cake_codebuffer_begin cake_codebuffer_end \
cake_bitmaps_buffer_begin cake_bitmaps_buffer_end"

taskset -c 0-15 nice -n 15 "$CC" -c -O2 -fPIC serve.S -o serve.o

OBJS=""
GEN="cake_images_gen.h"
{
  echo "/* GENERATED by build-cake-lib.sh — do not edit."
  echo "   ${N} symbol-disjoint per-shard images of the export-function serve, so"
  echo "   that many shards run the serve in parallel over private heaps. */"
  echo "#define CAKE_IMAGE_COUNT ${N}"
} > "$GEN"

for i in $(seq 0 $((N - 1))); do
  ren="ren_${i}.txt"
  : > "$ren"
  for g in $GLOBALS; do
    printf '%s cake%s_%s\n' "$g" "$i" "$g" >> "$ren"
  done
  objcopy --redefine-syms="$ren" serve.o "cake${i}.o"
  rm -f "$ren"
  OBJS="$OBJS cake${i}.o"
  {
    printf 'extern void *cake%s_cml_heap, *cake%s_cml_stack, *cake%s_cml_stackend;\n' "$i" "$i" "$i"
    printf 'extern void cake%s_cml_main(void);\n' "$i"
    printf 'extern uint64_t cake%s_serve(uint64_t,uint64_t,uint64_t,uint64_t);\n' "$i"
  } >> "$GEN"
done

# The dispatch tables, one row per image.
{
  echo "static void **const cake_heap_slot[CAKE_IMAGE_COUNT] = {"
  for i in $(seq 0 $((N - 1))); do printf '  &cake%s_cml_heap,\n' "$i"; done
  echo "};"
  echo "static void **const cake_stack_slot[CAKE_IMAGE_COUNT] = {"
  for i in $(seq 0 $((N - 1))); do printf '  &cake%s_cml_stack,\n' "$i"; done
  echo "};"
  echo "static void **const cake_stackend_slot[CAKE_IMAGE_COUNT] = {"
  for i in $(seq 0 $((N - 1))); do printf '  &cake%s_cml_stackend,\n' "$i"; done
  echo "};"
  echo "static void (*const cake_init_fn[CAKE_IMAGE_COUNT])(void) = {"
  for i in $(seq 0 $((N - 1))); do printf '  cake%s_cml_main,\n' "$i"; done
  echo "};"
  echo "static uint64_t (*const cake_serve_fn[CAKE_IMAGE_COUNT])(uint64_t,uint64_t,uint64_t,uint64_t) = {"
  for i in $(seq 0 $((N - 1))); do printf '  cake%s_serve,\n' "$i"; done
  echo "};"
} >> "$GEN"

taskset -c 0-15 nice -n 15 "$CC" -c -O2 -fPIC cake_serve_ffi.c -o cake_serve_ffi.o

rm -f libcakeserve.a
# Archive the N images + the driver. serve.o is intentionally NOT archived: its
# un-prefixed globals would clash and nothing references them.
ar rcs libcakeserve.a $OBJS cake_serve_ffi.o
echo "built $(pwd)/libcakeserve.a with ${N} per-shard images"
