/-
# Dregg2.Crypto.Handlebars — injection-freedom as CFG language membership (the REAL property).

`ZkOracle.lean`'s deployed `InjectionFree` leg is a DELIMITER SUBSTRING stand-in: "the field matches
`neg (.* ⟨{{⟩ .*)`", i.e. "contains no `{{` token." That is a coarse denylist, not the structural
property injection-freedom actually is. This module builds the real thing on the SAME CFG stack the
well-formedness leg already rides (`Crypto/Cfg`, `Crypto/CfgCompact`, mathlib `ContextFreeGrammar`).

The property. A handlebars template `T` = fixed text segments interleaved with typed holes IS a
context-free grammar `g_T`:

  * each fixed-text segment contributes its bytes as TERMINAL symbols in the start production;
  * each `{{hole}}` contributes a NONTERMINAL that derives "safe data" — data confined to the slot,
    introducing no structural breakout (no `{{` delimiter).

A byte string is **injection-free FOR T** iff it lies in `g_T`'s language — i.e. it could have been
GENERATED by instantiating `T` with some per-hole data that stayed inside its slot. "Injection" = the
output has no such parse back to (template structure, benign hole-data); "injection-free" = it does.

The generation witness is exactly the leftmost derivation `Crypto/Cfg` and `Crypto/CfgCompact` already
verify. This first slice PROVES the tractable, load-bearing direction — GENERATION SOUNDNESS:

    render_mem_language : safe T d → render T d ∈ (handlebarsToGrammar T).language

(rendering `T` with safe per-hole data always produces a language member — a genuine generation
witness). It ties the property to the circuit-backed decision through the EXISTING `cfg_verify_sound`
(`injectionFree_of_verify`), so injection-freedom is decided by the SAME STARK the CFG well-formedness
leg (`ZkOracle.zkOracle_sound`) uses, not a fresh checker. The harder round-trip / uniqueness direction
is a NAMED RESIDUAL (§9), stated but not `sorry`-ed (this module is green with only closed theorems).

## The alphabet — a faithful STRUCTURAL abstraction

Injection-freedom is a STRUCTURAL question (structure vs data), so the terminal alphabet abstracts every
ordinary byte to a single `data` token and keeps only the one byte that carries structure, the open
brace `{` (0x7B), as `brace`. "Safe hole data" = a byte string with no two ADJACENT braces
(`NoDoubleBrace`): a single `{` is safe, `{{` is a breakout. This is exactly the Rust twin's contract
(`zkoracle-prove/src/injection.rs`: `b"a { b"` is injection-free, only `{{` is flagged) — see §11, which
reproduces the single-`{`-fine / `{{`-flagged split as `#guard`s.
-/
import Mathlib.Computability.ContextFreeGrammar
import Dregg2.Crypto.Cfg
import Dregg2.Tactics

namespace Dregg2.Crypto.Handlebars

open ContextFreeGrammar

/-! ## §1 The template and its alphabet. -/

/-- **`Tok`** — the terminal alphabet, a faithful structural abstraction of bytes:
`brace` = the one structure-carrying byte `{` (0x7B); `data` = any ordinary non-`{` byte. Injection-freedom
is a structural property, so collapsing all non-delimiter bytes to `data` loses nothing that decides it. -/
inductive Tok where
  | brace
  | data
  deriving DecidableEq, Repr

/-- Hole identifiers. Concrete `Nat` — a template names its holes `0, 1, …`. -/
abbrev HoleId : Type := Nat

/-- A template **segment**: either fixed literal text (a byte list) or a typed hole. -/
inductive Segment where
  | lit (text : List Tok)
  | hole (id : HoleId)
  deriving DecidableEq, Repr

/-- **`HandlebarsTemplate`** — a list of segments: fixed text interleaved with holes. -/
structure HandlebarsTemplate where
  segments : List Segment
  deriving DecidableEq, Repr

/-! ## §2 Render — the forward / generate direction. -/

/-- Render one segment under a hole assignment: literal text is itself, a hole is its data. -/
def renderSeg (d : HoleId → List Tok) : Segment → List Tok
  | .lit text => text
  | .hole h => d h

/-- **`render T d`** — instantiate `T` with per-hole data `d` and concatenate: the GENERATE direction. -/
def render (T : HandlebarsTemplate) (d : HoleId → List Tok) : List Tok :=
  T.segments.flatMap (renderSeg d)

/-! ## §3 Safe hole data — `NoDoubleBrace` (no `{{` breakout; a single `{` is fine). -/

/-- **`NoDoubleBrace w`** — `w` has no two ADJACENT `brace` tokens. A single `{` is allowed (matching the
Rust twin); `{{` is the delimiter breakout that must be excluded from safe hole data. -/
def NoDoubleBrace : List Tok → Prop
  | [] => True
  | [_] => True
  | a :: b :: rest => ¬ (a = Tok.brace ∧ b = Tok.brace) ∧ NoDoubleBrace (b :: rest)

/-- Decidability of `NoDoubleBrace` (for the executable `#guard`s in §11 and `decide` in §12). -/
instance decNoDoubleBrace : (w : List Tok) → Decidable (NoDoubleBrace w)
  | [] => isTrue trivial
  | [_] => isTrue trivial
  | a :: b :: rest =>
      have _ : Decidable (NoDoubleBrace (b :: rest)) := decNoDoubleBrace (b :: rest)
      inferInstanceAs (Decidable (¬ (a = Tok.brace ∧ b = Tok.brace) ∧ NoDoubleBrace (b :: rest)))

/-- The tail of a `NoDoubleBrace` list is `NoDoubleBrace`. -/
theorem NoDoubleBrace.tail {a : Tok} {rest : List Tok}
    (h : NoDoubleBrace (a :: rest)) : NoDoubleBrace rest := by
  cases rest with
  | nil => trivial
  | cons _ _ => exact h.2

/-- After a `brace`, a `NoDoubleBrace` list's tail cannot start with a `brace`. -/
theorem NoDoubleBrace.no_brace_after_brace {rest : List Tok}
    (h : NoDoubleBrace (Tok.brace :: rest)) : rest.head? ≠ some Tok.brace := by
  cases rest with
  | nil => simp
  | cons b _ =>
      cases b with
      | data => simp
      | brace => exact absurd ⟨rfl, rfl⟩ h.1

/-- **`safe T d`** — every hole of `T` receives `NoDoubleBrace` data: the generation-side guard. -/
def safe (T : HandlebarsTemplate) (d : HoleId → List Tok) : Prop :=
  ∀ h, Segment.hole h ∈ T.segments → NoDoubleBrace (d h)

/-! ## §4 `handlebarsToGrammar` — the template AS a context-free grammar.

Nonterminals: `start`, and per hole `h` a two-state pair (`safeD h`, `safeB h`) recognizing the
"no `{{`" language as a right-linear sub-grammar (`safeD` = no pending brace, `safeB` = just emitted a
brace, so a brace is now forbidden). The start production strings the segments together: literal bytes
as terminals, each hole as `nonterminal (safeD h)`. -/

/-- Grammar nonterminals. `NT` must live in `Type` (mathlib's `ContextFreeGrammar.NT` is monomorphic);
`HoleId = Nat : Type`, so this is fine. -/
inductive NT where
  | start
  | safeD (h : HoleId)
  | safeB (h : HoleId)
  deriving DecidableEq, Repr

/-- The state of the per-hole "no `{{`" recognizer. -/
inductive St where
  | d
  | b
  deriving DecidableEq, Repr

/-- The nonterminal for hole `h` in state `s`. -/
def stNT (h : HoleId) : St → NT
  | .d => NT.safeD h
  | .b => NT.safeB h

/-- The five productions realizing hole `h`'s "no `{{`" language:
`safeD → ε | data safeD | brace safeB`, `safeB → ε | data safeD` (no `safeB → brace …`). -/
def holeRules (h : HoleId) : List (ContextFreeRule Tok NT) :=
  [ ⟨NT.safeD h, []⟩,
    ⟨NT.safeD h, [Symbol.terminal Tok.data, Symbol.nonterminal (NT.safeD h)]⟩,
    ⟨NT.safeD h, [Symbol.terminal Tok.brace, Symbol.nonterminal (NT.safeB h)]⟩,
    ⟨NT.safeB h, []⟩,
    ⟨NT.safeB h, [Symbol.terminal Tok.data, Symbol.nonterminal (NT.safeD h)]⟩ ]

/-- One segment's contribution to the start production: literal bytes → terminals; a hole → its
`safeD` nonterminal. -/
def segSymbols : Segment → List (Symbol Tok NT)
  | .lit text => text.map Symbol.terminal
  | .hole h => [Symbol.nonterminal (NT.safeD h)]

/-- The right-hand side of the single `start` production for `T`. -/
def startSymbols (T : HandlebarsTemplate) : List (Symbol Tok NT) :=
  T.segments.flatMap segSymbols

/-- The `start` production `start → ⟨segments⟩`. -/
def startRule (T : HandlebarsTemplate) : ContextFreeRule Tok NT :=
  ⟨NT.start, startSymbols T⟩

/-- The holes named by `T` (in order, with multiplicity). -/
def holesOf (T : HandlebarsTemplate) : List HoleId :=
  T.segments.filterMap (fun | .hole h => some h | .lit _ => none)

/-- All productions of `handlebarsToGrammar T`: the start rule plus every named hole's five rules. -/
def allRules (T : HandlebarsTemplate) : List (ContextFreeRule Tok NT) :=
  startRule T :: (holesOf T).flatMap holeRules

/-- **`handlebarsToGrammar T`** — the template as a context-free grammar (mathlib `ContextFreeGrammar`),
its language exactly the strings `T` can generate with each hole staying inside its slot (no `{{`). -/
def handlebarsToGrammar (T : HandlebarsTemplate) : ContextFreeGrammar Tok :=
  ⟨NT, NT.start, (allRules T).toFinset⟩

/-! ## §5 Rule-membership plumbing. -/

/-- A hole appearing in `T` is in `holesOf T`. -/
theorem hole_mem_holesOf {T : HandlebarsTemplate} {h : HoleId}
    (hseg : Segment.hole h ∈ T.segments) : h ∈ holesOf T :=
  List.mem_filterMap.mpr ⟨Segment.hole h, hseg, rfl⟩

/-- Every rule of a named hole is a rule of the grammar. -/
theorem holeRule_mem {T : HandlebarsTemplate} {h : HoleId} (hh : h ∈ holesOf T)
    {r : ContextFreeRule Tok NT} (hr : r ∈ holeRules h) :
    r ∈ (handlebarsToGrammar T).rules :=
  List.mem_toFinset.mpr (List.mem_cons_of_mem _ (List.mem_flatMap.mpr ⟨h, hh, hr⟩))

/-- The start rule is a rule of the grammar. -/
theorem startRule_mem (T : HandlebarsTemplate) :
    startRule T ∈ (handlebarsToGrammar T).rules :=
  List.mem_toFinset.mpr List.mem_cons_self

/-! ## §6 The per-hole "no `{{`" derivation — safe data always derives. -/

/-- One leftmost pushdown step: applying a rule `r` at the head, then deriving `r.output` onward. -/
private theorem prodStep {T : HandlebarsTemplate} (r : ContextFreeRule Tok NT)
    (hr : r ∈ (handlebarsToGrammar T).rules)
    {target : List (Symbol Tok (handlebarsToGrammar T).NT)}
    (hd : (handlebarsToGrammar T).Derives r.output target) :
    (handlebarsToGrammar T).Derives [Symbol.nonterminal r.input] target :=
  Produces.trans_derives ⟨r, hr, ContextFreeRule.Rewrites.input_output⟩ hd

/-- **The recognizer is sound as a GENERATOR.** From either state `s`, any `NoDoubleBrace` word `w`
(that, in state `b`, does not start with a brace) is DERIVED from `stNT h s`. Proof: a leftmost pushdown
run — pop a terminal by emitting it (`safeD/safeB → data safeD`, `safeD → brace safeB`) or finish
(`… → ε`); the `safeB, brace ::` case is impossible under the hypothesis. -/
theorem safe_state_derives {T : HandlebarsTemplate} {h : HoleId} (hh : h ∈ holesOf T) :
    (s : St) → (w : List Tok) → NoDoubleBrace w → (s = St.b → w.head? ≠ some Tok.brace) →
      (handlebarsToGrammar T).Derives
        [Symbol.nonterminal (stNT h s)] (w.map Symbol.terminal)
  | St.d, [], _, _ =>
      prodStep ⟨NT.safeD h, []⟩ (holeRule_mem hh (by simp [holeRules]))
        Relation.ReflTransGen.refl
  | St.b, [], _, _ =>
      prodStep ⟨NT.safeB h, []⟩ (holeRule_mem hh (by simp [holeRules]))
        Relation.ReflTransGen.refl
  | St.d, Tok.data :: rest, hw, _ =>
      prodStep ⟨NT.safeD h, [Symbol.terminal Tok.data, Symbol.nonterminal (NT.safeD h)]⟩
        (holeRule_mem hh (by simp [holeRules]))
        ((safe_state_derives hh St.d rest hw.tail (by simp)).append_left [Symbol.terminal Tok.data])
  | St.b, Tok.data :: rest, hw, _ =>
      prodStep ⟨NT.safeB h, [Symbol.terminal Tok.data, Symbol.nonterminal (NT.safeD h)]⟩
        (holeRule_mem hh (by simp [holeRules]))
        ((safe_state_derives hh St.d rest hw.tail (by simp)).append_left [Symbol.terminal Tok.data])
  | St.d, Tok.brace :: rest, hw, _ =>
      prodStep ⟨NT.safeD h, [Symbol.terminal Tok.brace, Symbol.nonterminal (NT.safeB h)]⟩
        (holeRule_mem hh (by simp [holeRules]))
        ((safe_state_derives hh St.b rest hw.tail (fun _ => hw.no_brace_after_brace)).append_left
          [Symbol.terminal Tok.brace])
  | St.b, Tok.brace :: rest, _, hb =>
      absurd (show (Tok.brace :: rest).head? = some Tok.brace from rfl) (hb rfl)

/-- Safe hole data derives from the hole's `safeD` nonterminal (the state-`d` specialization). -/
theorem safeD_derives {T : HandlebarsTemplate} {h : HoleId} (hh : h ∈ holesOf T)
    {w : List Tok} (hw : NoDoubleBrace w) :
    (handlebarsToGrammar T).Derives
      [Symbol.nonterminal (NT.safeD h)] (w.map Symbol.terminal) :=
  safe_state_derives hh St.d w hw (by simp)

/-! ## §7 THE KEY THEOREM — generation soundness. -/

/-- Two derivations on concatenations compose. -/
theorem derives_append {g : ContextFreeGrammar Tok} {a a' b b' : List (Symbol Tok g.NT)}
    (ha : g.Derives a a') (hb : g.Derives b b') : g.Derives (a ++ b) (a' ++ b') :=
  (hb.append_left a).trans (ha.append_right b')

/-- The start production's RHS derives the rendered body: each `segSymbols` chunk derives its
`renderSeg` chunk (literals are fixed; holes derive their safe data). -/
theorem body_derives (T : HandlebarsTemplate) (d : HoleId → List Tok) :
    ∀ (segs : List Segment),
      (∀ h, Segment.hole h ∈ segs → NoDoubleBrace (d h)) →
      (∀ h, Segment.hole h ∈ segs → h ∈ holesOf T) →
      (handlebarsToGrammar T).Derives
        (segs.flatMap segSymbols)
        ((segs.flatMap (renderSeg d)).map Symbol.terminal)
  | [], _, _ => Relation.ReflTransGen.refl
  | seg :: rest, hsafe, hmem => by
      simp only [List.flatMap_cons, List.map_append]
      have ihrest := body_derives T d rest
        (fun h hh => hsafe h (List.mem_cons_of_mem _ hh))
        (fun h hh => hmem h (List.mem_cons_of_mem _ hh))
      have hhead : (handlebarsToGrammar T).Derives
          (segSymbols seg) ((renderSeg d seg).map Symbol.terminal) := by
        cases seg with
        | lit text => simp only [segSymbols, renderSeg]; exact Relation.ReflTransGen.refl
        | hole h =>
            simp only [segSymbols, renderSeg]
            exact safeD_derives (hmem h List.mem_cons_self) (hsafe h List.mem_cons_self)
      exact derives_append hhead ihrest

/-- **`render_mem_language`** — GENERATION SOUNDNESS: rendering `T` with safe per-hole data always
produces a member of `T`'s grammar language. The rendered output carries a genuine generation witness
(the leftmost derivation), so it is injection-free FOR `T` by construction: every byte is accounted for
by either fixed template structure or in-slot hole data that introduced no breakout delimiter. -/
theorem render_mem_language (T : HandlebarsTemplate) (d : HoleId → List Tok)
    (hsafe : safe T d) : render T d ∈ (handlebarsToGrammar T).language := by
  rw [mem_language_iff]
  have hstep : (handlebarsToGrammar T).Produces
      [Symbol.nonterminal NT.start] (startSymbols T) :=
    ⟨startRule T, startRule_mem T, ContextFreeRule.Rewrites.input_output⟩
  refine hstep.single.trans ?_
  exact body_derives T d T.segments hsafe (fun _ hh => hole_mem_holesOf hh)

/-! ## §8 `injectionFree` and the circuit tie — the SAME STARK decides it. -/

/-- **`injectionFree T output`** — `output` is injection-free for `T` iff it lies in `T`'s grammar
language: it has a parse back to (template structure, in-slot hole data). -/
def injectionFree (T : HandlebarsTemplate) (output : List Tok) : Prop :=
  output ∈ (handlebarsToGrammar T).language

/-- Generation soundness restated on `injectionFree`: safe rendering is injection-free. -/
theorem render_injectionFree (T : HandlebarsTemplate) (d : HoleId → List Tok)
    (hsafe : safe T d) : injectionFree T (render T d) :=
  render_mem_language T d hsafe

/-- **`injectionFree_of_verify`** — the circuit tie. An accepting proof of the CFG verifier kernel over
`(handlebarsToGrammar T, output)` — given the STARK `extractable` carrier — decides `injectionFree T
output`, through the EXISTING `Cfg.cfg_verify_sound`/`cfg_bridge`. Injection-freedom is decided by the
SAME STARK the well-formedness leg (`ZkOracle.zkOracle_sound`) already uses — no fresh checker. -/
theorem injectionFree_of_verify {Proof : Type} [K : Cfg.CfgVerifierKernel Tok Proof]
    (hext : K.extractable) (T : HandlebarsTemplate) (output : List Tok) (proof : Proof)
    (haccept : K.verify ⟨handlebarsToGrammar T, output⟩ proof = true) :
    injectionFree T output :=
  Cfg.cfg_verify_sound hext ⟨handlebarsToGrammar T, output⟩ proof haccept

#assert_axioms safe_state_derives
#assert_axioms render_mem_language
#assert_axioms render_injectionFree
#assert_axioms injectionFree_of_verify

/-! ## §9 RESIDUAL — the round-trip / uniqueness direction (stated, not proved).

Generation soundness (§7) is the tractable, load-bearing direction: safe rendering ⇒ language member.
The CONVERSE — that a language member decomposes back into template structure + recoverable per-hole
data, so no injection hid in the structure — is the harder direction and is NOT proved in this slice.
It is NOT `sorry`-ed; it is named here as a statement to discharge in a later slice.

  -- RESIDUAL (round_trip): for an UNAMBIGUOUS template T (holes separated by distinctive delimiters so
  -- no two hole/literal splits yield the same output),
  --   injectionFree T output → ∃ d, safe T d ∧ render T d = output
  -- and, under that unambiguity side-condition, the hole data is UNIQUE on holesOf T:
  --   injectionFree T output → ∃! (d restricted to holesOf T), render T d = output.
  -- Why unambiguity is required (an HONEST caveat, not a hole to hide): the `data`-abstracted alphabet
  -- makes some templates genuinely ambiguous — e.g. ⟨hole 0, lit [data], hole 1⟩ splits `data data data`
  -- many ways — so ∃! FAILS without a delimiter side-condition. The residual is the parse-uniqueness
  -- theorem for the delimiter-guarded template class (mathlib has no CFG unambiguity API; this is real
  -- automata-theory work). Its natural home is a CfgCompact-style leftmost-uniqueness argument.

  -- RESIDUAL (junction breakout): per-hole NoDoubleBrace is necessary but NOT sufficient for a
  -- byte-level no-`{{` guarantee across hole/literal JUNCTIONS: a hole ending in a single `brace`
  -- rendered before a literal starting with `brace` yields `{{` at the seam, which render_mem_language
  -- still (correctly) places in the language. So `∈ language` captures IN-SLOT confinement, which is the
  -- structural injection question; a sharper byte-level guarantee needs either a junction-aware `safe`
  -- or a template whose literals never abut hole braces. This is a real granularity finding about the
  -- Rust twin's per-field heuristic, recorded rather than hidden.

## §10 Relation to the deployed `ZkOracle.InjectionFree`.

`ZkOracle.InjectionFree field := derives field (.neg injectionTemplate) = true` is a COARSE STAND-IN: it
asks only "does the field contain the `{{` delimiter token?" — a denylist over a single field, with no
template, no holes, no generation witness, and no parse. `injectionFree` here is the generation property:
membership in `handlebarsToGrammar T`'s language, i.e. "this output could have been generated by
instantiating `T` with in-slot data." The two agree on the isolated-single-field question the Rust twin
encodes (single `{` fine, `{{` flagged — see §11), but the CFG property is strictly richer: it is
relative to a template `T`, carries an explicit generation/parse witness, and rides the same verified
`cfg_verify_sound` STARK as the well-formedness leg rather than a bespoke derivative matcher.
-/

/-! ## §11 RustTwin — the single-`{`-fine / `{{`-flagged split (agreement with `injection.rs`). -/

namespace RustTwin

/-- The Rust twin (`b"a { b"` injection-free): a SINGLE interior brace is safe. -/
theorem single_brace_safe : NoDoubleBrace [Tok.data, Tok.brace, Tok.data] := by decide

/-- The Rust twin (`{{` flagged): a DOUBLE brace is NOT safe. -/
theorem double_brace_unsafe : ¬ NoDoubleBrace [Tok.brace, Tok.brace] := by decide

-- Executable confirmation of the split the Rust `injection_free` also draws.
#guard decide (NoDoubleBrace [Tok.data, Tok.brace, Tok.data])   -- true  (single `{` fine)
#guard decide (NoDoubleBrace [Tok.brace])                        -- true  (lone `{` fine)
#guard ! decide (NoDoubleBrace [Tok.brace, Tok.brace])           -- false (`{{` breakout)

end RustTwin

/-! ## §12 Non-vacuity — a concrete template, generated and landed in the language. -/

namespace Demo

/-- Template `"[" ++ {{0}} ++ "]"` — a bracketed slot (literal `data`, hole `0`, literal `data`). -/
def greetT : HandlebarsTemplate :=
  ⟨[Segment.lit [Tok.data], Segment.hole 0, Segment.lit [Tok.data]]⟩

/-- Fill hole `0` with `"x{y"` (a single interior brace — SAFE, not a breakout). -/
def greetD : HoleId → List Tok
  | 0 => [Tok.data, Tok.brace, Tok.data]
  | _ => []

/-- The fill is safe at every hole (`greetD 0` has a lone interior brace; all others are empty). -/
theorem greetD_safe : safe greetT greetD := by
  intro h _
  cases h with
  | zero => decide
  | succ _ => trivial

/-- **Non-vacuity of `render_mem_language`** — the concrete generated output lands in the language,
carrying a real generation witness. A single interior `{` in the slot is injection-free. -/
theorem greet_injectionFree : injectionFree greetT (render greetT greetD) :=
  render_injectionFree greetT greetD greetD_safe

#assert_axioms greet_injectionFree

end Demo

end Dregg2.Crypto.Handlebars
