// @generated by metatheory/EmitWideRegistryProbe.lean via scripts/emit_descriptors.py — DO NOT EDIT BY HAND.
//
// THE E1 DELETION GEOMETRY (Epoch-1 SECOND flag-day): per wide-registry member, the
// DERIVED per-member kill-set of DEAD v1-face columns — every column at index >= 90
// referenced by NO surviving constraint / hash site / range (the retired aux band
// 90..187 incl. the 60-col balance bit-decomposition, and the note/heap/refusal/cap-open
// appendix scratch bands). Coordinates are POST-S2 (the columns as they sit in the
// S2-compacted member), as ascending half-open `[start, end)` runs. The scan is capped at
// the HOST width (`e1Ceiling`): the gentian floor-refuse aux block + the umem leg ride the
// TOP of the member and are NOT producer-emitted (the gentian aux is filled at PROVE time by
// `fill_refuse_aux`, AFTER the producer's `compact_e1`), so the kill-set must never reach
// into them — else the deployed producer's pre-gentian `compact_e1` panics on a too-short row.
// The Lean emit deleted these from the committed wide descriptors
// (`RotWideCompactE1.compactE1`, gated per member by `compactE1Ok`);
// the Rust trace producer must drop the SAME columns from its S2-compacted rows
// (`trace_rotated::compact_e1_columns`, draining descending). One source: this table.

/// `(registry key, &[(start, end), ...])` per wide member, in registry order — the
/// ascending half-open POST-S2 kill-set runs. An empty slice means no E1-dead columns.
pub const E1_COMPACT_TABLE: &[(&str, &[(usize, usize)])] = &[
    (
        "transferVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    ("burnVmDescriptor2R24", &[(90, 98), (101, 186), (187, 188)]),
    ("mintVmDescriptor2R24", &[(90, 98), (101, 186), (187, 188)]),
    (
        "noteSpendVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (702, 706), (994, 1028)],
    ),
    (
        "noteCreateVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (702, 706), (994, 1028)],
    ),
    (
        "cellSealVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "cellDestroyVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "refusalVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setPermsVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    ("setVKVmDescriptor2R24", &[(90, 98), (101, 186), (187, 188)]),
    (
        "exerciseVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "pipelinedSendVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "refreshVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "incrementNonceVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "revokeVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "introduceVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "attenuateVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "revokeCapabilityVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    ("customVmDescriptor2R24", &[(90, 188)]),
    ("setFieldDynVmDescriptor2R24", &[(90, 188)]),
    (
        "grantCapVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "makeSovereignVmDescriptor2R24",
        &[(90, 98), (101, 113), (117, 186), (187, 188)],
    ),
    (
        "createCellVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (702, 706), (994, 1028)],
    ),
    (
        "factoryVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    ("spawnVmDescriptor2R24", &[(90, 98), (101, 186), (187, 188)]),
    (
        "receiptArchiveVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "cellUnsealVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "emitEventVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-0R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-1R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-3R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-4R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-5R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-6R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "setFieldVmDescriptor2-7R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "delegateCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "introduceCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "grantCapCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "revokeCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "refreshDelegationCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "revokeCapabilityCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "transferCapOpenEffVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (607, 611)],
    ),
    (
        "attenuateCapOpenEffVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "transferFeeVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188)],
    ),
    (
        "transferCapOpenTBVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (607, 611)],
    ),
    (
        "heapWriteVmDescriptor2R24",
        &[
            (90, 102),
            (103, 188),
            (597, 601),
            (681, 685),
            (973, 1007),
            (1010, 1014),
        ],
    ),
    (
        "delegateWriteCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "introduceWriteCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "delegateAttenWriteCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "revokeDelegationWriteCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601), (1028, 1035)],
    ),
    (
        "revokeCapabilityWriteCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601), (1028, 1035)],
    ),
    (
        "refreshDelegationWriteCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "spawnWriteCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "spawnCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "exerciseCapOpenVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
    (
        "supplyMintVmDescriptor2R24",
        &[(90, 98), (101, 186), (187, 188), (597, 601)],
    ),
];
