// @generated by metatheory/EmitLayoutManifest.lean — DO NOT EDIT BY HAND.
//
// The rotated EffectVM column layout, exported from the Lean that DEFINES it and that emits the
// constraint descriptors READING it. The Rust producer (`turn::rotation_witness`) WRITES these
// same columns, and the audit gates check them — so all three now read one source instead of
// three hand-maintained mirrors.
//
// This module exists because the mirrors drifted, and drift here is not a lint failure — it is a
// soundness bug. The perms/VK completion weld once read limb 37 (`revoked_root` lane-0) while the
// producer wrote limb 38, and every honest setPermissions/setVerificationKey turn was UNSAT.
//
// Regenerate with the ack-gated emit pipeline (`scripts/emit_descriptors.py`); never hand-edit.

/// the v1 EffectVM face width — the base every rotated member graduates from
pub const EFFECT_VM_WIDTH: usize = 188;

/// pre-iroot limbs in one rotated block — projected from the verified RotatedLayout
pub const NUM_PRE_LIMBS: usize = 178;

/// one rotated state block's span (BEFORE and AFTER each occupy B_SPAN columns)
pub const B_SPAN: usize = 239;

/// column offset from a member's face to its AFTER block (= B_SPAN)
pub const AFTER_BLOCK_OFF: usize = 239;

/// the caveat region's span
pub const C_SPAN: usize = 43;

/// the caveat commitment carrier, in-region
pub const C_COMMIT: usize = 38;

/// the DFA route-commitment (rc) carrier, in-region
pub const C_RC_OFF: usize = 39;

/// 2*B_SPAN + C_SPAN — the rotated appendix appended to the v1 face
pub const APPENDIX_SPAN: usize = 521;

/// committed record/authority digest limb
pub const B_RECORD_DIGEST: usize = 24;

/// committed capability-root limb
pub const B_CAP_ROOT: usize = 25;

/// committed nullifier-root limb
pub const B_NULLIFIER_ROOT_OFF: usize = 26;

/// committed commitments-root limb
pub const B_COMMITMENTS_ROOT: usize = 27;

/// committed heap-root limb
pub const B_HEAP_ROOT: usize = 28;

/// committed lifecycle limb
pub const B_LIFECYCLE: usize = 29;

/// committed epoch limb
pub const B_EPOCH: usize = 30;

/// last SCALAR pre-iroot limb (disc/perms/vk/mode/fields-root ride past it)
pub const B_COMMITTED_HEIGHT: usize = 31;

/// WAVE-1 committed discriminant limb
pub const B_DISC: usize = 32;

/// WAVE-2 committed permissions-digest limb (lane 0 of the faithful 8-felt group)
pub const B_PERMS: usize = 33;

/// WAVE-2 committed verification-key-digest limb (lane 0 of the 8-felt group)
pub const B_VK: usize = 34;

/// WAVE-3 committed mode limb
pub const B_MODE: usize = 35;

/// WAVE-3 committed fields-root digest limb
pub const B_FIELDS_ROOT: usize = 36;

/// REVOKED-ROOT flag-day limb — inserted at 37, shifting every limb >= 37 by +1
pub const B_REVOKED_ROOT: usize = 37;

/// FIRST perms-digest completion limb; permsHash[1..7] ride B_PERMS_COMPLETION..+6. The producer writes these lanes and the in-circuit weld reads them: ONE source.
pub const B_PERMS_COMPLETION: usize = 38;

/// FIRST vk-digest completion limb; vkHash[1..7] ride B_VK_COMPLETION..+6
pub const B_VK_COMPLETION: usize = 45;

/// the iroot limb (pre-iroot limbs end here)
pub const B_IROOT: usize = 178;

/// the state-commitment limb
pub const B_STATE_COMMIT: usize = 179;

/// state register index of the first committed field (fields[0]); the AFTER-block field octet holds register r(FIELD_BASE+i) at octet index i, so octet_index(r) = r - FIELD_BASE
pub const FIELD_BASE: usize = 3;

/// in-block column base of the AFTER-block committed fields[0..8] lane-0 octet (the app-root weld octet): weldsAt maps base+CUSTOM_APP_FIELD_ROT_BASE+i ↔ stateBase+FIELD_BASE+i
pub const CUSTOM_APP_FIELD_ROT_BASE: usize = 4;

/// width of the app-root field octet (8 field lane-0 limbs)
pub const CUSTOM_APP_FIELD_OCTET_LEN: usize = 8;

/// in-block base of the child_vk carrier octet (app-PI octet base 0 of [89, 97, 105])
pub const B_CHILD_VK_OCTET: usize = 89;

/// in-block base of the contract_hash carrier octet (app-PI octet base 1 of [89, 97, 105])
pub const B_CONTRACT_HASH_OCTET: usize = 97;

/// in-block base of the public_key carrier octet (app-PI octet base 2 of [89, 97, 105])
pub const B_PUBKEY_OCTET: usize = 105;

/// One faithful-8 group: lane 0 followed by seven completion columns.
pub type Felt8Group = [usize; 8];

/// Every named group, emitted verbatim from `rotated178.groupTable`.
pub const ROTATED_GROUP_TABLE: [Felt8Group; 10] = [
    [24, 12, 13, 14, 15, 16, 17, 18],
    [25, 52, 53, 54, 55, 56, 57, 58],
    [26, 68, 69, 70, 71, 72, 73, 74],
    [27, 75, 76, 77, 78, 79, 80, 81],
    [28, 59, 60, 61, 62, 63, 64, 65],
    [33, 38, 39, 40, 41, 42, 43, 44],
    [34, 45, 46, 47, 48, 49, 50, 51],
    [36, 66, 67, 19, 20, 21, 22, 23],
    [37, 82, 83, 84, 85, 86, 87, 88],
    [0, 169, 170, 171, 172, 173, 174, 175],
];

pub const AUTHORITY_DIGEST_GROUP: Felt8Group = ROTATED_GROUP_TABLE[0];
pub const CAP_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[1];
pub const NULLIFIER_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[2];
pub const COMMITMENTS_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[3];
pub const HEAP_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[4];
pub const PERMS_GROUP: Felt8Group = ROTATED_GROUP_TABLE[5];
pub const VK_GROUP: Felt8Group = ROTATED_GROUP_TABLE[6];
pub const FIELDS_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[7];
pub const REVOKED_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[8];
pub const CELLS_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[9];

/// Compatibility/readability alias used by the Rust disjointness tooth.
pub const ALL_FELT8_GROUPS: [Felt8Group; 10] = ROTATED_GROUP_TABLE;

/// Derive the app-root field OCTET INDEX from a state register slot: the AFTER-block
/// `fields[0..8]` octet holds field register `r(FIELD_BASE + i)` at octet index `i`, so
/// `octet_index_of_register(r) == r - FIELD_BASE` — the single Lean-authored query the fold's
/// app-root weld reads (killing the hand `reg("winner") - 3`).
pub const fn octet_index_of_register(reg: usize) -> usize {
    reg - FIELD_BASE
}
