#!/usr/bin/env bash
# reachability-audit.sh — regenerate docs/gateway/REACHABILITY.md, or gate on it.
#
# The inventory answers the question a green build cannot: of everything drorb
# proves, what reaches the shipped binary? Three buckets per `@[export]` —
# DEFAULT-PATH / GATED (the gate is named) / ORPHANED — plus the Lean modules
# that are outside the `libdrorb.a` export closure entirely.
#
#   scripts/reachability-audit.sh            regenerate the doc + print the summary
#   scripts/reachability-audit.sh --check    CI gate: fail if the orphan count grew
#   scripts/reachability-audit.sh --why SYM  explain how one symbol is reached
#
# Pure source analysis: no build, no running server, ~1s on the whole tree.
#
# The gate's baseline lives here, one number, deliberately visible in the diff:
# wiring a seam lowers it (lower it in the same commit), adding an unwired
# `@[export]` raises it and the gate fails. That is the point — an orphaned
# proof should cost a conversation, not go unnoticed for a month.
#
# The number counts UNINTENTIONAL orphans only. Exports that are uncalled BY
# DESIGN live in `INTENTIONAL_EXPORTS` in the generator, each with a reason, and
# are counted separately — so a deliberate affordance never inflates this number
# and nobody is pushed to delete one to make the gate go green. A stale entry in
# that list (the symbol got wired, or vanished) fails `--check` too, so the
# allowlist cannot be turned into a silencer.
#
# 26 -> 20 (2026-07-25): six platform-IO `orb_*` executable entries moved to
# INTENTIONAL (they reach their C shell as a CLOSURE through the `@[extern]`
# serve-loop seam, which a name-based call graph cannot see; the export is the
# documented dual access by symbol), and the UNGATED `drorb_proxy_forward_resp`
# export was RETIRED — its own contract was "the host must not call it", and
# `ungated_resp_seam_differs` machine-checks that crossing it restores the
# response-splitting leak, so it was a footgun rather than an affordance.
set -euo pipefail
cd "$(dirname "$0")/.."

ORPHAN_BASELINE=20
DOC="docs/gateway/REACHABILITY.md"
AUDIT="scripts/reachability-audit.py"

case "${1:-}" in
  --check)
    python3 "$AUDIT" --quiet --check-orphan-max "$ORPHAN_BASELINE"
    # The doc must also be current, or the inventory drifts from the tree.
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT
    python3 "$AUDIT" --markdown "$tmp" --quiet
    if ! diff <(grep -v '^\*Generated by' "$DOC") \
              <(grep -v '^\*Generated by' "$tmp") >/dev/null; then
      echo "REACHABILITY-AUDIT FAIL: $DOC is stale — run scripts/reachability-audit.sh" >&2
      exit 1
    fi
    echo "REACHABILITY-AUDIT GATE PASSED (orphans <= $ORPHAN_BASELINE, $DOC current)"
    ;;
  --why)
    shift
    python3 "$AUDIT" --why "$@"
    ;;
  -h|--help)
    sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  *)
    python3 "$AUDIT" --markdown "$DOC" --json /tmp/drorb-reachability.json "$@"
    echo "wrote $DOC and /tmp/drorb-reachability.json"
    ;;
esac
