// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IDreggVault.sol";
import {IDreggSettlement} from "./IDreggSettlement.sol";

/// @title DreggVault
/// @notice Holds bridged assets (ERC-20 and ETH) with private note-based accounting.
///
/// Deposits create note commitments that the dregg federation observes and mirrors
/// into its private note tree. Withdrawals require an SP1-wrapped STARK proof that
/// verifies note ownership and spending validity.
///
/// SP1 verification is delegated to the SP1 Verifier Gateway (deterministic CREATE2
/// deployment across all EVM chains). The vault only needs to check that the proof
/// was generated by the correct program (matching programVkey) and that the public
/// outputs encode the expected withdrawal parameters.
///
/// ## The TIMEOUT/REFUND ESCROW (DrEX cross-chain routing safety)
///
/// The plain deposit/withdraw pair above is the GENERIC note-mirror surface: lock
/// an asset, mint a mirror, exit later against your own spend proof (§4(b) of
/// `docs/deos/DREX-ROUTING.md`). It has NO batch-scoped reclaim: an asset locked
/// for a DrEX trade that never clears (no ring match, or a stalled chain) would sit
/// forever. That made locking into DrEX unsafe.
///
/// The `escrow*` surface below is the load-bearing fix the routing design named
/// (`DREX-ROUTING.md §4(a)`, "the single most load-bearing build"): a locked
/// deposit is a TIMED escrow that reaches EXACTLY ONE terminal state —
///   • RELEASED to the ring-matched recipient, gated on a DrEX clearing/settlement
///     proof (an SP1 fill proof whose clearing root is proven by the on-chain
///     `IDreggSettlement` — the rung-8 accept-path), XOR
///   • REFUNDED to the depositor, gated only on the per-deposit deadline passing
///     (the timeout IS the condition; no proof needed).
///
/// The two branches are mutually exclusive on one `EscrowStatus` state machine
/// (`Locked → Released` XOR `Locked → Refunded`); each consumes the lock and is
/// idempotent-guarded, so a released escrow can never be refunded and vice-versa,
/// and no escrow is ever stuck (refund is always reachable after the deadline with
/// no external dependency). Escrow funds are accounted in `escrowedBalances`,
/// DISJOINT from the generic `tokenBalances` pool, so neither surface can drain the
/// other. The residual this does NOT close — full cross-vault atomic release across
/// a permanently-unavailable chain — is the named RESEARCH rung (`§4(a)`).
contract DreggVault is IDreggVault {
    // ─── Immutables ─────────────────────────────────────────────────────────

    /// Address of the SP1 Verifier Gateway contract (same on all EVM chains).
    address public immutable sp1Verifier;

    /// Verification key identifying the dregg STARK verifier guest program.
    /// The SP1 verifier checks that the proof was generated by this exact program.
    bytes32 public immutable programVkey;

    /// The on-chain dregg settlement client (`DreggSettlement`). An escrow RELEASE
    /// is gated on `settlement.isProvenRoot(clearingRoot)` — the rung-8 accept-path
    /// that answers "did dregg settle this clearing root?". Fail-closed: a codeless
    /// settlement address would make `isProvenRoot` a vacuous staticcall, so the
    /// constructor refuses to deploy against one.
    IDreggSettlement public immutable settlement;

    // ─── State ──────────────────────────────────────────────────────────────

    /// Incremental Merkle tree of note commitments (simplified: stores leaves only).
    ///
    /// PLACEHOLDER: this keccak256 tree is a stand-in pending Poseidon2 circuit
    /// alignment. The real note tree is Poseidon2 (see IDreggVault noteCommitment
    /// docs); the SP1 guest program proves membership against the Poseidon2 tree,
    /// so until the on-chain tree is rebuilt as an incremental Poseidon2 tree the
    /// keccak root here and the circuit root only agree because the federation
    /// mirrors deposits. The root COMPARISON below is real (withdraw proofs must
    /// commit to the current root or one of the last ROOT_HISTORY_SIZE roots);
    /// the hash function is the placeholder.
    bytes32[] private noteCommitments;

    /// Current root of the note commitment tree.
    bytes32 public noteTreeRoot;

    /// Total number of deposits (== noteCommitments.length).
    uint256 public depositCount;

    /// Ring buffer of recent tree roots (Tornado-style). Withdrawals may prove
    /// against any of the last ROOT_HISTORY_SIZE roots, so a proof generated
    /// just before a new deposit remains spendable.
    uint256 public constant ROOT_HISTORY_SIZE = 32;
    bytes32[ROOT_HISTORY_SIZE] public rootHistory;
    uint256 public rootHistoryCount;

    /// Spent nullifiers (prevents double-withdrawal).
    mapping(bytes32 => bool) public usedNullifiers;

    /// Deposits indexed by note commitment (for frontend querying).
    mapping(bytes32 => DepositRecord) public deposits;

    /// Per-token deposited balance (address(0) = native ETH). Withdrawals may
    /// never exceed what was actually deposited for that token (solvency).
    mapping(address => uint256) public tokenBalances;

    /// Reentrancy guard status.
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED = 2;
    uint256 private _reentrancyStatus = _NOT_ENTERED;

    // ─── Types ──────────────────────────────────────────────────────────────

    struct DepositRecord {
        address token;
        address depositor;
        uint256 amount;
        uint256 leafIndex;
        uint256 blockNumber;
    }

    // ─── Escrow (timeout/refund) types + state ──────────────────────────────

    /// The escrow state machine. A locked deposit is `Locked`; it transitions to
    /// EXACTLY ONE terminal state — `Released` (a DrEX fill cleared) XOR `Refunded`
    /// (the deadline passed with no fill). `None` is the default for an unknown id,
    /// so a fresh escrow can never be mistaken for one already created.
    enum EscrowStatus {
        None, // 0 — no escrow with this id (default)
        Locked, // 1 — funds held, not yet assignable
        Released, // 2 — terminal: paid to the ring-matched recipient (fill proof)
        Refunded // 3 — terminal: reclaimed by the depositor (timeout)
    }

    struct Escrow {
        address token; // address(0) == native ETH
        address depositor; // who locked (the refund recipient)
        uint256 amount; // exact locked amount (the only amount release/refund move)
        uint256 deadline; // unix time; refund enabled once block.timestamp > deadline
        EscrowStatus status;
    }

    /// Escrows keyed by a caller-supplied unique id (the batch mirror commitment).
    mapping(bytes32 => Escrow) public escrows;

    /// Per-token amount currently held under a `Locked` escrow. DISJOINT from
    /// `tokenBalances` (the generic note-mirror pool): the generic `withdraw`
    /// checks `amount <= tokenBalances[token]` and so can never draw down escrowed
    /// funds, and release/refund move only the per-escrow amount — the two exit
    /// surfaces cannot drain each other.
    mapping(address => uint256) public escrowedBalances;

    // ─── Errors ─────────────────────────────────────────────────────────────

    error ZeroAmount();
    error DuplicateNoteCommitment();
    error NullifierAlreadyUsed(bytes32 nullifier);
    error ProofVerificationFailed();
    error TransferFailed();
    error InvalidProofOutputs();
    error AmountMismatch();
    error RecipientMismatch();
    error TokenMismatch();
    error VerifierNotContract();
    error UnknownRoot(bytes32 root);
    error InsufficientVaultBalance(address token, uint256 requested, uint256 available);
    error ReentrantCall();
    // ── Escrow errors ──
    error SettlementNotContract();
    error DuplicateEscrowId(bytes32 escrowId);
    error ZeroDeadline();
    error EscrowNotLocked(bytes32 escrowId);
    error EscrowIdMismatch();
    error ClearingRootNotProven(bytes32 clearingRoot);
    error RefundBeforeDeadline(bytes32 escrowId, uint256 deadline, uint256 nowTs);
    error NotDepositor(address caller, address depositor);

    // ─── Modifiers ──────────────────────────────────────────────────────────

    /// Minimal hand-rolled reentrancy guard (no external dependency).
    modifier nonReentrant() {
        if (_reentrancyStatus == _ENTERED) revert ReentrantCall();
        _reentrancyStatus = _ENTERED;
        _;
        _reentrancyStatus = _NOT_ENTERED;
    }

    // ─── Constructor ────────────────────────────────────────────────────────

    /// @param _sp1Verifier Address of the SP1 Verifier Gateway.
    /// @param _programVkey Verification key for the dregg guest program.
    /// @param _settlement  The dregg settlement client that gates escrow releases
    ///                     (`isProvenRoot` — the rung-8 clearing accept-path).
    constructor(address _sp1Verifier, bytes32 _programVkey, IDreggSettlement _settlement) {
        // Fail-closed: a staticcall to a codeless address returns success, so a
        // misconfigured verifier would silently accept every proof. Refuse to
        // deploy against an address with no code.
        if (_sp1Verifier.code.length == 0) revert VerifierNotContract();
        // Same fail-closed rule for the settlement client: a codeless settlement
        // would make the escrow-release `isProvenRoot` gate vacuous (a staticcall
        // to a codeless address "succeeds"), so an escrow could release against an
        // unsettled clearing root. Refuse it at deploy.
        if (address(_settlement).code.length == 0) revert SettlementNotContract();
        sp1Verifier = _sp1Verifier;
        programVkey = _programVkey;
        settlement = _settlement;
    }

    // ─── Deposits ───────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function deposit(
        address token,
        uint256 amount,
        bytes32 noteCommitment
    ) external {
        if (amount == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Transfer ERC-20 tokens from sender to this contract.
        // Using a low-level call to support non-standard ERC-20s (USDT, etc.).
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSignature(
                "transferFrom(address,address,uint256)",
                msg.sender,
                address(this),
                amount
            )
        );
        if (!success || (data.length > 0 && !abi.decode(data, (bool)))) {
            revert TransferFailed();
        }

        // Record the deposit and update the note tree.
        uint256 leafIndex = depositCount;
        deposits[noteCommitment] = DepositRecord({
            token: token,
            depositor: msg.sender,
            amount: amount,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        noteCommitments.push(noteCommitment);
        depositCount = leafIndex + 1;
        tokenBalances[token] += amount;

        // Update the tree root (simplified: hash of all commitments).
        // In production, use an incremental Merkle tree for O(log n) updates.
        noteTreeRoot = _computeRoot();
        _recordRoot(noteTreeRoot);

        emit Deposit(token, amount, noteCommitment, leafIndex);
    }

    /// @inheritdoc IDreggVault
    function depositETH(bytes32 noteCommitment) external payable {
        if (msg.value == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Record the ETH deposit (token = address(0) for native ETH).
        uint256 leafIndex = depositCount;
        deposits[noteCommitment] = DepositRecord({
            token: address(0),
            depositor: msg.sender,
            amount: msg.value,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        noteCommitments.push(noteCommitment);
        depositCount = leafIndex + 1;
        tokenBalances[address(0)] += msg.value;

        noteTreeRoot = _computeRoot();
        _recordRoot(noteTreeRoot);

        emit Deposit(address(0), msg.value, noteCommitment, leafIndex);
    }

    // ─── Withdrawals ────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function withdraw(
        address token,
        uint256 amount,
        address recipient,
        bytes calldata sp1Proof
    ) external nonReentrant {
        if (amount == 0) revert ZeroAmount();

        // Decode + verify the SP1 proof (fail-closed on a codeless verifier).
        bytes memory publicValues = _verifySp1(sp1Proof);

        // Decode public values committed by the SP1 guest program.
        // Expected format: (bool valid, bytes32 nullifier, address token, uint256 amount, address recipient, bytes32 noteTreeRoot)
        (
            bool valid,
            bytes32 nullifier,
            address proofToken,
            uint256 proofAmount,
            address proofRecipient,
            bytes32 proofRoot
        ) = abi.decode(publicValues, (bool, bytes32, address, uint256, address, bytes32));

        // Verify the proof's public outputs match the withdrawal parameters.
        if (!valid) revert ProofVerificationFailed();
        if (proofAmount != amount) revert AmountMismatch();
        if (proofRecipient != recipient) revert RecipientMismatch();
        if (proofToken != token) revert TokenMismatch();

        // The proof must commit to the current note tree root or one of the
        // recent roots in the ring buffer (Tornado-style grace window).
        if (!isKnownRoot(proofRoot)) revert UnknownRoot(proofRoot);

        // Solvency: never release more of a token than was deposited.
        uint256 available = tokenBalances[token];
        if (amount > available) revert InsufficientVaultBalance(token, amount, available);

        // Check and mark the nullifier as used BEFORE any external transfer.
        if (usedNullifiers[nullifier]) revert NullifierAlreadyUsed(nullifier);
        usedNullifiers[nullifier] = true;
        tokenBalances[token] = available - amount;

        // Transfer funds to recipient.
        if (token == address(0)) {
            // Native ETH withdrawal.
            (bool ethSuccess, ) = recipient.call{value: amount}("");
            if (!ethSuccess) revert TransferFailed();
        } else {
            // ERC-20 withdrawal.
            (bool transferSuccess, bytes memory transferData) = token.call(
                abi.encodeWithSignature(
                    "transfer(address,uint256)",
                    recipient,
                    amount
                )
            );
            if (!transferSuccess || (transferData.length > 0 && !abi.decode(transferData, (bool)))) {
                revert TransferFailed();
            }
        }

        emit Withdrawal(token, amount, recipient, nullifier);
    }

    // ─── Escrow (timeout/refund) — the two-branch DrEX routing-safety surface ─

    /// Emitted when an asset is locked into a timed escrow. The dregg federation
    /// observes this to mint the batch mirror the ring trades (the mirror side is
    /// off-chain; on-chain this event is the instruction + the custody record).
    event EscrowLocked(
        bytes32 indexed escrowId,
        address indexed token,
        address indexed depositor,
        uint256 amount,
        uint256 deadline
    );

    /// Emitted when an escrow is RELEASED to the ring-matched recipient against a
    /// proven DrEX clearing root (terminal: `Released`).
    event EscrowReleased(
        bytes32 indexed escrowId,
        address indexed recipient,
        uint256 amount,
        bytes32 clearingRoot
    );

    /// Emitted when an escrow is REFUNDED to the depositor after its deadline
    /// (terminal: `Refunded`).
    event EscrowRefunded(bytes32 indexed escrowId, address indexed depositor, uint256 amount);

    /// @notice Lock ERC-20 `amount` of `token` into a timed escrow under `escrowId`,
    ///         reclaimable after `deadline` if no DrEX fill clears it.
    /// @dev The caller must have approved the vault for `amount`. `escrowId` must be
    ///      fresh (an escrow reaches exactly one terminal state, so an id is never
    ///      reused). `deadline` is a unix timestamp strictly in the meaning "refund
    ///      becomes available once `block.timestamp > deadline`".
    function escrowDeposit(
        address token,
        uint256 amount,
        uint256 deadline,
        bytes32 escrowId
    ) external {
        if (amount == 0) revert ZeroAmount();
        if (deadline == 0) revert ZeroDeadline();
        if (escrows[escrowId].status != EscrowStatus.None) revert DuplicateEscrowId(escrowId);

        // Pull the ERC-20 in (low-level call supports non-standard tokens like USDT).
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSignature(
                "transferFrom(address,address,uint256)",
                msg.sender,
                address(this),
                amount
            )
        );
        if (!success || (data.length > 0 && !abi.decode(data, (bool)))) {
            revert TransferFailed();
        }

        _recordEscrow(escrowId, token, amount, deadline);
    }

    /// @notice Lock native ETH into a timed escrow under `escrowId`.
    function escrowDepositETH(uint256 deadline, bytes32 escrowId) external payable {
        if (msg.value == 0) revert ZeroAmount();
        if (deadline == 0) revert ZeroDeadline();
        if (escrows[escrowId].status != EscrowStatus.None) revert DuplicateEscrowId(escrowId);

        _recordEscrow(escrowId, address(0), msg.value, deadline);
    }

    /// @notice RELEASE branch — pay a locked escrow to the ring-matched recipient,
    ///         gated on a DrEX clearing/settlement proof. Terminal: `Released`.
    /// @dev Requires (i) the escrow is `Locked`; (ii) an SP1 fill proof whose public
    ///      outputs name THIS escrow as filled — `(valid, escrowId, token, amount,
    ///      recipient, clearingRoot)` — and match the escrow record + `recipient`;
    ///      (iii) `settlement.isProvenRoot(clearingRoot)` — dregg actually settled
    ///      that clearing root (the rung-8 accept-path). No deadline check: a real
    ///      fill proof wins over a timeout, but only while the escrow is still
    ///      `Locked` — once refunded (or released) this reverts. Exactly-once: the
    ///      status flips to `Released` BEFORE the external transfer (checks-effects-
    ///      interactions + `nonReentrant`), so a second release reverts.
    function escrowRelease(
        bytes32 escrowId,
        address recipient,
        bytes calldata sp1Proof
    ) external nonReentrant {
        Escrow storage e = escrows[escrowId];
        if (e.status != EscrowStatus.Locked) revert EscrowNotLocked(escrowId);

        // Verify the SP1 fill proof (fail-closed on a codeless verifier).
        bytes memory publicValues = _verifySp1(sp1Proof);
        (
            bool valid,
            bytes32 proofEscrowId,
            address proofToken,
            uint256 proofAmount,
            address proofRecipient,
            bytes32 clearingRoot
        ) = abi.decode(publicValues, (bool, bytes32, address, uint256, address, bytes32));

        if (!valid) revert ProofVerificationFailed();
        if (proofEscrowId != escrowId) revert EscrowIdMismatch();
        if (proofToken != e.token) revert TokenMismatch();
        if (proofAmount != e.amount) revert AmountMismatch();
        if (proofRecipient != recipient) revert RecipientMismatch();

        // The clearing root the fill proof commits to must be a genuinely SETTLED
        // dregg root — the rung-8 accept-path. A fresh-nullifier proof over an
        // unsettled/forged root cannot pay out. `bytes32(0)` is never proven.
        if (!settlement.isProvenRoot(clearingRoot)) revert ClearingRootNotProven(clearingRoot);

        // Effects BEFORE interaction: consume the lock (terminal `Released`).
        address token = e.token;
        uint256 amount = e.amount;
        e.status = EscrowStatus.Released;
        escrowedBalances[token] -= amount;

        _transferOut(token, recipient, amount);

        emit EscrowReleased(escrowId, recipient, amount, clearingRoot);
    }

    /// @notice REFUND branch — reclaim a locked escrow to its depositor after the
    ///         deadline, if no fill cleared it. Terminal: `Refunded`.
    /// @dev Requires (i) the escrow is `Locked`; (ii) `block.timestamp > deadline`
    ///      (the timeout IS the condition — no proof); (iii) the caller is the
    ///      depositor. Refund is ALWAYS reachable after the deadline with no
    ///      external dependency, so a lock can never be stuck. Exactly-once: the
    ///      status flips to `Refunded` before the transfer, so a second refund — or
    ///      a release after refund — reverts.
    function escrowRefund(bytes32 escrowId) external nonReentrant {
        Escrow storage e = escrows[escrowId];
        if (e.status != EscrowStatus.Locked) revert EscrowNotLocked(escrowId);
        if (block.timestamp <= e.deadline) {
            revert RefundBeforeDeadline(escrowId, e.deadline, block.timestamp);
        }
        if (msg.sender != e.depositor) revert NotDepositor(msg.sender, e.depositor);

        address token = e.token;
        uint256 amount = e.amount;
        address depositor = e.depositor;
        e.status = EscrowStatus.Refunded;
        escrowedBalances[token] -= amount;

        _transferOut(token, depositor, amount);

        emit EscrowRefunded(escrowId, depositor, amount);
    }

    /// @notice The status of an escrow (`None`/`Locked`/`Released`/`Refunded`).
    function escrowStatus(bytes32 escrowId) external view returns (EscrowStatus) {
        return escrows[escrowId].status;
    }

    // ─── View Functions ─────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }

    /// @notice True if `root` is the current note tree root or one of the last
    ///         ROOT_HISTORY_SIZE roots. The zero root is never accepted.
    function isKnownRoot(bytes32 root) public view returns (bool) {
        if (root == bytes32(0)) return false;
        if (root == noteTreeRoot) return true;
        uint256 filled = rootHistoryCount < ROOT_HISTORY_SIZE ? rootHistoryCount : ROOT_HISTORY_SIZE;
        for (uint256 i = 0; i < filled; i++) {
            if (rootHistory[i] == root) return true;
        }
        return false;
    }

    // ─── Internal ───────────────────────────────────────────────────────────

    /// Record a fresh `Locked` escrow and its disjoint escrowed balance, then emit.
    /// Shared by `escrowDeposit` (ERC-20) and `escrowDepositETH` after custody of
    /// `amount` has been taken.
    function _recordEscrow(
        bytes32 escrowId,
        address token,
        uint256 amount,
        uint256 deadline
    ) internal {
        escrows[escrowId] = Escrow({
            token: token,
            depositor: msg.sender,
            amount: amount,
            deadline: deadline,
            status: EscrowStatus.Locked
        });
        escrowedBalances[token] += amount;
        emit EscrowLocked(escrowId, token, msg.sender, amount, deadline);
    }

    /// Transfer `amount` of `token` (address(0) == ETH) out to `to`, reverting on
    /// failure. Shared payout for escrow release/refund.
    function _transferOut(address token, address to, uint256 amount) internal {
        if (token == address(0)) {
            (bool ethSuccess, ) = to.call{value: amount}("");
            if (!ethSuccess) revert TransferFailed();
        } else {
            (bool transferSuccess, bytes memory transferData) = token.call(
                abi.encodeWithSignature("transfer(address,uint256)", to, amount)
            );
            if (!transferSuccess || (transferData.length > 0 && !abi.decode(transferData, (bool)))) {
                revert TransferFailed();
            }
        }
    }

    /// Decode an SP1 proof envelope and verify it via the SP1 Verifier Gateway.
    /// Fail-closed: a staticcall to a codeless address succeeds vacuously, so a
    /// verifier with no code (even one that lost its code after deploy) must
    /// never be able to accept. Returns the proof's public values on success.
    function _verifySp1(bytes calldata sp1Proof) internal view returns (bytes memory publicValues) {
        if (sp1Verifier.code.length == 0) revert VerifierNotContract();

        // SP1 proofs are encoded as: abi.encode(proofBytes, publicValues)
        bytes memory proofBytes;
        (proofBytes, publicValues) = abi.decode(sp1Proof, (bytes, bytes));

        // The gateway reverts if the proof is invalid.
        (bool verifySuccess, ) = sp1Verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(bytes32,bytes,bytes)",
                programVkey,
                publicValues,
                proofBytes
            )
        );
        if (!verifySuccess) revert ProofVerificationFailed();
    }

    /// Record a new root in the ring buffer of recent roots.
    function _recordRoot(bytes32 newRoot) internal {
        rootHistory[rootHistoryCount % ROOT_HISTORY_SIZE] = newRoot;
        rootHistoryCount += 1;
    }

    /// Compute the Merkle root of all note commitments.
    /// Simplified implementation: iterative hashing. In production, use an
    /// incremental Merkle tree with fixed depth (e.g., 20 levels = 1M leaves).
    function _computeRoot() internal view returns (bytes32) {
        uint256 count = noteCommitments.length;
        if (count == 0) return bytes32(0);
        if (count == 1) return noteCommitments[0];

        // Build a simple binary hash tree.
        bytes32[] memory layer = new bytes32[](count);
        for (uint256 i = 0; i < count; i++) {
            layer[i] = noteCommitments[i];
        }

        while (layer.length > 1) {
            uint256 newLen = (layer.length + 1) / 2;
            bytes32[] memory newLayer = new bytes32[](newLen);
            for (uint256 i = 0; i < newLen; i++) {
                if (2 * i + 1 < layer.length) {
                    newLayer[i] = keccak256(abi.encodePacked(layer[2 * i], layer[2 * i + 1]));
                } else {
                    newLayer[i] = layer[2 * i]; // Odd leaf promoted.
                }
            }
            layer = newLayer;
        }

        return layer[0];
    }
}
