// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IDreggVault.sol";
import {IDreggSettlement} from "./IDreggSettlement.sol";

/// @title DreggVault
/// @notice Holds bridged assets (ERC-20 and ETH) with private note-based accounting.
///
/// Deposits create note commitments that the dregg federation observes and mirrors
/// into its private note tree. Withdrawals require an SP1-wrapped STARK proof that
/// verifies note ownership and spending validity.
///
/// SP1 verification is delegated to the SP1 Verifier Gateway (deterministic CREATE2
/// deployment across all EVM chains). The vault only needs to check that the proof
/// was generated by the correct program (matching programVkey) and that the public
/// outputs encode the expected withdrawal parameters.
///
/// ## The TIMEOUT/REFUND ESCROW (DrEX cross-chain routing safety)
///
/// The plain deposit/withdraw pair above is the GENERIC note-mirror surface: lock
/// an asset, mint a mirror, exit later against your own spend proof (§4(b) of
/// `docs/deos/DREX-ROUTING.md`). It has NO batch-scoped reclaim: an asset locked
/// for a DrEX trade that never clears (no ring match, or a stalled chain) would sit
/// forever. That made locking into DrEX unsafe.
///
/// The `escrow*` surface below is the load-bearing fix the routing design named
/// (`DREX-ROUTING.md §4(a)`, "the single most load-bearing build"): a locked
/// deposit is a TIMED escrow that reaches EXACTLY ONE terminal state —
///   • RELEASED to the ring-matched recipient, gated on a DrEX clearing/settlement
///     proof (an SP1 fill proof whose clearing root is proven by the on-chain
///     `IDreggSettlement` — the rung-8 accept-path), XOR
///   • REFUNDED to the depositor, gated only on the per-deposit deadline passing
///     (the timeout IS the condition; no proof needed).
///
/// The two branches are mutually exclusive on one `EscrowStatus` state machine
/// (`Locked → Released` XOR `Locked → Refunded`); each consumes the lock and is
/// idempotent-guarded, so a released escrow can never be refunded and vice-versa,
/// and no escrow is ever stuck (refund is always reachable after the deadline with
/// no external dependency). Escrow funds are accounted in `escrowedBalances`,
/// DISJOINT from the generic `tokenBalances` pool, so neither surface can drain the
/// other. The residual this does NOT close — full cross-vault atomic release across
/// a permanently-unavailable chain — is the named RESEARCH rung (`§4(a)`).
contract DreggVault is IDreggVault {
    // ─── Immutables ─────────────────────────────────────────────────────────

    /// Address of the SP1 Verifier Gateway contract (same on all EVM chains).
    address public immutable sp1Verifier;

    /// Verification key identifying the dregg STARK verifier guest program.
    /// The SP1 verifier checks that the proof was generated by this exact program.
    bytes32 public immutable programVkey;

    /// The on-chain dregg settlement client (`DreggSettlement`). An escrow RELEASE
    /// is gated on `settlement.isProvenRoot(clearingRoot)` — the rung-8 accept-path
    /// that answers "did dregg settle this clearing root?". Fail-closed: a codeless
    /// settlement address would make `isProvenRoot` a vacuous staticcall, so the
    /// constructor refuses to deploy against one.
    IDreggSettlement public immutable settlement;

    // ─── State ──────────────────────────────────────────────────────────────

    /// INCREMENTAL fixed-depth Merkle tree of note commitments (Tornado/Semaphore
    /// style). Each deposit is O(TREE_DEPTH) hashes + SLOADs — CONSTANT per deposit,
    /// independent of `depositCount` — so deposits can never grow to exceed the
    /// block gas limit (the #5 gas-DoS the old `_computeRoot` full-tree rebuild left
    /// open: rebuilding the whole tree from storage per deposit was O(n) SLOADs and
    /// eventually un-depositable). See `_insertLeaf`.
    ///
    /// PLACEHOLDER (#12, separate design item): this is still the keccak256 tree,
    /// NOT domain-separated, and does NOT match the circuit's Poseidon2 note tree.
    /// The SP1 guest program proves membership against the Poseidon2 tree, so the
    /// keccak root here and the circuit root only agree because the federation
    /// mirrors deposits. The root COMPARISON below is real (withdraw proofs must
    /// commit to the current root or one of the last ROOT_HISTORY_SIZE roots); the
    /// hash function remains the placeholder pending Poseidon2 alignment.
    ///
    /// TREE_DEPTH = 20 → up to 1,048,576 notes. CONSERVATIVE DEFAULT: 2^20 leaves
    /// comfortably exceeds any pre-launch note volume while keeping the per-deposit
    /// hash count (20) tiny; a deployment expecting more should widen the depth.
    uint32 public constant TREE_DEPTH = 20;
    uint256 public constant MAX_LEAVES = uint256(1) << TREE_DEPTH;

    /// The left-sibling cache for the incremental insert (one per level) and the
    /// precomputed all-zero subtree roots (`zeros[i]` = root of an empty subtree of
    /// height `i`). Both are seeded in the constructor.
    bytes32[TREE_DEPTH] public filledSubtrees;
    bytes32[TREE_DEPTH] public zeros;

    /// Current root of the note commitment tree.
    bytes32 public noteTreeRoot;

    /// Total number of deposits (== the next free leaf index).
    uint256 public depositCount;

    /// Ring buffer of recent tree roots (Tornado-style). Withdrawals may prove
    /// against any of the last ROOT_HISTORY_SIZE roots, so a proof generated
    /// just before a new deposit remains spendable.
    uint256 public constant ROOT_HISTORY_SIZE = 32;
    bytes32[ROOT_HISTORY_SIZE] public rootHistory;
    uint256 public rootHistoryCount;

    /// Spent nullifiers (prevents double-withdrawal).
    mapping(bytes32 => bool) public usedNullifiers;

    /// Deposits indexed by note commitment (for frontend querying).
    mapping(bytes32 => DepositRecord) public deposits;

    /// Per-token deposited balance (address(0) = native ETH). Withdrawals may
    /// never exceed what was actually deposited for that token (solvency).
    mapping(address => uint256) public tokenBalances;

    /// Reentrancy guard status.
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED = 2;
    uint256 private _reentrancyStatus = _NOT_ENTERED;

    // ─── Types ──────────────────────────────────────────────────────────────

    struct DepositRecord {
        address token;
        address depositor;
        uint256 amount;
        uint256 leafIndex;
        uint256 blockNumber;
    }

    // ─── Escrow (timeout/refund) types + state ──────────────────────────────

    /// The escrow state machine. A locked deposit is `Locked`; it transitions to
    /// EXACTLY ONE terminal state — `Released` (a DrEX fill cleared) XOR `Refunded`
    /// (the deadline passed with no fill). `None` is the default for an unknown id,
    /// so a fresh escrow can never be mistaken for one already created.
    enum EscrowStatus {
        None, // 0 — no escrow with this id (default)
        Locked, // 1 — funds held, not yet assignable
        Released, // 2 — terminal: paid to the ring-matched recipient (fill proof)
        Refunded // 3 — terminal: reclaimed by the depositor (timeout)
    }

    struct Escrow {
        address token; // address(0) == native ETH
        address depositor; // who locked (the refund recipient)
        uint256 amount; // exact locked amount (the only amount release/refund move)
        uint256 deadline; // unix time; refund enabled once block.timestamp > deadline
        EscrowStatus status;
    }

    /// Escrows keyed by a caller-supplied unique id (the batch mirror commitment).
    mapping(bytes32 => Escrow) public escrows;

    /// Per-token amount currently held under a `Locked` escrow. DISJOINT from
    /// `tokenBalances` (the generic note-mirror pool): the generic `withdraw`
    /// checks `amount <= tokenBalances[token]` and so can never draw down escrowed
    /// funds, and release/refund move only the per-escrow amount — the two exit
    /// surfaces cannot drain each other.
    mapping(address => uint256) public escrowedBalances;

    // ─── Errors ─────────────────────────────────────────────────────────────

    error ZeroAmount();
    error DuplicateNoteCommitment();
    error NullifierAlreadyUsed(bytes32 nullifier);
    error ProofVerificationFailed();
    error TransferFailed();
    error InvalidProofOutputs();
    error AmountMismatch();
    error RecipientMismatch();
    error TokenMismatch();
    error VerifierNotContract();
    error UnknownRoot(bytes32 root);
    error InsufficientVaultBalance(address token, uint256 requested, uint256 available);
    error ReentrantCall();
    error BalanceQueryFailed();
    /// The withdraw proof is bound to a DIFFERENT vault deployment (`address(this)`).
    error VaultBindingMismatch(address boundVault, address thisVault);
    /// The withdraw proof is bound to a DIFFERENT chain (`block.chainid`).
    error ChainBindingMismatch(uint256 boundChainId, uint256 thisChainId);
    /// The incremental note tree is full (`depositCount == MAX_LEAVES`).
    error MerkleTreeFull();
    // ── Escrow errors ──
    error SettlementNotContract();
    error DuplicateEscrowId(bytes32 escrowId);
    error ZeroDeadline();
    error EscrowNotLocked(bytes32 escrowId);
    error EscrowIdMismatch();
    error ClearingRootNotProven(bytes32 clearingRoot);
    error RefundBeforeDeadline(bytes32 escrowId, uint256 deadline, uint256 nowTs);
    error NotDepositor(address caller, address depositor);

    // ─── Modifiers ──────────────────────────────────────────────────────────

    /// Minimal hand-rolled reentrancy guard (no external dependency).
    modifier nonReentrant() {
        if (_reentrancyStatus == _ENTERED) revert ReentrantCall();
        _reentrancyStatus = _ENTERED;
        _;
        _reentrancyStatus = _NOT_ENTERED;
    }

    // ─── Constructor ────────────────────────────────────────────────────────

    /// @param _sp1Verifier Address of the SP1 Verifier Gateway.
    /// @param _programVkey Verification key for the dregg guest program.
    /// @param _settlement  The dregg settlement client that gates escrow releases
    ///                     (`isProvenRoot` — the rung-8 clearing accept-path).
    constructor(address _sp1Verifier, bytes32 _programVkey, IDreggSettlement _settlement) {
        // Fail-closed: a staticcall to a codeless address returns success, so a
        // misconfigured verifier would silently accept every proof. Refuse to
        // deploy against an address with no code.
        if (_sp1Verifier.code.length == 0) revert VerifierNotContract();
        // Same fail-closed rule for the settlement client: a codeless settlement
        // would make the escrow-release `isProvenRoot` gate vacuous (a staticcall
        // to a codeless address "succeeds"), so an escrow could release against an
        // unsettled clearing root. Refuse it at deploy.
        if (address(_settlement).code.length == 0) revert SettlementNotContract();
        sp1Verifier = _sp1Verifier;
        programVkey = _programVkey;
        settlement = _settlement;

        // Seed the incremental Merkle tree: `zeros[i]` is the root of an empty
        // subtree of height `i` (zeros[0] is the zero leaf), and the left-sibling
        // cache starts as those empty subtrees. `noteTreeRoot` begins as the empty
        // tree's root, which `isKnownRoot` still rejects (nothing is spendable until
        // a deposit records a real root).
        bytes32 currentZero = bytes32(0);
        for (uint32 i = 0; i < TREE_DEPTH; i++) {
            zeros[i] = currentZero;
            filledSubtrees[i] = currentZero;
            currentZero = keccak256(abi.encodePacked(currentZero, currentZero));
        }
    }

    // ─── Deposits ───────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function deposit(
        address token,
        uint256 amount,
        bytes32 noteCommitment
    ) external nonReentrant {
        if (amount == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Pull the ERC-20 in and credit ONLY what actually arrived (the measured
        // before/after `balanceOf(this)` delta). A fee-on-transfer / rebasing token
        // delivers LESS than `amount`; crediting the requested `amount` (as this
        // did) over-credits `tokenBalances[token]` so a later withdrawal draws down
        // OTHER depositors' balances of the same token — cross-user theft. Measuring
        // the delta credits exactly the custodied amount. `nonReentrant` makes the
        // measurement sound: a malicious token cannot re-enter `deposit` between the
        // two `balanceOf` reads to double-count its own inbound transfer.
        uint256 received = _pullERC20(token, msg.sender, amount);
        if (received == 0) revert ZeroAmount();

        // Record the deposit and update the note tree. `received` is the custodied
        // amount — the record, the credited balance, and the event all reflect it.
        // `_insertLeaf` appends the commitment at `depositCount` in O(TREE_DEPTH)
        // and moves `noteTreeRoot` — constant work per deposit (the #5 gas fix).
        uint256 leafIndex = _insertLeaf(noteCommitment);
        deposits[noteCommitment] = DepositRecord({
            token: token,
            depositor: msg.sender,
            amount: received,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        depositCount = leafIndex + 1;
        tokenBalances[token] += received;

        _recordRoot(noteTreeRoot);

        emit Deposit(token, received, noteCommitment, leafIndex);
    }

    /// @inheritdoc IDreggVault
    function depositETH(bytes32 noteCommitment) external payable {
        if (msg.value == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Record the ETH deposit (token = address(0) for native ETH). The
        // incremental insert is O(TREE_DEPTH) — constant per deposit (the #5 fix).
        uint256 leafIndex = _insertLeaf(noteCommitment);
        deposits[noteCommitment] = DepositRecord({
            token: address(0),
            depositor: msg.sender,
            amount: msg.value,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        depositCount = leafIndex + 1;
        tokenBalances[address(0)] += msg.value;

        _recordRoot(noteTreeRoot);

        emit Deposit(address(0), msg.value, noteCommitment, leafIndex);
    }

    // ─── Withdrawals ────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function withdraw(
        address token,
        uint256 amount,
        address recipient,
        bytes calldata sp1Proof
    ) external nonReentrant {
        if (amount == 0) revert ZeroAmount();

        // Decode + verify the SP1 proof (fail-closed on a codeless verifier), then
        // decode the public values and enforce every field match INCLUDING the #3
        // deployment binding. Split into a helper so `withdraw` stays under the
        // stack-depth limit. Returns the nullifier and the committed root.
        (bytes32 nullifier, bytes32 proofRoot) =
            _decodeAndCheckWithdraw(_verifySp1(sp1Proof), token, amount, recipient);

        // The proof must commit to the current note tree root or one of the
        // recent roots in the ring buffer (Tornado-style grace window).
        if (!isKnownRoot(proofRoot)) revert UnknownRoot(proofRoot);

        // Solvency: never release more of a token than was deposited.
        uint256 available = tokenBalances[token];
        if (amount > available) revert InsufficientVaultBalance(token, amount, available);

        // Check and mark the nullifier as used BEFORE any external transfer.
        if (usedNullifiers[nullifier]) revert NullifierAlreadyUsed(nullifier);
        usedNullifiers[nullifier] = true;
        tokenBalances[token] = available - amount;

        // Transfer funds to recipient.
        if (token == address(0)) {
            // Native ETH withdrawal.
            (bool ethSuccess, ) = recipient.call{value: amount}("");
            if (!ethSuccess) revert TransferFailed();
        } else {
            // ERC-20 withdrawal.
            (bool transferSuccess, bytes memory transferData) = token.call(
                abi.encodeWithSignature(
                    "transfer(address,uint256)",
                    recipient,
                    amount
                )
            );
            if (!transferSuccess || (transferData.length > 0 && !abi.decode(transferData, (bool)))) {
                revert TransferFailed();
            }
        }

        emit Withdrawal(token, amount, recipient, nullifier);
    }

    // ─── Escrow (timeout/refund) — the two-branch DrEX routing-safety surface ─

    /// Emitted when an asset is locked into a timed escrow. The dregg federation
    /// observes this to mint the batch mirror the ring trades (the mirror side is
    /// off-chain; on-chain this event is the instruction + the custody record).
    event EscrowLocked(
        bytes32 indexed escrowId,
        address indexed token,
        address indexed depositor,
        uint256 amount,
        uint256 deadline
    );

    /// Emitted when an escrow is RELEASED to the ring-matched recipient against a
    /// proven DrEX clearing root (terminal: `Released`).
    event EscrowReleased(
        bytes32 indexed escrowId,
        address indexed recipient,
        uint256 amount,
        bytes32 clearingRoot
    );

    /// Emitted when an escrow is REFUNDED to the depositor after its deadline
    /// (terminal: `Refunded`).
    event EscrowRefunded(bytes32 indexed escrowId, address indexed depositor, uint256 amount);

    /// @notice Lock ERC-20 `amount` of `token` into a timed escrow under `escrowId`,
    ///         reclaimable after `deadline` if no DrEX fill clears it.
    /// @dev The caller must have approved the vault for `amount`. `escrowId` must be
    ///      fresh (an escrow reaches exactly one terminal state, so an id is never
    ///      reused). `deadline` is a unix timestamp strictly in the meaning "refund
    ///      becomes available once `block.timestamp > deadline`".
    function escrowDeposit(
        address token,
        uint256 amount,
        uint256 deadline,
        bytes32 escrowId
    ) external nonReentrant {
        if (amount == 0) revert ZeroAmount();
        if (deadline == 0) revert ZeroDeadline();
        if (escrows[escrowId].status != EscrowStatus.None) revert DuplicateEscrowId(escrowId);

        // Credit only the measured balance delta: `escrowRelease`/`escrowRefund`
        // pay out `e.amount`, so a fee-on-transfer token MUST escrow what actually
        // arrived, never the requested `amount` (else a release would pay more than
        // was custodied and drain other escrows of the same token). Same fix and
        // same soundness argument as `deposit`.
        uint256 received = _pullERC20(token, msg.sender, amount);
        if (received == 0) revert ZeroAmount();

        _recordEscrow(escrowId, token, received, deadline);
    }

    /// @notice Lock native ETH into a timed escrow under `escrowId`.
    function escrowDepositETH(uint256 deadline, bytes32 escrowId) external payable {
        if (msg.value == 0) revert ZeroAmount();
        if (deadline == 0) revert ZeroDeadline();
        if (escrows[escrowId].status != EscrowStatus.None) revert DuplicateEscrowId(escrowId);

        _recordEscrow(escrowId, address(0), msg.value, deadline);
    }

    /// @notice RELEASE branch — pay a locked escrow to the ring-matched recipient,
    ///         gated on a DrEX clearing/settlement proof. Terminal: `Released`.
    /// @dev Requires (i) the escrow is `Locked`; (ii) an SP1 fill proof whose public
    ///      outputs name THIS escrow as filled — `(valid, escrowId, token, amount,
    ///      recipient, clearingRoot, boundVault, boundChainId)` — and match the escrow
    ///      record + `recipient` + the #8 deployment binding (`boundVault ==
    ///      address(this)`, `boundChainId == block.chainid`); (iii)
    ///      `settlement.isProvenRoot(clearingRoot)` — dregg actually settled that
    ///      clearing root (the rung-8 accept-path). No deadline check: a real fill
    ///      proof wins over a timeout, but only while the escrow is still `Locked` —
    ///      once refunded (or released) this reverts. Exactly-once: the status flips
    ///      to `Released` BEFORE the external transfer (checks-effects-interactions +
    ///      `nonReentrant`), so a second release reverts.
    ///
    ///      DEPLOYMENT BINDING (#8, the same class as the #3 withdraw binding):
    ///      before `boundVault`/`boundChainId` the fill statement carried nothing
    ///      tying it to THIS vault, so a valid fill proof for one DreggVault could be
    ///      replayed on any other DreggVault sharing `programVkey` (the same guest on
    ///      another address or chain) to release a same-id escrow there. Folding
    ///      `address(this)` + `block.chainid` into the checked statement stops that
    ///      cross-deployment replay. The check bites once the SP1 guest COMMITS these
    ///      values — the companion circuit change is off-chain (the guest fill
    ///      statement), not here; landing the check on-chain first is fail-closed.
    function escrowRelease(
        bytes32 escrowId,
        address recipient,
        bytes calldata sp1Proof
    ) external nonReentrant {
        Escrow storage e = escrows[escrowId];
        if (e.status != EscrowStatus.Locked) revert EscrowNotLocked(escrowId);

        // Verify the SP1 fill proof (fail-closed on a codeless verifier), then decode
        // its public values and enforce every field match INCLUDING the #8 deployment
        // binding. Split into a helper so `escrowRelease` stays under the stack-depth
        // limit (same shape as `withdraw` / `_decodeAndCheckWithdraw`). Returns the
        // committed clearing root.
        bytes32 clearingRoot =
            _decodeAndCheckFill(_verifySp1(sp1Proof), escrowId, e.token, e.amount, recipient);

        // The clearing root the fill proof commits to must be a genuinely SETTLED
        // dregg root — the rung-8 accept-path. A fresh-nullifier proof over an
        // unsettled/forged root cannot pay out. `bytes32(0)` is never proven.
        if (!settlement.isProvenRoot(clearingRoot)) revert ClearingRootNotProven(clearingRoot);

        // Effects BEFORE interaction: consume the lock (terminal `Released`).
        address token = e.token;
        uint256 amount = e.amount;
        e.status = EscrowStatus.Released;
        escrowedBalances[token] -= amount;

        _transferOut(token, recipient, amount);

        emit EscrowReleased(escrowId, recipient, amount, clearingRoot);
    }

    /// @notice REFUND branch — reclaim a locked escrow to its depositor after the
    ///         deadline, if no fill cleared it. Terminal: `Refunded`.
    /// @dev Requires (i) the escrow is `Locked`; (ii) `block.timestamp > deadline`
    ///      (the timeout IS the condition — no proof); (iii) the caller is the
    ///      depositor. Refund is ALWAYS reachable after the deadline with no
    ///      external dependency, so a lock can never be stuck. Exactly-once: the
    ///      status flips to `Refunded` before the transfer, so a second refund — or
    ///      a release after refund — reverts.
    function escrowRefund(bytes32 escrowId) external nonReentrant {
        Escrow storage e = escrows[escrowId];
        if (e.status != EscrowStatus.Locked) revert EscrowNotLocked(escrowId);
        if (block.timestamp <= e.deadline) {
            revert RefundBeforeDeadline(escrowId, e.deadline, block.timestamp);
        }
        if (msg.sender != e.depositor) revert NotDepositor(msg.sender, e.depositor);

        address token = e.token;
        uint256 amount = e.amount;
        address depositor = e.depositor;
        e.status = EscrowStatus.Refunded;
        escrowedBalances[token] -= amount;

        _transferOut(token, depositor, amount);

        emit EscrowRefunded(escrowId, depositor, amount);
    }

    /// @notice The status of an escrow (`None`/`Locked`/`Released`/`Refunded`).
    function escrowStatus(bytes32 escrowId) external view returns (EscrowStatus) {
        return escrows[escrowId].status;
    }

    // ─── View Functions ─────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }

    /// @notice True if `root` is the current note tree root or one of the last
    ///         ROOT_HISTORY_SIZE roots. The zero root is never accepted.
    function isKnownRoot(bytes32 root) public view returns (bool) {
        if (root == bytes32(0)) return false;
        if (root == noteTreeRoot) return true;
        uint256 filled = rootHistoryCount < ROOT_HISTORY_SIZE ? rootHistoryCount : ROOT_HISTORY_SIZE;
        for (uint256 i = 0; i < filled; i++) {
            if (rootHistory[i] == root) return true;
        }
        return false;
    }

    // ─── Internal ───────────────────────────────────────────────────────────

    /// Record a fresh `Locked` escrow and its disjoint escrowed balance, then emit.
    /// Shared by `escrowDeposit` (ERC-20) and `escrowDepositETH` after custody of
    /// `amount` has been taken.
    function _recordEscrow(
        bytes32 escrowId,
        address token,
        uint256 amount,
        uint256 deadline
    ) internal {
        escrows[escrowId] = Escrow({
            token: token,
            depositor: msg.sender,
            amount: amount,
            deadline: deadline,
            status: EscrowStatus.Locked
        });
        escrowedBalances[token] += amount;
        emit EscrowLocked(escrowId, token, msg.sender, amount, deadline);
    }

    /// Transfer `amount` of `token` (address(0) == ETH) out to `to`, reverting on
    /// failure. Shared payout for escrow release/refund.
    function _transferOut(address token, address to, uint256 amount) internal {
        if (token == address(0)) {
            (bool ethSuccess, ) = to.call{value: amount}("");
            if (!ethSuccess) revert TransferFailed();
        } else {
            (bool transferSuccess, bytes memory transferData) = token.call(
                abi.encodeWithSignature("transfer(address,uint256)", to, amount)
            );
            if (!transferSuccess || (transferData.length > 0 && !abi.decode(transferData, (bool)))) {
                revert TransferFailed();
            }
        }
    }

    /// Pull `amount` of ERC-20 `token` from `from` into the vault, returning the
    /// ACTUAL received amount — the before/after `balanceOf(this)` delta. This is
    /// the fee-on-transfer / rebasing guard: a token that skims a fee on transfer
    /// delivers less than `amount`, and only the measured delta may be credited (a
    /// requested-amount credit lets one token's pool draw down other depositors'
    /// balances). Low-level call supports non-standard ERC-20s (USDT, etc.).
    function _pullERC20(address token, address from, uint256 amount) internal returns (uint256 received) {
        uint256 balBefore = _erc20SelfBalance(token);
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSignature("transferFrom(address,address,uint256)", from, address(this), amount)
        );
        if (!success || (data.length > 0 && !abi.decode(data, (bool)))) {
            revert TransferFailed();
        }
        uint256 balAfter = _erc20SelfBalance(token);
        // Checked subtraction (Solidity 0.8): a pull that somehow REDUCED our
        // balance reverts rather than underflowing into a huge phantom credit.
        received = balAfter - balBefore;
    }

    /// This vault's own ERC-20 balance of `token`, fail-closed: a token whose
    /// `balanceOf` reverts or returns fewer than 32 bytes cannot be measured, so
    /// the deposit reverts rather than crediting a guessed amount.
    function _erc20SelfBalance(address token) internal view returns (uint256) {
        (bool ok, bytes memory data) = token.staticcall(
            abi.encodeWithSignature("balanceOf(address)", address(this))
        );
        if (!ok || data.length < 32) revert BalanceQueryFailed();
        return abi.decode(data, (uint256));
    }

    /// Decode an SP1 proof envelope and verify it via the SP1 Verifier Gateway.
    /// Fail-closed: a staticcall to a codeless address succeeds vacuously, so a
    /// verifier with no code (even one that lost its code after deploy) must
    /// never be able to accept. Returns the proof's public values on success.
    function _verifySp1(bytes calldata sp1Proof) internal view returns (bytes memory publicValues) {
        if (sp1Verifier.code.length == 0) revert VerifierNotContract();

        // SP1 proofs are encoded as: abi.encode(proofBytes, publicValues)
        bytes memory proofBytes;
        (proofBytes, publicValues) = abi.decode(sp1Proof, (bytes, bytes));

        // The gateway reverts if the proof is invalid.
        (bool verifySuccess, ) = sp1Verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(bytes32,bytes,bytes)",
                programVkey,
                publicValues,
                proofBytes
            )
        );
        if (!verifySuccess) revert ProofVerificationFailed();
    }

    /// Decode a withdraw proof's public values and enforce EVERY field match:
    /// validity, (token, amount, recipient), and the #3 deployment binding
    /// (`boundVault == address(this)`, `boundChainId == block.chainid`). Returns the
    /// nullifier and the committed note-tree root (checked against the ring buffer
    /// by the caller). Split out of `withdraw` to stay under the stack-depth limit.
    ///
    /// Expected public-values format (the SP1 guest statement):
    ///   (bool valid, bytes32 nullifier, address token, uint256 amount,
    ///    address recipient, bytes32 noteTreeRoot,
    ///    address boundVault, uint256 boundChainId)
    ///
    /// `boundVault`/`boundChainId` are the DEPLOYMENT BINDING (#3): before them the
    /// withdraw statement carried nothing tying it to THIS vault, so a valid proof
    /// replayed on any DreggVault sharing `programVkey` (the same guest on another
    /// address or chain). The check only bites once the guest COMMITS these values —
    /// the companion circuit change is off-chain (the SP1 guest statement), not here.
    function _decodeAndCheckWithdraw(
        bytes memory publicValues,
        address token,
        uint256 amount,
        address recipient
    ) internal view returns (bytes32 nullifier, bytes32 proofRoot) {
        (
            bool valid,
            bytes32 nf,
            address proofToken,
            uint256 proofAmount,
            address proofRecipient,
            bytes32 root,
            address boundVault,
            uint256 boundChainId
        ) = abi.decode(publicValues, (bool, bytes32, address, uint256, address, bytes32, address, uint256));

        // Verify the proof's public outputs match the withdrawal parameters.
        if (!valid) revert ProofVerificationFailed();
        if (proofAmount != amount) revert AmountMismatch();
        if (proofRecipient != recipient) revert RecipientMismatch();
        if (proofToken != token) revert TokenMismatch();

        // Deployment binding: reject a proof built for a different vault or chain.
        if (boundVault != address(this)) revert VaultBindingMismatch(boundVault, address(this));
        if (boundChainId != block.chainid) revert ChainBindingMismatch(boundChainId, block.chainid);

        nullifier = nf;
        proofRoot = root;
    }

    /// Decode an escrow fill proof's public values and enforce EVERY field match:
    /// validity, (escrowId, token, amount, recipient), and the #8 deployment binding
    /// (`boundVault == address(this)`, `boundChainId == block.chainid`). Returns the
    /// committed clearing root (checked against the settlement client by the caller).
    /// Split out of `escrowRelease` to stay under the stack-depth limit — the twin of
    /// `_decodeAndCheckWithdraw`.
    ///
    /// Expected public-values format (the SP1 guest fill statement):
    ///   (bool valid, bytes32 escrowId, address token, uint256 amount,
    ///    address recipient, bytes32 clearingRoot,
    ///    address boundVault, uint256 boundChainId)
    ///
    /// `boundVault`/`boundChainId` are the DEPLOYMENT BINDING (#8): before them the
    /// fill statement carried nothing tying it to THIS vault, so a valid fill proof
    /// replayed on any DreggVault sharing `programVkey` (the same guest on another
    /// address or chain) could release a same-id escrow there. The check bites once
    /// the guest COMMITS these values — the companion circuit change is off-chain.
    function _decodeAndCheckFill(
        bytes memory publicValues,
        bytes32 escrowId,
        address token,
        uint256 amount,
        address recipient
    ) internal view returns (bytes32 clearingRoot) {
        (
            bool valid,
            bytes32 proofEscrowId,
            address proofToken,
            uint256 proofAmount,
            address proofRecipient,
            bytes32 root,
            address boundVault,
            uint256 boundChainId
        ) = abi.decode(publicValues, (bool, bytes32, address, uint256, address, bytes32, address, uint256));

        if (!valid) revert ProofVerificationFailed();
        if (proofEscrowId != escrowId) revert EscrowIdMismatch();
        if (proofToken != token) revert TokenMismatch();
        if (proofAmount != amount) revert AmountMismatch();
        if (proofRecipient != recipient) revert RecipientMismatch();

        // Deployment binding: reject a fill proof built for a different vault or chain.
        if (boundVault != address(this)) revert VaultBindingMismatch(boundVault, address(this));
        if (boundChainId != block.chainid) revert ChainBindingMismatch(boundChainId, block.chainid);

        clearingRoot = root;
    }

    /// Record a new root in the ring buffer of recent roots.
    function _recordRoot(bytes32 newRoot) internal {
        rootHistory[rootHistoryCount % ROOT_HISTORY_SIZE] = newRoot;
        rootHistoryCount += 1;
    }

    /// Append `leaf` at index `depositCount` into the incremental fixed-depth
    /// Merkle tree, update `noteTreeRoot`, and return the leaf index. O(TREE_DEPTH)
    /// hashes + SLOADs — CONSTANT per deposit regardless of how many notes already
    /// exist (the #5 gas-DoS fix: the old full-tree rebuild was O(n)). Reverts once
    /// the tree is full (`MAX_LEAVES` leaves).
    ///
    /// Standard Tornado/Semaphore insert: walk from the leaf to the root, and at
    /// each level pair the running hash with either the freshly cached left sibling
    /// (`filledSubtrees[i]`, when this node is a right child) or the empty subtree
    /// root (`zeros[i]`, when it is a left child — in which case cache it as the
    /// left sibling for the next insert at this level).
    function _insertLeaf(bytes32 leaf) internal returns (uint256 index) {
        index = depositCount;
        if (index >= MAX_LEAVES) revert MerkleTreeFull();

        uint256 currentIndex = index;
        bytes32 currentLevelHash = leaf;
        bytes32 left;
        bytes32 right;
        for (uint32 i = 0; i < TREE_DEPTH; i++) {
            if (currentIndex % 2 == 0) {
                left = currentLevelHash;
                right = zeros[i];
                filledSubtrees[i] = currentLevelHash;
            } else {
                left = filledSubtrees[i];
                right = currentLevelHash;
            }
            currentLevelHash = keccak256(abi.encodePacked(left, right));
            currentIndex /= 2;
        }
        noteTreeRoot = currentLevelHash;
    }
}
