// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// Groth16(BN254) verifier over the PEER-CHAIN FINALITY statement — the portable
/// "chain X finalized state root R at height H" claim that a light-client STARK
/// produces, wrapped to a Groth16 exactly as dregg's own whole-history proof is
/// (`chain/gnark`, `docs/deos/ETH-NATIVE-WRAP.md`).
///
/// This is the MIRROR of `IGroth16Verifier25`: where that interface pins the
/// call shape for verifying DREGG's state on a peer chain, THIS interface pins
/// the call shape for verifying a PEER chain's finalized state on dregg (or on
/// any chain hosting a `DreggPeerRegistry`). Together they are the two halves of
/// mutual cross-chain verification — TRUE PEERS.
///
/// ## The 4-lane public-input contract (pinned)
///
/// The peer-finality claim is 4 BN254 scalar-field lanes, in this exact order:
///
///   [0] chainId  — the peer chain's identifier (EIP-155 chain id for an EVM
///                  peer: 1 = ETH mainnet, 8453 = Base, …). Binds the proof to
///                  ONE chain, so a proof of chain A's finality can never be
///                  recorded as chain B's.
///   [1] height   — the finalized height. For an EVM peer this is the finalized
///                  EXECUTION block number (`FinalizedExecution.execution_block_number`
///                  in `eth-lightclient/src/finality.rs`), the natural anchor for
///                  a state-trie inclusion proof.
///   [2] rootHi   — the TOP 128 bits (big-endian) of the 32-byte finalized state
///                  root R (`execution_state_root`).
///   [3] rootLo   — the BOTTOM 128 bits of R.
///
/// R is split into two 128-bit halves because a full 256-bit keccak/SSZ root can
/// exceed the BN254 scalar field order; each half is < 2^128 < R, so both are
/// canonical scalar-field residues and the pair binds the FULL root with no
/// truncation. `DreggPeerRegistry` reconstructs R = (rootHi << 128) | rootLo.
///
/// The concrete implementation is the STARK->SNARK wrap verifier generated by
/// gnark-solidity-verifier for the peer light-client wrap circuit, wrapped in the
/// bool-returning shape (see `Groth16Verifier25Adapter` for the dregg twin), and
/// SHOULD sit behind the timelocked VK-epoch registry pattern of
/// `DreggGroth16VerifierUpgradeable` so a peer-VK rotation is a two-phase
/// propose/activate, not a redeploy.
interface IPeerLightClientVerifier {
    /// Run the BN254 pairing check for proof (a, b, c) against the 4-lane
    /// peer-finality public-input vector. Word order for `b` matches EIP-197
    /// (imaginary coordinate first). `commitments`/`commitmentPok` are the gnark
    /// commit-based range checker's Pedersen commitment (2 words) + proof of
    /// knowledge (2 words) — part of the proof, not the statement. Returns true
    /// iff the proof verifies.
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[2] calldata commitments,
        uint256[2] calldata commitmentPok,
        uint256[4] calldata publicInputs
    ) external view returns (bool);
}
