/-
# EmitStepWrapChainJson — write the CHAINED wrap rungs as prover-ready JSON.

The wrap-side assembly of `KimchiWrapMain`, with its transcript driven by the phase-1 Fq tape of a
proof of `KimchiStepMain`'s OWN emission (`KimchiStepWrapChainFixture`, generated by
`metatheory/fixtures/pickles-extractors/src/tape.rs` from `pickles_kimchi_marshal`'s step proof —
⚑ THE SAME proof whose forty public words the wrap statement must derive. It used to be written by
`pickles-chain-harness/src/bin/export_step_tape.rs`, a second binary proving a second step proof
with `OsRng`; that binary is DELETED).

Four files, and the last two are the point:

  chain_w1_transcript{,_unwired}.json   the Fq sponge over the step proof's tape
  chain_w4_bind{,_unwired}.json         ...closed onto the wrap statement's public words
  chainbent_w4_bind.json                the SAME assembly with ONE Fq coordinate of the step
                                        proof's `w_comm` bent — its public vector must DIFFER
  chainunread_w4_bind.json              the SAME assembly driven by the tape re-extracted from a
                                        proof whose `z_1`/`z_2`/`ft_eval1`/`delta`/`sg` were bent —
                                        must be BYTE-IDENTICAL to `chain_w4_bind.json`

    cd metatheory
    lake build Dregg2.Circuit.Emit.KimchiStepWrapChain
    lake env lean --run Dregg2/Circuit/Emit/EmitStepWrapChainJson.lean
    cargo run --release --manifest-path fixtures/pickles-chain-harness/Cargo.toml \
      --bin harness -- /tmp/pickles-chain
-/
import Dregg2.Circuit.Emit.KimchiStepWrapChain

open Dregg2.Circuit.Emit.KimchiStepWrapChain
open Dregg2.Circuit.Emit.KimchiWrapMain

/-- Emit one rung of one `WrapData`, both polarities, refusing loudly if `placeChecked` did.

⚑ ONE witness, used for BOTH circuits — the same discipline `EmitWrapMainJson.emitRung` follows.
That is what makes the UNWIRED emission a CONTROL: rows, gate types, coefficients and every witness
cell byte-identical, and the ONLY difference the copy-permutation. Computing a second witness from
the unwired rows would leave the probe cells empty there and the "control" would be a different
circuit. (`KimchiWrapMain.rungJson` recomputes it per polarity, which is why this driver renders
directly rather than calling it for the unwired half.) -/
def emitChainRung (dir pfx : String) (t : WrapData) (k : Rung) (both : Bool) : IO Nat := do
  let rowsW := rungRows t k true
  let rowsU := rungRows t k false
  let p := rungPub t.sh k
  let gs := wrapGates rowsW
  let gu := wrapGates rowsU
  if refusalOf t.sh k p gs != none then
    throw (IO.userError s!"placeChecked REFUSED at {pfx}_{k.tag}: {repr (refusalOf t.sh k p gs)}")
  -- ⚑ **THE §17b CAPS' OBLIGATION, HERE TOO.** This driver emits `.transcript` and `.bind`, both
  -- below the three-block wall, so the check is satisfied by every rung it currently writes — which
  -- is the reason to install it now rather than the reason to skip it: the day a lane adds a rung at
  -- or above `w10_finalize` here, a region escape is a refusal instead of a silently aliased σ class.
  match regionEscape t.sh t.sp k gs with
  | some i =>
    throw (IO.userError s!"⚑ REGION CAP ESCAPED at {pfx}_{k.tag}: a gate references external {i}, \
      outside every block {k.tag} declares {repr (rungRegions t.sh t.sp k)} and not below the wall \
      {baseWh t.sh t.sp}. Refusing rather than emitting it; see `KimchiWrapMainCore` §17b.")
  | none => pure ()
  -- ⚠ ⚑ RUNG-EXPLICIT. These read `wrapWitness t p rowsW` / `wrapPublic t` until 2026-08-04; those
  -- aliases silently denoted `.prev` after W-PREV, so this driver would have written
  -- `"public_input_size": 22` beside a 23-element `"public_input"` and a witness grid from another
  -- rung's environment. The aliases are deleted; see `KimchiStepWrapChain` §9a.
  let wit := wrapWitnessAt t k p rowsW
  let pub := if p == 0 then [] else wrapPublicAt t k
  let probes := rungProbeRows t k
  IO.FS.writeFile s!"{dir}/{pfx}_{k.tag}.json"
    (renderWrapCircuit s!"{pfx}_{k.tag}" p (p + rowsW.length) (placedOf t.sh k p gs) wit pub probes
      (if p == 0 then [] else wrapSlotsAt t.sh k) (if p == 0 then [] else wrapInertOk t.sh k))
  if both then
    IO.FS.writeFile s!"{dir}/{pfx}_{k.tag}_unwired.json"
      (renderWrapCircuit s!"{pfx}_{k.tag}_UNWIRED" p (p + rowsU.length) (placedOf t.sh k p gu) wit
        pub probes (if p == 0 then [] else wrapSlotsAt t.sh k)
        (if p == 0 then [] else wrapInertOk t.sh k))
  IO.println s!"  {pfx}_{k.tag}: {rowsW.length} rows, pub {p}, {probes.length} probes"
  pure rowsW.length

def main : IO Unit := do
  let dir := "/tmp/pickles-chain"
  IO.FS.createDirAll dir
  IO.println "emitting the CHAINED wrap rungs — the transcript is dregg's OWN step proof's tape"
  IO.println s!"  step circuit : {Dregg2.Circuit.Emit.KimchiStepWrapChainFixture.STEP_CIRCUIT}"
  IO.println s!"  shape        : {repr shapeChain}"
  IO.println s!"  tape words   : {chainTape.length}  (schedule {(chainSchedule shapeChain).length} events)"
  IO.println s!"  step key     : branch {tChain.br.idx} of step_keys, index digest \
{keyDigestVal shapeChain chainRun tChain.br.idx}"
  IO.println s!"  tape word 0  : {(chainRun.evs.getD 0 default).word}"
  let _ ← emitChainRung dir "chain" tChain .transcript true
  let _ ← emitChainRung dir "chain" tChain .bind true
  -- ⚑ **THE CLIMB.** `w5_key` was unemittable on this tape until 2026-08-05: `keyRows`' `digestTie`
  -- welded the index sponge's squeeze to the transcript's first absorbed word, and the wrap
  -- circuit committed to MINA's `step-transaction` key while this tape is dregg's own step proof's.
  -- `KEY_CHAIN_BRANCH` puts dregg's step rule in `step_keys` and `chainBranch` selects it, so the
  -- row now has an honest witness — see `the_chain_climbs_past_bind_at_dreggs_own_step_key`.
  let _ ← emitChainRung dir "chain" tChain .key true
  let _ ← emitChainRung dir "chainbent" tChainBent .bind false
  let _ ← emitChainRung dir "chainunread" tChainUnread .bind false
  let _ ← emitChainRung dir "chainbent" tChainBent .key false
  let _ ← emitChainRung dir "chainunread" tChainUnread .key false
  -- ⚑ A LOUD refusal if the two controls collapsed into each other. The harness checks this too,
  -- but a driver that wrote a file it knew was wrong would be the worse failure.
  for k in [Rung.bind, Rung.key] do
    if wrapPublicAt tChainBent k == wrapPublicAt tChain k then
      throw (IO.userError s!"the BENT emission's public vector equals the honest one at {k.tag} \
        - no chain")
    if wrapPublicAt tChainUnread k != wrapPublicAt tChain k then
      throw (IO.userError s!"the UNREAD-bend emission's public vector moved at {k.tag} \
        - the tape is not the input")
  IO.println s!"wrote {dir}/chain_*.json, chainbent_w4_bind.json, chainunread_w4_bind.json"
