/-
# Dregg2.Circuit.Emit.KimchiWrapHackDigest — ⚑ `hash_messages_for_next_wrap_proof`, WHERE BOTH SIDES
CAN SEE IT

⚑ **WHY THIS MODULE EXISTS, AND IT IS THE `whSgOld` LESSON APPLIED ONE LEVEL UP.** Packed statement
words **55** and **56** are `prev_statement.messages_for_next_wrap_proof.(p)`. The WRAP circuit
COMPUTES them (`wrap_main.ml:340-348` — they are not witnessed there), and the STEP circuit
PUBLISHES them (`step_main.ml:364-366` `exists ~request:Req.Messages_for_next_wrap_proof`). **One
object, two circuits.** While the derivation lived only in `KimchiWrapMainField`, the step side had
no way to name it and put a deterministic fixture there instead — so `whRows`' two
`Field.Assert.equal` rows had no satisfying witness on dregg's own step proof, and `w11_wraphack`
sat in the harness's `STATEMENT_BLOCKED` set for exactly that reason.

The namespace is unchanged (`Dregg2.Circuit.Emit.KimchiWrapMain`), so nothing is renamed and no
wrap-side consumer moves; the file boundary exists only so that `KimchiStepMainCore` can import the
DERIVATION rather than transcribe its OUTPUT. Transcribing it is the defect this file exists to
prevent: two literals holding one object is how `RC_SGOLD` moved to dregg's own step proof on
2026-08-05 while `whSgOld` did not, and every pin stayed green.

## ⚠ THE FIXPOINT, AND WHY IT CONVERGES IN ONE PASS

`whPrevDigest p` reads `whOldChals p` (a `wrapFixtureQ` — upstream's `old_bp_chals` carry no `typ` at
all, `wrap_main.ml:226-256`, so a named fixture is the FAITHFUL choice and not a stand-in) and
`whSgOld p` = `KimchiStepWrapChainFixture.STEP_PREVCOMM_XY`. That second one makes the step emitter
depend on a file generated by proving the step circuit — which would be a loop if it moved. It does
not: `STEP_PREVCOMM_XY` is the step proof's `prev_challenges[i].comm`, an ARGUMENT to
`ProverProof::create_recursive` built by `pickles_kimchi_marshal` from its own deterministic
`step_pre` ladder, so it is a fixed constant of the pipeline and is unmoved by re-proving with a
different public input. One edit, one re-prove.

⚠ **AND IT READS NO PACKED STATEMENT WORD** — `KimchiWrapMain.the_wraphack_tape_reads_no_published
_statement_entry` (`…Pins12` §20c) is that as a theorem, over the tape rather than over this
docblock. Slot 11's closing sponge is a different question and is NOT here: `whNewChals` is
`compute_challenges` of the statement's own packed words, so it lives in `…Core` above `liftValQ`.
-/
import Dregg2.Circuit.Emit.PastaField
import Dregg2.Circuit.Emit.PastaPoseidonFq
import Dregg2.Circuit.Emit.KimchiStepWrapChainFixture

namespace Dregg2.Circuit.Emit.KimchiWrapMain

open Dregg2.Circuit.Emit.PastaField (qN)

set_option autoImplicit false

/-- The named filler for the wrap side's fixtures. ⚑ It lives here rather than in
`KimchiWrapMainField` because `whOldChal` needs it and the step side needs `whOldChal`; every wrap
use site is unchanged, since the namespace did not move. -/
def wrapFixtureQ (tag i : Nat) : Nat := (11 + 1000003 * (17 * tag + i)) % qN

/-! ### ⚑ **W-WRAPHACK's VALUE LAYER** (`wrap_hack.ml:99-141`, `wrap_main.ml:340-355,421-431`).

⚑ **THE ABSORPTION ORDER IS THE OPPOSITE OF THE STEP SIDE'S.**
`Messages_for_next_wrap_proof.to_field_elements` (`composition_types.ml:411-418`) is

    Array.concat [ Vector.to_array old_bulletproof_challenges |> Array.concat_map ~f:Vector.to_array
                 ; Array.of_list (g1_to_field_elements challenge_polynomial_commitment) ]

— every old bulletproof challenge FIRST, flattened, and the commitment's `[x; y]` LAST. The step
side interleaves; this one does not.

⚑ **AND THE FRONT PAD IS A PRECOMPUTED SPONGE STATE, NOT AN IN-CIRCUIT ABSORB.** `pad_vector`
(`wrap_hack.ml:26-28`) is `Vector.extend_front_exn v Padded_length.n dummy` — the padding goes at
the FRONT, which is exactly why upstream can precompute it: `Checked
.hash_messages_for_next_wrap_proof` (`wrap_hack.ml:110-137`) does NOT pad `t` at all. It opens the
sponge at `dummy_messages_for_next_wrap_proof_sponge_states.(2 − max_proofs_verified)`, the state a
fresh sponge reaches after absorbing that many DUMMY challenge vectors, injected as
`Impls.Wrap.Field.constant`. -/

/-- `Backend.Tock.Rounds.n` — one `old_bulletproof_challenges` vector's length (`wrap_main.ml:230`,
`composition_types.ml:1358`). ⚠ **Tock's 15, not Tick's 16**; `ipaRounds` is the other one. -/
def WH_ROUNDS : Nat := 15

/-- `Wrap_hack.Padded_length = Nat.N2` (`wrap_hack.ml:24`) — the length every accumulator is padded
UP TO, at the front. -/
def WH_PADDED : Nat := 2

/-- ⚑ How many DUMMY challenge vectors the precomputed opening state stands for
(`wrap_hack.ml:124-130`): `2 − max_proofs_verified`. -/
def whPadVectors (mlmb : Nat) : Nat := WH_PADDED - mlmb

/-- ⚑ **`max_local_max_proofs_verified` AT THE COMMITTED SHAPE, AND IT IS A SHAPE CHOICE THAT IS
SAID RATHER THAN BANKED.** `Max_widths_by_slot.maxes` (`wrap_main.ml:130-133`) is a per-slot
constant of the compiled instance; this assembly fixes it at `WH_PADDED` for every slot, which is
also what `Max_proofs_verified.n = 2` gives the closing hash at `wrap_main.ml:423`. So
`whPadVectors WH_MLMB = 0` in all three sponges and the front pad is the FRESH state — the one the
wrap file can pin to zero out of its own `Sponge.create` rows.

⚠ **THE OTHER CASE IS NOT EMITTED AND THE REASON IS NOT "LATER".** At `mlmb < 2` the opening state
is the sponge state after absorbing `Dummy.Ipa.Wrap.challenges_computed`, and those values are
`Ipa.Wrap.compute_challenge` of `Ro.scalar_chal ()` (`dummy.ml:30-35`) — an OCaml random-oracle draw
this tree has no independent source for. Emitting it would mean a FIXTURE constant standing in for a
derived sponge state, which is defect class 5 in a new place and inside the pad specifically. A
shape choice that avoids inventing a constant is the honest one; `whPadVectors` is here so the
general statement is in the file rather than the instance. -/
def WH_MLMB : Nat := 2

/-- The absorbed elements of ONE `hash_messages_for_next_wrap_proof`, in
`to_field_elements` order. -/
def whTape (chals : List Nat) (g : Nat × Nat) : List Nat := chals ++ [g.1, g.2]

/-- `Tock_field_sponge.digest` in circuit — `Sponge.squeeze_field` of an Fq sponge over the tape
(`wrap_hack.ml:131-137`). ⚑ `newSponge` IS the `whPadVectors WH_MLMB = 0` opening state. -/
def whDigestOf (chals : List Nat) (g : Nat × Nat) : Nat :=
  (Dregg2.Circuit.Emit.PastaPoseidonFq.squeeze1 Dregg2.Circuit.Emit.PastaPoseidonFq.fqParams
      (Dregg2.Circuit.Emit.PastaPoseidonFq.absorbMany Dregg2.Circuit.Emit.PastaPoseidonFq.fqParams
        Dregg2.Circuit.Emit.PastaPoseidonFq.newSponge (whTape chals g))).2

/-- `old_bp_chals.(p)` flattened — `Vector.typ (Vector.typ Field.typ Tock.Rounds.n)` with NO check
of any kind (`wrap_main.ml:226-256`), so a free witness upstream and a NAMED FIXTURE here. -/
def whOldChal (p k : Nat) : Nat := wrapFixtureQ 41 (WH_PADDED * WH_ROUNDS * p + k)
def whOldChals (p : Nat) : List Nat := (List.range (WH_MLMB * WH_ROUNDS)).map (whOldChal p)

/-- `prev_step_accs.(p)` — ⚑ the TRANSCRIPT's own `sg_old` coordinates, not a second copy of them.
This mirrors `KimchiWrapMain.itemVal T_SGOLD` exactly, including its fallback, so §21's tie row
joins two cells that already hold one value.

⚠ ⚑ **AND "MIRRORS" WAS ONE EDIT AWAY FROM FALSE, WHICH IS WHY IT NOW READS THE SAME LIST.** This
def used to name `PastaPoseidonFq.PREVCOMM_XY` and `itemVal T_SGOLD` used to name it too, so the
sentence above was true by coincidence of two literals. On 2026-08-05 `RC_SGOLD` moved to the step
proof this pipeline is actually about and this one did not — instantly making the emitted §21 rows
(which read the TRANSCRIPT cells, `absPtVal t.sp T_SGOLD p`) hash a different `sg_old` from the one
`prevWordVal` packs into statement words 55/56 and the x_hat MSM consumes.
`wraphack_digest_is_the_emitted_squeeze` is the pin that would have gone red for it. Two defs holding
one object is the defect; both now resolve through
`KimchiStepWrapChainFixture.STEP_PREVCOMM_XY`. -/
def whSgOld (p : Nat) : Nat × Nat :=
  ((Dregg2.Circuit.Emit.KimchiStepWrapChainFixture.STEP_PREVCOMM_XY).getD (2 * p)
      (wrapFixtureQ 1 (2 * p)),
   (Dregg2.Circuit.Emit.KimchiStepWrapChainFixture.STEP_PREVCOMM_XY).getD (2 * p + 1)
      (wrapFixtureQ 1 (2 * p + 1)))

/-- ⚑ **PACKED STATEMENT WORD `55 + p`** — `prev_statement.messages_for_next_wrap_proof.(p)`.

⚑ **AND SINCE 2026-08-06 THE STEP CIRCUIT PUBLISHES THIS VALUE**, which is the whole reason this
module exists. `KimchiStepMainCore.stmtWrapMsgVal` is one application of it, so the two circuits
hold ONE number by construction rather than by a coincidence of two fixtures. -/
def whPrevDigest (p : Nat) : Nat := whDigestOf (whOldChals p) (whSgOld p)

end Dregg2.Circuit.Emit.KimchiWrapMain
