/-
# Dregg2.Circuit.Emit.KimchiWrapHackDigest — ⚑ `hash_messages_for_next_wrap_proof`, WHERE BOTH SIDES
CAN SEE IT

⚑ **WHY THIS MODULE EXISTS, AND IT IS THE `whSgOld` LESSON APPLIED ONE LEVEL UP.** Packed statement
words **55** and **56** are `prev_statement.messages_for_next_wrap_proof.(p)`. The WRAP circuit
COMPUTES them (`wrap_main.ml:340-348` — they are not witnessed there), and the STEP circuit
PUBLISHES them (`step_main.ml:364-366` `exists ~request:Req.Messages_for_next_wrap_proof`). **One
object, two circuits.** While the derivation lived only in `KimchiWrapMainField`, the step side had
no way to name it and put a deterministic fixture there instead — so `whRows`' two
`Field.Assert.equal` rows had no satisfying witness on dregg's own step proof, and `w11_wraphack`
sat in the harness's `STATEMENT_BLOCKED` set for exactly that reason.

The namespace is unchanged (`Dregg2.Circuit.Emit.KimchiWrapMain`), so nothing is renamed and no
wrap-side consumer moves; the file boundary exists only so that `KimchiStepMainCore` can import the
DERIVATION rather than transcribe its OUTPUT. Transcribing it is the defect this file exists to
prevent: two literals holding one object is how `RC_SGOLD` moved to dregg's own step proof on
2026-08-05 while `whSgOld` did not, and every pin stayed green.

## ⚠ THE FIXPOINT, AND WHY IT CONVERGES IN ONE PASS

`whPrevDigest p` reads `whRecordAt WH_REAL_SLOTS` — the record `step.rs:2764-2772` and
`wrap.rs:476-491` build from the two sides. Its REAL slots read `whRealChals` (⚑ **Mina devnet block
539508's own carried IPA challenges since 2026-08-07** — it was a `wrapFixtureQ`, which is the honest
shape for an upstream `exists` carrying no `typ` at all, `wrap_main.ml:226-256`) and `whRealSgs` =
`KimchiStepWrapChainFixture.STEP_PREVCOMM_XY`; its PAD slots read `whPadChals` / `whPadSg`, openmina's
own `dummy_padding()` and `dummy_ipa_step_sg()`.

The `STEP_PREVCOMM_XY` leg makes the step emitter depend on a file generated by proving the step
circuit — which would be a loop if it moved. It does not: `STEP_PREVCOMM_XY` is the step proof's
`prev_challenges[i].comm`, an ARGUMENT to `ProverProof::create_recursive` built by
`pickles_kimchi_marshal` from its own deterministic `step_pre` ladder, so it is a fixed constant of
the pipeline and is unmoved by re-proving with a different public input. One edit, one re-prove.

⚑⚑ **AND THE PAD LEG IS THE ONE THAT CLOSED ON 2026-08-07.** `whPrevDigest` computed BOTH words as a
hash over a slot of `STEP_PREVCOMM_XY` — two real previous proofs — with a `getD … (wrapFixtureQ 1 …)`
fallback, so when `marshal::STEP_RECURSION_SLOTS` went to **1** and the list went from four
coordinates to two, slot 1 did not refuse: it hashed an invented field element into packed statement
word 56. `the_wrap_record_refuses_a_short_prevcomm` is the refusal that replaced the fallback, and
`the_pad_slot_derives_minas_own_padding_digest` is the pad DERIVED rather than transcribed.

⚠ **AND IT READS NO PACKED STATEMENT WORD** — `KimchiWrapMain.the_wraphack_tape_reads_no_published
_statement_entry` (`…Pins12` §20c) is that as a theorem, over the tape rather than over this
docblock. Slot 11's closing sponge is a different question and is NOT here: `whNewChals` is
`compute_challenges` of the statement's own packed words, so it lives in `…Core` above `liftValQ`.
-/
import Dregg2.Tactics
import Dregg2.Circuit.Emit.PastaField
import Dregg2.Circuit.Emit.PastaPoseidonFq
import Dregg2.Circuit.Emit.KimchiStepWrapChainFixture
import Dregg2.Circuit.Emit.MinaRealBlockTranscript
import Dregg2.Circuit.Emit.MinaWrapHackDummySg

namespace Dregg2.Circuit.Emit.KimchiWrapMain

open Dregg2.Circuit.Emit.PastaField (qN)

set_option autoImplicit false

/-- The named filler for the wrap side's fixtures. ⚑ It lives here rather than in
`KimchiWrapMainField` because `whOldChal` needs it and the step side needs `whOldChal`; every wrap
use site is unchanged, since the namespace did not move. -/
def wrapFixtureQ (tag i : Nat) : Nat := (11 + 1000003 * (17 * tag + i)) % qN

/-! ### ⚑ **W-WRAPHACK's VALUE LAYER** (`wrap_hack.ml:99-141`, `wrap_main.ml:340-355,421-431`).

⚑ **THE ABSORPTION ORDER IS THE OPPOSITE OF THE STEP SIDE'S.**
`Messages_for_next_wrap_proof.to_field_elements` (`composition_types.ml:411-418`) is

    Array.concat [ Vector.to_array old_bulletproof_challenges |> Array.concat_map ~f:Vector.to_array
                 ; Array.of_list (g1_to_field_elements challenge_polynomial_commitment) ]

— every old bulletproof challenge FIRST, flattened, and the commitment's `[x; y]` LAST. The step
side interleaves; this one does not.

⚑ **AND THE FRONT PAD IS A PRECOMPUTED SPONGE STATE, NOT AN IN-CIRCUIT ABSORB.** `pad_vector`
(`wrap_hack.ml:26-28`) is `Vector.extend_front_exn v Padded_length.n dummy` — the padding goes at
the FRONT, which is exactly why upstream can precompute it: `Checked
.hash_messages_for_next_wrap_proof` (`wrap_hack.ml:110-137`) does NOT pad `t` at all. It opens the
sponge at `dummy_messages_for_next_wrap_proof_sponge_states.(2 − max_proofs_verified)`, the state a
fresh sponge reaches after absorbing that many DUMMY challenge vectors, injected as
`Impls.Wrap.Field.constant`. -/

/-- `Backend.Tock.Rounds.n` — one `old_bulletproof_challenges` vector's length (`wrap_main.ml:230`,
`composition_types.ml:1358`). ⚠ **Tock's 15, not Tick's 16**; `ipaRounds` is the other one. -/
def WH_ROUNDS : Nat := 15

/-- `Wrap_hack.Padded_length = Nat.N2` (`wrap_hack.ml:24`) — the length every accumulator is padded
UP TO, at the front. -/
def WH_PADDED : Nat := 2

/-- ⚑ How many DUMMY challenge vectors the precomputed opening state stands for
(`wrap_hack.ml:124-130`): `2 − max_proofs_verified`. -/
def whPadVectors (mlmb : Nat) : Nat := WH_PADDED - mlmb

/-- ⚑ **`max_local_max_proofs_verified` AT THE COMMITTED SHAPE, AND IT IS A SHAPE CHOICE THAT IS
SAID RATHER THAN BANKED.** `Max_widths_by_slot.maxes` (`wrap_main.ml:130-133`) is a per-slot
constant of the compiled instance; this assembly fixes it at `WH_PADDED` for every slot, which is
also what `Max_proofs_verified.n = 2` gives the closing hash at `wrap_main.ml:423`. So
`whPadVectors WH_MLMB = 0` in all three sponges and the front pad is the FRESH state — the one the
wrap file can pin to zero out of its own `Sponge.create` rows.

⚠ ⚑ **THE OTHER CASE IS NOT EMITTED, AND THE REASON THIS DOCBLOCK GAVE FOR IT WAS FALSE.** It read:
*"At `mlmb < 2` the opening state is the sponge state after absorbing
`Dummy.Ipa.Wrap.challenges_computed`, and those values are `Ipa.Wrap.compute_challenge` of
`Ro.scalar_chal ()` (`dummy.ml:30-35`) — an OCaml random-oracle draw **this tree has no independent
source for**."* There is a source and it was two directories away: openmina carries the fifteen as
literals in `MessagesForNextWrapProof::dummy_padding()` (`public_input/messages.rs:114-134`), and
`MinaWrapHackDummySg.DUMMY_PAD_CHALS` is that export. The `mlmb < 2` opening state is not emitted
because **no slot of this assembly needs it** — `whPadVectors WH_MLMB = 0` at both committed shapes
— and not because the constant could not be had. A cost estimate that hardened into a constraint;
the note is kept because that is the shape of the error, not because the conclusion moved. -/
def WH_MLMB : Nat := 2

/-- The absorbed elements of ONE `hash_messages_for_next_wrap_proof`, in
`to_field_elements` order. -/
def whTape (chals : List Nat) (g : Nat × Nat) : List Nat := chals ++ [g.1, g.2]

/-- `Tock_field_sponge.digest` in circuit — `Sponge.squeeze_field` of an Fq sponge over the tape
(`wrap_hack.ml:131-137`). ⚑ `newSponge` IS the `whPadVectors WH_MLMB = 0` opening state. -/
def whDigestOf (chals : List Nat) (g : Nat × Nat) : Nat :=
  (Dregg2.Circuit.Emit.PastaPoseidonFq.squeeze1 Dregg2.Circuit.Emit.PastaPoseidonFq.fqParams
      (Dregg2.Circuit.Emit.PastaPoseidonFq.absorbMany Dregg2.Circuit.Emit.PastaPoseidonFq.fqParams
        Dregg2.Circuit.Emit.PastaPoseidonFq.newSponge (whTape chals g))).2

/-- `old_bp_chals.(p)` flattened — `Vector.typ (Vector.typ Field.typ Tock.Rounds.n)` with NO check
of any kind (`wrap_main.ml:226-256`), so a free witness upstream.

⚑⚑ **AND SINCE 2026-08-07 IT IS MINA DEVNET BLOCK 539508's OWN CARRIED CHALLENGES, NOT A MIXER —
AND THAT IS A MEASUREMENT, NOT A PREFERENCE.** The step assembly's own transcript IS that block's
Wrap proof: `KimchiWrapMain.the_live_block_declares_itself_minas_own_wrap_proof` measures the live
per-proof block's packed digest, β, γ, α′ and ζ′ equal to `MinaRealBlockTranscript.FQ_DIGEST`,
`BETA_N`, `GAMMA_N`, `ALPHA_CHAL`, `ZETA_CHAL` to the digit, and §19c's evaluation columns are the
same proof's `es`. A proof that declares itself that block must carry that block's
`old_bulletproof_challenges`, and `MinaRealBlockTranscript.CHALS_FLAT` — `CHALS0 ++ CHALS1`, by
`chals_flat_is_the_carried_challenges` — is exactly the `WH_MLMB * WH_ROUNDS` of them.

⚑ **WHAT THIS BUYS, AND IT IS A REFEREE OUTSIDE THE LOOP.** `KimchiWrapMainCore`'s `finChalSponge`
reads this list, and its squeeze is tape slot 1 of `finalize_other_proof`'s 91-element sponge. Driven
on a mixer that slot could only ever agree with itself; driven on these it reproduces
`MinaRealBlockTranscript.PREV_CHAL_DIGEST` — the value kimchi's own verifier computed for that block
(`verifier.rs:290-299`) — which is what `KimchiWrapFinalizeSpongeGate
.finalize_sponge_reproduces_the_accepted_block` has been able to say about the *machine* since
2026-08-05 and could not say about the *emission*.

⚠ **THE `p` IS GONE FROM THE VALUE, exactly as it went from `finColVal`.** There is ONE real Wrap
proof in this tree, and every REAL slot of the record reads it. The PAD slot does not read it at all
— see `whPadChals`. -/
def whRealChals : List Nat := Dregg2.Circuit.Emit.MinaRealBlockTranscript.CHALS_FLAT

/-- ⚑⚑ **THE PAD SLOT'S CHALLENGE VECTORS — `[Dummy.Ipa.Wrap.challenges_computed; 2]`.**

`wrap.rs:484-485` builds the padded entry with `old_bulletproof_challenges: vec![
MessagesForNextWrapProof::dummy_padding(); 2]`, and `messages.rs:89-98`'s `to_fields` would pad an
empty vector to the same two. So the pad's tape is these thirty followed by `whPadSg`'s two
coordinates — thirty-two elements, the same width every real slot has. -/
def whPadChals : List Nat :=
  Dregg2.Circuit.Emit.MinaWrapHackDummySg.DUMMY_PAD_CHALS
  ++ Dregg2.Circuit.Emit.MinaWrapHackDummySg.DUMMY_PAD_CHALS

/-- ⚑ **THE PAD SLOT'S COMMITMENT — `Dummy.Ipa.STEP.sg`, and the OTHER dummy is a different
record's.** `wrap.rs:484` is `challenge_polynomial_commitment: InnerCurve::from(dummy_ipa_step_sg())`.
`dummy_ipa_wrap_sg()` pads `messages_for_next_step_proof.challenge_polynomial_commitments` at
`wrap.rs:736` instead, and swapping them is a digest that agrees with nothing. -/
def whPadSg : Nat × Nat := Dregg2.Circuit.Emit.MinaWrapHackDummySg.DUMMY_STEP_SG

/-- ⚑ `prev_step_accs`' REAL entries, paired off `STEP_PREVCOMM_XY`.

⚠ ⚑ **AND THE PAIRING IS WHERE THE OLD `getD` FALLBACK LIVED.** `whSgOld` used to read
`STEP_PREVCOMM_XY.getD (2*p) (wrapFixtureQ 1 (2*p))`, so a list carrying fewer points than the
record has slots did not refuse — it hashed an INVENTED field element into packed statement word
`55 + p` and every downstream pin agreed with it, because both sides of every tie read the same
invented number. That is exactly what happened when `marshal::STEP_RECURSION_SLOTS` went to 1:
`STEP_PREVCOMM_XY` went from four coordinates to two, slot 1 fell through, and
`the_published_statement_carries_every_derived_word_but_the_arity_mismatched_one` went red on a
digest of a filler. The pairing below drops an unpaired tail instead of inventing one, and
`the_wrap_record_refuses_a_short_prevcomm` is the REFUSAL: it is closed by `decide` in this module,
so a `STEP_PREVCOMM_XY` of the wrong length does not produce a wrong digest, it produces a module
that does not elaborate and consumers that do not load. -/
def whPairs : List Nat → List (Nat × Nat)
  | x :: y :: rest => (x, y) :: whPairs rest
  | _ => []

def whRealSgs : List (Nat × Nat) :=
  whPairs Dregg2.Circuit.Emit.KimchiStepWrapChainFixture.STEP_PREVCOMM_XY

/-- ⚑⚑ **`actual_proofs_verified` — HOW MANY OF THE RECORD'S `WH_PADDED` SLOTS ARE REAL.**

`wrap.rs:666` reads it off the step record; `marshal::STEP_RECURSION_SLOTS` and
`gates::STEP_RULE_N_PREVIOUS` are the same number from the two Rust sides. Dregg's step rule
assembles ONE `verify_one`.

⚠ **IT IS NOT `WH_PADDED` AND IT IS NOT `KimchiWrapMainCore.MAX_PROOFS_VERIFIED`.** One name served
all three until 2026-08-07, and they agreed only while dregg's step proof was padded where upstream
is not. -/
def WH_REAL_SLOTS : Nat := 1

/-- `n_padding = 2 - expanded_proofs.len()` (`step.rs:2765`). -/
def whNPad (nReal : Nat) : Nat := WH_PADDED - nReal

/-- ⚑⚑⚑ **THE WRAP RECORD, WHOLE — `[pad …; real …]`, `step.rs:2764-2772` AND `wrap.rs:476-491`
SAYING THE SAME THING FROM THE TWO SIDES.**

The step prover builds `messages_for_next_wrap_proof_padded : [Fp; 2]` by putting `n_padding` copies
of `messages_for_next_wrap_proof_padding()` at the FRONT; the wrap prover builds the same list as
whole `MessagesForNextWrapProof` records via `pad_messages_for_next_wrap_proof` and HASHES each in
circuit (`wrap.rs:2919-2932`). So one object, two circuits, and the pad slot is a SPONGE on both
sides rather than a literal on either.

⚠ **THE OLD SHAPE MODELLED TWO REAL PREVIOUS PROOFS AND HAD NO PAD AT ALL.** `whPrevDigest p` was
`whDigestOf (whOldChals p) (whSgOld p)` for both `p`, which is right only when
`actual_proofs_verified = WH_PADDED`. -/
def whRecordAt (nReal : Nat) : List (List Nat × (Nat × Nat)) :=
  List.replicate (whNPad nReal) (whPadChals, whPadSg)
  ++ (whRealSgs.take nReal).map (fun g => (whRealChals, g))

/-- ⚑ **PACKED STATEMENT WORD `55 + p`** — `prev_statement.messages_for_next_wrap_proof.(p)`.

⚑ **AND SINCE 2026-08-06 THE STEP CIRCUIT PUBLISHES THIS VALUE**, which is the whole reason this
module exists. `KimchiStepMainCore.stmtWrapMsgVal` is one application of it, so the two circuits
hold ONE number by construction rather than by a coincidence of two fixtures.

⚠ **THE `0` OUTSIDE THE RECORD IS NOT A FALLBACK IN THE OLD SENSE.** The record has exactly
`WH_PADDED` slots (`the_wrap_record_refuses_a_short_prevcomm`), so `p ≥ WH_PADDED` is outside the
object rather than a short read of it, and `0` is a value no slot can hold — `whDigestOf` is a
Poseidon squeeze and `wraphack_digest_bends_at_every_probed_input` exhibits both slots as nonzero.
What the old `getD` did was different in kind: it manufactured a PLAUSIBLE digest out of invented
field elements at an index the record was supposed to have. -/
def whPrevDigestAt (nReal p : Nat) : Nat :=
  ((whRecordAt nReal).map (fun e => whDigestOf e.1 e.2)).getD p 0

def whPrevDigest (p : Nat) : Nat := whPrevDigestAt WH_REAL_SLOTS p

/-- ⚑ Record slot `p`'s absorbed challenge vector. **`KimchiWrapMainCore` reads the record through
this rather than keeping its own copy**, which is the whole reason this module was split out of
`KimchiWrapMainField`: two defs holding one object is how `RC_SGOLD` moved to dregg's own step proof
and `whSgOld` did not, with every pin staying green.

⚠ **IT IS `whNPad`-SHAPED AND NOT AN INDEX INTO `whRecordAt`.** `whRecordAt` is the REAL pipeline's
record, whose real slots read `whRealSgs` and are therefore `WH_REAL_SLOTS` long; a shape whose
`prevs` exceeds that (`shapeSmoke.prevs = 2`) would index past its end and silently take the default.
The challenge vector at a slot does not need the commitment list at all, so it does not consult it. -/
def whSlotChals (nReal p : Nat) : List Nat :=
  if p < whNPad nReal then whPadChals else whRealChals

/-- ⚑ …and slot `p`'s commitment, off the record itself. ⚠ `KimchiWrapMainCore.whSlotSgAt` is the
one the EMITTED sponge uses, and it reads the TRANSCRIPT's cell at the real slots rather than this
list — so the two are joined by a tie row rather than by being one def, exactly as `sgOldVar` is. -/
def whSlotSg (nReal p : Nat) : Nat × Nat :=
  ((whRecordAt nReal).getD p (whPadChals, whPadSg)).2

/-- ⚑ **A REAL PREVIOUS PROOF'S `old_bulletproof_challenges`, WHICH IS A DIFFERENT OBJECT FROM
`whSlotChals` AND WAS THE SAME ONE UNTIL 2026-08-07.**

`finalize_other_proof` (`wrap_main.ml:258-338`) absorbs the challenges the previous proof CARRIES —
always the real block's, never a pad's, because the padded slot has no proof to finalize.
`whSlotChals` is the WRAP RECORD's slot `p`, which is the dummy vector when `p` is a padded slot.
They coincided while `actual_proofs_verified = WH_PADDED`, and `KimchiWrapMainCore.finChalSponge`
reading the record's slot rather than the block's vector is how the pad would have leaked into
`KimchiWrapFinalizeSpongeGate.finalize_sponge_reproduces_the_accepted_block`.

⚠ The `p` was already gone from the value before this split — there is ONE real Wrap proof in this
tree and both per-proof blocks read it; the argument is kept so the call sites still say which
instance they are about. -/
def whOldChal (_p k : Nat) : Nat := whRealChals.getD k 0
def whOldChals (_p : Nat) : List Nat := whRealChals

/-- ⚑⚑⚑ **THE REFUSAL THAT REPLACED THE FALLBACK.**

Every length the record's construction depends on, asserted where a short list would otherwise be
absorbed silently. Closed by `decide` in this module, so a `STEP_PREVCOMM_XY` that carries fewer
points than `WH_REAL_SLOTS` — or a `CHALS_FLAT` that is not `WH_MLMB · WH_ROUNDS` long, or a
`DUMMY_PAD_CHALS` that is not `WH_ROUNDS` long — makes **this file fail to elaborate**, and with it
`KimchiWrapMainField`, `KimchiWrapMainCore` and `KimchiStepMainCore`. That is what "refuses" means
here: not a louder default, a build that does not produce an artifact.

⚠ The last conjunct is the anti-vacuity: the record really does carry a pad and a real slot, i.e.
`whNPad WH_REAL_SLOTS = 1`, so this is a statement about `[pad, real]` and not about a degenerate
`[real, real]` that would satisfy every length above. -/
theorem the_wrap_record_refuses_a_short_prevcomm :
    Dregg2.Circuit.Emit.KimchiStepWrapChainFixture.STEP_PREVCOMM_XY.length = 2 * WH_REAL_SLOTS
  ∧ whRealSgs.length = WH_REAL_SLOTS
  ∧ whRealChals.length = WH_MLMB * WH_ROUNDS
  ∧ whPadChals.length = WH_MLMB * WH_ROUNDS
  ∧ Dregg2.Circuit.Emit.MinaWrapHackDummySg.DUMMY_PAD_CHALS.length = WH_ROUNDS
  ∧ (whRecordAt WH_REAL_SLOTS).length = WH_PADDED
  ∧ (whRecordAt WH_REAL_SLOTS).all (fun e => e.1.length == WH_MLMB * WH_ROUNDS) = true
  ∧ whNPad WH_REAL_SLOTS = 1 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- ⚑⚑⚑ **THE PAD SLOT IS A DERIVATION OF openmina's OWN CONSTANT, NOT A TRANSCRIPTION OF IT.**

`whPrevDigest 0` is this file's Fq sponge over `whPadChals ++ [whPadSg.1, whPadSg.2]` — thirty-two
elements openmina publishes as `dummy_padding()` and `dummy_ipa_step_sg()` — and the value it
squeezes is `messages_for_next_wrap_proof_padding()` **to the digit**, a number
`transaction.rs:3691-3700` computed with `poseidon::hash::hash_fields` and this tree did not write.

⚑ **SO THE PAD IS THE SECOND INDEPENDENT CHECK THAT OUR `hash_messages_for_next_wrap_proof` IS
MINA'S**, on a preimage with no overlap with the first: `wraphack_closing_sponge_reproduces_minas
_slot_eleven` drives the same sponge on the step proof's own commitment and thirty measured
prechallenges. Two disjoint preimages, one squeeze function, both agreeing with openmina.

⚠ **THE RED CONTROLS ARE WHY THIS IS NOT A NUMBER AGREEING WITH A NUMBER.** The commitment is the
STEP dummy and not the WRAP dummy — swap them and it breaks; the pad carries TWO copies of the
fifteen and not one — halve it and it breaks; and bending a single challenge breaks it. The first
control is the one worth having: `DUMMY_WRAP_SG` is the point this file named for the pad until
2026-08-07, and it is exhibited here as wrong rather than quietly replaced. -/
theorem the_pad_slot_derives_minas_own_padding_digest :
    whPrevDigest 0 = Dregg2.Circuit.Emit.MinaWrapHackDummySg.NEXT_WRAP_PROOF_PADDING
  -- ⚠ …the WRAP dummy is not the STEP dummy, and this is the swap that used to be in the file.
  ∧ whDigestOf whPadChals Dregg2.Circuit.Emit.MinaWrapHackDummySg.DUMMY_WRAP_SG
      ≠ Dregg2.Circuit.Emit.MinaWrapHackDummySg.NEXT_WRAP_PROOF_PADDING
  -- ⚠ …the pad carries TWO copies of the fifteen, not one.
  ∧ whDigestOf Dregg2.Circuit.Emit.MinaWrapHackDummySg.DUMMY_PAD_CHALS whPadSg
      ≠ Dregg2.Circuit.Emit.MinaWrapHackDummySg.NEXT_WRAP_PROOF_PADDING
  -- ⚠ …and one bent challenge moves it.
  ∧ whDigestOf (whPadChals.set 0 1) whPadSg
      ≠ Dregg2.Circuit.Emit.MinaWrapHackDummySg.NEXT_WRAP_PROOF_PADDING
  -- ⚑ …and slot 1 is the REAL one, which is a different number: `[pad, real]`, not `[pad, pad]`.
  ∧ whPrevDigest 1 = whDigestOf whRealChals (whRealSgs.getD 0 whPadSg)
  ∧ whPrevDigest 0 ≠ whPrevDigest 1
  -- ⚠ …and the digest fits the field it is PUBLISHED in. These are Fq squeezes and a step statement
  -- word is Fp, with `q > p`, so an `Fp::from_str` would reduce silently.
  ∧ decide (whPrevDigest 0 < Dregg2.Circuit.Emit.PastaField.pN) = true
  ∧ decide (whPrevDigest 1 < Dregg2.Circuit.Emit.PastaField.pN) = true := by
  native_decide

#assert_compiled the_pad_slot_derives_minas_own_padding_digest

end Dregg2.Circuit.Emit.KimchiWrapMain
