/-
# MinaWrapHackDummySg — ⚑ THE WRAP RECORD'S PADDED SLOT, PREIMAGE AND DIGEST.

⚑ GENERATED by `pickles-extractors/src/bin/wrap_hack_dummy_sg.rs` out of openmina's own
`dummy_ipa_wrap_sg()`, `dummy_ipa_step_sg()`, `MessagesForNextWrapProof::dummy_padding()`
and `messages_for_next_wrap_proof_padding()`. Do not hand-edit.

⚠ **TWO RECORDS, TWO DUMMY POINTS, AND THEY ARE NOT INTERCHANGEABLE.**
`wrap.rs:729-737` pads `messages_for_next_step_proof.challenge_polynomial_commitments` — the
ACCUMULATOR list — by inserting `Dummy.Ipa.Wrap.sg` at index 0. `wrap.rs:476-491` pads
`messages_for_next_wrap_proof` — the record packed statement words 55/56 carry — by
inserting a whole `MessagesForNextWrapProof` whose commitment is `Dummy.Ipa.STEP.sg` and
whose challenge vectors are two copies of `Dummy.Ipa.Wrap.challenges_computed`. Both pads
are PREPENDS, so on a rule whose `actual_proofs_verified` is 1 both lists are
`[dummy, real]` and NOT `[real, dummy]`.

⚑ **THE PAD SLOT IS A DERIVATION, NOT A CONSTANT THIS TREE IS TOLD.** `wrap.rs:2919-2932`
hashes every slot of the PADDED record in circuit, so the wrap circuit computes the pad's
digest out of the preimage below. `NEXT_WRAP_PROOF_PADDING` is here as the ORACLE that
derivation is checked against — `KimchiWrapMain.the_pad_slot_derives_minas_own_padding
_digest` — and not as the value the assembly emits.

⚠ WHAT THIS RETIRED: `KimchiWrapHackDigest.whSgOld`'s `getD … (wrapFixtureQ 1 …)`
fallback, which turned a too-short `STEP_PREVCOMM_XY` into a hashed filler instead of a
refusal.
-/
namespace Dregg2.Circuit.Emit.MinaWrapHackDummySg

/-- `Dummy.Ipa.Wrap.sg`'s affine `x` — the ACCUMULATOR list's pad (`wrap.rs:736`). ⚠ NOT
the wrap record's; see `DUMMY_STEP_SG`. -/
def DUMMY_WRAP_SG_X : Nat := 8063668238751197448664615329057427953229339439010717262869116690340613895496

/-- …and its `y`. -/
def DUMMY_WRAP_SG_Y : Nat := 2694491010813221541025626495812026140144933943906714931997499229912601205355

/-- …as a point. -/
def DUMMY_WRAP_SG : Nat × Nat := (DUMMY_WRAP_SG_X, DUMMY_WRAP_SG_Y)

/-- ⚑ `Dummy.Ipa.Step.sg`'s affine `x` — the WRAP RECORD's pad commitment
(`wrap.rs:484`), i.e. `prev_step_accs.(0)` on a one-`verify_one` rule. -/
def DUMMY_STEP_SG_X : Nat := 7157847628472818669877981787153253278122158060570991904823379281596325861730

/-- …and its `y`. -/
def DUMMY_STEP_SG_Y : Nat := 9959746677904483136261451107528553963316638248277760417056251351537540061100

/-- …as a point. -/
def DUMMY_STEP_SG : Nat × Nat := (DUMMY_STEP_SG_X, DUMMY_STEP_SG_Y)

/-- ⚑ **`Dummy.Ipa.Wrap.challenges_computed`** (`wrap_hack.ml:37`,
`messages.rs:114-134`) — ONE `Tock.Rounds.n = 15` vector. The pad carries TWO copies.

⚠ These are `Ipa.Wrap.compute_challenge` of `Ro.scalar_chal ()`, i.e. an OCaml
random-oracle draw. `KimchiWrapHackDigest.WH_MLMB` used to call that "a value this tree
has no independent source for" and declined to emit the `mlmb < 2` opening state because
of it. openmina carries them as literals; this is that source. -/
def DUMMY_PAD_CHALS : List Nat :=
  [ 7048930911355605315581096707847688535149125545610393399193999502037687877674
  , 5945064094191074331354717685811267396540107129706976521474145740173204364019
  , 20315491820009986698838977727629973056499886675589920515484193128018854963801
  , 375929229548289966749422550601268097380795636681684498450629863247980915833
  , 19682218496321100578766622300447982536359891434050417209656101638029891689955
  , 516598185966802396400068849903674663130928531697254466925429658676832606723
  , 23729760760563685146228624125180554011222918208600079938584869191222807389336
  , 11155777282048225577422475738306432747575091690354122761439079853293714987855
  , 24977767586983413450834833875715786066408803952857478894197349635213480783870
  , 2813347787496113574506936084777563965225649411532015639663405402448028142689
  , 22626141769059119580550800305467929090916842064220293932303261732461616709448
  , 18748107085456859495495117012311103043200881556220793307463332157672741458218
  , 22196219950929618042921320796106738233125483954115679355597636800196070731081
  , 13054421325261400802177761929986025883530654947859503505174678618288142017333
  , 4799483385651443229337780097631636300491234601736019220096005875687579936102
  ]

/-- ⚑⚑⚑ **`Dummy.Ipa.Wrap.challenges` — THE PRECHALLENGE FORM, AND THE ONE A PACKED
STATEMENT WORD CAN HOLD.** `unfinalized.rs:286-290`, `from_fn(|i| ro::chal(15 - i).inner)`.

`DUMMY_PAD_CHALS` above is the endo-EXPANDED vector and the expansion is one-way, so a
statement word cannot carry it; these fifteen 128-bit draws are its preimage — asserted in
the generator, not assumed — and they are what the padding block's fifteen
`bpChallenge` words must be.

⚠ **THIS IS WHAT `KimchiStepMainCore.stmtDummyVal` DOES NOT YET EMIT.** It fills every
128-bit padding slot with `(7 + 1000003·j) % 2^127` — 24-25 bits — so the wrap proof's
PAD recursion slot commits a challenge polynomial that is not Mina's, while
`prover.rs:130-140` front-pads the reader's list with `DUMMY_WRAP_SG`. `gate_a2` reports
that slot RED, and `marshal::ACCUMULATOR_PRECHALLENGE_MIN_BITS` refuses the same shape
wherever it reaches a slot the record PUBLISHES.
-/
def DUMMY_WRAP_PRECHALS : List Nat :=
  [ 161621990286339861369413299182831583087
  , 294397517322790754025793051151124957079
  , 10455894452509500744048069718178570187
  , 224814704134265519234947971901913897491
  , 330128161163701260858569889180053145483
  , 102493828312258879830323023652412497031
  , 215326567078568560823705023668614618897
  , 120359744259981153545389569741970563149
  , 221360828059242236386510005024107555656
  , 257571901803291014519404945390244881518
  , 209025140278641004900167089918138330057
  , 201591733645229477386800950847198767694
  , 318881875946480425567146057353930829431
  , 198219236102229943192453714701868046676
  , 122049445183499159876948789073679959987
  ]

/-- ⚑⚑ **`messages_for_next_wrap_proof_padding()`** (`transaction.rs:3691-3700`) — the
`hash()` of the padded record's slot-0 entry, i.e. the squeeze over
`DUMMY_PAD_CHALS ++ DUMMY_PAD_CHALS ++ [DUMMY_STEP_SG_X, DUMMY_STEP_SG_Y]`.

⚠ **THIS IS AN ORACLE, NOT AN INPUT.** The assembly DERIVES this value; the theorem
`KimchiWrapMain.the_pad_slot_derives_minas_own_padding_digest` is the two agreeing. A use
site that emitted this literal instead of the sponge would be transcribing an object it
can compute, which is what `KimchiWrapHackDigest`'s whole docblock refuses. -/
def NEXT_WRAP_PROOF_PADDING : Nat := 11943760337307326502667319749275090450041849796096728414246455935807077355613

end Dregg2.Circuit.Emit.MinaWrapHackDummySg
