/-
# MinaStepOwnAccumulator — the step record's own `challenge_polynomial_commitment`.

⚑ GENERATED by `pickles-extractors/src/bin/pickles_kimchi_marshal.rs`
(`gates::step_own_accumulator_lean`). Do not hand-edit: re-run the marshal and copy it over.

`commit(b_poly(chals))` over the Tock SRS (`SRS::<Pallas>::create(2 ^ 15)`) at the 15
prechallenges of the WRAP proof's PUBLISHED recursion slot — the step statement's own
packed words, entries `32·p + 16 + j` (`marshal::step_statement_prechallenges`).

It is a **Pallas** point, so its coordinates live in Fp — the step circuit's own field,
which is why segment D can absorb them. ⚠ The STEP proof's own `prev_challenges[_].comm`
is a VESTA point in Fq and does NOT belong here; that mistake emitted a witness whose
`assert_on_curve` could not hold and the step prover refused outright.

⚑ WHAT BINDS IT ON MINA'S SIDE: **gate A2**, not `accumulator_check`.
`accumulator_check` reads `messages_for_next_WRAP_proof.challenge_polynomial_commitment`
(Vesta, slot 11) and is structurally blind to this one. `gates::gate_a2` front-pads the
step record's commitments with `dummy_ipa_wrap_sg()`, zips them against
`messages_for_next_wrap_proof.old_bulletproof_challenges`, and checks
`comm == ⟨b_poly_coefficients(chals), pallas_srs.g⟩` per slot.

⚑ WHAT CONSUMES THIS: `KimchiStepMainCore.mkStepAtAdvice`'s `specD := hmOutSpec s sp gAcc`,
i.e. cells 58–59 of the seventy-six `hash_messages_for_next_step_proof` absorbs. §19's
`check_bulletproof` does NOT: it keeps `solveG`'s output (`StepData.gXY`), and that split
is stated at `KimchiStepMainCore.vGaX` rather than here.

⚠ **A WITNESS, NOT A PIN.** These two words reach the step circuit's WITNESS and never its
gates, so the step VK is invariant under this module. And the fifteen it is taken over are
statement entries 16…30 / 48…62 while segment D's squeeze is entry 64 — re-emitting with a
different `[Gx; Gy]` was MEASURED to move entry 64 alone, so the install converges in ONE
pass, the same asymmetry `MinaWrapOwnVerifierKey`'s docblock states for the 56 index words.
-/
namespace Dregg2.Circuit.Emit.MinaStepOwnAccumulator

/-- The accumulator's `x`. -/
def ACC_X : Nat :=
  22158190242456080330731868133320991237447344204520506337874291371627985893037

/-- …and its `y`. -/
def ACC_Y : Nat :=
  24655624305627157927052913966353516703158120325981215138413789187926541013620

/-- The pair segment D absorbs. -/
def ACC_XY : Nat × Nat := (ACC_X, ACC_Y)

end Dregg2.Circuit.Emit.MinaStepOwnAccumulator
