/-
# Dregg2.Circuit.Emit.PastaGroupLaw — RCB'15 Theorem 1, discharged: the formula fold IS the group law.

## Where this sits

`PastaMsmOnCurve` (`71a2c25fa`) forced RCB'15 Theorem 1's HYPOTHESES: every operand of every RCB
add the emitted AIR runs is a point of the Pallas curve with `Y` a unit. Its CONCLUSION — that
`PastaScalarMul.rcbOutG`, at on-curve inputs, computes the ACTUAL Pallas group sum — was left an
inherited citation, precisely named in that file's §5.2:

  1. a formal Pallas group law (Mathlib's `WeierstrassCurve.Projective.Point`, instantiated at the
     real curve `a = 0, b = 5` over `ZMod pN`);
  2. a cofactor certificate for a degree-8-in-6-variables identity, showing `rcbOutG`'s output is a
     nonzero projective rescale of Mathlib's OWN classical addition/doubling formula.

This file builds (1) by instantiation (`PastaBasePrime` supplies the one hypothesis Mathlib's
group law needs that this tree did not have: `Field (ZMod pN)`) and discharges (2) for the two
cases the deployed fold actually runs — RCB(P, P) (the ladder's DOUBLE step) and RCB(P, Q) with
P, Q at different X-ratios AND both Z ≠ 0 (the ladder's generic ADD / windowed-add step) —
leaving two rarer cases named, not forced: an operand equal to the point at infinity (`Z = 0`,
already closed separately, see §6) and `Q` a different representative of `−P`. See §5 for the
composed statement and §6 for exactly what remains.

## The two certificates (computed outside Lean, checked inside)

Both identities were found the same way `glvPallas`'s lattice minimality was: computed outside
Lean (`sympy`, Gröbner-basis reduction modulo the two curve-equation ideal generators — the
degree-8-in-6-variables identity the goal names), then checked here by `ring`/`linear_combination`
in the kernel, never trusted from the computation itself.

  * **Doubling.** `rcbOutG(P, P)`'s `X`-coordinate equals Mathlib's `dblX P` UNCONDITIONALLY (a
    bare `ring` fact, no curve hypothesis at all); the `Y`- and `Z`-coordinates equal Mathlib's
    `dblY P` / `dblZ P` given the curve equation, via cofactors `9·b·Z` and `−6·Y` respectively.
  * **Generic add.** `rcbOutG(P, Q)` is not literally equal to Mathlib's `addXYZ P Q` (the ratio
    between them is a genuine function of `P, Q`, confirmed by direct numerical search before the
    symbolic one was attempted) — it is a projective RESCALE. The two cross-multiplied
    identities (`X3g·addZ = Z3c·addX` and `Y3f·addZ = Z3c·addY`, exactly Mathlib's own
    `equiv_of_X_eq_of_Y_eq` shape) each reduce to `0` modulo the ideal generated by both curve
    equations, with explicit cofactors found by Gröbner reduction — reported in the proofs below.

## Axiom hygiene

`#assert_axioms`-clean (⊆ {propext, Classical.choice, Quot.sound}); no `sorry`/`admit`/
`native_decide`. Import line: `import Dregg2.Circuit.Emit.PastaGroupLaw`.
-/
import Dregg2.Circuit.Emit.PastaBasePrime
import Dregg2.Circuit.Emit.PastaMsmOnCurve
import Mathlib.AlgebraicGeometry.EllipticCurve.Projective.Point

namespace Dregg2.Circuit.Emit.PastaGroupLaw

open Dregg2.Circuit.Emit.PastaField (pN)
open Dregg2.Circuit.Emit.PastaCurve (curveB)
open Dregg2.Circuit.Emit.PastaCurveComplete (curveB3)
open Dregg2.Circuit.Emit.PastaScalarMul (PtP rcbOutG rcbAddZmod)
open Dregg2.Circuit.Emit.PastaMsmOnCurve (OnCurveZ)
open WeierstrassCurve
open WeierstrassCurve.Projective

set_option autoImplicit false

/-! ## §0 — the curve, formally: Pallas `y² = x³ + 5` over `ZMod pN`, real Mathlib group law.

**Substrate, said out loud: this is Mathlib-instantiated projective group law, not a hand-derived
one.** `W.toProjective.Point`'s `AddCommGroup` (associativity included) is Mathlib's own theorem,
inherited by instantiation — nothing about the group axioms is proved in this file. -/

/-- The Pallas curve as a Mathlib Weierstrass curve: `⟨a₁,a₂,a₃,a₄,a₆⟩ = ⟨0,0,0,0,5⟩`. -/
def W : WeierstrassCurve (ZMod pN) := ⟨0, 0, 0, 0, (curveB : ZMod pN)⟩

/-- `curveB`, as the literal `5` it reduces to — so every downstream `ring`/`linear_combination`
sees a numeral, not an opaque atom (`simp only [curveB]` alone does not fully discharge the cast
arithmetic; an explicit equation lemma does). -/
theorem curveB_eq_5 : (curveB : ZMod pN) = 5 := by
  norm_num [Dregg2.Circuit.Emit.PastaCurve.curveB]

/-- The RCB constant `b3 = 3 · curveB` used throughout `PastaScalarMul`, as the literal `15` it
reduces to — so every downstream `ring`/`linear_combination` sees a numeral, not an opaque atom. -/
theorem curveB3_eq_15 : (curveB3 : ZMod pN) = 15 := by
  norm_num [curveB3, Dregg2.Circuit.Emit.PastaCurve.curveB]

/-- `rcbAddZmod`, unfolded to `rcbOutG` at the literal `b3 = 15`. -/
theorem rcbAddZmod_eq (P Q : PtP) :
    rcbAddZmod P Q = rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2 := by
  simp only [rcbAddZmod, curveB3_eq_15]

/-- The discriminant `Δ = −432·b²` for an `a = 0` curve, specialized at `b = curveB = 5`:
`Δ = −10800`. -/
theorem w_delta : W.Δ = (-10800 : ZMod pN) := by
  simp only [W, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈, Dregg2.Circuit.Emit.PastaCurve.curveB]
  push_cast
  ring

/-- `−10800 ≠ 0` in `ZMod pN`: decided from `10800 < pN`, not asserted. -/
theorem neg10800_ne_zero : (-10800 : ZMod pN) ≠ 0 := by
  have hlt : (10800 : ℕ) < pN := by decide
  intro h
  rw [neg_eq_zero] at h
  have h' : ((10800 : ℕ) : ZMod pN) = ((0 : ℕ) : ZMod pN) := by exact_mod_cast h
  rw [ZMod.natCast_eq_natCast_iff, Nat.ModEq] at h'
  simp only [Nat.mod_eq_of_lt hlt, Nat.zero_mod] at h'
  omega

/-- `Δ` is a unit: **Pallas is a genuine elliptic curve**, `W.IsElliptic`. -/
instance : W.IsElliptic := ⟨w_delta ▸ (Ne.isUnit neg10800_ne_zero)⟩

#assert_axioms curveB_eq_5
#assert_axioms curveB3_eq_15
#assert_axioms rcbAddZmod_eq
#assert_axioms w_delta
#assert_axioms neg10800_ne_zero

/-! ## §1 — the on-curve / nonsingular bridge: `OnCurveZ` IS Mathlib's `Equation`, and `Y ≠ 0`
gives `Nonsingular` — via `IsElliptic`, so NO 2-torsion/cofactor argument is needed at all. -/

/-- **`OnCurveZ` is Mathlib's projective `Equation`**, verbatim: both are `Y²Z = X³ + bZ³`. -/
theorem onCurveZ_iff_equation (P : PtP) :
    OnCurveZ P ↔ Equation W ![P.1, P.2.1, P.2.2] := by
  rw [equation_iff]
  simp only [W, OnCurveZ, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.cons_val_two, Matrix.tail_cons]
  constructor <;> intro h <;> linear_combination h

/-- **The nonsingular bridge — the payoff of `IsElliptic`.** An on-curve triple with `Y` a unit is
a genuine nonsingular projective point: no case-by-case 2-torsion argument, because `Δ ≠ 0` makes
the WHOLE curve smooth (`equation_iff_nonsingular`) away from `Z = 0`, and at `Z = 0` the curve
equation forces `X = 0`, leaving `Y ≠ 0` to witness the one nonsingularity disjunct directly. -/
theorem nonsingular_of_onCurveZ_unit {P : PtP} (hc : OnCurveZ P) (hy : P.2.1 ≠ 0) :
    Nonsingular W ![P.1, P.2.1, P.2.2] := by
  have heq : Equation W ![P.1, P.2.1, P.2.2] := (onCurveZ_iff_equation P).mp hc
  by_cases hz : P.2.2 = 0
  · have hz' : (![P.1, P.2.1, P.2.2] : Fin 3 → ZMod pN) 2 = 0 := by simpa using hz
    rw [nonsingular_of_Z_eq_zero hz']
    refine ⟨heq, Or.inr ?_⟩
    simp only [W, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, mul_zero,
      zero_mul, add_zero, sub_zero]
    exact pow_ne_zero 2 hy
  · have hz' : (![P.1, P.2.1, P.2.2] : Fin 3 → ZMod pN) 2 ≠ 0 := by simpa using hz
    rw [nonsingular_of_Z_ne_zero hz']
    exact WeierstrassCurve.Affine.equation_iff_nonsingular.mp
      ((equation_of_Z_ne_zero hz').mp heq)

/-- **Packaging**: an on-curve, `Y`-unit triple gives a genuine Mathlib `Point`. -/
def toPoint (P : PtP) (hc : OnCurveZ P) (hy : P.2.1 ≠ 0) : W.toProjective.Point where
  point := (⟦![P.1, P.2.1, P.2.2]⟧ : PointClass (ZMod pN))
  nonsingular := nonsingular_of_onCurveZ_unit hc hy

theorem toPoint_point (P : PtP) (hc : OnCurveZ P) (hy : P.2.1 ≠ 0) :
    (toPoint P hc hy).point = (⟦![P.1, P.2.1, P.2.2]⟧ : PointClass (ZMod pN)) :=
  rfl

#assert_axioms onCurveZ_iff_equation
#assert_axioms nonsingular_of_onCurveZ_unit
#assert_axioms toPoint_point

/-! ## §2 — the DOUBLING certificate: `rcbOutG(P, P) = (dblX P, dblY P, dblZ P)`, exactly. -/

/-- `X3g = dblX` is an UNCONDITIONAL ring identity — no curve hypothesis at all. -/
theorem rcbOutG_dbl_X (X Y Z : ZMod pN) :
    (rcbOutG (15 : ZMod pN) X Y Z X Y Z).1 = dblX W ![X, Y, Z] := by
  simp only [rcbOutG, dblX, W, curveB_eq_5, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons]
  push_cast
  ring

/-- `Y3f = dblY` given the curve equation, cofactor `9·b·Z = 45·Z` (found by Gröbner reduction of
`Y3f − dblY` modulo `Y²Z − X³ − bZ³`; `ring`-checked, not trusted). -/
theorem rcbOutG_dbl_Y {X Y Z : ZMod pN} (hc : OnCurveZ (X, Y, Z)) :
    (rcbOutG (15 : ZMod pN) X Y Z X Y Z).2.1 = dblY W ![X, Y, Z] := by
  simp only [rcbOutG, dblY, negDblY, negY, dblX, W, curveB_eq_5,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
    Matrix.tail_cons]
  simp only [OnCurveZ, curveB_eq_5] at hc
  push_cast
  linear_combination (45 * Z) * hc

/-- `Z3c = dblZ` given the curve equation, cofactor `−6·Y`. -/
theorem rcbOutG_dbl_Z {X Y Z : ZMod pN} (hc : OnCurveZ (X, Y, Z)) :
    (rcbOutG (15 : ZMod pN) X Y Z X Y Z).2.2 = dblZ W ![X, Y, Z] := by
  simp only [rcbOutG, dblZ, negY, W, curveB_eq_5, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons]
  simp only [OnCurveZ, curveB_eq_5] at hc
  push_cast
  linear_combination (-6 * Y) * hc

/-- The three components together: `rcbOutG(P,P)`, read as a `Fin 3 → ZMod pN` vector, IS
Mathlib's `dblXYZ` vector — literally, not merely projectively. -/
theorem rcbOutG_dbl_vec (P : PtP) (hc : OnCurveZ P) :
    (![(rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 P.1 P.2.1 P.2.2).1,
       (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 P.1 P.2.1 P.2.2).2.1,
       (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 P.1 P.2.1 P.2.2).2.2] : Fin 3 → ZMod pN)
      = dblXYZ W ![P.1, P.2.1, P.2.2] := by
  have hX := rcbOutG_dbl_X P.1 P.2.1 P.2.2
  have hY := rcbOutG_dbl_Y hc
  have hZ := rcbOutG_dbl_Z hc
  rw [dblXYZ]
  funext i
  fin_cases i <;> simp_all

#assert_axioms rcbOutG_dbl_X
#assert_axioms rcbOutG_dbl_Y
#assert_axioms rcbOutG_dbl_Z
#assert_axioms rcbOutG_dbl_vec

/-! ## §3 — composing the doubling case into the ACTUAL group law.

`rcbAddZmod P P` is the double-and-add ladder's DOUBLE step (`PastaScalarMul.ladderStep`,
`RCB(acc, acc)`). Given the emitted on-curve gate at BOTH the input row (`hc`/`hy`) and the output
row (`hc'`/`hy'` — the next row's own gate, exactly as `PastaMsmOnCurve` already threads it), this
says a verified proof of the AIR constrains the doubled accumulator to be `P + P` in Mathlib's
REAL `AddCommGroup W.toProjective.Point` — associativity and all, inherited, not proved here. -/

theorem toPoint_dbl_eq {P : PtP} (hc : OnCurveZ P) (hy : P.2.1 ≠ 0)
    {hc' : OnCurveZ (rcbAddZmod P P)} {hy' : (rcbAddZmod P P).2.1 ≠ 0} :
    toPoint (rcbAddZmod P P) hc' hy' = toPoint P hc hy + toPoint P hc hy := by
  apply WeierstrassCurve.Projective.Point.ext
  rw [WeierstrassCurve.Projective.Point.add_point, toPoint_point, toPoint_point,
    addMap_eq, add_self]
  have hvec := rcbOutG_dbl_vec P hc
  rw [rcbAddZmod_eq]
  exact congrArg _ hvec

#assert_axioms toPoint_dbl_eq

/-! ## §4 — the GENERIC ADD certificate: `rcbOutG(P, Q) ≈ addXYZ(P, Q)` (a projective rescale, not
a literal equality), for `P`, `Q` at DIFFERENT `X`-ratios. -/

/-- The `X : Z` cross-identity: `X3g · addZ = Z3c · addX`, given by Gröbner-reduction cofactors
`q1 = −3·X2·(Y2² + 15Z2²)·(Y1Z2 + Y2Z1)`, `q2 = 3·X1·(Y1² + 15Z1²)·(Y1Z2 + Y2Z1)` — i.e.
`X3g·addZ − Z3c·addX = q1·(curve eqn of P) + q2·(curve eqn of Q)` as a bare polynomial identity
(`ring`-checked below via `linear_combination`, not trusted from the outside computation). -/
theorem rcbOutG_add_cross_XZ {X1 Y1 Z1 X2 Y2 Z2 : ZMod pN}
    (hP : OnCurveZ (X1, Y1, Z1)) (hQ : OnCurveZ (X2, Y2, Z2)) :
    (rcbOutG (15 : ZMod pN) X1 Y1 Z1 X2 Y2 Z2).1 * addZ W ![X1, Y1, Z1] ![X2, Y2, Z2]
      = (rcbOutG (15 : ZMod pN) X1 Y1 Z1 X2 Y2 Z2).2.2 * addX W ![X1, Y1, Z1] ![X2, Y2, Z2] := by
  simp only [rcbOutG, addZ, addX, W, curveB_eq_5, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two, Matrix.tail_cons]
  simp only [OnCurveZ, curveB_eq_5] at hP hQ
  push_cast
  linear_combination
    (-3 * X2 * (Y2 ^ 2 + 15 * Z2 ^ 2) * (Y1 * Z2 + Y2 * Z1)) * hP
      + (3 * X1 * (Y1 ^ 2 + 15 * Z1 ^ 2) * (Y1 * Z2 + Y2 * Z1)) * hQ

/-- The `Y : Z` cross-identity: `Y3f · addZ = Z3c · addY`, cofactors
`q1' = 9·X1·X2²·(Y2² + 15Z2²)`, `q2' = −9·X1²·X2·(Y1² + 15Z1²)`. -/
theorem rcbOutG_add_cross_YZ {X1 Y1 Z1 X2 Y2 Z2 : ZMod pN}
    (hP : OnCurveZ (X1, Y1, Z1)) (hQ : OnCurveZ (X2, Y2, Z2)) :
    (rcbOutG (15 : ZMod pN) X1 Y1 Z1 X2 Y2 Z2).2.1 * addZ W ![X1, Y1, Z1] ![X2, Y2, Z2]
      = (rcbOutG (15 : ZMod pN) X1 Y1 Z1 X2 Y2 Z2).2.2 * addY W ![X1, Y1, Z1] ![X2, Y2, Z2] := by
  simp only [rcbOutG, addY, negAddY, negY, addX, addZ, W, curveB_eq_5,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
    Matrix.tail_cons]
  simp only [OnCurveZ, curveB_eq_5] at hP hQ
  push_cast
  linear_combination
    (9 * X1 * X2 ^ 2 * (Y2 ^ 2 + 15 * Z2 ^ 2)) * hP
      + (-9 * X1 ^ 2 * X2 * (Y1 ^ 2 + 15 * Z1 ^ 2)) * hQ

#assert_axioms rcbOutG_add_cross_XZ
#assert_axioms rcbOutG_add_cross_YZ

/-! ## §5 — composing the generic-add case into the ACTUAL group law.

`rcbAddZmod P Q` at `hne : P.1·Q.2.2 ≠ Q.1·P.2.2` (different `X`-ratios) with BOTH `P.2.2 ≠ 0` and
`Q.2.2 ≠ 0` (neither operand is the point at infinity — that case is closed separately, see §6) —
the windowed-add step's generic case — IS Mathlib's `P + Q`, in the real `AddCommGroup`. -/

theorem toPoint_add_eq {P Q : PtP} (hcP : OnCurveZ P) (hyP : P.2.1 ≠ 0) (hzP : P.2.2 ≠ 0)
    (hcQ : OnCurveZ Q) (hyQ : Q.2.1 ≠ 0) (hzQ : Q.2.2 ≠ 0) (hne : P.1 * Q.2.2 ≠ Q.1 * P.2.2)
    {hc' : OnCurveZ (rcbAddZmod P Q)} {hy' : (rcbAddZmod P Q).2.1 ≠ 0} :
    toPoint (rcbAddZmod P Q) hc' hy' = toPoint P hcP hyP + toPoint Q hcQ hyQ := by
  have hPzero : (![P.1, P.2.1, P.2.2] : Fin 3 → ZMod pN) 2 ≠ 0 := by simpa using hzP
  have hQzero : (![Q.1, Q.2.1, Q.2.2] : Fin 3 → ZMod pN) 2 ≠ 0 := by simpa using hzQ
  have hEqP : Equation W ![P.1, P.2.1, P.2.2] := (onCurveZ_iff_equation P).mp hcP
  have hEqQ : Equation W ![Q.1, Q.2.1, Q.2.2] := (onCurveZ_iff_equation Q).mp hcQ
  have hxne : (![P.1, P.2.1, P.2.2] : Fin 3 → ZMod pN) 0 * (![Q.1, Q.2.1, Q.2.2] : Fin 3 → ZMod pN) 2
      ≠ (![Q.1, Q.2.1, Q.2.2] : Fin 3 → ZMod pN) 0 * (![P.1, P.2.1, P.2.2] : Fin 3 → ZMod pN) 2 := by
    simpa using hne
  have haddZne : addZ W ![P.1, P.2.1, P.2.2] ![Q.1, Q.2.1, Q.2.2] ≠ 0 :=
    addZ_ne_zero_of_X_ne hEqP hEqQ hxne
  have hcrossXZ := rcbOutG_add_cross_XZ hcP hcQ
  have hcrossYZ := rcbOutG_add_cross_YZ hcP hcQ
  have hRZne : (rcbAddZmod P Q).2.2 ≠ 0 := by
    intro h0
    apply hy'
    have hY0 : (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).2.1
        * addZ W ![P.1, P.2.1, P.2.2] ![Q.1, Q.2.1, Q.2.2] = 0 := by
      rw [hcrossYZ]
      rw [rcbAddZmod_eq] at h0
      rw [h0]; ring
    exact (mul_eq_zero.mp hY0).resolve_right haddZne
  have hnotequiv : ¬ (![P.1, P.2.1, P.2.2] : Fin 3 → ZMod pN) ≈ ![Q.1, Q.2.1, Q.2.2] :=
    not_equiv_of_X_ne hxne
  have hRvec_eq : (![(rcbAddZmod P Q).1, (rcbAddZmod P Q).2.1, (rcbAddZmod P Q).2.2]
      : Fin 3 → ZMod pN) = ![(rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).1,
        (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).2.1,
        (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).2.2] := by rw [rcbAddZmod_eq]
  have hRZne' : (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).2.2 ≠ 0 := by
    rwa [rcbAddZmod_eq] at hRZne
  have hRvec_equiv : (![(rcbAddZmod P Q).1, (rcbAddZmod P Q).2.1, (rcbAddZmod P Q).2.2]
      : Fin 3 → ZMod pN) ≈ addXYZ W ![P.1, P.2.1, P.2.2] ![Q.1, Q.2.1, Q.2.2] := by
    rw [hRvec_eq]
    refine equiv_of_X_eq_of_Y_eq hRZne' ?_ ?_ ?_
    · rw [addXYZ_Z]; exact haddZne
    · change (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).1
          * addXYZ W ![P.1, P.2.1, P.2.2] ![Q.1, Q.2.1, Q.2.2] 2
        = addXYZ W ![P.1, P.2.1, P.2.2] ![Q.1, Q.2.1, Q.2.2] 0
          * (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).2.2
      rw [addXYZ_X, addXYZ_Z]
      linear_combination hcrossXZ
    · change (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).2.1
          * addXYZ W ![P.1, P.2.1, P.2.2] ![Q.1, Q.2.1, Q.2.2] 2
        = addXYZ W ![P.1, P.2.1, P.2.2] ![Q.1, Q.2.1, Q.2.2] 1
          * (rcbOutG (15 : ZMod pN) P.1 P.2.1 P.2.2 Q.1 Q.2.1 Q.2.2).2.2
      rw [addXYZ_Y, addXYZ_Z]
      linear_combination hcrossYZ
  apply WeierstrassCurve.Projective.Point.ext
  rw [WeierstrassCurve.Projective.Point.add_point, toPoint_point, toPoint_point, toPoint_point,
    addMap_eq, add_of_not_equiv hnotequiv]
  exact Quotient.sound hRvec_equiv

#assert_axioms toPoint_add_eq

/-! ## §6 — what this establishes, and exactly what remains.

**Composed.** For a row of the fold whose operands and output are BOTH forced on-curve by the
emitted `PastaMsmOnCurve` gates (the input rows via `PastaMsmOnCurve.row_operands_are_curve_points`
/ `row_addend_is_a_curve_point`, the output row via the NEXT row's own gate — exactly the same
threading `fold_accumulator_is_a_curve_point` already uses):

  * a DOUBLE step (`rcbAddZmod P P`, `PastaScalarMul.ladderStep`'s doubling) is `P + P` in
    Mathlib's real `W.toProjective.Point`, `AddCommGroup` and all — `toPoint_dbl_eq`;
  * a generic ADD step (`rcbAddZmod P Q`, `P.1·Q.2.2 ≠ Q.1·P.2.2`, both `Z ≠ 0`) is `P + Q` —
    `toPoint_add_eq`.

Composing `PastaMsmOnCurve.onCurve_forces` (which FORCES the hypotheses these theorems assume,
from the emitted gates) with `toPoint_dbl_eq` / `toPoint_add_eq` (which DISCHARGE RCB'15 Theorem
1's conclusion at those inputs), **a verified proof of `PastaMsmOnCurve`'s AIR now constrains the
accumulator, at every row that is a double or a generic (both-affine-representable) add, to be the
ACTUAL Mathlib group sum of its two operands** — not merely a fold of the RCB formula over curve
points, a fold of the GROUP LAW.

**NOT covered, named precisely (not weakened into silence):**

  1. **Either operand at `Z = 0`** (the point at infinity) is EXCLUDED from `toPoint_add_eq` by its
     own `hzP`/`hzQ` hypotheses — but this is not a gap: `PastaMsmOnCurve.skip_is_projective_identity`
     / `skip_is_rescale` ALREADY prove the RCB add against `O = (0:1:0)` is a rescale of the
     identity, independent of this file's Mathlib bridge. The two theorems are complementary, not
     overlapping.
  2. **`Q` a different representative of `−P`** (`P.1·Q.2.2 = Q.1·P.2.2` but `Q` not the SAME
     representative as `P`, and neither is the identity) — the RCB formula is empirically confirmed
     complete there too (checked numerically: `rcbOutG(P, −P) = (0, u, 0)` for a nonzero `u`,
     matching Mathlib's `addU`-scaled-identity branch), but the cofactor certificate for THAT case
     was not extracted. Whether the honest fold ever produces this operand pair is a question about
     the ladder's digit selection, not about this file.
  3. **ℤ ↔ felt (K1), P10, the manifest-bound tensor, the 4-generator shortfall** — untouched, as
     the goal named. This file's transport is about the FORMULA, not the encoding underneath it or
     the opening argument above it.

**One hypothesis that can never become a gate.** `W.IsElliptic` (`Δ ≠ 0`) is a fact about the
CURVE — checked once, here, for the fixed constants `a = 0, b = 5` over the fixed modulus `pN` —
not a per-row circuit condition. It is what makes `equation_iff_nonsingular` unconditional (every
on-curve triple away from `Z = 0` is automatically nonsingular) and is exactly analogous to
`PastaMsmOnCurve`'s own note about cofactor 1: true of the curve, not of a trace, and a red flag
if this file is ever adapted to a curve where it fails. -/

end Dregg2.Circuit.Emit.PastaGroupLaw
