-- The /descent no-cheat leaderboard board — the durable backing of `commands::descent`'s
-- `DescentBoardStore`. Before this, the Descent board lived only in-process on the dedicated
-- `descent-store` thread, so every ranked run was lost on restart. It is now DURABLE, over the same
-- store-and-replay discipline as the UGC gallery (005_ugc_gallery.sql).
--
-- Only the reproducible PUBLIC input is stored:
--   * descent_universes  — a day-world's committed beacon SEED (never a cached world). The world is
--     regenerated byte-for-byte from the seed by `daily_scene` on boot; `id_hex` is the content
--     address it hashed to at publish time (the PK + tamper check).
--   * descent_completions — a WINNING run's MOVE SEQUENCE + player + claimed turns (never a trusted
--     receipt blob). The receipt chain is re-recorded from the moves on a fresh identically-seeded
--     world and re-verified at load.
--
-- BOOT REPLAY + RE-VERIFY: `commands::descent::load_board` regenerates every day-world from its
-- seed (dropping any whose recomputed content address no longer matches its stored id — a tampered
-- seed) and REPLAYS every completion through the real no-cheat gate (`Registry::submit`), which
-- re-executes the moves on a fresh world and only ranks a run that provably reaches the WIN with a
-- truthful turn count. So a tampered row cannot resurrect a cheat: a losing/ineligible move line is
-- refused, a lied `claimed_turns` is a result mismatch, a mismatched seed drops the whole day-world.
--
-- NOTE: `Database::connect` also creates these tables inline (CREATE TABLE IF NOT EXISTS), matching
-- the bot's schema-in-code pattern; this file documents the schema for the migrations dir.

CREATE TABLE IF NOT EXISTS descent_universes (
    id_hex   TEXT PRIMARY KEY,   -- the day-universe content address (hex) at publish time
    author   TEXT NOT NULL,      -- the board author label the day's world is published under
    seed_hex TEXT NOT NULL       -- hex of the 32-byte committed beacon seed the world regenerates from
);

CREATE TABLE IF NOT EXISTS descent_completions (
    key_hex         TEXT PRIMARY KEY,   -- blake3(universe_id_hex ‖ player ‖ moves_json) idempotency key
    universe_id_hex TEXT NOT NULL,      -- the day-universe this winning run is for
    player          TEXT NOT NULL,      -- the player's (short) tag
    moves_json      TEXT NOT NULL,      -- the recorded choice-index sequence (a JSON array)
    claimed_turns   INTEGER NOT NULL    -- claimed turns-to-win; stored independently → a lie is caught
);

CREATE INDEX IF NOT EXISTS idx_descent_completions_universe
    ON descent_completions (universe_id_hex);
