/-
# CanonicalCodecDayWire — the derived codec standing in for a shipped hand-written one.

`NightWatchLoopWire.DayWire` is the smallest live wire type in Path-of-Angels: two `Nat`s
(`NightWatchLoopWire.lean:228`), encoder hand-written at `:279`, reader hand-written at
`:363` (`parseDay`, and `private`, so it cannot be compared against from here — see below).
It is the demonstration type because
it is the only small one whose fields are ALL derivable — every other candidate carries a
`Digest32`, and there is no proved `parseBytes32Hex? (bytes32Hex d) = some d` in this tree,
so `CanonicalCodec` refuses those on purpose (see the falsifier).

## What is shown

* `DayWire.renderCanon` — DERIVED — emits the SAME BYTES as the shipped `DayWire.toJson`,
  for every value, proved (`renderCanon_eq_toJson`), not sampled. That is the replacement
  criterion: the derived encoder is a drop-in whose drift is a build failure.
* `DayWire.readRow_toRow` — DERIVED — is the acceptance direction: the strict reader accepts
  the writer's output for EVERY well-formed value. **No PoA module proves this today.** The
  33 shipped `_reencodes` theorems prove canonicality (accepted bytes are canonical), which
  the falsifier shows a decoder accepting nothing also satisfies.
* The derived reader is STRICTLY STRONGER than `parseDay`: `parseDay` uses `exactKeys`, a SET
  check, so `{"day_index":…,"content_epoch":…}` reaches it and the byte-order refusal is left
  entirely to the re-encode comparison. The literal-row match pins key ORDER in the reader
  itself (`readRow_refuses_transposed_keys`).

## What is NOT done here — three things, all stated

1. **The encoder swap is not applied in `NightWatchLoopWire.lean`.** The landing patch is
   three lines there: `import Dregg2.Games.PathOfAngels.CanonicalCodec`, then
   `deriving instance Dregg2.Canonical.Canonical for DayWire` after the structure, then
   `def DayWire.toJson (day : DayWire) : String := DayWire.renderCanon day`. It is not applied
   because that file is 1,638 lines with the whole PoA wire cone downstream, this lane cannot
   run `lake`, and a red there is a red for every lane sharing the tree. `renderCanon_eq_toJson`
   is what makes the swap a no-op on the bytes; it is the reason the patch is three lines and
   not a review.
2. **`parseDay` is not replaced and cannot be compared against from here** — it is `private`,
   so no theorem outside `NightWatchLoopWire` can name it. Replacing the READER is a same-file
   edit or nothing.
3. **The byte-layer roundtrip is not proved for a general value** (see the section below); it
   is `native_decide`d at one point, and labelled as one point.
-/
import Dregg2.Games.PathOfAngels.CanonicalCodec
import Dregg2.Games.PathOfAngels.NightWatchLoopWire

/-! ## Derivation

Both the derivation and the `canonWf` witness sit at the ROOT namespace on purpose: the
handler places its declarations beside the structure (`…NightWatchLoopWire.DayWire.toRow`,
`…readRow`, `…readRow_toRow`), and `#assert_codec_nonvacuous` looks the witness up at
`<type>.canonWf_witness`. Declaring the witness inside a local namespace would put it
somewhere the gate cannot see, and the gate would refuse — correctly. -/

deriving instance Dregg2.Canonical.Canonical for
  Dregg2.Games.PathOfAngels.NightWatchLoopWire.DayWire

/-- The satisfiability witness for `readRow_toRow`'s hypothesis. A conditional roundtrip
whose condition no value satisfies is vacuous in a second, quieter way than an unsatisfiable
premise, so `#assert_codec_nonvacuous` refuses without this. The value is the live
deployment's own: content epoch 1, day counter 6. -/
theorem Dregg2.Games.PathOfAngels.NightWatchLoopWire.DayWire.canonWf_witness :
    Dregg2.Games.PathOfAngels.NightWatchLoopWire.DayWire.canonWf ⟨1, 6⟩ = true := by
  decide

/-! ⚑ Why `#assert_axioms` on a DERIVED theorem is not ceremony.

A derived proof is generated by a tactic macro, and a tactic macro is the one place a
generated theorem could go hollow: if `canonical_roundtrip` ever half-succeeds, Lean's
recovery fills the remainder with `sorryAx` and the declaration still enters the environment
with the advertised STATEMENT. A solver reading the emitted table cannot tell the difference —
an unproved lemma emits the same table as a proved one. So every derived theorem is pinned,
and the pin is what makes "uniform coverage" mean something rather than look like something. -/

#assert_axioms Dregg2.Games.PathOfAngels.NightWatchLoopWire.DayWire.canonWf_witness
#assert_axioms Dregg2.Games.PathOfAngels.NightWatchLoopWire.DayWire.readRow_toRow
#assert_codec_nonvacuous Dregg2.Games.PathOfAngels.NightWatchLoopWire.DayWire

namespace Dregg2.Games.PathOfAngels.CanonicalCodecDayWire

open Dregg2.Games.PathOfAngels.NightWatchLoopWire

set_option autoImplicit false

/-! ## Byte identity with the shipped encoder

Proved for all values, by `rfl`. It reduces because the derived renderer is built LEFT-nested,
which is how `++` (an `infixl:65`) already associates in every hand-written PoA encoder — so the
two sides differ only by `fieldRender` versus `toString`, which is delta/projection reduction
through the `HasFieldCodec Nat` instance and needs no string-append reasoning at all.

⚠ The handler emitted a RIGHT-nested render until 2026-08-05, under a comment claiming that was
what `++` does. It is not, `String.append` is not definitionally associative over variable
fields, and this `rfl` was the thing that went red. -/
theorem renderCanon_eq_toJson (day : DayWire) :
    DayWire.renderCanon day = DayWire.toJson day := by
  cases day
  rfl

#assert_axioms renderCanon_eq_toJson

/-- The derived key list is the shipped key list, in the shipped order. Pinned against the
literal spelling rather than against the derived definition — a constant checked against its
own definition is decoration; two independent sources are a gate. -/
theorem canonKeys_are_the_wire_keys :
    DayWire.canonKeys = ["content_epoch", "day_index"] := by
  rfl

#assert_axioms canonKeys_are_the_wire_keys

/-! ## The byte layer, for ONE point

The derived `readRow_toRow` stops at the row layer. Crossing to bytes needs
`Dregg2.Canonical.RowAdapterFaithful` (the `Std.TreeMap.Raw` leg) and
`Dregg2.Canonical.ParserAdequate` (Lean's own JSON parser), neither of which is proved for a
general value anywhere in this repository. These two run the ACTUAL path — render, then
`Lean.Json.parse`, then the adapter, then the derived reader, then the canonicality
comparison — for one concrete value, by compiled evaluation, and say so with
`#assert_compiled` rather than hiding the compiler trust in a `#guard`. One point is one
point; it is not the general fact and is not labelled as one. -/

def dayFixture : DayWire := ⟨1, 6⟩

theorem dayFixture_bytes :
    DayWire.renderCanon dayFixture = "{\"content_epoch\":1,\"day_index\":6}" := by
  native_decide

#assert_compiled dayFixture_bytes

theorem dayFixture_decodes :
    Dregg2.Canonical.canonicalDecode DayWire.canonKeys DayWire.readRow DayWire.renderCanon
      1024 (DayWire.renderCanon dayFixture) = some dayFixture := by
  native_decide

#assert_compiled dayFixture_decodes

/-- The strictness the derived reader adds over `exactKeys`: a row whose keys are the right
SET in the wrong ORDER is refused by the reader itself, not merely by the re-encode
comparison downstream. -/
theorem readRow_refuses_transposed_keys :
    (DayWire.readRow [("day_index", Dregg2.Canonical.natToJson 6),
                      ("content_epoch", Dregg2.Canonical.natToJson 1)]).isOk = false := by
  native_decide

#assert_compiled readRow_refuses_transposed_keys

/-- The wire bound is really enforced: one over `WIRE_U64_MAX` is refused by the reader. -/
theorem readRow_refuses_oversize_epoch :
    (DayWire.readRow [("content_epoch", Dregg2.Canonical.natToJson (2 ^ 64)),
                      ("day_index", Dregg2.Canonical.natToJson 6)]).isOk = false := by
  native_decide

#assert_compiled readRow_refuses_oversize_epoch

/-- The derived bound agrees with the bound `NightWatchLoopWire.objectNat` defaults to. Two
independent constants, one comparison — if either moves, this reds. -/
theorem wire_bound_agrees :
    Dregg2.Canonical.WIRE_U64_MAX = NightWatchLoopWire.WIRE_U64_MAX := by
  rfl

#assert_axioms wire_bound_agrees

end Dregg2.Games.PathOfAngels.CanonicalCodecDayWire
