/-
# Finite POAG1 tables for Relay Repair and Salvage Lock

These declarations enumerate the duplicate-free legal-state closure of each
small game and the complete state x action transition table over that closure.
The web host dispatches these tables; it does not carry a second implementation
of either state machine.
-/
import Dregg2.Games.PathOfAngels.RelayRepair
import Dregg2.Games.PathOfAngels.SalvageLock
import Dregg2.Tactics

namespace Dregg2.Games.PathOfAngels.FiniteTables

open Dregg2.Games.PathOfAngels

/-! ## Generic finite closure -/

def expandStates {State Action : Type} [DecidableEq State]
    (step : State → Action → Option State) (actions : List Action)
    (states : List State) : List State :=
  (states ++ states.flatMap fun state => actions.filterMap (step state)).eraseDups

def stateClosure {State Action : Type} [DecidableEq State]
    (step : State → Action → Option State) (actions : List Action)
    (initial : State) : Nat → List State
  | 0 => [initial]
  | n + 1 => expandStates step actions (stateClosure step actions initial n)

/-! ## Relay Repair -/

def relayActions : List RelayRepair.Action :=
  [.alphaBeta, .alphaGamma, .betaDelta, .gammaDelta, .deltaOmega]

def relayActionId : RelayRepair.Action → String
  | .alphaBeta => "alpha-beta"
  | .alphaGamma => "alpha-gamma"
  | .betaDelta => "beta-delta"
  | .gammaDelta => "gamma-delta"
  | .deltaOmega => "delta-omega"

def relayActionLabel : RelayRepair.Action → String
  | .alphaBeta => "Install Alpha-Beta"
  | .alphaGamma => "Install Alpha-Gamma"
  | .betaDelta => "Install Beta-Delta"
  | .gammaDelta => "Install Gamma-Delta"
  | .deltaOmega => "Install Delta-Omega"

def relayActionFrom : RelayRepair.Action → String
  | .alphaBeta | .alphaGamma => "alpha"
  | .betaDelta => "beta"
  | .gammaDelta => "gamma"
  | .deltaOmega => "delta"

def relayActionTo : RelayRepair.Action → String
  | .alphaBeta => "beta"
  | .alphaGamma => "gamma"
  | .betaDelta | .gammaDelta => "delta"
  | .deltaOmega => "omega"

def relayPanelMask (panel : RelayRepair.Panel) : Nat :=
  (if panel.alphaBeta then 1 else 0) +
  (if panel.alphaGamma then 2 else 0) +
  (if panel.betaDelta then 4 else 0) +
  (if panel.gammaDelta then 8 else 0) +
  (if panel.deltaOmega then 16 else 0)

/-- The panel and the clock are the whole state; spares are a projection of the
panel against the board, so the id does not name them. -/
def relayStateId (state : RelayRepair.State) : String :=
  "relay:" ++ toString (relayPanelMask state.panel) ++ ":" ++ toString state.turns

def relayInstalledActionIds (panel : RelayRepair.Panel) : List String :=
  (relayActions.filter fun action => RelayRepair.installed panel action).map relayActionId

theorem relayActions_length : relayActions.length = 5 := rfl

theorem relayActions_complete (action : RelayRepair.Action) : action ∈ relayActions := by
  cases action <;> simp [relayActions]

/-- No Config-erased twin exists: the closure is generated by the source transition
itself, parameterised only by the semantically relevant argument. -/
theorem relayStep_eq_source (cfg : RelayRepair.Config) (state : RelayRepair.State)
    (action : RelayRepair.Action) :
    RelayRepair.stepB cfg.board state action = RelayRepair.step cfg state action := rfl

def relayStates (board : RelayRepair.Board) : List RelayRepair.State :=
  stateClosure (RelayRepair.stepB board) relayActions RelayRepair.initialState
    RelayRepair.MAX_TURNS

structure RelayTransition where
  state : RelayRepair.State
  action : RelayRepair.Action
  next : Option RelayRepair.State
deriving DecidableEq, Repr

def relayTransitions (board : RelayRepair.Board) : List RelayTransition :=
  (relayStates board).flatMap fun state =>
    relayActions.map fun action =>
      { state, action, next := RelayRepair.stepB board state action }

def relayTableClosedB (board : RelayRepair.Board) : Bool :=
  (relayTransitions board).all fun transition =>
    match transition.next with
    | none => true
    | some next => decide (next ∈ relayStates board)

def relayStatesNodupB (board : RelayRepair.Board) : Bool := (relayStates board).Nodup

def relayStateIdsUniqueB (board : RelayRepair.Board)
    (stateId : RelayRepair.State → String) : Bool :=
  ((relayStates board).map stateId).Nodup

/-- The complete refusal vocabulary, and every one of the five fires on a reachable
state of the emitted board — `relayRefusalReasonsLiveB`.  A refusal a run can never
provoke is a badge no client can earn. -/
def relayRefusalVocabulary : List String :=
  ["solved", "turn-limit", "already-installed", "no-spares", "stranded"]

def relayRefusalReason (board : RelayRepair.Board) (state : RelayRepair.State)
    (action : RelayRepair.Action) : Option String :=
  if RelayRepair.routedB state.panel then some "solved"
  else if RelayRepair.MAX_TURNS ≤ state.turns then some "turn-limit"
  else if RelayRepair.installed state.panel action then some "already-installed"
  else if RelayRepair.sparesLeft board state.panel < RelayRepair.cost board action then
    some "no-spares"
  else if RelayRepair.completableB board state = false then some "stranded"
  else none

def relayRefusalReasonsCompleteB (board : RelayRepair.Board) : Bool :=
  (relayTransitions board).all fun transition =>
    match transition.next, relayRefusalReason board transition.state transition.action with
    | some _, none => true
    | none, some _ => true
    | _, _ => false

/-- Every declared reason is provoked by some reachable (state, action) pair. -/
def relayRefusalReasonsLiveB (board : RelayRepair.Board) : Bool :=
  relayRefusalVocabulary.all fun reason =>
    (relayTransitions board).any fun transition =>
      relayRefusalReason board transition.state transition.action == some reason

/-- Conversely, no row invents a reason outside the vocabulary. -/
def relayRefusalReasonsDeclaredB (board : RelayRepair.Board) : Bool :=
  (relayTransitions board).all fun transition =>
    match relayRefusalReason board transition.state transition.action with
    | none => true
    | some reason => relayRefusalVocabulary.contains reason

theorem relayTransitions_length (board : RelayRepair.Board) :
    (relayTransitions board).length = (relayStates board).length * relayActions.length := by
  simp [relayTransitions]

theorem relayTransition_spec (board : RelayRepair.Board) (transition : RelayTransition)
    (h : transition ∈ relayTransitions board) :
    transition.next = RelayRepair.stepB board transition.state transition.action := by
  simp only [relayTransitions, List.mem_flatMap, List.mem_map] at h
  obtain ⟨state, _hstate, action, _haction, rfl⟩ := h
  rfl

/-- The emitted board: the one `Emit.relayRunSeed` selects (`Emit.relayBoardIndex`). -/
abbrev relayEmittedBoard : RelayRepair.Board := RelayRepair.boardAt 2

theorem relayTable_closed : relayTableClosedB relayEmittedBoard = true := by
  native_decide

theorem relayStates_nodup : relayStatesNodupB relayEmittedBoard = true := by
  native_decide

theorem relayRefusalReasons_complete :
    relayRefusalReasonsCompleteB relayEmittedBoard = true := by
  native_decide

theorem relayRefusalReasons_live : relayRefusalReasonsLiveB relayEmittedBoard = true := by
  native_decide

theorem relayRefusalReasons_declared :
    relayRefusalReasonsDeclaredB relayEmittedBoard = true := by
  native_decide

theorem relayStateIds_unique :
    relayStateIdsUniqueB relayEmittedBoard relayStateId = true := by
  native_decide

theorem relayStates_count : (relayStates relayEmittedBoard).length = 25 := by
  native_decide

theorem relayTransitions_count : (relayTransitions relayEmittedBoard).length = 125 := by
  native_decide

#assert_axioms relayActions_length
#assert_axioms relayActions_complete
#assert_axioms relayStep_eq_source
#assert_axioms relayTransitions_length
#assert_axioms relayTransition_spec
#assert_compiled relayTable_closed
#assert_compiled relayStates_nodup
#assert_compiled relayRefusalReasons_complete
#assert_compiled relayRefusalReasons_live
#assert_compiled relayRefusalReasons_declared
#assert_compiled relayStateIds_unique
#assert_compiled relayStates_count
#assert_compiled relayTransitions_count

/-! ## Salvage Lock -/

def salvageActions : List SalvageLock.Action :=
  (List.finRange 6).map SalvageLock.Action.expose

def salvageActionId (action : SalvageLock.Action) : String :=
  "slot-" ++ toString (SalvageLock.actionSlot action).val

def salvageActionLabel (action : SalvageLock.Action) : String :=
  "Expose plate " ++ toString (SalvageLock.actionSlot action).val

def salvageGlyphLabel (glyph : Fin 3) : String :=
  "glyph-" ++ toString glyph.val

def salvageClearedMask (state : SalvageLock.State) : Nat :=
  SalvageLock.allSlots.foldl (fun mask slot =>
    if slot ∈ state.cleared then mask + 2 ^ slot.val else mask) 0

def salvageStateId (state : SalvageLock.State) : String :=
  let exposed := match state.exposed with
    | none => "none"
    | some slot => toString slot.val
  "salvage:" ++ toString (salvageClearedMask state) ++ ":" ++ exposed ++ ":" ++
    toString state.turns

def salvageClearedSlots (state : SalvageLock.State) : List (Fin 6) :=
  SalvageLock.allSlots.filter fun slot => decide (slot ∈ state.cleared)

theorem salvageActions_length : salvageActions.length = 6 := by
  simp [salvageActions]

theorem salvageActions_complete (action : SalvageLock.Action) : action ∈ salvageActions := by
  cases action with
  | expose slot => simp [salvageActions]

/-- The seed the pinned run seed draws its board from.  No literal is written here:
the value is whatever the four consuming draws return, and
`salvagePinnedSeed_resolved` is the compiled statement that they returned something
rather than falling through to the `getD`.  Pinning a literal instead would be a
constant checked against its own definition. -/
def salvagePinnedSeed : Fin SalvageLock.SEED_SPACE :=
  (SalvageLock.seedFromRunSeed? SalvageLock.PINNED_RUN_SEED).getD ⟨0, by decide⟩

theorem salvagePinnedSeed_resolved :
    SalvageLock.seedFromRunSeed? SalvageLock.PINNED_RUN_SEED = some salvagePinnedSeed := by
  native_decide

/-- Salvage's source transition parameterized only by the semantically relevant
seed; MissionSpec and reward proofs do not influence play. -/
def salvageStep (seed : Fin SalvageLock.SEED_SPACE) (state : SalvageLock.State) :
    SalvageLock.Action → Option SalvageLock.State
  | .expose slot =>
      if SalvageLock.openB state slot then
        match state.exposed with
        | none => some { state with exposed := some slot, turns := state.turns + 1 }
        | some first =>
            let cleared :=
              if SalvageLock.glyphAt seed first = SalvageLock.glyphAt seed slot then
                insert slot (insert first state.cleared)
              else state.cleared
            some { cleared, exposed := none, turns := state.turns + 1 }
      else none

theorem salvageStep_eq_source (cfg : SalvageLock.Config) (state : SalvageLock.State)
    (action : SalvageLock.Action) :
    salvageStep cfg.seed state action = SalvageLock.step cfg state action := by
  cases action <;> rfl

def salvageStates (seed : Fin SalvageLock.SEED_SPACE) : List SalvageLock.State :=
  stateClosure (salvageStep seed) salvageActions SalvageLock.initialState SalvageLock.MAX_TURNS

structure SalvageTransition where
  state : SalvageLock.State
  action : SalvageLock.Action
  next : Option SalvageLock.State
deriving DecidableEq

def salvageTransitions (seed : Fin SalvageLock.SEED_SPACE) : List SalvageTransition :=
  (salvageStates seed).flatMap fun state =>
    salvageActions.map fun action => { state, action, next := salvageStep seed state action }

/-- `states` is bound OUTSIDE the fold: it used to sit inside the lambda, so the
whole twelve-round closure was recomputed once per transition row (984 times).  That
was affordable only because the old board was two arithmetic operations. -/
def salvageTableClosedB (seed : Fin SalvageLock.SEED_SPACE) : Bool :=
  let states := salvageStates seed
  (salvageTransitions seed).all fun transition =>
    match transition.next with
    | none => true
    | some next => decide (next ∈ states)

def salvageStatesNodupB (seed : Fin SalvageLock.SEED_SPACE) : Bool := (salvageStates seed).Nodup

def salvageStateIdsUniqueB (seed : Fin SalvageLock.SEED_SPACE)
    (stateId : SalvageLock.State → String) : Bool :=
  ((salvageStates seed).map stateId).Nodup

def salvageRefusalReason (state : SalvageLock.State) (action : SalvageLock.Action) :
    Option String :=
  let slot := SalvageLock.actionSlot action
  if SalvageLock.solvedB state then some "solved"
  else if SalvageLock.MAX_TURNS ≤ state.turns then some "turn-limit"
  else if slot ∈ state.cleared then some "cleared-slot"
  else if state.exposed = some slot then some "already-exposed"
  else none

def salvageRefusalReasonsCompleteB (seed : Fin SalvageLock.SEED_SPACE) : Bool :=
  (salvageTransitions seed).all fun transition =>
    match transition.next, salvageRefusalReason transition.state transition.action with
    | some _, none => true
    | none, some _ => true
    | _, _ => false

theorem salvageTransitions_length (seed : Fin SalvageLock.SEED_SPACE) :
    (salvageTransitions seed).length = (salvageStates seed).length * salvageActions.length := by
  simp [salvageTransitions]

theorem salvageTransition_spec (seed : Fin SalvageLock.SEED_SPACE) (transition : SalvageTransition)
    (h : transition ∈ salvageTransitions seed) :
    transition.next = salvageStep seed transition.state transition.action := by
  simp only [salvageTransitions, List.mem_flatMap, List.mem_map] at h
  obtain ⟨state, _hstate, action, _haction, rfl⟩ := h
  rfl

theorem salvageStates_nodup_pinned : salvageStatesNodupB salvagePinnedSeed = true := by
  native_decide

theorem salvageTable_closed_pinned : salvageTableClosedB salvagePinnedSeed = true := by
  native_decide

theorem salvageRefusalReasons_complete_pinned :
    salvageRefusalReasonsCompleteB salvagePinnedSeed = true := by
  native_decide

theorem salvageStateIds_unique_pinned :
    salvageStateIdsUniqueB salvagePinnedSeed salvageStateId = true := by
  native_decide

theorem salvageStates_count_pinned : (salvageStates salvagePinnedSeed).length = 164 := by
  native_decide

theorem salvageTransitions_count_pinned : (salvageTransitions salvagePinnedSeed).length = 984 := by
  native_decide

/-- One seed per perfect matching: the fifteen with a canonical glyph labelling
(`seed % 6 = 0`).  The glyph names cannot change the closure — `salvageStep` only
ever compares two glyphs for equality — so these fifteen cover the whole seed space
for any question about the machine's SHAPE. -/
def salvagePairingRepresentatives : List (Fin SalvageLock.SEED_SPACE) :=
  (List.finRange SalvageLock.SEED_SPACE).filter fun seed => seed.val % 6 == 0

/-- ⚑ The emitted table's SHAPE does not leak the board.  Every one of the fifteen
matchings yields the same 164 states and 984 transitions, all state ids distinct and
the table closed, so a client cannot read the instance off the descriptor's size or
its refusal pattern — only off its contents, which it does publish (see the
`SalvageLock` header). -/
theorem salvage_machine_shape_is_seed_independent :
    (salvagePairingRepresentatives.length == 15 &&
      (salvagePairingRepresentatives.all (fun seed =>
        (salvageStates seed).length == 164 &&
        (salvageTransitions seed).length == 984 &&
        salvageStatesNodupB seed &&
        salvageTableClosedB seed &&
        salvageStateIdsUniqueB seed salvageStateId &&
        salvageRefusalReasonsCompleteB seed))) = true := by
  native_decide

#assert_axioms salvageActions_length
#assert_axioms salvageActions_complete
#assert_axioms salvageStep_eq_source
#assert_axioms salvageTransitions_length
#assert_axioms salvageTransition_spec
#assert_compiled salvagePinnedSeed_resolved
#assert_compiled salvageStates_nodup_pinned
#assert_compiled salvageTable_closed_pinned
#assert_compiled salvageRefusalReasons_complete_pinned
#assert_compiled salvageStateIds_unique_pinned
#assert_compiled salvageStates_count_pinned
#assert_compiled salvageTransitions_count_pinned
#assert_compiled salvage_machine_shape_is_seed_independent

end Dregg2.Games.PathOfAngels.FiniteTables
