/-
# Dregg2.Calculus.InteractionNetTrace — local graph-rewrite proof objects

This file is the first executable slice of an interaction-net-style proof
calculus.  A proof object is a list of small local graph interactions:

* `Agent` is a finite, one-wire-type port signature.
* `Net` is the finite rooted, sharing-free fragment of that port-graph syntax.
* `ActiveRule` contracts a local gate/literal interaction.
* `Context` is a one-hole graph context, so a `LocalCert` identifies one local
  interaction inside a larger net without giving the rule global authority.
* `replay` is an executable trace checker.
* `checkTrace_sound` proves that every accepted trace preserves Boolean
  denotation; `checkStep_observational` strengthens this to every surrounding
  graph context.

This is intentionally not claimed to be the whole interaction-net formalism:
there is no sharing, erasure/duplication agent, lambda node, proof-net switching
criterion, or confluence theorem yet.  It is the small honest seam on which
those extensions can land.
-/
import Dregg2.Tactics

namespace Dregg2.Calculus.InteractionNetTrace

/-! ## Finite typed local graph syntax -/

/-- The first slice has one wire type.  Keeping it explicit makes the extension
to products, linear resources, or STLC arrows a change to the signature rather
than a reinterpretation of untyped nodes. -/
inductive WireTy where
  | bit
  deriving DecidableEq, Repr

/-- The finite agent signature.  The first auxiliary port of a binary gate is
its left input and the second is its right input; the principal port is its
output. -/
inductive Agent where
  | lit (value : Bool)
  | neg
  | and
  | or
  deriving DecidableEq, Repr

/-- Auxiliary-port types of each agent.  Every principal port has type `bit`.
The signature itself therefore records local typing independently of any
particular evaluator implementation. -/
def Agent.auxPortTypes : Agent → List WireTy
  | .lit _ => []
  | .neg => [.bit]
  | .and => [.bit, .bit]
  | .or => [.bit, .bit]

def Agent.principalType (_ : Agent) : WireTy := .bit

/-- A finite rooted port tree generated by the signature.  This sharing-free
fragment is typed by construction: every child occupies a `bit` auxiliary port
and every node exposes a `bit` principal port. -/
inductive Net where
  | lit (value : Bool)
  | neg (input : Net)
  | and (left right : Net)
  | or (left right : Net)
  deriving DecidableEq, Repr

def Net.rootAgent : Net → Agent
  | .lit b => .lit b
  | .neg _ => .neg
  | .and _ _ => .and
  | .or _ _ => .or

/-- A structural size measure showing that every proof state is a finite graph. -/
def Net.nodeCount : Net → Nat
  | .lit _ => 1
  | .neg n => n.nodeCount + 1
  | .and l r => l.nodeCount + r.nodeCount + 1
  | .or l r => l.nodeCount + r.nodeCount + 1

/-- Boolean meaning of a net. -/
def Net.denote : Net → Bool
  | .lit b => b
  | .neg n => !n.denote
  | .and l r => l.denote && r.denote
  | .or l r => l.denote || r.denote

/-! ## Local active interactions -/

/-- A local gate/literal interaction.  The Boolean parameters are part of the
certificate, so checking a rule never searches for an unstated witness. -/
inductive ActiveRule where
  | negLit (value : Bool)
  | andLit (left right : Bool)
  | orLit (left right : Bool)
  deriving DecidableEq, Repr

def ActiveRule.lhs : ActiveRule → Net
  | .negLit b => .neg (.lit b)
  | .andLit a b => .and (.lit a) (.lit b)
  | .orLit a b => .or (.lit a) (.lit b)

def ActiveRule.rhs : ActiveRule → Net
  | .negLit b => .lit (!b)
  | .andLit a b => .lit (a && b)
  | .orLit a b => .lit (a || b)

/-- Every primitive interaction preserves meaning.  This is the semantic law a
future richer rule table must discharge before its tag can enter the checker. -/
theorem activeRule_preserves (r : ActiveRule) : r.rhs.denote = r.lhs.denote := by
  cases r <;> simp [ActiveRule.lhs, ActiveRule.rhs, Net.denote]

/-! ## One-hole contexts: locality inside a larger graph -/

/-- A one-hole port-tree context.  It is a zipper for the selected local
interaction: all constructors preserve the untouched neighbours exactly. -/
inductive Context where
  | hole
  | underNeg (inside : Context)
  | andLeft (inside : Context) (right : Net)
  | andRight (left : Net) (inside : Context)
  | orLeft (inside : Context) (right : Net)
  | orRight (left : Net) (inside : Context)
  deriving DecidableEq, Repr

def Context.plug : Context → Net → Net
  | .hole, n => n
  | .underNeg c, n => .neg (c.plug n)
  | .andLeft c r, n => .and (c.plug n) r
  | .andRight l c, n => .and l (c.plug n)
  | .orLeft c r, n => .or (c.plug n) r
  | .orRight l c, n => .or l (c.plug n)

/-- A context acts on the Boolean meaning at its hole. -/
def Context.act : Context → Bool → Bool
  | .hole, b => b
  | .underNeg c, b => !(c.act b)
  | .andLeft c r, b => c.act b && r.denote
  | .andRight l c, b => l.denote && c.act b
  | .orLeft c r, b => c.act b || r.denote
  | .orRight l c, b => l.denote || c.act b

theorem plug_denote (c : Context) (n : Net) :
    (c.plug n).denote = c.act n.denote := by
  induction c <;> simp [Context.plug, Context.act, Net.denote, *]

/-- A local interaction remains sound in every graph context. -/
theorem contextualRule_preserves (c : Context) (r : ActiveRule) :
    (c.plug r.rhs).denote = (c.plug r.lhs).denote := by
  rw [plug_denote, plug_denote, activeRule_preserves]

/-! ## The local reduction relation and its closure -/

/-- One semantic reduction contracts exactly one active rule inside a one-hole
context.  The context is the frame that remains untouched by the local step. -/
inductive Step : Net → Net → Prop where
  | interact (context : Context) (rule : ActiveRule) :
      Step (context.plug rule.lhs) (context.plug rule.rhs)

/-- Reflexive-transitive local reduction. -/
abbrev Reduces : Net → Net → Prop := Relation.ReflTransGen Step

/-- Every one-step local reduction preserves Boolean evaluation. -/
theorem step_preserves {before after : Net} (h : Step before after) :
    after.denote = before.denote := by
  cases h with
  | interact context rule => exact contextualRule_preserves context rule

/-- Every finite semantic reduction preserves Boolean evaluation. -/
theorem reduces_preserves {start finish : Net} (h : Reduces start finish) :
    finish.denote = start.denote := by
  induction h using Relation.ReflTransGen.head_induction_on with
  | refl => rfl
  | head hstep _ ih => exact ih.trans (step_preserves hstep)

/-! ## Executable local certificates and traces -/

/-- One proof step: a rule tag plus the one-hole context that locates it. -/
structure LocalCert where
  context : Context
  rule : ActiveRule
  deriving DecidableEq, Repr

def LocalCert.before (c : LocalCert) : Net := c.context.plug c.rule.lhs
def LocalCert.after (c : LocalCert) : Net := c.context.plug c.rule.rhs

/-- Check a fully exposed before/after step. -/
def LocalCert.check (c : LocalCert) (before after : Net) : Bool :=
  decide (before = c.before ∧ after = c.after)

theorem localCheck_exact (c : LocalCert) (before after : Net) :
    c.check before after = true ↔ before = c.before ∧ after = c.after := by
  simp [LocalCert.check]

theorem localCheck_sound {c : LocalCert} {before after : Net}
    (h : c.check before after = true) : after.denote = before.denote := by
  rcases (localCheck_exact c before after).mp h with ⟨rfl, rfl⟩
  exact contextualRule_preserves c.context c.rule

/-- The executable checker refines the semantic one-step relation. -/
theorem localCheck_step {c : LocalCert} {before after : Net}
    (h : c.check before after = true) : Step before after := by
  rcases (localCheck_exact c before after).mp h with ⟨rfl, rfl⟩
  exact .interact c.context c.rule

/-- Conversely, every semantic local step has a checkable finite certificate. -/
theorem step_has_localCert {before after : Net} (h : Step before after) :
    ∃ c : LocalCert, c.check before after = true := by
  cases h with
  | interact context rule =>
      exact ⟨⟨context, rule⟩, by simp [LocalCert.check, LocalCert.before, LocalCert.after]⟩

/-- Contextual observation: two nets are indistinguishable when every one-hole
Boolean test context gives them the same result. -/
def ObservationalEq (before after : Net) : Prop :=
  ∀ test : Context, (test.plug before).denote = (test.plug after).denote

/-- Local checking gives the proof-net/biorthogonality-facing result: accepted
rewrites preserve *every* surrounding test, not merely the empty context. -/
theorem checkStep_observational {c : LocalCert} {before after : Net}
    (h : c.check before after = true) : ObservationalEq before after := by
  intro test
  rw [plug_denote, plug_denote, localCheck_sound h]

/-- Apply one local certificate if its exposed left-hand graph is exactly the
current state.  Failure is fail-closed. -/
def applyCert (current : Net) (c : LocalCert) : Option Net :=
  if current = c.before then some c.after else none

theorem applyCert_sound {current next : Net} {c : LocalCert}
    (h : applyCert current c = some next) : next.denote = current.denote := by
  unfold applyCert at h
  split at h
  next heq =>
    simp only [Option.some.injEq] at h
    subst next
    rw [heq]
    exact contextualRule_preserves c.context c.rule
  next => contradiction

/-- Replay a proof-object trace.  The trace contains only local certificates;
intermediate nets are reconstructed by the checker. -/
def replay : Net → List LocalCert → Option Net
  | current, [] => some current
  | current, c :: cs =>
      match applyCert current c with
      | none => none
      | some next => replay next cs

theorem replay_preserves : ∀ (certs : List LocalCert) (start finish : Net),
    replay start certs = some finish → finish.denote = start.denote := by
  intro certs
  induction certs with
  | nil =>
      intro start finish h
      simp only [replay, Option.some.injEq] at h
      subst finish
      rfl
  | cons c cs ih =>
      intro start finish h
      cases hstep : applyCert start c with
      | none =>
          simp [replay, hstep] at h
      | some middle =>
          have htail : replay middle cs = some finish := by
            simpa [replay, hstep] using h
          exact (ih middle finish htail).trans (applyCert_sound hstep)

/-- Successful replay also builds the corresponding reflexive-transitive
semantic reduction. -/
theorem replay_reduces : ∀ (certs : List LocalCert) (start finish : Net),
    replay start certs = some finish → Reduces start finish := by
  intro certs
  induction certs with
  | nil =>
      intro start finish h
      simp only [replay, Option.some.injEq] at h
      subst finish
      exact Relation.ReflTransGen.refl
  | cons c cs ih =>
      intro start finish h
      cases hstep : applyCert start c with
      | none =>
          simp [replay, hstep] at h
      | some middle =>
          have htail : replay middle cs = some finish := by
            simpa [replay, hstep] using h
          have hlocalCheck : c.check start middle = true := by
            unfold applyCert at hstep
            split at hstep
            next heq =>
              simp only [Option.some.injEq] at hstep
              subst middle
              simp [LocalCert.check, heq]
            next => contradiction
          exact Relation.ReflTransGen.head (localCheck_step hlocalCheck)
            (ih middle finish htail)

/-- A closed trace checker with an explicit claimed endpoint. -/
def checkTrace (start : Net) (certs : List LocalCert) (finish : Net) : Bool :=
  decide (replay start certs = some finish)

theorem checkTrace_exact (start : Net) (certs : List LocalCert) (finish : Net) :
    checkTrace start certs finish = true ↔ replay start certs = some finish := by
  simp [checkTrace]

/-- Any accepted local interaction trace preserves the source Boolean meaning. -/
theorem checkTrace_sound {start finish : Net} {certs : List LocalCert}
    (h : checkTrace start certs finish = true) :
    finish.denote = start.denote :=
  replay_preserves certs start finish ((checkTrace_exact start certs finish).mp h)

/-- Any accepted trace witnesses a finite semantic reduction. -/
theorem checkTrace_reduces {start finish : Net} {certs : List LocalCert}
    (h : checkTrace start certs finish = true) : Reduces start finish :=
  replay_reduces certs start finish ((checkTrace_exact start certs finish).mp h)

/-! ## Non-vacuity and refusal -/

namespace Reference

def start : Net := .neg (.and (.lit true) (.lit false))
def middle : Net := .neg (.lit false)
def finish : Net := .lit true

def reduceAnd : LocalCert :=
  ⟨.underNeg .hole, .andLit true false⟩

def reduceNeg : LocalCert :=
  ⟨.hole, .negLit false⟩

theorem trace_checks : checkTrace start [reduceAnd, reduceNeg] finish = true := by
  decide

theorem trace_preserves : finish.denote = start.denote :=
  checkTrace_sound trace_checks

/-- The same rule at the wrong location is refused; a certificate cannot silently
rewrite a different subgraph. -/
theorem wrong_location_refused :
    reduceNeg.check start finish = false := by
  decide

end Reference

#assert_all_clean [
  activeRule_preserves,
  plug_denote,
  contextualRule_preserves,
  step_preserves,
  reduces_preserves,
  localCheck_exact,
  localCheck_sound,
  localCheck_step,
  step_has_localCert,
  checkStep_observational,
  applyCert_sound,
  replay_preserves,
  replay_reduces,
  checkTrace_exact,
  checkTrace_sound,
  checkTrace_reduces,
  Reference.trace_checks,
  Reference.trace_preserves,
  Reference.wrong_location_refused
]

end Dregg2.Calculus.InteractionNetTrace
