#!/usr/bin/env python3
"""gen-mina-step-srs.py — generate `Dregg2/Circuit/Emit/MinaStepSrsG.lean` from the byte-pinned
Vesta SRS blob.

  python3 scripts/gen-mina-step-srs.py [--check]

WHY A GENERATOR AND NOT A HAND-TRANSCRIPTION. `metatheory/emitted/mina-accumulator/vesta_srs_g.bin`
is the artifact `dregg_bridge::mina_accumulator_discharge` already trusts: it is sha256-pinned by
`VESTA_SRS_G_SHA256`, and `vesta_srs_g(0)` re-checks all 65,536 points are on `y² = x³ + 5` over
`q` before the native oracle discharges a single claim. Decoding it twice — once in Rust, once by
hand into Lean — is the ungated transcription hop this repo keeps deleting. This script is the one
decode, and `--check` is the gate: it regenerates into memory and diffs, so a drifted blob or an
edited Lean file is findable without a commit.

⚠ The Vesta SRS is the STEP/Tick leg. `MinaWrapSrsG` is 32,768 PALLAS points (Wrap/Tock). Mixing
them is a silent wrong-curve proof; that is why they are separate modules at separate namespaces.
"""
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOB = ROOT / "metatheory/emitted/mina-accumulator/vesta_srs_g.bin"
OUT = ROOT / "metatheory/Dregg2/Circuit/Emit/MinaStepSrsG.lean"
SHA = "f28a8a9136eb087645fb250238f5ae70d8bf3d6abf68a0ad90ab3463450c271a"
N = 65536
BLK = 512
# Vesta base field q (`PastaField.qN`) — the modulus these coordinates are reduced at.
Q = 28948022309329048855892746252171976963363056481941647379679742748393362948097

HEADER = f'''/-! GENERATED by `scripts/gen-mina-step-srs.py` from
`metatheory/emitted/mina-accumulator/vesta_srs_g.bin` (sha256
`{SHA}`) — the STEP/Tick SRS generators
`srs.g`, {N} **VESTA** points in projective form `(x, y, 1)`, decimal. DO NOT EDIT.

⚑ This is the OTHER curve from `MinaWrapSrsG`. That module carries 32768 **Pallas** points (the
Wrap/Tock commitment curve); these are the {N} **Vesta** points the deferred accumulator actually
lives on — `accumulator_check.rs:11`, `urs: &SRS<Vesta>`, `Fq::SRS_DEPTH = 65_536`. Mixing them is
a silent wrong-curve proof, so they are separate modules with separate namespaces and the
coordinates here are reduced at `q`, not `p`.

Provenance chain, unbroken: openmina's own `get_srs::<Fp>()` (rev `82480cd468`)
→ `metatheory/fixtures/pickles-extractors/src/bin/accumulator_discharge_export.rs`, which asserts
`accumulator_check` on seven real block proofs before writing a byte
→ this blob, byte-pinned by `dregg_bridge::mina_accumulator_discharge::VESTA_SRS_G_SHA256`, whose
`vesta_srs_g(0)` re-checks all {N} are on `y² = x³ + 5` over `q`
→ this file. Same bytes, same pin, one decode.

⚠ ALLOWLISTED OUT OF THE `Dregg2` ROOT, exactly as `MinaWrapSrsG` is: rooting a module of this size
makes `lake build Dregg2` impossible to finish. -/
namespace Dregg2.Circuit.Emit.MinaStepSrsG
abbrev Pt := Nat × Nat × Nat'''


def render() -> str:
    blob = BLOB.read_bytes()
    got = hashlib.sha256(blob).hexdigest()
    if got != SHA:
        sys.exit(f"gen-mina-step-srs: blob sha256 is {got}, expected {SHA} — re-pin deliberately")
    if len(blob) != N * 64:
        sys.exit(f"gen-mina-step-srs: blob is {len(blob)} bytes, expected {N * 64}")
    out = [HEADER]
    names = []
    for b in range(N // BLK):
        name = f"blk{b}"
        names.append(name)
        rows = []
        for i in range(b * BLK, (b + 1) * BLK):
            r = blob[i * 64 : i * 64 + 64]
            x = int.from_bytes(r[:32], "little")
            y = int.from_bytes(r[32:], "little")
            if not (x < Q and y < Q):
                sys.exit(f"gen-mina-step-srs: generator {i} is not reduced at q")
            rows.append(f"  ({x}, {y}, 1)")
        out.append(f"def {name} : List Pt := [\n" + ",\n".join(rows) + "]")
    out.append("def SRS_G : List Pt := " + " ++ ".join(names))
    out.append("end Dregg2.Circuit.Emit.MinaStepSrsG")
    return "\n".join(out) + "\n"


def main() -> None:
    text = render()
    if "--check" in sys.argv:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur != text:
            sys.exit("gen-mina-step-srs: MinaStepSrsG.lean is STALE — re-run without --check")
        print(f"gen-mina-step-srs: MinaStepSrsG.lean is current ({N} Vesta generators).")
        return
    OUT.write_text(text)
    print(f"gen-mina-step-srs: wrote {N} Vesta generators to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
