//! ⚑⚑ **THE TOWER'S ONE RULE, AS THREE EQUATIONS.**
//!
//! `recursion_layer_over(child)` is the config the layer ABOVE `child` runs at: it verifies the
//! child at the child's own minting engine and mints at `create_recursion_config`'s. Every leaf
//! wrap, every fold and every root verify in the workspace is now generated by iterating that one
//! function, so the facts it must satisfy are facts the whole tower rests on:
//!
//! 1. **it does not move a child's acceptance** — its verify knobs ARE the child's mint knobs, for
//!    every config in the workspace;
//! 2. **over an IR-v2 descriptor batch it is the leaf wrap** — `ir2_leaf_wrap_split_config()`,
//!    the object the 13.8× was measured on;
//! 3. **it has a fixed point, and the fixed point is `create_recursion_config()`** — which is what
//!    makes "leaf, then every layer above it" a two-config tower rather than an infinite regress.
//!
//! ⚠ These are claims about the CONFIG OBJECTS, and a config object being right is exactly what
//! was already true while the split was inert (`59b82fa60`). The claims about EMITTED PROOFS live
//! in `dregg-circuit-prove`'s `production_leaves_mint_at_their_own_engine.rs` and
//! `leaf_wrap_mint_blowup_repricing.rs`, which read query counts and Merkle depths off real roots
//! through both dispatch branches. This file is the algebra; those are the artifacts.

use dregg_recursion_verify::config::{
    DreggRecursionConfig, IR2_INNER_COMMIT_POW_BITS, IR2_INNER_LOG_BLOWUP,
    IR2_INNER_LOG_FINAL_POLY_LEN, IR2_INNER_QUERY_POW_BITS, RECURSION_FRI_COMMIT_POW_BITS,
    RECURSION_FRI_LOG_BLOWUP, RECURSION_FRI_LOG_FINAL_POLY_LEN, RECURSION_FRI_MAX_LOG_ARITY,
    RECURSION_FRI_NUM_QUERIES, RECURSION_FRI_QUERY_POW_BITS, create_recursion_config,
    ir2_leaf_wrap_config, ir2_leaf_wrap_split_config, recursion_layer_over,
};

/// The full observable identity of a config: what it mints, and what it accepts.
fn shape(
    c: &DreggRecursionConfig,
) -> (
    (usize, usize, usize, usize, usize, usize),
    (usize, usize, usize, usize),
) {
    let k = c.mint_knobs();
    (
        (
            k.log_blowup,
            k.log_final_poly_len,
            k.max_log_arity,
            k.num_queries,
            k.commit_pow_bits,
            k.query_pow_bits,
        ),
        c.verify_knobs(),
    )
}

/// (1) **A LAYER NEVER MOVES ITS CHILD'S ACCEPTANCE.** Stated over every config the workspace
/// builds, not over one of them: the verify knobs of `recursion_layer_over(c)` are `c`'s mint
/// knobs, elementwise. This is the whole reason the split is not a soundness change on the child
/// side — the same unmodified `Ir2BatchProof` is checked by the same in-circuit verifier.
#[test]
fn a_layer_verifies_its_child_at_exactly_the_childs_minting_engine() {
    for (name, child) in [
        ("ir2_leaf_wrap_config", ir2_leaf_wrap_config()),
        ("create_recursion_config", create_recursion_config()),
        ("ir2_leaf_wrap_split_config", ir2_leaf_wrap_split_config()),
    ] {
        let k = *child.mint_knobs();
        let over = recursion_layer_over(&child);
        assert_eq!(
            over.verify_knobs(),
            (
                k.log_blowup,
                k.log_final_poly_len,
                k.commit_pow_bits,
                k.query_pow_bits
            ),
            "the layer over {name} must check that child at the child's OWN engine — a different \
             verify engine is a different acceptance decision on an unchanged proof"
        );
    }
}

/// (1b) …and it always mints at the recursion engine, whatever the child was. The mint side is
/// the free choice; this pins which choice is taken.
#[test]
fn a_layer_always_mints_at_the_recursion_engine() {
    let expected = (
        RECURSION_FRI_LOG_BLOWUP,
        RECURSION_FRI_LOG_FINAL_POLY_LEN,
        RECURSION_FRI_MAX_LOG_ARITY,
        RECURSION_FRI_NUM_QUERIES,
        RECURSION_FRI_COMMIT_POW_BITS,
        RECURSION_FRI_QUERY_POW_BITS,
    );
    for child in [
        ir2_leaf_wrap_config(),
        create_recursion_config(),
        ir2_leaf_wrap_split_config(),
    ] {
        assert_eq!(shape(&recursion_layer_over(&child)).0, expected);
    }
}

/// (2) **OVER THE IR-v2 DESCRIPTOR BATCH IT IS THE LEAF WRAP.** `ir2_leaf_wrap_split_config()` is
/// the object `leaf_wrap_mint_blowup_repricing.rs` measured 13.8× on; the production leaves reach
/// it by derivation from the config they are handed, never by naming it. If these two ever
/// disagreed, the measured object and the deployed object would be different objects.
#[test]
fn the_layer_over_an_ir2_descriptor_batch_is_the_split_leaf_wrap() {
    assert_eq!(
        shape(&recursion_layer_over(&ir2_leaf_wrap_config())),
        shape(&ir2_leaf_wrap_split_config()),
    );
    // and its verify side is the IR-v2 inner engine, named from the constants the deployed
    // descriptor prover actually reads rather than reconstructed.
    assert_eq!(
        ir2_leaf_wrap_split_config().verify_knobs(),
        (
            IR2_INNER_LOG_BLOWUP,
            IR2_INNER_LOG_FINAL_POLY_LEN,
            IR2_INNER_COMMIT_POW_BITS,
            IR2_INNER_QUERY_POW_BITS
        ),
    );
}

/// (3) **THE FIXED POINT.** A leaf wrap emits at the recursion engine, so the fold above it is
/// `recursion_layer_over(leaf_wrap)` — and that is `create_recursion_config()`, which is its own
/// layer. Two applications reach the top of the tower and a third changes nothing, which is why
/// every orchestrator can write `recursion_layer_over(&recursion_layer_over(inner))` and be done.
#[test]
fn create_recursion_config_is_the_fixed_point() {
    let base = create_recursion_config();
    assert_eq!(shape(&recursion_layer_over(&base)), shape(&base));

    let inner = ir2_leaf_wrap_config();
    let leaf = recursion_layer_over(&inner);
    let fold = recursion_layer_over(&leaf);
    assert_eq!(
        shape(&fold),
        shape(&base),
        "the fold engine IS create_recursion_config"
    );
    assert_eq!(
        shape(&recursion_layer_over(&fold)),
        shape(&fold),
        "and iterating past it is a no-op — the tower is two configs deep, not N"
    );
    assert_ne!(
        shape(&leaf),
        shape(&fold),
        "the leaf wrap and the fold must NOT be the same object: they accept different children"
    );
}

/// ⚑ **THE SOUNDNESS LEDGER OF THE MOVE, ON THE OBJECTS.** `log_blowup · num_queries + query_pow`
/// is the capacity column the params gate judges. The split leaf wrap lands on **128** — exactly
/// `create_recursion_config`'s, because it IS `create_recursion_config`'s minting half — against
/// the deployed leaf wrap's 130. No knob moves below the standing drift margin, and the reason
/// there is zero headroom is that the weakest shipped config is the one it adopts.
#[test]
fn the_split_lands_on_the_standing_capacity_margin_not_below_it() {
    let deployed = ir2_leaf_wrap_config();
    let leaf = recursion_layer_over(&deployed);
    let base = create_recursion_config();

    assert_eq!(deployed.mint_knobs().capacity_bits(), 6 * 19 + 16);
    assert_eq!(deployed.mint_knobs().capacity_bits(), 130);
    assert_eq!(leaf.mint_knobs().capacity_bits(), 3 * 38 + 14);
    assert_eq!(leaf.mint_knobs().capacity_bits(), 128);
    assert_eq!(
        leaf.mint_knobs().capacity_bits(),
        base.mint_knobs().capacity_bits(),
        "the split leaf wrap mints at create_recursion_config's engine, so its capacity column is \
         that config's — not a new posture to be judged separately"
    );
    // The arity knob is a soundness lever (`Dregg2.Circuit.FriArityTransfer`) and it does not move
    // either: both are fold-by-2.
    assert_eq!(leaf.mint_knobs().max_log_arity, 1);
    assert_eq!(deployed.mint_knobs().max_log_arity, 1);
}
